### ISSUE TITLE
client.remove(torrentId, [function callback (err) {}]) not removing temp folder

### ISSUE THREAD

**Issue by davidgatti** [webtorrent/webtorrent#1000]
The documentation states:

> Remove a torrent from the client. Destroy all connections to peers and delete all saved file data. If callback is specified, it will be called when file data is removed.

The issue that I'm having is with the following statement: `and delete all saved file data`, this seams not to be true. If I check the content of the following folder `/tmp/webtorrent` after firing this method, the folder of the selected torrent is not being delete. 

Is this a bug, feature or I'm doing something wrong? :)

* WebTorrent version: 0.98.0
* Node.js version: v6.4.0
* Browser name/version (if using WebTorrent in the browser): Using NodeJS module.

**Comment by feross** [comment]
You're right, this is not behaving as documented. The removal of files on the filesystem is unimplemented. In the meantime, I suggest using the `rimraf` module to delete the entire `/tmp/webtorrent` folder, or just the `/tmp/webtorrent/<infohash>` folder for a single torrent.

**Comment by davidgatti** [comment]
OK, good to know :) it be nice if in the documentation there as a sentence like the following:

`for not to delete the folder related to the torrent, please implement your own way` - or somethign like that to give an idea what to expect :)

**Comment by austin-rausch** [comment]
The wording seems kind of confusing, if this were implemented would this remove both the tmp folder as well as the path if specified? Or just clean up the tmp folder. I'm assuming it is the latter but I just wanted clarification.
