### ISSUE TITLE
When you call .seed method, the tracker receives a START event with a "left" parameter greater than zero

### ISSUE THREAD

**Issue by zephrax** [webtorrent/webtorrent#1105]
Version: webtorrent-hybrid 1.0.5
OS: Archlinux
Node: v.6.10.0

**What did you expect to happen?**
I expect the tracker receives the "left" parameter with 0, because I'm seeding directly a file I have.
 
**What actually happened?**
The tracker got a "left" with the actual size of the file. 

I'm trying to detect when a user is going to download a file, and I think this is a false positive.

**Comment by DiegoRBaquero** [comment]
Another message with a left=0 is sent shortly after.

**Comment by feross** [comment]
This could be addressed by waiting to start peer discovery until after file verification is complete. Though I haven't considered all the implications of doing this.
