### ISSUE TITLE
Torrent file select

### ISSUE THREAD

**Issue by AceVance** [webtorrent/webtorrent#1108]
Streaming only specific file, even though torrent link has multiple files. Will be again, HUGE.

**Comment by AceVance** [comment]
Thanks in advance!!!

**Comment by marcus-sa** [comment]
I'm currently not on PC, but what you'd have to do is either check for the most torrented file, or the file with the biggest size, and from there deselect all the others.

**Comment by AceVance** [comment]
Anyway we can talk over email?

**Comment by kocoten1992** [comment]
Do you want something like this:
```
Sintel/
Sintel/poster.jpg
Sintel/Sintel.en.srt
Sintel/Sintel.mp4
Sintel/Sintel.es.srt
...
```
But only interested in ```Sintel/Sintel.mp4``` and ```Sintel/poster.jpg```, correct?

**Comment by DiegoRBaquero** [comment]
You can do that already with the current API. Deselect unwanted files and streaming render only the wanted file. I'm closing this issue, but please continue with the discussion.
