### ISSUE TITLE
why don't you make an raspberrypi app to download p2p file?

### ISSUE THREAD

**Issue by lemonhall** [webtorrent/webtorrent#1113]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by allthetime** [comment]
lol, why don't you?

**Comment by DiegoRBaquero** [comment]
I don't think Electron works in arm CPUs. Else we would build WD for it too.

**Comment by lemonhall** [comment]
node.js is just fine, just b/s model...  like your instant.io but...is an browser / server style

**Comment by feross** [comment]
@DiegoRBaquero Actually, Electron started providing ARM builds a while ago. We just need to add that as a build target and test it out.

**Comment by DiegoRBaquero** [comment]
@feross wow! I didn’t know, that’s cool, we can now build for raspis too!

**Comment by feross** [comment]
@DiegoRBaquero Yep!

**Comment by feross** [comment]
@lemonhall For now, you can build WebTorrent Desktop from scratch and it'll automatically pick up the platform you're building on (ARM) and it should work for Raspberry Pi 2. More info: https://github.com/webtorrent/webtorrent-desktop/issues/633

**Comment by lemonhall** [comment]
@feross ok,thx
