### ISSUE TITLE
webtorrent crashes with a parallel webrtc video session in same chrome browser

### ISSUE THREAD

**Issue by so010** [webtorrent/webtorrent#1115]
If there is a webRTC session with video in the same browser webtorrent slows down extremly and crashes often while downloading.

Step by step:
- seed a big file (1GB) on instant.io
- dowload the torrent: download speed ca 10MB/s
- open new tab and start a website with webRTC video ( appear.in )
- download rate decreases to < 1MB/s
- Chrome tab of webtorrent crashes after some seconds ...

**What version of WebTorrent?** 0.98.16 and reproduced also on instant.io

**What operating system and Node.js version?** Debian Jessie with node: v4.4.5
on my testserver but reproduced this on instant.io too.

**What browser and version? (if using WebTorrent in the browser)** Chrome Version 56.0.2924.87 (64-bit) Linux (Firefox 52 seems to crash as well)

**What did you expect to happen?**
No crash and only slightly lower download-rates

**What actually happened?**
Download goes from 10MB/s to < 1MB/s and chrome tab of webtorrent crashes after several seconds

I think it's a Chromium webRTC bug but thought to post it here first to get second opinion.
Update: Firefox crashes as well

**Comment by DiegoRBaquero** [comment]
Such large torrent would be loaded to RAM fully. Maybe that's why (?)

**Comment by feross** [comment]
I think that WebTorrent in Chrome works much better with large files thanks to recent Chrome updates, so I'm going to close this since it's been a while since it was opened.
