### ISSUE TITLE
torrent with multifiles download done immediately to be use

### ISSUE THREAD

**Issue by bluefchen** [webtorrent/webtorrent#1119]
I have a webtorrent file with multifiles  inside.
Is there any way to listen `'torrent.files.forEach'` download status.
So when a file is downloaded successfully, i can render it immediately.

**Comment by DiegoRBaquero** [comment]
You can use `renderTo`, `appendTo`, `getBlob`, `getBlobURL` and `getBuffer` methods for such.

More info: [API#getBuffer](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#filegetbufferfunction-callback-err-buffer-)
