### ISSUE TITLE
WebSeed memory hog causing crash (chrome)

### ISSUE THREAD

**Issue by kocoten1992** [webtorrent/webtorrent#1120]
**What version of WebTorrent?**
0.98.18
**What operating system and Node.js version?**
Ubuntu 17.04, v7.3.0
**What browser and version? (if using WebTorrent in the browser)**
Chrome 57.0

It crash wasn't because of file too big for memory, I was using idb-chunk-store and chrome-chunk-store

When just webRTC connection, it went well, but when add webseed it causing crash, my speculation is that, when forEach loop https://github.com/webtorrent/webtorrent/blob/master/lib/webconn.js#L111, 

During the loop, memory wasn't release until the end, that what cause the hog (sorry if I'm wrong), might be fix if we split it into smaller forEach.

Thought, boss ?

**Comment by SilentBot1** [comment]
Hey @kocoten1992,

How large was the files you were testing with?

Sounds similar to the issue #1303.

All the best.

**Comment by kocoten1992** [comment]
@SilentBot1 hey

The file should larger than 2GB and we will see the effect.

On side note: when doing with big file, don't open f12 (or open and must close it periodically), the console log or the network tab will keep the memory from being collect by garbage collection.
