### ISSUE TITLE
When using the webtorrent client how do you specify that a torrent downloads in-order?

### ISSUE THREAD

**Issue by BrutalSimplicity** [webtorrent/webtorrent#1123]
I don't see in the documentation where there is a parameter that specifies that torrents download in-order. Is this functionality baked in? If so, I'm wondering if you could point me in the direction of where/how this was implemented.

**Comment by DiegoRBaquero** [comment]
It is! :) Torrents are downloaded in-order (sequentially) by default: https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L79

You can switch to `rarest` if you don't want to use sequential strategy.

**Comment by yourmother1917** [comment]
hi m ot_h.e.r f-u_0c-kEr @BrutalSimplicity  ... how is ur dad ... long see no time ... he visits me more often ... tell him to come with ur mom ,,, we hyave more customers for ur mo00im
