### ISSUE TITLE
Audio codec unspported 

### ISSUE THREAD

**Issue by MahmoudELSharawy** [webtorrent/webtorrent#1128]
I cant stream any torrent ... how i cant solve it ? please answer :(
![capture](https://cloud.githubusercontent.com/assets/28805538/26245283/b0aa1342-3c93-11e7-8e57-af2d5dddeb11.PNG)

**Comment by adrianoresende** [comment]
Same error here! 
+1 to add codec

**Comment by marcus-sa** [comment]
The HTML5 <video> tag only supports certain codecs and formats, hence why you need to use e.g VLC.
There's several modules on NPM that encodes e.g mkv into mp4 meanwhile streaming, so that could be a nice feature.

**Comment by DiegoRBaquero** [comment]
We are restricted by the Node, Electron, HTML5 environment. For now, the only way is to install VLC, streaming still works.
