### ISSUE TITLE
I deleted webtorrent, because CPU high

### ISSUE THREAD

**Issue by adrianoresende** [webtorrent/webtorrent#1129]
Only a torrent downloading:
![image](https://cloud.githubusercontent.com/assets/798755/26269668/90385518-3ccc-11e7-9aac-c45495d2f555.png)

**Comment by DiegoRBaquero** [comment]
Was this webtorrent lib or Desktop app? 29% out of 1 core seems reasonable to me, considering what a bittorrent library does. What's your disk like?

Would be cool if you provided more information.

**Comment by adrianoresende** [comment]
I used the desktop, opened a torrent for the first time and checked that my CPU was high, so CPU came back normally after closing the application. That's it.

**Comment by DiegoRBaquero** [comment]
But it didn't reach that high. While downloading a torrent hashing of each piece must be done. It should be much lower while not downloading.
