### ISSUE TITLE
Database location

### ISSUE THREAD

**Issue by m-2k** [webtorrent/webtorrent#1131]
I'm using the NPM package and can not find where the torrent database on the disk is stored.

Also how correct foreach for client.torrents object? I see a lot of copies of the Torrent object although I only added one. Help!

WT 0.98.18
Mac OSX
Node 7.8.0

**Comment by kocoten1992** [comment]
the default would be ```/tmp/webtorrent/```

https://webtorrent.io/docs

**Comment by m-2k** [comment]
Where data is stored I know
I wonder where the database state is stored between program restarts

Also how to delete all active and inactive torrents in the tracker
I want clean start

**Comment by kocoten1992** [comment]
afaik, there isn't any database, webtorrent will fetch meta info of torrent, then do a checksum on each segment of file, then download which part that you don't have, no database is needed.

Everytime you restart webtorrent, it'll do it from the start, so delete the directory/file would be enough.

**Comment by m-2k** [comment]
Oh, right, sorry
