### ISSUE TITLE
How to get file progress?

### ISSUE THREAD

**Issue by TAiS46** [webtorrent/webtorrent#1132]
Hi there,

is it possible to get the file progress inside a torrent?

**Comment by allthetime** [comment]
There are docs for this question:

https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#torrentondownload-function-bytes-

**Comment by TAiS46** [comment]
But it's only for the torrent and not for the files / items in it right?

**Comment by m-2k** [comment]
**Torrent API**
`torrent.on('download', function (bytes) {})`
`torrent.files[...]`

**File API**
`file.length / file.downloaded`

Use this 4 methods as solution

**Comment by DiegoRBaquero** [comment]
We should def get `file.progress` added.

**Comment by AshlessCinder** [comment]
https://github.com/webtorrent/webtorrent/pull/1140

**Comment by AshlessCinder** [comment]
This feature is merged now, so this issue can be closed :D

**Comment by feross** [comment]
Fixed by https://github.com/webtorrent/webtorrent/pull/1140
