### ISSUE TITLE
Can't get a browser to load webtorrent

### ISSUE THREAD

**Issue by CraigglesO** [webtorrent/webtorrent#1135]
**What version of WebTorrent?**
version - 0.98.18
**What operating system and Node.js version?**
OS X Sierra - Node v7.10.0
**What browser and version? (if using WebTorrent in the browser)**
Tried both Firefox and Chrome [Version 58.0.3029.110 (64-bit)], both latest verisons.
**What did you expect to happen?**
A functional Webtorrent
**What actually happened?**
Errors.
`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

I almost got something working once, but it doesn't pull from any peers -_-

The webtorrent website doesn't have anything anymore either. I tried multiple browsers. No luck.

Is there something new that has caused webtorrent to be broken?

I even tried the example code to the letter on the website and it still doens't work.

**Comment by vv01f** [comment]
same here in FF 53 and Chromium 58. worked few weeks ago without problems.

> (index):17 GET https://webtorrent.io/bundle.js net::ERR_INCOMPLETE_CHUNKED_ENCODING
> (index):1 GET https://webtorrent.io/img/screenshot-player.png net::ERR_CONTENT_LENGTH_MISMATCH

the [CodePen](http://codepen.io/yciabaud/full/XdOeWM/) works just fine on both.

**Comment by alxhotel** [comment]
Looks like a server side bug. In the meantime you can use:

[https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js](https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js)

Please move this issue to [webtorrent/webtorrent.io](/webtorrent/webtorrent.io)

**Comment by alxhotel** [comment]
Moved to: [webtorrent/webtorrent.io#118](/webtorrent/webtorrent.io/issues/118)

**Comment by feross** [comment]
Thanks for posting this issue. It's resolved now. The webtorrent.io server had run out of disk space. I only had log rotation set up for the node.js server logs. I'm setting it up for the nginx logs as well now. Cheers!
