### ISSUE TITLE
Local Service Discovery (BEP14)

### ISSUE THREAD

**Issue by HughIsaacs2** [webtorrent/webtorrent#1136]
I feel WebTorrent (node.js) and WebTorrent Desktop needs this to push for further decentralization.
Plus it'd be useful for simply making lives easier by allowing local PCs to share over the BitTorrent protocol.

[http://bittorrent.org/beps/bep_0014.html](http://bittorrent.org/beps/bep_0014.html)

Personally, I'd like to take a jab at this but I'm far too deep in the noob realm to grasp everything here.
At first I thought torrent clients were using [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS) to accomplish this and I thought I could just slap on some Node mDNS library to get by but it appears to be something else (at least from my perspective).

Any thoughts?

**Comment by HughIsaacs2** [comment]
Also, I could've sworn an issue for this BEP was posted before.

**Comment by epvbergen** [comment]
There are two extensions that do this apparently: BEP-14 straight on top of UDP multicast, and BEP-26 on top of mDNS.

Is there any way to get either transport mechanism working in the browser?

**Comment by feross** [comment]
This was implemented by @hicom150 in https://github.com/webtorrent/bittorrent-lsd and it will be included in the next release of WebTorrent, 0.111.0.
