### ISSUE TITLE
seed finished torrents without initial check

### ISSUE THREAD

**Issue by BenmasterTM** [webtorrent/webtorrent#1139]
What i want to do is "load" into webtorrent finished torrents like actually client.seed(torrentID) make, but preventing the "check" of the torrent, I mean when you load a previous downloaded torrent in the disk, webtorrent run from 0% to 100% like is checking the file. its possible avoid this in some way? Because if I have many many files completed, if I add with client.seed() cause extreme HDD usage untill finish to check all files.

Im not sure what do this proces, if the proces is spliting chunks in memory or something similar, can be an option to store in disk to load faster and dont make the process again every time the client is started?

Other torrent clients like Deluge dont have this problem, if try to put big quantity of linux ISOS, and let finish, then close and open again the program, the "check" process dont happen, but the files are shared correctly (I see the upload rates of all files changing)

**Comment by BenmasterTM** [comment]
after some research i found the way to load the torrent into the client without check the chucks again, its undocumented feature of webtorrent, I found it looking in the webtorrent-desktop client sources:

```
const torrent = client.add(torrentID, {
    path: path,
    fileModtimes: fileModtimes
})
```
The "trick" is the fileModtimes variable, its returned by (undocumented) function in torrent objects:

```
torrent.getFileModtimes(function (err, fileModtimes) {
```

In this way the webtorrent client bypass the checksum of the pieces.

**Comment by andreapaiola** [comment]
What value do you assign to fileModtimes?

**Comment by feross** [comment]
@BenmasterTM Yep, you're correct. This feature isn't documented because the API design is quite terrible and I'd like to improve it before too many people start to use it. In the meantime, feel free to use it as this is this same way that WebTorrent Desktop accomplishes seeding upon restart.
