### ISSUE TITLE
Torrents stuck on 0% but shows multiple peers and upload speed and time remaining, 

### ISSUE THREAD

**Issue by d8sh** [webtorrent/webtorrent#1141]
**What version of WebTorrent?**
Current
**What operating system and Node.js version?**
Windows 10 Current
**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
Reinstalled Current Release of Webtorrent and removed torrent from the list.. upon reinstalling and relaunching I expected it to continue the download
**What actually happened?**
was still stuck at 0% or 26% on others...  seems to have occured after one file finished at 100% and was removed from list.. 

Shows "Downloading 26% 1.0GB/ 3,9GB 26 peers

If i delete the torrent file from the downloads and re-add the torrent via magnet link it sometimes works again. but not always.. It has happened so often it made Webtorrent not useable, and I need to find a replacement program.

**Comment by DiegoRBaquero** [comment]
Is this in Node.js?

**Comment by d8sh** [comment]
I don’t know what Node.Js is.. I just use the desktop app for windows the 64 bit version. 
It happens a lot.

**Comment by DiegoRBaquero** [comment]
Please open an issue here: https://github.com/webtorrent/webtorrent-desktop
