### ISSUE TITLE
Webtorrent freezes with high speeds

### ISSUE THREAD

**Issue by Deenoking** [webtorrent/webtorrent#1142]
**What version of WebTorrent?**
0.18.0

**What operating system and Node.js version?**
Windows 10 (64bit)

**What browser and version? (if using WebTorrent in the browser)**
Google Chrome

**What did you expect to happen?**
Download to complete

**What actually happened?**
Downloading a few torrents at the moment but for some reason the down speed goes insanely high (78Mbs etc.) and then my torrent stays like that with no progress

**Comment by DiegoRBaquero** [comment]
Are you using WebTorrent Desktop? If so, please open an issue in its repository.

**Comment by ItsDizzy** [comment]
I can confirm that when the download speed goes over 10MB/s the download speed drops to around 20kb/s and will stay there. I have tested this with both webtorrent and webtorrent-hybrid.

**Comment by CallMeRev** [comment]
i can confirm that too , i seeded from a windows server vm with a 1gb/s net big buck bunny 
and used this on a diffrent box on again a windows server vm . 
I used a counter to mesure how long it would take for the webtorrent to download the file and on that server i installed utorrent and did the same test again .

Utorrent : 50 secornds to complite .
WebTorrent : 1 minute and 30 seconds .

*webtorrent seems to get stable arrount 1.5 mb download speed and it has some very tempory "speed boosts" that go to the actuall seeding upload speed but that only last 1-2 seconds , then it drops again to 1-1.5.mb

**Comment by multimedialstudio** [comment]
I can confirm speed drop.

Tested on Ubuntu Linux 16,Google Chrome latest. Performed an lo0 interface test in order to isolate the problem from network connection.

Opened several Chrome incognito windows, seeding and peering. Download speed ramped up to 12 MBps (which should be equivalent to the 100 Mbps speed of lo0) then fell to 1-2 MBps and stable,  with very temporary "speed boosts" up to 7-8 MBps for 1-2 seconds, then again back to 1-2 MBps.

I would suggest others repeat the local test on different systems in order to assess if the issue is browser and/or OS dependant.

**Comment by andreapaiola** [comment]
I'm testing the average download speed with a big file (Ubuntu ISO) which I find more interesting...

https://github.com/andreapaiola/P2P-CDN/blob/master/P2p-Cdn.js#L128

116.637739 megabits / sec

**Comment by andreapaiola** [comment]
Average download speed 7142826.576713005
Average download speed 7110193.8568471735
Average download speed 6590948.408349137
(also memory intensive)

**Comment by kmoe** [comment]
This happens when using webtorrent from nodejs as well. My download is stuck at:

```
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 314572.8
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 314572.8
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 419430.4
info: progress: 0.9794758739306746
info: just downloaded:  524288
info: total downloaded: 50041346
info: download speed: 104857.6
info: progress: 0.9794758739306746
```

**Comment by feross** [comment]
I've also noticed this jumpy download speed behavior from time-to-time. My guess is that we're downloading too fast for WebTorrent to handle processing the data (we're doing something inefficient somewhere). This spikes the CPU to 100% during which time we're blocked and not acknowledging data from peers, so they lower their speeds.

This "slowing down" response from peers could be happening at the TCP level (we don't support uTP yet) or it could be at the protocol level (we're not acknowledging the received pieces quickly when we're blocked)

Duplicate: #810
