### ISSUE TITLE
"100% downloaded ↓ 0 B/s ↑ 0 B/s"

### ISSUE THREAD

**Issue by FlaggedBrad** [webtorrent/webtorrent#1143]
![](https://i.imgur.com/c8rq8ZV.png)

Why is this a thing? The download is 100% completed, and it should not be showing a downloading message. It should probably be telling me something along the lines that my computer is buffering the video because my system is low-spec.

**Comment by DiegoRBaquero** [comment]
Please open an issue here: https://github.com/webtorrent/webtorrent-desktop
