### ISSUE TITLE
Managing subtitles and audio with video playback at runtime

### ISSUE THREAD

**Issue by KioriSun** [webtorrent/webtorrent#1144]
This is a feature request.

It would be cool if when playing a video you could choose between the many audio channels a video might have(multiple languages), and couple it with the many subtitles it might come with.
The ability to switch at any moment would complete the player in many ways.

For me, enabling VLC makes swapping the audio channels possible and I just load the srt from the downloaded folder, also forward skipping worked better(shift+arrows).

Great work!

**Comment by andreapaiola** [comment]
Well for subtitles the integration is simple...

https://andreapaiola.name/niagara/

**Comment by DiegoRBaquero** [comment]
Is this for WebTorrent Desktop? Or the webtorrent module?

If it's the module, I'd say it's out of its scope.

**Comment by KioriSun** [comment]
I was referring to the desktop app at the time.
