### ISSUE TITLE
Webtorrent browser version not working

### ISSUE THREAD

**Issue by logeshhy** [webtorrent/webtorrent#1145]
**What version of WebTorrent?** NA

**What operating system and Node.js version?** NA

**What browser and version? (if using WebTorrent in the browser)** Am using latest versions of chrome and firefox

**What did you expect to happen?** I just copied the code available on webtorrent website to stream the torrent locally from localhost

**What actually happened?** But the code as it is works fine on firefox but not in chrome, and when i change the torrent Id to any other torrents which has mp4 files.. it not streaming or downloading the torrent either in firefox or chrome

**Comment by DiegoRBaquero** [comment]
Are the torrents you are trying to stream hosted by WebRTC peers?

Please see: https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#why-does-browser-downloading-not-work-i-see-no-peers
