### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ThatFatPat** [webtorrent/webtorrent#1153]
Hi, My name is Iddo.
Amazing work on th Desktop client, keep it up!
I have a problem. I am not a native speaker and need to use subtitles.
Problem is, it's not very easy with the player...
So I'm asking for two things:

- Enabling Timeshifting for subtitles

- Integrate the OpenSubtitles API for looking up subtitles, or even just acquiring the best match.

If it helps, I can work on the behind the scenes code for getting the best match from OpenSubtitles...

Thanks anyway, and keep up the good work!

**Comment by DiegoRBaquero** [comment]
Hi @ThatFatPat.

I noticed you had already opened an issue in WD repo. To not clutter the main lib, I'm gonna close this :)
