### ISSUE TITLE
Temporary IE and Safari Support

### ISSUE THREAD

**Issue by Cheedoong** [webtorrent/webtorrent#1157]
The Temasys Plugins bring support for webRTC to Desktop versions of Safari and IE:
https://confluence.temasys.com.sg/display/TWPP

Then only thing you need to do is to include a modified version of Adapter.js:
https://confluence.temasys.com.sg/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website

**Comment by iShift** [comment]
it is bad way, you advice to install custom plugin to browser, it is flash-like way...

**Comment by DiegoRBaquero** [comment]
This has been discussed before. But it's really up to the people and website who implement webtorrent to advice users to get this plugin. WebRTC is coming to Safari and Edge already has it.
