### ISSUE TITLE
[QUESTION] Is webtorrent support P2P Live TV?

### ISSUE THREAD

**Issue by nickcartery** [webtorrent/webtorrent#1158]
Hi Everyone,

I'm a newbie in bittorent. As I see, bittorrent support Live TV, so Webtorrent also supports, right? Anyone has demo? And how can I build a streaming Live TV using bittorent protocol?

https://btlive.tv/

Thanks!

**Comment by DiegoRBaquero** [comment]
Please refer to: https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#is-it-possible-to-do-live-streaming-with-webtorrent

Related:
https://github.com/webtorrent/webtorrent/issues/448 https://github.com/webtorrent/webtorrent/issues/14 https://github.com/webtorrent/webtorrent/issues/826
