### ISSUE TITLE
Stream files to Google Drive, Dropbox or Mega.nz

### ISSUE THREAD

**Issue by abhishek-raj** [webtorrent/webtorrent#1168]
I was thinking is there a way to stream chunks of data to google drive or some other storage?

I was using web-torrent to download files to server and then download the files from the server directly as my university prevents P2P transfers but then the server just has about 500mb of hard drive space. So if it is possible to download chunks of data to googledrive and then retrieve it on the fly.

After reading most of the docs everywhere, I found out that I could implement a chunk-store for google drive but don't know much about chunk stores. Other possibilty is to pause the torrent and then create a stream to the files giving specific start and end bytes and store them to google drive but that will create a hassle if the server restarts which means then I will have to store states.

Is there some easier way?

**Comment by abhishek-raj** [comment]
I wanted to create something similar to this but using webtorrent.
https://github.com/jpillora/node-torrent-cloud

**Comment by abhishek-raj** [comment]
I think I can implement a chunk-store for google drive but can anyone help on what happens when the file is downloaded using the memory-chunk-store?

Like I can see how that works but how do I make sense of the chunks in the memory after it has been downloaded?

**Comment by feross** [comment]
@abhishek-raj When you use memory-chunk-store, the entire torrent is stored in memory. You should ensure that you have enough free RAM to actually store the entire torrent, or you'll have problems.

Once a file is complete, you can access the raw data using `file.createReadStream([opts])` or `file.getBuffer(function callback (err, buffer) {})` and do whatever you want with it.

See the docs: https://webtorrent.io/docs
