### ISSUE TITLE
Can't seed a file and then download it

### ISSUE THREAD

**Issue by pmosse** [webtorrent/webtorrent#1172]
I am using webtorrent 0.98.19 in Ubuntu 16 with Node v8.1.0.

I created a small Node app which seeds a file, and another one which tries to download it. For some reason, the download never starts, and I think the onTorrent event is never called.

You can find an example of the code in https://github.com/lautarodragan/webtorrent-test. You run it with:
- node seeder.js
- Then you copy the torrentHash into downloader.js
- Then you do node downloader.js

Thanks!

**Comment by feross** [comment]
I believe this is a NAT issue. WebTorrent does not support NATs #195
