### ISSUE TITLE
Uninstallation of webtorrent is unavailable

### ISSUE THREAD

**Issue by clixkster** [webtorrent/webtorrent#1173]
I accidentally install the webtorrent by mistake and now the chronium browser keep popping up a page title "Vuze WebTorrent Protocol". It is using 70% of my CPU resources
Please help! Thank you in advance.
**What version of WebTorrent?**
I am not sure. There is no way to check the version from the chromium browser.
**What operating system and Node.js version?**
I am not sure. Where do i check?
**What browser and version? (if using WebTorrent in the browser)**
Chromium, Version 50.0.2631.0
**What did you expect to happen?**
Uninstallation button
**What actually happened?**
As described

**Comment by DiegoRBaquero** [comment]
This seems like the Vuze WebTorrent plugin. Please contact Vuze's support.

WebTorrent Desktop app can be uninstalled. This is the core lib
