### ISSUE TITLE
MKV without subtitles

### ISSUE THREAD

**Issue by Rei-Kodoku** [webtorrent/webtorrent#1174]
When stream a video in MKV format, the enclosed subtitles doesn't appear.
EDIT: Probably the problem is the format of subtitles .mks and .ass
I would suggest making these formats compatible as they are very much used.

**Comment by karuppiah7890** [comment]
I think SRT is more widely used

**Comment by DiegoRBaquero** [comment]
Subtitles are out of the scope for the core lib.
