### ISSUE TITLE
How to buid a web site power by webtorrent?

### ISSUE THREAD

**Issue by ddyllen-z** [webtorrent/webtorrent#1176]
I have try the example on offical site. And replace torrentId to my magnet uri,it can not to play.
no error, no request, nothing to do.
How to do?

**Comment by DiegoRBaquero** [comment]
Please see https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#why-does-browser-downloading-not-work-i-see-no-peers

**Comment by ddyllen-z** [comment]
It's means torrent file or magnet uri must contains wss protocol tracker?
I tested magnet uri:`magnet:?xt=urn:btih:2b0250c18e54598bb4eee99fe9d8b24e12a45787&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=http://tr.cili001.com:8070/announce&tr=http://tracker.trackerfix.com:80/announce&tr=udp://open.demonii.com:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337&tr=wss://tracker.openwebtorrent.com&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz`
Tracker wss://tracker.btorrent.xyz connect ok.
vuze download fast，webtorrent page no peers.

**Comment by DiegoRBaquero** [comment]
No, it means that it must be seeded by webrtc peers.

Diego R.

**Comment by ddyllen-z** [comment]
I got it, thanks
