### ISSUE TITLE
Got an error "out of memory" while streaming a large video file.

### ISSUE THREAD

**Issue by zikoops** [webtorrent/webtorrent#1177]
**What version of WebTorrent?**
The latest (I'm embeding the script)

**What operating system and Node.js version?**
v8.4.0

**What browser and version? (if using WebTorrent in the browser)**
Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**What did you expect to happen?**

**What actually happened?**
I was streaming a video file quite large (2 GB), it was really smooth at very first of the video but after a while, Webtorrent downloaded a half of content, my browser got lag and crashed with error "out of memory"
I think it is about my Webtorrent application used over of memory on my computer, so is there any way to handle it?
I used example code "HTML example with status showing UI" part in [this thread](https://github.com/webtorrent/webtorrent/blob/master/docs/get-started.md)
Thanks!

Update 1:
There is a new error on chrome "Aw, Snap! Something went wrong while displaying this webpage".

**Comment by feross** [comment]
This used to be a Chrome bug, but it was fixed. Chrome can handle seeding files larger than 500MB now.

You still might see this error if:

- You're seeding torrents that are larger than the amount of RAM that you have (by default, WebTorrent uses an in-memory file store in the browser)
- You're on a 32-bit OS, in which case no process on the system is allowed to use more than ~2-4GB RAM

**Comment by feross** [comment]
Duplicate https://github.com/webtorrent/webtorrent/issues/319
