### ISSUE TITLE
CPU Intensive on RPi 

### ISSUE THREAD

**Issue by santiac89** [webtorrent/webtorrent#1179]
**What version of WebTorrent?** 0.98.19

**What operating system and Node.js version?** OSMC 2017.07-1 and Node v8.2.1

**What actually happened?**

I'm working on an app to use my RPi as a Media Center and use webtorrent library to download files to later see them on my TV. My app includes an API to also be able to start torrents from the browser. What happens is that when downloading any torrent the RPi CPU goes 100% every time even if I disable all my other app features.
Is this a common behavior for a RPi downloading torrents using this library or I'm missing something? 

Also, all my videos gets broken, can this be related to the stress the RPi is having?

Edit: Forgot to mention, I've configured the app to download all my files to an external USB drive. I think that this can be affecting it also.

I leave my app repo just in case https://github.com/santiac89/odin

**Comment by ojoel** [comment]
How many connections?  Each connection has a transfer overhead AND a processing load.

**Comment by santiac89** [comment]
How many connections from where?

**Comment by feross** [comment]
WebTorrent has CPU utilization issues. It has no notion of a resource queue – it tries to do everything at once, as fast as possible, which leads to lots of CPU contention.

One workaround you can try is to lower the `maxConns` property to the `WebTorrent` constructor, which will limit the number of connections to peers (and therefore the total amount of work done). More info in [the docs](https://webtorrent.io/docs).

Follow #903 for updates on this issue.
