### ISSUE TITLE
Torrent stalled when added > removed > added again

### ISSUE THREAD

**Issue by pldubouilh** [webtorrent/webtorrent#1180]
Webtorrent fails at starting torrents that were previously added and then removed.

I observe that behaviour both in the desktop app and the web-ui for webtorrent I'm writing ([here](https://github.com/pldubouilh/webtorrent-webui)), hence me writing here directly in webtorrent/webtorrent.

**What version of WebTorrent?**
0.98.19

**What operating system and Node.js version?**
Archlinux latest kernel, node v8.1.3

**What did you expect to happen?**
Torrents to start.

**What actually happened?**
+ Add torrent with magnet link on webtorrent-desktop
+ Wait for it to download (download kicks off instantly on very active torrents)
+ Remove torrent (no matter if it's `data` or `from list`)
+ Add magnet link again

... and that's where it's stuck, at `Loading torrent...`. After leaving it for ~15 minutes it's starting and switching between halted and very low speed (100s of KB/s where the normal speed is close to 10MB/s)

I noticed pausing and restarting sometimes makes it restart at normal speed on webtorrent-desktop. 
On the web-ui, the only reliable way I could find was to destroy the client, and restart all the torrents, but that seems a bit drastic !

Thanks !

**Comment by Fabiencdp** [comment]
I noticed the same issue when using infohash, 
`client.add(infoHash)` 
But it work as excepted when using magnet link or http link.
When using infoHash, then deleting torrent, then reusing the same infoHash, the "on('metadata')" event is not triggered.   

@pldubouilh, Did you find a better solution ?
