### ISSUE TITLE
webtorrent resolve but do not download - FR

### ISSUE THREAD

**Issue by Sibiraj-S** [webtorrent/webtorrent#1181]
**What version of WebTorrent?** 0.98.19

**What operating system and Node.js version?** Windows, Node 8+

**What did you expect to happen?**
```
var client = new WebTorrent();
client.resolve(torrentId, function (torrent) {
       console.log(torrent); // torrent information but don't download
});
```
**What actually happened?**
this starts downloading file automatically

  ```
var client = new WebTorrent();
client.add(torrentId, function (torrent) {
       /* ... */
 });
```
is there any method available to get torrent information including 
```
torrent.torrentFile
torrent.torrentFileBlobURL
```
feature to not start downloading files automatically will be nice. or am I missing something

**Comment by DiegoRBaquero** [comment]
The only thing that you could get without actually downloading any data is the metadata of the torrent. Not the files, not the blob url.

resolve is not in the API, so this is not a bug, is a feature request.

**Comment by Sibiraj-S** [comment]
Yes that was a feature request .

**Comment by Sibiraj-S** [comment]
@DiegoRBaquero Any updates on this FR?

**Comment by DiegoRBaquero** [comment]
I don’t think that anyone is working on this

**Comment by Sibiraj-S** [comment]
it will be nice to know what are the files that we are going to download. before start downloading. also, we can save that as a .torrent file

**Comment by DiegoRBaquero** [comment]
can you not do that with the code you posted?

**Comment by Sibiraj-S** [comment]
yeah, I have been doing that. But that is a cool feature to have. isn't it

**Comment by DiegoRBaquero** [comment]
It'd be best to have it as another module built on top of the core lib. Feel free to publish your code as a standalone npm module. I'm gonna leave this open for anyone (or you) who wants to build it :)
