### ISSUE TITLE
Torrent streams over TLS

### ISSUE THREAD

**Issue by dmarkwat** [webtorrent/webtorrent#1190]
There's a feature provided under the BitTorrent [reference manual](http://libtorrent.org/manual-ref.html#ssl-torrents) for peers to communicate with one another over SSL/TLS for torrents specifying the 'ssl-cert' field in their info metadata.  I'm curious if webtorrent offers this ability to communicate over TLS (far as I can tell it does not?), if there is any plan or interest to, or if there's a recommended approach to accomplishing this.

I saw the 'ssl-cert' field was added to create-torrent ([issue here](https://github.com/webtorrent/create-torrent/issues/9)) but I don't see any reference within the webtorrent code to support its presence and use.  I did a fair bit of digging over the weekend and I made some progress with a hacked-up impl but am blocked in a few places where a TLS handshake would almost certainly be prone to getting bungled -  by intervaled events being sent or even the Wire picking up the handshake and mistaking it for a message.  Figured now would be a good time to ask if this is even something of interest before I spent more time on it :)

**Comment by knoxcard** [comment]
Yes, dont ISP's look at this data, is everything encrypted?  Good point.

**Comment by feross** [comment]
> I saw the 'ssl-cert' field was added to create-torrent (issue here) but I don't see any reference within the webtorrent code to support its presence and use.

We added support to create torrents with this field, but the WebTorrent engine doesn't support it.

> Figured now would be a good time to ask if this is even something of interest before I spent more time on it :)

This is a neat feature, but I'm skeptical that this is useful in practice. You have to have to set up certificate signing for each peer in some out-of-band method.  What is the actual use case for this?
