### ISSUE TITLE
feature request - chunk versioning

### ISSUE THREAD

**Issue by raxim1** [webtorrent/webtorrent#1192]
### # I would like to discuss about the feasibility of two requirements:
**I have a custom file format which has got index table about particular chunks of the file. The file can be split up by chunks and merge.

1, version control of the chunks. (it's not git related as it need to be a developer)
2, download part of the file on demand**

**Scenario:**
Servers are very expensive if you would like to hold large downloadable files on it, so it would drastically reduce the cost.

Lets say i have a board and i draw on that, and save update the chunk of the file, i need to push my changes to a server or client i'm not sure at the moment. (whether i need to think on a centralized tracker which is cost related so not ideal)

So what it does it queries the server or clients and make a sync with my file chunk, so i see every modification on my board and i can fix and check in.

It's a very large board, so i'm not interested to download anything else, just what i see, so i can seed not the file itself, just the chunk of it, what i have previously used.

I saw the boarding example, but it's a little bit more.

The board example might not entail why this whole thing is important, but the versioning can be used as a decentralized software updater. (to make a better example)

That's it!!!

I have posted it, as reading through the webtorrent code, it's quite hard. No typescript has been used, no class files, just prototypes. I saw the Azure code some years ago, and my feeling is, that node related code is similar. (classes which holds hundreds of lines of code without any single responsibility)

It simply takes much more time to me, what i have expected to introduce my changes.

I have just created a good example how to use Electron with typescript and ionic.

In this case i'm not thinking in Electron, the file saving will be in the IndexedDB.

Parallel library can use async or Promise.
If you use typescript, you can use decorators which i love. (because of code simplification)

**Comment by miketamis** [comment]
You can do number 2 with the current API. First I would deselect the whole torrent using `torrent.deselect(0, torrent.pieces.length - 1, false)`, then you can prioritize (enable) chunks using either `torrent.select` or `torrent.critical`

as for number 1, I'm not sure if that would be possible given how torrents work, my suggestion would be to break it up into multiple torrents, you can still share peers across the torrents so there shouldn't be a big overhead.

**Comment by raxim1** [comment]
Thanks for your comment. The 1. point is an extension either way. I had some idea and worked 1,5 month on the whole thing what i would have liked to do, but the fact is it's though. I might share the exact idea and try to raise some money to organize a competition, quite challenging either way. (it's far from the board game) I have a fear that if i'm sharing my idea and my code it won't make any difference, nobody will help me, as many github project hasn't reached even the first version, the npm repository is a nightmare, i have to say just fiddling around, looking for project, and 10-15% is working in a way it should be without glitches. Free software is a good thing, just it's not how things are developing in this world, i have to admit. (the idea is an edge of webrtc + DHT + lots of other stuff - probably it can make the version controlling in the torrent word a reality:)) At least it can clean up its javacript base. Thanks anyway.
