### ISSUE TITLE
webtorrent-hybrid download torrent error - libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by etzto** [webtorrent/webtorrent#1202]
**What version of WebTorrent?**
1.10.1 (0.98.19)

**What operating system and Node.js version?**
CentOS Linux 7 / Node.js v6.11.3

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
I wanted to download a torrent on my server using webtorrent-hybrid

**What actually happened?**
error during download, more details in print

![bug](https://user-images.githubusercontent.com/32571834/31279182-7d662986-aa7e-11e7-887e-96d56b5cba67.png)

**Comment by DiegoRBaquero** [comment]
You must install `libgtk-x11`, name may vary.
