### ISSUE TITLE
Multi-language support.

### ISSUE THREAD

**Issue by funny110** [webtorrent/webtorrent#1204]
Many people want to translate WebTorrent to other languages, but WebTorrent do not support.

**Comment by DiegoRBaquero** [comment]
Is this about the Desktop app?

**Comment by funny110** [comment]
@DiegoRBaquero Yes, desktop app.

**Comment by DiegoRBaquero** [comment]
See https://github.com/webtorrent/webtorrent-desktop/issues/371
