### ISSUE TITLE
Removing a torrent doesn't release memory in the browser

### ISSUE THREAD

**Issue by skzap** [webtorrent/webtorrent#1208]
**What version of WebTorrent?**
0098

**What browser and version?**
Chromium 59

**What did you expect to happen?**
Ability to seed a 500 MB file, remove it, seed **another** 500MB file, remove it, seed another 500MB file,  etc... without the total memory usage growing
**What actually happened?**
Removing a torrent doesn't release the memory, therefore after a finite amount of steps, the maximum tab memory usage gets reached.

You can open the chrome task manager to check memory usage.(shift + escape)
You can try through https://btorrent.xyz/ where the same behavior happens.

**Comment by DedSec002** [comment]
This issue is not just with seeding the file but also been a same problem when other common operations done on chrome... You can use plugins to limit the usage on each request you make

**Comment by DiegoRBaquero** [comment]
Could be, I'd need to check. @skzap does it happen only in btorrent or is it a general thing?
