### ISSUE TITLE
can i watch torrents without downloading it as i do in youtube,just watch and run?

### ISSUE THREAD

**Issue by manyasurvey** [webtorrent/webtorrent#1209]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by DiegoRBaquero** [comment]
That's the default on the browser, torrent is not persisted, remains in RAM.

**Comment by manyasurvey** [comment]
what? dont understand sorry ): please tell me in simple language sir and u know that its application also not opening it was opened only once,it opens only in taskbar but not in fully not even in minimized ):
![capture](https://user-images.githubusercontent.com/32989944/31856525-a35e7562-b6e0-11e7-9975-2db699a4ee94.PNG)

**Comment by DedSec002** [comment]
try my website www.hawabytes.com
