### ISSUE TITLE
how I cand handle errors when adding torrents to a client?

### ISSUE THREAD

**Issue by rafaelleru** [webtorrent/webtorrent#1210]
I tryed `client.add(t, function(err, torrent){manage error if it  happens here})` but didn't work.

**Comment by alxhotel** [comment]
I believe you can do something like this:
```js
client.on('error', function (err) {
  // Handle error
})
client.on('warning', function (err) {
  // Handle warning
})
```

**Comment by rafaelleru** [comment]
Yes but I want to manage the duplicated torrent and invalid torrent identifier when adding a torrent.
So I need to get the errors in the callback `client.add(torrent, callback(err, torrent))`

**Comment by DiegoRBaquero** [comment]
@rafaelleru You need to use the error event of the client.

The onTorrent callback function of `client.add` is not an error-first callback function.

**Comment by feross** [comment]
You can also listen for the `'error'` event on the torrent object, which is more specific than the client `'error'` event.

```js
torrent.on('error', function (err) {})
```

From the [docs](https://webtorrent.io/docs):

> Note: Torrent errors are emitted at torrent.on('error'). If there are no 'error' event handlers on the torrent instance, then the error will be emitted at client.on('error'). This prevents throwing an uncaught exception (unhandled 'error' event), but it makes it impossible to distinguish client errors versus torrent errors. Torrent errors are not fatal, and the client is still usable afterwards. Therefore, always listen for errors in both places (client.on('error') and torrent.on('error')).
