### ISSUE TITLE
Live Stream From Webcam

### ISSUE THREAD

**Issue by MegaUITeam** [webtorrent/webtorrent#1214]
The subject is a duplicate, but all the previous topics DO NOT give any answer at all, and are closed. So let's once and for all answer the question.

if the `seed` method can get a "Readable stream", then why we can not get getUserMedia stream into Readable stream?`

like:
```javascript
navigator.getUserMedia({audio: true, video: true}, function(mediaStream) {

  var readableStream = convertToReadableStream(mediaStream)
  client.seed(readableStream )

})
```

I know that this is beyond the scope of the project, but still. This is an extremely important feature. Everyone can create their own Twitch without having hundreds of data centers!

I'm not asking you to come up with an implementation of the convertToReadableStream function, I'm asking: IS THIS CONCEPT IN THE PRINCIPLE POSSIBLE )?

**Comment by MegaUITeam** [comment]
Well, I realized that the only way out. Divide the video into chunks, seconds into 20, and take each chunk as a file. But then the question is how to give all the spectators a magnet link to the NEXT chunk?

**Comment by DiegoRBaquero** [comment]
This is not something part of the core lib itself. It must be built on top of it. You want to keep 2 chunks at all times, current and next to be able to have the reference inside of the torrent.

A torrent is inmmutable, but there's a BEP: https://github.com/webtorrent/webtorrent/issues/886

See: https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#is-it-possible-to-do-live-streaming-with-webtorrent

**Comment by MegaUITeam** [comment]
@DiegoRBaquero Fuck you shut the ticket? we did not finish it. I asked a clear question. Is there any method for all torrents to distribute a message?

**Comment by DiegoRBaquero** [comment]
Yes, I closed it, doesn’t mean the conversation is closed. And no, there’s not a method for such thing. You would need to create an extension.

Diego

**Comment by MegaUITeam** [comment]
> I closed it, doesn’t mean the conversation is closed.

damn, sorry, I'm from russia and I did not know)
I was always angry that my discussions are closing.
