### ISSUE TITLE
Update CHANGELOG for RELEASES

### ISSUE THREAD

**Issue by Sibiraj-S** [webtorrent/webtorrent#1215]
Update either changelog in GitHub or in the documentation.

**Comment by DiegoRBaquero** [comment]
We are very outdated on it, I'll add latest release info.

**Comment by Sibiraj-S** [comment]
Why not use [standard version](https://github.com/conventional-changelog/standard-version) or [semantic release](https://github.com/semantic-release/semantic-release)

**Comment by DiegoRBaquero** [comment]
Would really like to implement semantic release when I find the time
