### ISSUE TITLE
Warning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by marcelodelta** [webtorrent/webtorrent#1216]
**What version of WebTorrent?**
"webtorrent": "~0.98.20" 

**What operating system and Node.js version?**
v6.11.1

**What browser and version? (if using WebTorrent in the browser)**
N/A

**What did you expect to happen?**
Do not show this message again and worning

**What actually happened?**
I am getting this message in the node console when I start a torrent client.

Warning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by alxhotel** [comment]
Duplicate of #889
