### ISSUE TITLE
Why not use lerna and have all the modules under a single repo ?

### ISSUE THREAD

**Issue by askamist** [webtorrent/webtorrent#1217]
I think having all the modules under one repo helps development because these modules are inter-dependent. especially when there are changes that has to made across these modules.

So why not use [lerna](https://lernajs.io/) ?

**Comment by DiegoRBaquero** [comment]
The modules are inter-dependent, but are also independent. Rarely does it happen that an update on one means update on the other.

**Comment by askamist** [comment]
But When It does one has to create a pull request on the first repo get it merged then create a pull request on the second repo. Don't you think it would discourage contributions ? and I don't think It is so rare.

**Comment by DiegoRBaquero** [comment]
Changes to each module need to be submitted apart, however, I see the benefit while releasing at the same time, but again, that rarely happens in webtorrent, we need to keep things simple and avoid too much tooling, it's fatiguing.
