### ISSUE TITLE
Download does not start when using a webseed torrent.

### ISSUE THREAD

**Issue by marcelodelta** [webtorrent/webtorrent#1218]
I created a torrent with the create-torrent module.
I am using a webseed in these torrent.

**What version of WebTorrent?**
webtorrent web
v0.98.18

create-webtorrent
v3.29.2

**What operating system and Node.js version?**
v6.11.1

**What browser and version? (if using WebTorrent in the browser)**
Google Chrome

**What did you expect to happen?**
The download starts

**What actually happened?**
The webtorrent web and desktop does not load too.
No error is shown, just nothing happens.
The download does not start.

**Comment by DiegoRBaquero** [comment]
Can you please provide the torrent file, the webseed url and the full debug logs?

**Comment by marcelodelta** [comment]
Hi Diego,

Torrent: www.mwti.com.br/video.torrent
Video:  www.mwti.com.br/video.mp4

Where is the full log?

**Comment by DiegoRBaquero** [comment]
For debug logs: https://github.com/webtorrent/webtorrent#enable-debug-logs

Can you enable CORS in your server too?

**Comment by marcelodelta** [comment]
CORS is enable
Log in attachament

[localhost-1509423587965.log](https://github.com/webtorrent/webtorrent/files/1429583/localhost-1509423587965.log)

**Comment by DiegoRBaquero** [comment]
It does try to start for me, but, as I'm trying from btorrent.xyz, the non-https requests to your webseed are blocked. You should set your webseed to use https.

**Comment by marcelodelta** [comment]
Yes it's the same file.
No peers are found.

The CORS configuration of my file.
Files "video.mp4">
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Methods: "*"
  Header set Access-Control-Allow-Headers: "Origin, X-Requested-With, Content-Type, Accept"
</Files>

I even tried using the magnet link
magnet:?xt=urn:btih:699f6411bc409254234ff5413ddc59dbedb54f63&dn=video.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=http%3A%2F%2Fmwti.com.br%2Fvideo.mp4

**Comment by DiegoRBaquero** [comment]
Can you enable cors for the torrent file as well?

**Comment by marcelodelta** [comment]
video.torrent enable.

I use the magnet to load the webtorrent

**Comment by marcelodelta** [comment]
With the video.torrent file the webtorrent works.

When I use the magnet link the webtorrent does not find the webseed.

**Comment by Chocobozzz** [comment]
Torrent file is mandatory when using webseed. You can specify the torrent URL in magnet URI with `xs` parameter: https://github.com/webtorrent/webtorrent/issues/875

**Comment by marcelodelta** [comment]
It is work.
