### ISSUE TITLE
what port did webtorrent use? browser keep loading

### ISSUE THREAD

**Issue by teddybugs** [webtorrent/webtorrent#1220]
Im using the latest webtorrent with videojs, seeding with webtorrent-desktop windows.

i have uploaded the same code to 2 of different server, one is working fine, able to stream the video, but another one is keep spinning (loading forever, no player, no html, just blank, http status did not show 200 or 404, 500 just loading). i wonder did the webtorrent js query the torrent with some sort of port and get blocked by firewall of the server or network?

-on my windows 7 localhost using wamp, it working fine. just one of the centos server failed to load. any idea?

**Comment by DiegoRBaquero** [comment]
1. What's your code? Are you using the minified webtorrent, using the module with browserify?
2. How is the code being published, please link to both.
3. Can you post full debug logs?

**Comment by teddybugs** [comment]
What's your code? Are you using the minified webtorrent, using the module with browserify?
-> webtorrent.min.js
How is the code being published, please link to both.
-> using winscp on ssh
please check at:
http://avs.topcat.io/demo/ (not working)
http://pino.suka.se/demo/ (working fine)

#both are same copy.

Can you post full debug logs?
#on F12 - console, just blank, nothing showing.

**Comment by DiegoRBaquero** [comment]
It seems like a problem with the web server, as the page won't load. Not really a webtorrent issue
