### ISSUE TITLE
Download speed units

### ISSUE THREAD

**Issue by hector** [webtorrent/webtorrent#1225]
I have the impression that there is a mistake in the download/upload speed units. For transfer speeds the norm is to us bits, or Kilobits (Kb) and Megabits (Mb), opposed to bytes, or Kilobytes (Kb) and Megabytes (MB) etc., which are used for file size.

I see the use of bytes for download/upload speed. Any clue about that?

**Comment by DiegoRBaquero** [comment]
This is normal. It simplifies what you show. It's directly connected to what will actually consume in disk.

If you want to get the bits/s, simply multiply by 8.

**Comment by hector** [comment]
Great, thank you for the information. There's always something new to learn :)
