### ISSUE TITLE
client.add's callback does not get called

### ISSUE THREAD

**Issue by Hissvard** [webtorrent/webtorrent#1227]
**What version of WebTorrent?**
0.98.20

**What operating system and Node.js version?**
Ubuntu 17.04, Node v8.2.0

**What browser and version? (if using WebTorrent in the browser)**
Chrome 61

**What did you expect to happen?**
I'm trying to use webtorrent in a React app.

**What actually happened?**
I'm using webpack - I initially tried to import webtorrent like

```javascript
import WebTorrent from 'webtorrent';
```

But got errors related to the fs module not being found - makes sense since I'm running the app inside a browser. I "solved" this issue the same way a user in another issue did, importing the minified version like

```javascript
import WebTorrent from 'webtorrent/webtorrent.min';
```

However this seems to produce a nasty litttle warning
![image](https://user-images.githubusercontent.com/19749322/32692900-e2ed0a54-c720-11e7-8ebf-094a3464d4c3.png)
And this snippet doesn't work:

```javascript
import WebTorrent from 'webtorrent/webtorrent.min';
const client = new WebTorrent();
const torrentMagnet = torrentData.magnet;
client.add(torrentMagnet, (torrent) => {
    console.info("YAY!");
    console.log(torrent);
});
```

Does not produce errors, but the callback is never called.

**Comment by DiegoRBaquero** [comment]
The callback is called when metadata is fetched. You might be using a magnet which is not seeded anywhere. Try the same magnet in instant.io
