### ISSUE TITLE
Example with other torrent files

### ISSUE THREAD

**Issue by Wertos** [webtorrent/webtorrent#1228]
**What version of WebTorrent?**
0.98.20
**What operating system and Node.js version?**
Centos 7 x64, Node v6.11.3
**What browser and version? (if using WebTorrent in the browser)**
Opera 51.0.2776.0 (PGO)
Microsoft Edge 41.16299.15.0
**What did you expect to happen?**
View video in browser
**What actually happened?**
https://codepen.io/yciabaud/pen/XdOeWM Here is an example, it works only with the torrent file that is specified there. I substituted the links to different torrent files, not with one given example no longer works.
The video file itself must be present on the server? I read the documentation ... I do not understand what I'm doing wrong?

**Comment by DiegoRBaquero** [comment]
The torrent must be seeded by WebRTC (webtorrent) peers. Even if you find the most popular torrent in a directory, it might not be seeded by WebRTC peers at all, so it won't work.

Please read https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#troubleshooting

**Comment by Wertos** [comment]
Thanks, did not see.
My plans collapsed :(
