### ISSUE TITLE
Leaked IP information when using WebTorrent?

### ISSUE THREAD

**Issue by mayeaux** [webtorrent/webtorrent#1232]
Hi there, I'm considering incorporating WebTorrent into a project I'm doing but am worried about privacy concerns. Obviously the torrent mechanism will have to make one's IP public via WebRTC, just to be clear this means that someone can note who is seeding certain information based on their IP, right? Thanks

**Comment by Ciao121** [comment]
Yes.

**Comment by mayeaux** [comment]
Thanks, what's the API for logging current connections from the console?

**Comment by DiegoRBaquero** [comment]
There's not a direct API method for that. You need to iterate over all the wires.
