### ISSUE TITLE
Sending updates to the tracker

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent#1236]
**What version of WebTorrent?**
0.98.20
**What operating system and Node.js version?**
Win10/8.5.0
**What browser and version? (if using WebTorrent in the browser)**
Electron

I'm building an electron app. I just noticed that my app does not send updates to the tracker at all (I'm using bittorrent-tracker, ws protocol and --interval option) as I see webtorrent-desktop does, and I cannot find out why.

I tried to find where this happen in webtorrent-desktop but I couldn't find it (maybe because "update" is a very generic term and I'm loosing myself in the code).

Can somebody give an help to find the problem?
Thank you!!

**Comment by DiegoRBaquero** [comment]
What do you mean "send updates to tracker"?

**Comment by Ciao121** [comment]
When I seed a local file using webtorrent-desktop I can see on the tracker console those events:
```
start: 2d5757303039382d425745706f536b5465486c58 (when I start seeding)
update: 2d5757303039382d425745706f536b5465486c58 (repeating exery x secondos/minutes)
update: 2d5757303039382d425745706f536b5465486c58
update: 2d5757303039382d425745706f536b5465486c58
stop: 2d5757303039382d493450363365576d33586e48(when I stop seeding)
```
With my client the updates events are missing and I only get:

```
start: 2d5757303039382d493450363365576d33586e47 (when I start seeding)
stop: 2d5757303039382d493450363365576d33586e47 (when I stop seeding)
```

**Comment by DiegoRBaquero** [comment]
Are you using node version in electron, or browser version?

**Comment by Ciao121** [comment]
In electron.

**Comment by Ciao121** [comment]
mmmm I think I have found the problem...
I copied in my app the bittorrent-tracker module folder form webtorrent-desktop and it sends updates now.
I'm now looking if was something I changed  in my bittorrent-tracker module folder.. I really do not remember... I'll **update** :)

**Comment by Ciao121** [comment]
Ok, sorted out.
in my app's /node_modules/bittorrent-tracker/lib/client/tracker.js
lines 
```
  if (intervalMs) {
    self.interval = setInterval(function () {
      self.announce(self.client._defaultAnnounceOpts())
    }, intervalMs)
    if (self.interval.unref) self.interval.unref()
  }
```
were commente out :/
Really can't remember if/when/why I did it.

**Comment by DiegoRBaquero** [comment]
ALright :)
