### ISSUE TITLE
Custom video player (Videojs)

### ISSUE THREAD

**Issue by payflix** [webtorrent/webtorrent#1238]
Did anyone figured out how to use the .renderTo function with videojs lib?

**Comment by Chocobozzz** [comment]
Yes, we use VideoJS with WebTorrent in PeerTube.

See the plugin we made https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/peertube-videojs-plugin.ts (that we use here: https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/videos/%2Bvideo-watch/video-watch.component.ts#L286).

Basically you just need to call `videojs` function on the HTML element, and then use the `renderTo` function to render data in the element.

**Comment by payflix** [comment]
@Jad3z I have the exact same issue.
Like @Chocobozzz mentioned he made a plugin because videojs is missing some components to work with webtorrrent. But it would be great if we could figure out the minimum adjustments to the videojs library.

**Comment by Jad3z** [comment]
This seems to fix the play issue:
@Chocobozzz videojs plugin
`
//  Hack to "simulate" src link in video.js >= 6
videojs.src = function() {
	return true;
}
`
Still trying to figure out to fix the forward and backward freezing issue

**Comment by Chocobozzz** [comment]
Yes, I forgot to add that you need this [monkey patch](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/peertube-videojs-plugin.ts#L197) with VideoJS >= 6.
