### ISSUE TITLE
Cole websocket connection under a condition

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent#1239]
Hi,
when a seeder changes ip (e.g. switching from a vpn to another one) the websocket connection to the tracker is still available. I'd like to disconnect the seeder from the tracker when this happens. So my idea was to kill the websocket connection (on the seeder client I'm making). But I can't find how to do it.

**Comment by DiegoRBaquero** [comment]
You would need to detect IP changes on the seeder and make it disconnect. There must be packages to detect IP, you'd need to set an interval in which it's checked.

**Comment by Ciao121** [comment]
Thanks @DiegoRBaquero 
I'm already detecting the IP change. What I'n not understanding is how, in the client, to close the WS connection (and to reopen a new one later) to the tracker. Right now I'm using client.destroy() but this also destroy client.torrent, calculated hashes etc etc.

**Comment by DiegoRBaquero** [comment]
Destroy the bittorent-tracker client, not the webtorrent client. See: https://github.com/webtorrent/bittorrent-tracker#client
