### ISSUE TITLE
Cast blob to chromecast?

### ISSUE THREAD

**Issue by payflix** [webtorrent/webtorrent#1240]
Using webtorrent in the browser it seems impossible to cast any media directly because of the blob format.
Did anyone experienced this issue, and if so did you solved it?

**Comment by feross** [comment]
If you stream the torrent into a video tag with `file.appendTo()` or `file.renderTo()` then you'll get a video tag. From there, how to get it onto a Chromecast is up to you. I think there's Chromecast library or SDK for that.
