### ISSUE TITLE
[query] Does WebTorrent expose my IP address via BitTorrent?

### ISSUE THREAD

**Issue by kwill** [webtorrent/webtorrent#1242]
Your FAQ addresses whether WebTorrent exposes my IP address via WebRTC when running over a VPN. Thanks for the confirmation!

However, my understanding is that the BitTorrent protocol itself exposes IP addresses, making it unsuitable for address-hiding over VPN (or Tor, not that you should be running torrents over Tor). Does WebTorrent inherit this characteristic?

For example, if I was running a torrent with WebTorrent, and a peer on the same torrent was using Vuze, would they be able to see my IP address?

**Comment by DiegoRBaquero** [comment]
It exposes the facing IP, if you use a full VPN it shouldn't expose your real IP.
