### ISSUE TITLE
tracker.fastcast.nz down/dead again - happens often - possibly remove it from js script?

### ISSUE THREAD

**Issue by ventz** [webtorrent/webtorrent#1244]
It seems that tracker.fastcast.nz is down/dead -- not even resolving in DNS for quite some time now.
(Host tracker.fastcast.nz not found: 3(NXDOMAIN))

It also seems like this happen quite often/for long periods of time.
Could you remove it from the JS script?

**Comment by DiegoRBaquero** [comment]
@jakefb, should we remove it?

**Comment by jakefb** [comment]
@ventz @DiegoRBaquero Sorry I forgot to renew the domain. I have a full time job now so I can afford to keep the domain renewed so it doesn't expire again.

The previous time was to do with the web server, we solved the issue so hopefully it doesn't go down again.

**Comment by DiegoRBaquero** [comment]
Thanks
