### ISSUE TITLE
Problem when seeder disconnect/reconnect

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent#1245]
Hi,
Let's say I'm seeding 5 files; if I disconnect the seeder, e.g. disconnecting ethernet cable for few second and reconnecting it, the seeder only sends an annonunce for one of the seeded files. All others file are not announced (I do not receive those on the tracker). But in client.torrents I can see all seeded files.
Any idea why is this happening?
Thank you!

**Comment by Ciao121** [comment]
This is happening using ws to send announces. using udp it seems it works fine.

**Comment by DiegoRBaquero** [comment]
It should send announces every 120 seconds by default iirc

**Comment by Ciao121** [comment]
@DiegoRBaquero ,
thanks for your answer. But the problem is not about the timing.
If the seeder is seeding 5 files it sends 5 updates in the interval (default 120 sec if you remember right). But if the communication is interrupted (e.g for 5 seconds disconnecting the lan cable) and reconnected, the client only sends updates for 1 of the 5 seeded files. 
And, as I said, this happen only sending updates to a ws tracker. When sending to a udp tracker all 5 announces are send.

I saw this adding a console.log('update') after
`WebSocketTracker.prototype._onAnnounceResponse
`in bittorrent-tracker/lib/client/websocket-tracker.js

You may now know that I'm not really a programmer (^_^) and not really inside the torrent protocol. So I'm sorry if I'm misunderstanding something...

**Comment by Ciao121** [comment]
I'm investigating why I do have this issue.
Looking at /bittorrent-tracker/lib/client/websocket-tracker.js
The code at 
WebSocketTracker.prototype._startReconnectTimer = function () {
.....
}

Is executed as many times as the number of seeded files.
So, if I'm seeding 5 files, it is executed 5 times. It's like if a websocket connection to the tracker is needed for every seeded file (I don't think this is true)

When the seeder reconnects the first "expected socket"(???) 
self.reconnecting is set to false
and all "missing expected sockets" are not reconnecting so, I presume, announces are not sent for files "associated" to those sockets.

Sorry for my english. It's not easy to clearly explain a such technical thing :)

**Comment by Ciao121** [comment]
I made a video (look ad 1080p) where the problem is very clear. I used a very short tracker update interval to make the video.
https://www.youtube.com/watch?v=ekFrREJAlQs

**Comment by feross** [comment]
Thanks for reporting this and for the helpful video. Sorry for the long delay. This looks like a real bug. If it's still in the current version, we should fix it.
