### ISSUE TITLE
MPEG-DASH With Webtorrent

### ISSUE THREAD

**Issue by DanielRios549** [webtorrent/webtorrent#1246]
Webtorrent version 0.98.20, Ubuntu Gnome 16.04, Node 8.9.3, Opera 49.0.2725.56

Is there an way to use webtorrent side by side with dash.js, or just use segmented videos with webtorrent directly? Actually, either I use webtorrent with normal videos, such as mp4 files, or I use dash.js to make use of segmented videos.

**Comment by DiegoRBaquero** [comment]
Not right now. WebTorrent is supported by videostream package which only supports one mp4 file to be streamed.

I don't know if any implementation to use webtorrent's file in dash to join them

**Comment by feross** [comment]
You can always pull the raw data out of the files you need with `file.createReadStream({ start, end })` to make your DASH player implementation work.
