### ISSUE TITLE
It does not work inside a worker.

### ISSUE THREAD

**Issue by ander7agar** [webtorrent/webtorrent#1248]
**What version of WebTorrent?**
WebTorrent 0.98.20
**What operating system and Node.js version?**
Ubuntu 17.10 Artful with Node 8.9.0
**What browser and version? (if using WebTorrent in the browser)**
Electron framework
**What did you expect to happen?**
I am developing a desktop application with Electron that WebTorrent uses to download and share files. So far I started the WebTorrent along with the rest of the application's scripts and it worked perfectly. The bad thing is that sometimes the application froze, so I decided to run the WebTorrent in a different thread. I have done it with the `workerjs` module, the communication between the processes works correctly, I can add files and it returns the result without problems. 
**What actually happened?**
What happens is that it does not share the files nor download them. If I do not use the Worker everything works fine, except that it freezes the application.

**Comment by RationalCoding** [comment]
WebRTC doesn't work inside ServiceWorkers or WebWorkers, and probably never will.

See: https://github.com/xuset/aether-torrent
Or: https://github.com/mafintosh/browser-server

**Comment by DiegoRBaquero** [comment]
Electron allows this, check WebTorrent Desktop app design.
