### ISSUE TITLE
Chrome is very slow to download file when iframe is sandboxed without "allow-same-origin"

### ISSUE THREAD

**Issue by norzak** [webtorrent/webtorrent#1251]
**What version of WebTorrent?**
desktop client Version 0.18.0 (0.98.5)

**What operating system and Node.js version?**
Macos 10.11.6

**What browser and version? (if using WebTorrent in the browser)**
Chrome latest

**What did you expect to happen?**
All browsers get the seeded file in microseconds. File is seeded on desktop WebTorrent client.

**What actually happened?**
Chrome gets the seeded file(380K 4-5 seconds) very slowly however Firefox and Safari gets it in a snap.

All browsers have asm.js warning on the console and uses latest webtorrent.min.js if that matters for chrome.

**Comment by norzak** [comment]
Firefox log

just downloaded: 1151 total downloaded: 0 download speed: 1151
torrent.js:2583 progress: 0 time: Mon Dec 25 2017 20:35:10 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 17535 download speed: 14028
torrent.js:2583 progress: 0.046390975255500906 time: Mon Dec 25 2017 20:35:11 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 33919 download speed: 27135.2
torrent.js:2583 progress: 0.0897368400166145 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 50303 download speed: 40242.4
torrent.js:2583 progress: 0.1330827047777281 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 66687 download speed: 44458
torrent.js:2583 progress: 0.1764285695388417 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 83071 download speed: 55380.666666666664
torrent.js:2583 progress: 0.2197744342999553 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 99455 download speed: 66303.33333333333
torrent.js:2583 progress: 0.2631202990610689 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 115839 download speed: 77226
torrent.js:2583 progress: 0.3064661638221825 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 132223 download speed: 88148.66666666667
torrent.js:2583 progress: 0.3498120285832961 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 148607 download speed: 99071.33333333333
torrent.js:2583 progress: 0.39315789334440965 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 164991 download speed: 94280.57142857143
torrent.js:2583 progress: 0.4365037581055233 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 181375 download speed: 103642.85714285714
torrent.js:2583 progress: 0.47984962286663685 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 197759 download speed: 113005.14285714286
torrent.js:2583 progress: 0.5231954876277505 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 214143 download speed: 122367.42857142857
torrent.js:2583 progress: 0.566541352388864 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 230527 download speed: 131729.7142857143
torrent.js:2583 progress: 0.6098872171499776 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 246911 download speed: 141092
torrent.js:2583 progress: 0.6532330819110912 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 263295 download speed: 150454.2857142857
torrent.js:2583 progress: 0.6965789466722049 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 279679 download speed: 159816.57142857142
torrent.js:2583 progress: 0.7399248114333185 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 296063 download speed: 169178.85714285713
torrent.js:2583 progress: 0.783270676194432 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 312447 download speed: 178541.14285714287
torrent.js:2583 progress: 0.8266165409555456 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 328831 download speed: 164415.5
torrent.js:2583 progress: 0.8699624057166592 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 345215 download speed: 172607.5
torrent.js:2583 progress: 0.9133082704777729 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 361599 download speed: 180799.5
torrent.js:2583 progress: 0.9566541352388864 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 377983 download speed: 188991.5
torrent.js:2583 progress: 1 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------

**Comment by norzak** [comment]
Chrome log (takes 5 seconds)

just downloaded: 1151 total downloaded: 0 download speed: 1151
torrent.js:2583 progress: 0 time: Mon Dec 25 2017 20:35:10 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 17535 download speed: 14028
torrent.js:2583 progress: 0.046390975255500906 time: Mon Dec 25 2017 20:35:11 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 33919 download speed: 27135.2
torrent.js:2583 progress: 0.0897368400166145 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 50303 download speed: 40242.4
torrent.js:2583 progress: 0.1330827047777281 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 66687 download speed: 44458
torrent.js:2583 progress: 0.1764285695388417 time: Mon Dec 25 2017 20:35:12 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 83071 download speed: 55380.666666666664
torrent.js:2583 progress: 0.2197744342999553 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 99455 download speed: 66303.33333333333
torrent.js:2583 progress: 0.2631202990610689 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 115839 download speed: 77226
torrent.js:2583 progress: 0.3064661638221825 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 132223 download speed: 88148.66666666667
torrent.js:2583 progress: 0.3498120285832961 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 148607 download speed: 99071.33333333333
torrent.js:2583 progress: 0.39315789334440965 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 164991 download speed: 94280.57142857143
torrent.js:2583 progress: 0.4365037581055233 time: Mon Dec 25 2017 20:35:13 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 181375 download speed: 103642.85714285714
torrent.js:2583 progress: 0.47984962286663685 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 197759 download speed: 113005.14285714286
torrent.js:2583 progress: 0.5231954876277505 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 214143 download speed: 122367.42857142857
torrent.js:2583 progress: 0.566541352388864 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 230527 download speed: 131729.7142857143
torrent.js:2583 progress: 0.6098872171499776 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 246911 download speed: 141092
torrent.js:2583 progress: 0.6532330819110912 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 263295 download speed: 150454.2857142857
torrent.js:2583 progress: 0.6965789466722049 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 279679 download speed: 159816.57142857142
torrent.js:2583 progress: 0.7399248114333185 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 296063 download speed: 169178.85714285713
torrent.js:2583 progress: 0.783270676194432 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 312447 download speed: 178541.14285714287
torrent.js:2583 progress: 0.8266165409555456 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 328831 download speed: 164415.5
torrent.js:2583 progress: 0.8699624057166592 time: Mon Dec 25 2017 20:35:14 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 345215 download speed: 172607.5
torrent.js:2583 progress: 0.9133082704777729 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 361599 download speed: 180799.5
torrent.js:2583 progress: 0.9566541352388864 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------
torrent.js:2582 just downloaded: 16384 total downloaded: 377983 download speed: 188991.5
torrent.js:2583 progress: 1 time: Mon Dec 25 2017 20:35:15 GMT+0300 (MSK)
torrent.js:2584 ------------------------

**Comment by norzak** [comment]
It looks like sandboxed iframe wihout "allow-same-origin" slows down the Webtorrent on Chrome to crawl. Any ideas why?

**Comment by norzak** [comment]
It is probably a chrome related problem not related to webtorrent.

**Comment by feross** [comment]
My guess is that the torrent file you're using has an HTTP web seed and when you don't have `allow-same-origin`, then the content can't be fetched over HTTP and only WebRTC works. So you're only getting data from peers.
