### ISSUE TITLE
Regression in 0.98.20; asm.js warning is back

### ISSUE THREAD

**Issue by norzak** [webtorrent/webtorrent#1252]
Both Chrome and Firefox give asm.js warning in 0.98.20. The 0.98.19 does not give the warning.

**Comment by norzak** [comment]
https://github.com/webtorrent/webtorrent/issues/281

**Comment by feross** [comment]
This is not an issue anymore. I just checked Chrome and Firefox now. This issue must have resolved itself in a browser update, or perhaps when we updated the `babel-minify` minifier that we use.

**Comment by feross** [comment]
Nevermind - just confirmed it. It only happens with the `webtorrent.min.js`. This must be an artifact of using `babel-minify` on the JavaScript.

It's not harmful, so I'm still going to keep this issue closed. If you want to fix the issue upstream in `babel-minify` that would be great.
