### ISSUE TITLE
Get peers uploaded/download info (seeders/leechers)

### ISSUE THREAD

**Issue by francoism90** [webtorrent/webtorrent#1255]
**What version of WebTorrent?**
0.98.20

**What operating system and Node.js version?**
Linux

**What browser and version? (if using WebTorrent in the browser)**
/

**What did you expect to happen?**
To get the seed/peers stats

**What actually happened?**
Empty

```
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var torrentId = 'magnet:?xt=urn:btih:40448d478d9203a3919b0900e7fbb9e8748dcdf9'
var torrent = client.add(torrentId, {}, onseed)

torrent.on('wire', function (wire, addr) {
    console.log(wire.uploaded)
    console.log(wire.isSeeder)
})

function onseed (torrent) {
    console.log('onseed getting called')
}
```

What I'm I doing wrong?

Thanks!

**Comment by DiegoRBaquero** [comment]
`.uploaded` is empty? not even 0?

`.isSeeder` doesn't exist: https://github.com/webtorrent/bittorrent-protocol/blob/master/index.js

**Comment by francoism90** [comment]
@DiegoRBaquero  It's indeed `0` - but for all peers.

```
torrent.on('ready', function() {
    console.log('Peers', torrent.numPeers)
})

torrent.on('wire', function (wire, addr) {
    console.log('Downloaded', wire.downloaded)
    console.log('Uploaded', wire.uploaded)
    console.log('Download Speed', wire.downloadSpeed())
    console.log('Upload Speed', wire.uploadSpeed())
})
```

Log:
```
..
Downloaded 0
Uploaded 0
Download Speed 0
Upload Speed 0
Downloaded 0
Uploaded 0
Download Speed 0
Upload Speed 0
Downloaded 0
Uploaded 0
Download Speed 0
Upload Speed 0
Downloaded 0
Uploaded 0
Download Speed 0
Upload Speed 0
Downloaded 0
Uploaded 0
Download Speed 0
Upload Speed 0
onseed getting called
Peers 113
```

**Comment by DiegoRBaquero** [comment]
Looks correct to me, when a peer has *just* connected, it hasn't downloaded or uploaded anything to the client, and speed is 0 as it hasn't started the transfer. Seems about right

**Comment by francoism90** [comment]
Yeah, but even after waiting for 30min. nothing happens, only the zero's are showing.

**Comment by DiegoRBaquero** [comment]
torrent.on('wire', cb) **only** gets called when the wire connects. You are seeing all the logs when peers connect, but that's it.

**Comment by francoism90** [comment]
@DiegoRBaquero Hmm, would it be possible to scrape the seeds/peers on the DHT?
I'm I missing a method? I wish to get the peers/seeds amount as qBt does (without trackers, only DHT).
Would that be possible?

**Comment by DiegoRBaquero** [comment]
Doesn't seem like it would be possible. https://github.com/webtorrent/bittorrent-dht doesn't support getting whether a peer is seeder/leecher.

**Comment by francoism90** [comment]
@DiegoRBaquero Could you tell me how is it possible for qBt to get the number of Seeds/Peers? I'm trying to see how they do it. :)

bittorrent-dht works, but is it possible to get the down speed/downloaded of this too?

**Comment by DiegoRBaquero** [comment]
I don't know anything about qBt, and I'm not proficient in DHT, as I mostly work in the browser part which doesn't have it.

> bittorrent-dht works, but is it possible to get the down speed/downloaded of this too?

no, that's only possible with the wire that you are using.
