### ISSUE TITLE
Seeding doesn't show up as complete in tracker

### ISSUE THREAD

**Issue by elirankon** [webtorrent/webtorrent#1256]
**What version of WebTorrent?**
0.98.20
**What operating system and Node.js version?**
Node 8.9.6 Ubuntu 17.10
**What did you expect to happen?**
After calling `.seed()` I expected to see new torrent appear with 1 seeder in the tracker. The torrent received in the `ontorrent` callback shows up as done and as having all the file downloaded.
**What actually happened?**
For some reason, the seeder appears as a leecher and the file doesn't appear as complete.

**Comment by feross** [comment]
This issue is a duplicate of https://github.com/webtorrent/webtorrent/issues/1105
