### ISSUE TITLE
Get webtorrent jsdelivr script stats

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1258]
Wow, apparently the CDN-hosted version of "webtorrent.min.js" on jsdelivr is downloaded 1 million times per month, according to this badge:

![](https://data.jsdelivr.com/v1/package/npm/webtorrent/badge)
https://data.jsdelivr.com/v1/package/npm/webtorrent/badge

Does anyone know how to get detailed stats? Which domains are including the script?

The "webtorrent" npm package only gets 12K downloads/month, so I'm super shocked to see 1M downloads/month on the CDN-hosted script... seems like a mistake.

**Comment by feross** [comment]
Ongoing discussion happening on Twitter: https://twitter.com/feross/status/949699972643151872

**Comment by DiegoRBaquero** [comment]
It does make sense if each visit is a hit, btorrent gets 38k unique visitors per month, which can be alone more than 38k hits.

@jimaek might have more info

**Comment by jimaek** [comment]
@DiegoRBaquero Hey, the data is 100% correct. npm downloads and CDN hits have nothing in common :)
I even PMed feross with a list of domains that use it.
Let me know if you have any other questions.

**Comment by feross** [comment]
@jimaek Nice, thanks for chiming in. Cheers!

**Comment by feross** [comment]
PR to add the badge to our readme: https://github.com/webtorrent/webtorrent/pull/1294
