### ISSUE TITLE
Handshake before downloading file

### ISSUE THREAD

**Issue by heroldsh** [webtorrent/webtorrent#1259]
**What version of WebTorrent?**
1.11.0 (0.98.20)

**What operating system and Node.js version?**
ubuntu 16.04 - v8.9.4

I didn't find a Q&A forum so I'll ask it here, sorry if it's not the place...

I'm trying to implement kind of handshake with one peer (the closest between all peer available) before downloading the file. I looked at the source code and tried to figure out where do I get the IP address and the port of the one I'm going to download from and where the one I'm going to download from know that I'm download from him. 

I'll give an example for what I want, let's say I'm looking for torrent with `torrentId` which Node B has, I do `client.add(torrentId, opts, func...)` and before Node B gives me the file he asks me 'You sure you want `torrentId`?` and only if I'll say yes I'll start downloading the file from him.

Does someone know where should I'll look for?
Thanks and have a great day!

**Comment by Robien** [comment]
I am just passing and I saw this question...
Have you looked at https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#torrentonwire-function-wire- ?

You can do a custom extension like shown here https://github.com/webtorrent/bittorrent-protocol#extension-api

you can even look at my very (very) simple example here https://github.com/Robien/eth_reward/blob/master/index.js where I do an extension to exchange ethereum address between peers

hope it helps
