### ISSUE TITLE
Will support cordova hybrid app?

### ISSUE THREAD

**Issue by ghostgzt** [webtorrent/webtorrent#1264]
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-udp  
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp  
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcpServer  
base on these plugins,this project can working on cordova not using WebRTC?

**Comment by DiegoRBaquero** [comment]
I'd say it's not probable, but you can only try.
