### ISSUE TITLE
Native VPN support/WebTorrent starts seeding things I've manually stopped seeding

### ISSUE THREAD

**Issue by bwheeler96** [webtorrent/webtorrent#1266]
I uncheck the "seeding" box, torrent stops seeding.

I do other things.

Torrent starts seeding again.

Clearly this is by design, and I understand why, but sometimes we don't have our VPNs on and at those times it would be really, really ideal not to seed.

Proposal: add VPN support into webtorrent directly so that, as an option, users can choose to only allow connections through a specific VPN configuration. 

I'm happy to help get this done if you guys approve of the idea.

**Comment by feross** [comment]
Thanks for the issue @bwheeler96. This should have been an issue on `webtorrent-desktop`. But it turns out there's already an issue for it. You can follow: https://github.com/webtorrent/webtorrent-desktop/issues/578
