### ISSUE TITLE
All torrent file's won't work in browser version of webtorrent (react)!

### ISSUE THREAD

**Issue by gaphu** [webtorrent/webtorrent#1269]
**What version of WebTorrent?**
^0.98.20

**What operating system and Node.js version?**
v9.4.0

**What browser and version? (if using WebTorrent in the browser)**
Chrome v63.0.3239.132

Why can't i play all the torrent files in browser, when the same torrents work fine on webtorrent-desktop client?

**Comment by DiegoRBaquero** [comment]
See https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#why-does-browser-downloading-not-work-i-see-no-peers
