### ISSUE TITLE
Seeding doesn't work on server node js

### ISSUE THREAD

**Issue by Er-rchydy** [webtorrent/webtorrent#1275]
**What version of WebTorrent?**
0.98.20
**What operating system and Node.js version?**
Operating system : Centos 7
Node.js  : v8.9.4
**What browser and version? (if using WebTorrent in the browser)**
Version 63.0.3239.132 (Official Build) (64-bit)
**What did you expect to happen?**
To watch the video when i put magnet link on instant.io
**What actually happened?**
Nothing , after i put the magnet link on instant.io it gives me 

> Downloading torrent from xxxxxx

but the  videos doesn't appear in the page + no errors in the console.
This is the code : 

```
const WebTorrent = require('webtorrent');
webtorrent.seed('./public/video.webm', function (torrent)
{
    console.log('Client is seeding ' + torrent.magnetURI);
});
```

**Comment by aszokalski** [comment]
Found solution. You have to download webtorrent-hybrid

**Comment by Er-rchydy** [comment]
@aszokalski  Can you explain more what i need to do, i'm a beginner so i'm not sure what do you mean by ' download webtorret-hybrid '

**Comment by aszokalski** [comment]
https://github.com/webtorrent/webtorrent-hybrid this is webtorrent-hybrid. I am begginer too and I had the same problem.

**Comment by Er-rchydy** [comment]
@aszokalski thanks, i got it to work on mac os but it's not working on Centos7 , after i install all what's it need, i got this error `Error: electron-eval error: Electron process exited with code 127.`, did you made it to seed from the server yet ?

**Comment by aszokalski** [comment]
No I didn't try Cent OS but I see that you have to run this command `sudo yum install xorg-x11-server-Xvfb`. If you already did it then I have no clue what's wrong. I'd be glad if you look on my issue: https://github.com/webtorrent/webtorrent/issues/1276

**Comment by feross** [comment]
@Er-rchydy CentOS is not an officially-supported OS in the webtorrent project. There are too many Linux variants to support them all, but if you discover the source of the issue and want to send a PR, we're happy to merge it so it can work for you. We just don't have the time to invest in fixing things for every Linux variant.

**Comment by Er-rchydy** [comment]
@feross what OS are supported  in the webtorrent project ?
