### ISSUE TITLE
How to using torrent file not magnet url ?

### ISSUE THREAD

**Issue by nekadevmaster** [webtorrent/webtorrent#1281]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by DiegoRBaquero** [comment]
From: https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-

```
torrentId can be one of:

    magnet uri (string)
    torrent file (buffer)
    info hash (hex string or buffer)
    parsed torrent (from parse-torrent)
    http/https url to a torrent file (string)
    filesystem path to a torrent file (string) (Node.js only)
```
