### ISSUE TITLE
feature request: change audio and subtitle track from in-client player

### ISSUE THREAD

**Issue by jaderager** [webtorrent/webtorrent#1282]
**What version of WebTorrent?**
0.19.0

As stated, WebTorrent is a fantastic client for streaming videos _in English,_ but if you want to watch anime it becomes suddenly unusable. You have to download the full file before watching it, because there is no way to change the audio or subtitle track from within the client's video player. Better off using Deluge or another full-fledged client, in that case.

**Comment by DiegoRBaquero** [comment]
You are referring to the desktop client. If the files are not streamable in HTML, it won't work in the HTML viewer. You'd have to use VLC stream. Maybe in VLC you can change the audio and subtitles track.

**Comment by jaderager** [comment]
How can I force the client to stream in VLC? There's no menu option for it, that I see.

**Comment by feross** [comment]
@jaderager Uncheck this box:

<img width="497" alt="screen shot 2018-04-18 at 3 39 04 pm" src="https://user-images.githubusercontent.com/121766/38961718-a6f72d48-431e-11e8-98bf-a68b716b72b2.png">
