### ISSUE TITLE
Ask how to achieve concurrent download

### ISSUE THREAD

**Issue by kslr** [webtorrent/webtorrent#1283]
**What version of WebTorrent?**
0.98.21
**What operating system and Node.js version?**
v6.12.3
**What browser and version? (if using WebTorrent in the browser)**
nodejs
**What did you expect to happen?**
Multiple seeds are downloaded at the same time
**What actually happened?**

```javascript
const client = new WebTorrent();
client.add(magnet);

client.on('torrent', (torrent) => {
  console.log('Client is downloading:', torrent.infoHash);
});
```
```shell
12|app     | Client is downloading: 27e93d46e7cd92a943d9b51960fe54ee9a78f537
12|app     | Client is downloading: 8af9179a315187cddafb661d82906093b111e529
12|app     | Client is downloading: accf88cd77f07618d5d96942def538107947e72d
12|app     | Client is downloading: b708c536584b1b33e8751f8124e20ed12164c2e8
12|app     | Client is downloading: 38f43e4967281db50083760adb034224a78a4538
12|app     | Client is downloading: 613b92b3db4d0dc8e422416bd26b8d0269cb59d1
```

I added 2000 seed tests.
But orderly download, Can not reflect async.

**Comment by kslr** [comment]
After many tests, it is not sequential download, But whether to increase the number of concurrent deployments by configuring DHT?

**Comment by DiegoRBaquero** [comment]
Use disk store. By default all torrents live in memory. And use Node.js v8

**Comment by kslr** [comment]
Upgraded to v8, but there are always only a few tasks to download
