### ISSUE TITLE
WebRTC support missing

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent#1291]
From https://webtorrent.io/faq:

> WebRTC works everywhere, and browser support is excellent. Chrome, Firefox, and Opera for Desktop and Android, as well as Microsoft Edge and Safari have support.

But on the WebRTC website Edge and Safari are not reported as supporting WebRTC.
Also on the slides linked frm the webtorrent's website faq it states:

> No IE/Safari yet

and

> Edge support coming soon

So which one is right? I can only try IE and EDGE and non of them seems to be capable of play a webtorrent shared file.

Thank you!

**Comment by feross** [comment]
Edge now has WebRTC, but lacks WebRTC DataChannel so it won't work for WebTorrent.

Safari has WebRTC including DataChannel, so it should work.

IE has no WebRTC and never will.

Hope this makes sense! ✨
