### ISSUE TITLE
Does Webtorrent works on node.js on server ?

### ISSUE THREAD

**Issue by Er-rchydy** [webtorrent/webtorrent#1295]
I don't know if `Webtorrent` work on server or not, i made a simple test but it didn't work.
this is the code i use : 
`var WebTorrent = require('webtorrent');`
`var client = new WebTorrent();`
`client.seed('./out.mp4', function (torrent) {`
    `console.log('Seeding out.mp4: ', torrent.infoHash)`
`})`
i got this on the output `Seeding out.mp4 : bbd73a021f02c6e21f619ddf3f3bb602e96d9f07`, but when i copy the torrent infoHash and paste it to `instant.io`, it didn't play, i didn't get any error
the server is running `Centos7`

**Comment by feross** [comment]
By default if you use 'webtorrent' in Node.js, it won't connect to browser peers. You need to use `webtorrent-hybrid`.

**Comment by Er-rchydy** [comment]
I did tried `webtorrent-hybrid` too but it gives me this error
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: electron-eval error: Electron process exited with code 127.
Stderr:
/root/app/node_modules/electron/dist/electron: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

**Comment by feross** [comment]
It looks like Electron (which gives the WebRTC implementation we use) doesn't provide pre-built binaries for CentOS: https://github.com/electron/electron/issues/259
