### ISSUE TITLE
When would it come to android platform?

### ISSUE THREAD

**Issue by ambarpathak11** [webtorrent/webtorrent#1313]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by ambarpathak11** [comment]
I am waiting eagerly

**Comment by SilentBot1** [comment]
Hey @ambarpathak11,

From my testing the library works fine in Android under browsers which support WebRTC,  which can be seen [here](https://caniuse.com/#search=Webrtc).

Hope this helps.

**Comment by DiegoRBaquero** [comment]
Should work under chrome

**Comment by ambarpathak11** [comment]
thanks for a quick reply9 @DiegoRBaquero and @SilentBot1 
is there any apk file available in android play store that has been made by the creators of webtorrents and
work exactly the same?

**Comment by SilentBot1** [comment]
Hey @ambarpathak11,

From my understanding, there is no first party (or third) Android application for the webtorrent library on Android. 

If you are thinking of a standalone application similar to webtorrent-desktop, for Android, this doesn't exist though browser based clients such as [βTorrent](https://btorrent.xyz/) and [lofiTorrent](https://lofitorrent.js.org/) should work from a browser (Chrome, Firefox, Samsung Internet) on your Android device.

All the best.

**Comment by ambarpathak11** [comment]
Thanks for being in touch.
