### ISSUE TITLE
Instant.io not working as expected

### ISSUE THREAD

**Issue by mayurbavisiya** [webtorrent/webtorrent#1316]
**What version of WebTorrent?**
https://instant.io/

**What browser and version? (if using WebTorrent in the browser)**
   chrome  Version 64.0.3282.167 (Official Build) (64-bit)

**What did you expect to happen?**
   It should stream after uploading successful.

**What actually happened?**
   Its not getting stream after uploaded.

![capture](https://user-images.githubusercontent.com/26430799/36639143-3d376698-1a1f-11e8-9393-c23e2b7904e9.PNG)

**Comment by feross** [comment]
@mayurbavisiya This looks like a bug in the `videostream` library that we use for video playback. Can you share the original video that is causing the issue so we can debug it. Please do not share copyrighted material that is not owned by you, please.

(cc @jhiesey who maintains `videostream`)
