### ISSUE TITLE
Browser VS Electron

### ISSUE THREAD

**Issue by Ciao121** [webtorrent/webtorrent#1318]
**What version of WebTorrent?**
0.98.23
**What operating system and Node.js version?**
Windows 10 / Node 8.5.0 / electron 1.7.9
**What browser and version? (if using WebTorrent in the browser)**
Chrome / Firefox

Hi,
I'm developing an electron app and I have a problem with time needed to start a download.
I tried e.g. the infohash 6a9759bffd5c0af65319979fb7832189f4f3c35d (a sintel infohash).

On instant.io and using magnet player in the browser it starts in few seconds.
In the electron app it waits a lot (also minutes) before starting download.

Obviously I'm trying on the same PC, same connection etc.
Any idea?

Thank you!

**Comment by DiegoRBaquero** [comment]
Depending on which process (render or main) of Electron you run WebTorrent in you might be connecting to WebRTC clients or TCP/UDP clients.

I think this might be it.

**Comment by Ciao121** [comment]
I'm going to look into it. But it happens also with files I'm the only seeder (seeding using WebRTC).

**Comment by feross** [comment]
https://instant.io automatically adds tracker servers (which helps with finding peers super quickly).

If you're using `client.add()` with an info hash (which you said you're doing) then you need to pass the `announce` option to force add tracker servers.

Or, a better way to do this is:

```js
global.WEBTORRENT_ANNOUNCE = createTorrent.announceList
  .map(function (arr) {
    return arr[0]
  })
  .filter(function (url) {
    return url.indexOf('wss://') === 0 || url.indexOf('ws://') === 0
  })
```

From instant.io source code: https://github.com/webtorrent/instant.io/blob/b898193ba36f6f1b748cf23c444d3491c2d3fa78/client/index.js#L15-L21

**Comment by Ciao121** [comment]
I was alread adding a tracker programmatically (did not specify this in my post) in this way:
`client.add(dataFolder+parsed.infoHash+'.torrent',{
        announce: ['wss://mytracker.com'],
      path: myFolder
})`

I made another test. I simply opened instant.io in electron and used the same hash.
It tooks 44 seconds to start downloading (while using chrome it only took 3 seconds).
