### ISSUE TITLE
How to enable ut_pex?

### ISSUE THREAD

**Issue by muneebm** [webtorrent/webtorrent#1322]
Hi All, ut_pex seems to be by default disabled for browser
// from package.json
  "browser": {
    "./lib/server.js": false,
    "./lib/tcp-pool.js": false,
    "bittorrent-dht/client": false,
    "fs-chunk-store": "memory-chunk-store",
    "load-ip-set": false,
    "net": false,
    "os": false,
    **"ut_pex": false**
  }
And the available options don't have one for enabling ut_pex
{
  maxConns: Number,        // Max number of connections per torrent (default=55)
  nodeId: String|Buffer,   // DHT protocol node ID (default=randomly generated)
  peerId: String|Buffer,   // Wire protocol peer ID (default=randomly generated)
  tracker: Boolean|Object, // Enable trackers (default=true), or options object for Tracker
  dht: Boolean|Object,     // Enable DHT (default=true), or options object for DHT
  webSeeds: Boolean        // Enable BEP19 web seeds (default=true)
}
Is there any other way to enable ut_pex in webtorrent?

Sorry if it's a noob question and thanks in advance for any help!

**Comment by SilentBot1** [comment]
Hey @muneebm,

As you mentioned, in the `package.json` ut_pex is excluded from being bundled when a script is passed through Browserify. Changing the key `ut_pex`'s  value to true in `package.json` then running Browserify again should be enough to include the `ut_pex` in the bundle. Once it is included it will be ran on all wires created as is defined [here](https://github.com/webtorrent/webtorrent/blob/c29e02ce29245cba2b198a3b5da533d961118fb8/lib/torrent.js#L994), so no need to run it on each wire yourself.

The module `ut_pex` was set to not load in the browser when Browserify support was first introduced in [this](https://github.com/webtorrent/webtorrent/commit/93686505fbc90522c75b6c151ec7261aa76098de?diff=split#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21) commit. There may have been a reason behind it but it wasn't document, so I would love to hear back if it works without issue after re-enabling it in `package.json`.


All the best.

**Comment by feross** [comment]
The `ut_pex` spec is written assuming that peers can be described by their ip addresses and ports, but this won't work for browser (webrtc) peers. That's why it's disabled.

**Comment by muneebm** [comment]
Thanks to both of you for your responses.
