### ISSUE TITLE
Is it possible to get WebTorrent version on runtime?

### ISSUE THREAD

**Issue by fgvieira** [webtorrent/webtorrent#1323]
**What version of WebTorrent?**
0.98.24
**What operating system and Node.js version?**
Win10 
**What browser and version? (if using WebTorrent in the browser)**
Firefox 58.0.2
**What did you expect to happen?**
NA
**What actually happened?**
NA

Not quite sure this is the best place to ask this (since this is not an "issue" but rather a question), but is it possible to get current WebTorrent version at runtime? Ideally, one would have something like `WebTorrent.VERSION` or similar.

thanks,

**Comment by DiegoRBaquero** [comment]
I noticed it isn't. Will edit it to export it this week.

**Comment by feross** [comment]
This was released in v0.99.1 on 2018-04-24
