### ISSUE TITLE
Is this project suitable for building an ebook sharing feature in Electron App? 

### ISSUE THREAD

**Issue by hz0324** [webtorrent/webtorrent#1324]
I have read a lot about this project and watched the intro video on Youtube. But I am still not sure whether this is the right place I am looking for. Please help.

We are building an ePub reader using Electron. Now we'd like to add the "ebook sharing" feature to our app. We want to make it decentralized because of the legal issue.

This is the user story. User A open our app and setup a special folder for SHARING which contains several epub files. And after the first setup, each time user A are reading books in our app, this folder will be in SEEDING state. And then, user B start to use our app, and find the book share feature and type in the book name he want to find. If this book is inside the share folder of user A, user B will be able to downloading the book from user A. But if user A has closed the app, user B won't be able to see the book he looks for inside user A's share folder.

Is WebTorrent suitable for this use case?

I have downloaded the WebTorrent Desk App and tried "create new torrent for folder". It says all the files inside the folder is SEEDING, but I don't know how to find this files on the internet. The app didn't show the hash info for those SEEDING files and there is no place to search for these file by name. What can I do next after "create new torrent for folder"? I am confused.

As for the search part, do we have to host a special server to record the map info between filename and the hash info? How can we know the seeder is offline then? Please help.

Thank you very much.

**Comment by DiegoRBaquero** [comment]
If you are concerned about the possible legal issues, please don't use WebTorrent. We don't support copyright infringement.
