### ISSUE TITLE
Feature Request: Kodi addon integration

### ISSUE THREAD

**Issue by Darkcast** [webtorrent/webtorrent#1325]
Hi

This app is great and it has the ability to blow every kodi addon out of the water. 
I wish there was an kodi addon that would include a torrent search feature so one could just search directly from the app download / view inside of kodi.

**Comment by ndm13** [comment]
Kodi addons are essentially Python projects.  Look around for a Python implementation, or a bridge between NodeJS and Python.  WebTorrent is a protocol, not a database, unless your intent is to search DHT.  Regardless, this appears to be pretty far outside the scope of this project.
However, that's not to imply that this is impossible by any means.  I can totally see this as a cool standalone project with a customizable tracker.  I'd love to see what someone comes up with.

**Comment by DiegoRBaquero** [comment]
This is out of the scope for the library.
