### ISSUE TITLE
Can be get support torrent streaming .mkv (h.264) video in Chrome-like browsers?

### ISSUE THREAD

**Issue by jun-dev** [webtorrent/webtorrent#1326]
Hello. May be you add of support .mkv video format for use in Chrome-like browsers. 

This is very simple code sample .mkv video plays in Chrome, used tag <video> from  HTML5.
[JSFiddle Example](https://jsfiddle.net/3trzdn1m/5/)

Thank you for the developed amazing webtorrent library!

**Comment by DiegoRBaquero** [comment]
mkv support depends on the codecs of the files inside the mkv. mkv support was added in `render-media` long time ago (https://github.com/feross/render-media/issues/13), but it all comes down to the codecs used in the video and audio.

Real support must be added in `videostream`. See https://github.com/jhiesey/videostream/issues/29

**Comment by jun-dev** [comment]
https://github.com/feross/render-media/commit/94e0d3e215156d9dd2623aaa7dd68f254000230b
https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test4.mkv?raw=true // This file is accurately reproduced in my browser Chromium.
Can you give a minimal sample code on JSFiddle using Webtorrent and. mkv file?

**Comment by DiegoRBaquero** [comment]
I don't really have any mkv torrented or even webseeded to test. Mostly work with mp4's

**Comment by jun-dev** [comment]
I can reset the link, choose any. torrent or magnet link from the list where the file ends in. mkv. The content is probably pirated, so use a VPN or anonymizer if it is not allowed in your country.
[Https://nyaa.si/?page=rss&q=Koi+wa+Ameagari+no+You+ni&c=0_0&f=0](Https://nyaa.si/?page=rss&q=Koi+wa+Ameagari+no+You+ni&c=0_0&f=0)

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
