### ISSUE TITLE
Remote Directory support using --path=ftp@...

### ISSUE THREAD

**Issue by kunaldodiya** [webtorrent/webtorrent#1327]
Anyway possible to download torrent instead of local directory but FTP, Dropbox or AWS EC2 HardDisk ???

**Comment by SilentBot1** [comment]
Hey @kunaldodiya,

This seems like it could be done if an [abstract-chunk-store](https://github.com/mafintosh/abstract-chunk-store) compliant store was made, which stored the chunks within the specific service you're looking for (FTP, Dropbox, EC2 ect.) and was passed through to the WebTorrent library on torrent creation. 

Hope this helps.
