### ISSUE TITLE
How to seed all the files inside a folder using the desk app? is this possible?

### ISSUE THREAD

**Issue by hz0324** [webtorrent/webtorrent#1332]
I would like to seed all the files in side a particular folder, there maybe more than 1000 files. 
I have tried to seed the folder, but it seed the folder as one. 

Can I achieve this using the APP? Or do I have to do this programatically?

Thanks

**Comment by xwjonline** [comment]
Sadly , I find  WebTorrent Desktop  can only add file one by one.  T_T

**Comment by KayleePop** [comment]
You could use the cli of [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid) to do this easily

`$ npx webtorrent-hybrid seed /path/to/folder/*`

(need npm installed)

**Comment by feross** [comment]
You can do this programmatically, or as @KayleePop says, you can do it using https://github.com/webtorrent/webtorrent-cli.

However, you should note that WebTorrent doesn't manage resources efficiently enough at the moment to handle seeding 1000s of files IMO. If you need to seed that many files, you might want to look into web seeds. http://www.bittorrent.org/beps/bep_0019.html

**Comment by hz0324** [comment]
@feross 
Hi, I have tried to use webseed in our project, but confused about how it works.
Could you please help us? This is the issue I just opened. https://github.com/webtorrent/webtorrent/issues/1393
