### ISSUE TITLE
Sending messages to webtorrents peers

### ISSUE THREAD

**Issue by Fabiencdp** [webtorrent/webtorrent#1335]
Hello, 
i wonder if there is a way to send custom message/data to peer who use webTorrent directly. 
It work well using the simple-peer module, after doing all the signaling process i can send message with for example :
```
var peer = new Peer(options);
// Handle signaling process 
// ... 
peer.send("hey mate!")
```
and i receive it in the other browser using the "data" event. 

Here is a way to do that directly with the webtorrent wires ? for example 
`torrent.wires[0].send("hey mate");`

Thanks for your help !

**Comment by feross** [comment]
You can technically reach into the wire's private `simple-peer` object and call `send()` but you'll likely confuse the remote peer who will then just disconnect.

The correct way to implement this is to use the [extension API in `bittorrent-protocol`](https://github.com/webtorrent/bittorrent-protocol#extension-api) which will send a standard message to the remote peer which advertises support for your extension. If the remote peer also has support for your extension, then you can send custom messages to each other.
