### ISSUE TITLE
New Chrome autoplay policy blocks demo

### ISSUE THREAD

**Issue by isaackwan** [webtorrent/webtorrent#1339]
The [new Chrome autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) blocks the demo at [https://webtorrent.io/](https://webtorrent.io/).

Example screenshot:
![screenshot from 2018-03-27 00-15-56](https://user-images.githubusercontent.com/1005813/37918612-2e9c02e6-3154-11e8-894a-aa88c340ca43.png)

My user agent string:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.33 Safari/537.36
```

**Comment by DiegoRBaquero** [comment]
That's after you click begin demo??

**Comment by isaackwan** [comment]
Umm, if I recall correctly, I don't have to click anything to start the demo, it just loads on its own, no?

In more abstract words:

#### Expected Behaviour
1. Visit [https://webtorrent.io/](https://webtorrent.io/)
2. The WebTorrent instance starts downloading stuff
3. The video starts playing on its own

#### Observed Behaviour
1. Visit [https://webtorrent.io/](https://webtorrent.io/)
2. The WebTorrent instance starts downloading stuff
3. The video is not played

Unfortunately because of the [Media Engagement Index](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei) it's hard to reproduct/test. For instance, the video is blocked on my Linux, but not blocked on my Windows installation which presumably because I had visited this site before.

**Comment by isaackwan** [comment]
Ah, I see why now. The "begin demo" button only shows on small viewports (e.g. phones).

**Comment by isaackwan** [comment]
I've written a quick test to show how it fails: [https://github.com/isaackwan/webtorrent.io/commit/598cca1ff45fc539e237930a99bb646afffb84a5](https://github.com/isaackwan/webtorrent.io/commit/598cca1ff45fc539e237930a99bb646afffb84a5)

**Comment by feross** [comment]
Thanks for reporting this issue. I opened an issue on the website repo here: https://github.com/webtorrent/webtorrent.io/issues/128

Working on fixing this right now. Let's continue discussion in that issue.
