### ISSUE TITLE
Uncaught TypeError: dgram.createSocket is not a function

### ISSUE THREAD

**Issue by luchux** [webtorrent/webtorrent#1340]
I am getting this error when trying to call the consturctor. 
var client = new WebTorrent();

any ideas? 

cheers

**Comment by KayleePop** [comment]
You have to use browserify when using webtorrent in the browser.

**Comment by luchux** [comment]
Im using Meteor+Vue, so can't really use another bundling tool. Shouldn't be possible to avoid browserify tool? Why is it needed? 
Just asking to find a way to work around. Cheers

**Comment by KayleePop** [comment]
See here: https://github.com/meteor/meteor/issues/6890

And here: https://github.com/webtorrent/webtorrent/blob/master/package.json#L10-L19

**Comment by feross** [comment]
It appears that Meteor does not support using the `"browser"` field to override package names, only local files. We use the former in WebTorrent.

Consider using the bundled version of WebTorrent which has already been browserified. You can find it in the repo -- `webtorrent.min.js`.
