### ISSUE TITLE
Is there a way to get the raw data from a file and embed it in a page?

### ISSUE THREAD

**Issue by ki4jgt** [webtorrent/webtorrent#1346]
**What version of WebTorrent?**
Current -- using CDN
**What operating system and Node.js version?**
Windows -- in browser
**What browser and version? (if using WebTorrent in the browser)**
Mozilla 59
**What did you expect to happen?**
N/A
**What actually happened?**

I'm working on a P2P video-sharing platform in the browser. I would like to read a txt file -- containing video information -- and then display its contents within the page.

**Comment by KayleePop** [comment]
``` javascript
file.getBuffer(function (err, buffer) {
  if (err) throw err
  let text = buffer.toString('utf8')
  console.log(text) //or render to DOM
})
```

**Comment by feross** [comment]
Thanks for sharing a code example, @KayleePop :)

@ki4jgt There are more methods of accessing file data in the docs: http://webtorrent.io/docs
