### ISSUE TITLE
Can we create a private data channel with a peer?

### ISSUE THREAD

**Issue by norzak** [webtorrent/webtorrent#1359]
Is it possible to create a private webrtc channel with a specific peer over a specific torrent link? It would be awesome to use webtorrent as a signaling server to establish both data and media communications.

**Comment by norzak** [comment]
A private torrent may have a flag for allowing a private communication channel with the connecting peers.

**Comment by feross** [comment]
You can try to reuse the existing simple-peer (webrtc datachannel) instance by iterating over `torrent.wires`. But it's probably to implement what you have in mind as a [`bittorrent-protocol` extension](https://github.com/webtorrent/bittorrent-protocol#extension-api). There's a robust extension API that should allow you to send whatever custom messages you desire between peers that support your extension.

**Comment by norzak** [comment]
@feross is bittorrent protocol extension available in browser?
