### ISSUE TITLE
Possible to script downloading from bitchute? Forum somewhere?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [webtorrent/webtorrent#1375]
I can't seem to find a forum for either webtorrent or bitchute. If this is the wrong place to ask this, maybe you could point me in the right direction.

I want to use webtorrent from a bash script to download the media from the most recent magnet link  on a particular bitchute page. The idea is that it will check once a day & download the newest media, ideally checking to see if it has already been downloaded or if it is less than 24 hours old. If this is possible, I'd appreciate a suggestion on what to read to get an idea how to do it. If it isn't possible, this is a
feature request. Thanks.

**Comment by feross** [comment]
You have two ways to use WebTorrent for your use case:

1. The command line (see https://github.com/webtorrent/webtorrent-cli)

2. The JavaScript API (see https://webtorrent.io/docs)

You need to write code to do whatever logic you wish to obtain the magnet link. It sounds like you'll need to fetch the HTML page in question, search for a magnet link, check if it already exists on disk, then trigger WebTorrent to download it.

That last part is where you can invoke the `webtorrent` command line program, or use the WebTorrent Node.js API. See the documentation for each of these (linked above) for instructions on how to use them.
