### ISSUE TITLE
Autofind subtitles

### ISSUE THREAD

**Issue by odahcam** [webtorrent/webtorrent#1378]
#### What did you expect to happen?
I want to click on the subtitles button and the player antumatically searches for subtitles for the video I'm playing. This behavior can be found in bitLord client, which has awesome features and terrible performance and UX.

#### What actually happened?
I can only add subtitles files.

#### Also interesting
VLC player has a searcher that ~searches~ for subtitles on the web, but BitLord's one is by far better than anything I've ever used. That's an awesome feature and I'd like to see that in here.

**Comment by feross** [comment]
We're unlikely to add a feature like this because it's unclear whether using subtitles like this is legal. However, can you link to a webpage that explains how this VLC functionality works so I can read about it?

**Comment by odahcam** [comment]
Sure! Here's some:

- https://www.maketecheasier.com/get-vlc-to-download-subtitles/
- https://github.com/exebetche/vlsub

**Comment by feross** [comment]
Hmm, if VLC is shipping this now, then let's consider it. Leaving this open to remind me to look into it.

**Comment by feross** [comment]
Oh, this belongs on the `webtorrent-desktop` issue tracker: https://github.com/webtorrent/webtorrent-desktop/issues/1383

**Comment by odahcam** [comment]
Very nice, thanks.
