### ISSUE TITLE
bad cpu performance, not a viable bittorrent server solution

### ISSUE THREAD

**Issue by arxii** [webtorrent/webtorrent#1381]
This is not a bittorrent replacement solution for servers running node , please make benchmarks to compare performance with other clients, running over 3 killed my CPU!! even with only one active torrent it still jumps to over 60% compared to transmission-daemon which ran smooth at 7-8% cpu.

**Comment by feross** [comment]
Known issue. I'm going to work on reducing CPU utilization soon.
