### ISSUE TITLE
Hybrid streaming - http + webtorrent

### ISSUE THREAD

**Issue by GooG2e** [webtorrent/webtorrent#1386]
Hello!
I have a website with some videos (a lot videos - more than 3000).
Usually I stream them via http/https but in peeks I have load more than 1Gbit/s
I want to use webtorrent for hybrid streaming .
For example: user watching video and simultaneously seed it (but receive video from http because no other ways) or user start watching from webtorrent but  at some moment - no others seeds  and it starts download from htttp
Is there anyway I can do such thing?

As I read I understand that I can't use any clients to simultaneously stream 3000+ videos and I can't totally disable http because webtorrent stream can be not enough

So I want to listen to some advices in this way
Thank you!

**Comment by DiegoRBaquero** [comment]
You would have to build a custom solution where you first scrape the trackers for a certain torrent and if there are not enough peers, add HTTP webseed.

If you have a 1gbps unlimited bw server, I'd just always include it and let it max out, while rarelimit each connection.

**Comment by calvincs** [comment]
I have played with this quite a bit.  Use webseed, and do a per connection limit at X speed to conserve bandwidth, if you must, to ensure as many people as possible can start a connection/stream if no other peers are online.  You can use iptables on a per connection bases to limit speeds, and or work with a load balancer to better distribute your content.   You may also want to look at web seeding your content via a CDN service as well if that's an option.

**Comment by GooG2e** [comment]
Hmm as I seed I need example to configure nginx as webseed

**Comment by GooG2e** [comment]
And one more question
I begin download with  client.add
Add webseed
Will peers interconnect before they will download everything?
Or I can seed and give parts only after finishing?

**Comment by SilentBot1** [comment]
@GooG2e [this issue](https://github.com/webtorrent/webtorrent/issues/1312) may be of interest to you.

> You would have to build a custom solution where you first scrape the trackers for a certain torrent and if there are not enough peers, add HTTP webseed.

An example of this which I quickly threw together can be found [here](https://github.com/webtorrent/webtorrent/issues/1312#issuecomment-387738102).

>How can I add http webseed?

A webseed can be added by calling `torrent.addWebSeed('http://example.com/path/to/torrent')` assuming you have a webserver (nginx, express) which supports range requests which has the torrents content available at some path. Using express adds the option for route based logic (such as videos only accessible to certain users) and authentication.
>Can you give somehelp with setting tracker and generating torrent or magnet for this (better generate magnet or torrent in php)

[This](https://github.com/webtorrent/webtorrent/issues/1385#issuecomment-388628232) may help you regarding setting trackers, look into [create-torrent](https://github.com/webtorrent/create-torrent) for torrent generation, I don't know any solutions for php unfortunately, maybe somebody else could help on this part?
> And can you say what do I need to register file and how to do this better?

What do you mean by this?
> Will peers interconnect before they will download everything?

Yes, peers will start uploading the moment they get a piece allowing any other peer to request this piece even while they are still downloading the file, this is the nature of the bittorrent protocol.
>Or I can seed and give parts only after finishing?

There currently isn't a way to stop seeding, `torrent.pause()` only prevents new peer connections, maybe you could call `.pause()` after adding the webseed before any other peer connections are made but I haven't tested this and it likely wouldn't be reliable. 

Hope this helps and answers some of your questions!

**Comment by GooG2e** [comment]
Have webseed priority over usual peers?

**Comment by GooG2e** [comment]
@SilentBot1  And may be you test webtorrent with some players?
such as videojs?

**Comment by SilentBot1** [comment]
@GooG2e, look at [this](https://github.com/webtorrent/webtorrent/issues/1377) and [this](https://github.com/webtorrent/webtorrent/issues/1377) issue for links to examples of VideoJS and JWPlayer.

**Comment by GooG2e** [comment]
@SilentBot1 tested such example with iOS11. It's support webrtc but very slow((
I am going to disable on mobile devices...

**Comment by GooG2e** [comment]
How can I check that webseed have the lowest priority
For example I want to use it only as starter wehn other peers are exists or no other peers

**Comment by calvincs** [comment]
I'm not sure that is even possible.  You can however set a per connection
bandwidth limit to provide enough bandwidth to feed the torrent until there
are other peers to help seed.  This would be setup in your webserver or you
could use iptables to rate limit those connections.

**Comment by feross** [comment]
Closing this since it's not an issue with WebTorrent, but feel free to continue the discussion.
