### ISSUE TITLE
Is magnet faster than hashinfo for peer discovery?

### ISSUE THREAD

**Issue by hz0324** [webtorrent/webtorrent#1387]

**Comment by hz0324** [comment]
Sorry about that.
Basically, I am trying to figure out which one is better to use, magnet link or hashinfo? It all works in the demo. I personally like the hashinfo style, it looks sleek.

More specifically, I just come across the concept of "webseed",(https://github.com/webtorrent/webtorrent/issues/1087) I found it that, there are more information attached to the magnet link when using webseed. Does webseed can only work when using magnet link?

Thanks.

**Comment by hz0324** [comment]
Closed, because the question in unclear

**Comment by feross** [comment]
I'd use a magnet link so you can also specify tracker servers and web seeds, both of which can speed up peer discovery, and thus total transfer time.

**Comment by hz0324** [comment]
@feross 
Thank you for reply, it is really helpful
