### ISSUE TITLE
Old FAQ version on webtorrent.io/faq

### ISSUE THREAD

**Issue by codealchemist** [webtorrent/webtorrent#1390]
Just checked Watchtor's URL on https://webtorrent.io/faq and it's pointing to the old version.
FAQ is up to date on github.
We're just missing a deploy.
:)

Cheers!

**Comment by feross** [comment]
There needs to be a push to `master` on the [`webtorrent.io`](https://github.com/webtorrent/webtorrent.io) repo in order for a new deploy to happen.

But I was able to add a similar hook to this repo too. In the future, pushes to `master` will trigger a deploy of https://webtorrent.io.

This should help keep the docs up-to-date on the site :)

**Comment by codealchemist** [comment]
Nice! :)
