### ISSUE TITLE
Implement support for 'select only' (so) magnet link parameter

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1395]
*Originally proposed by @Daniel-Abrecht in https://github.com/webtorrent/webtorrent-desktop/issues/83#issuecomment-389965535*

There's a BEP that we should probably support: http://www.bittorrent.org/beps/bep_0053.html

> This magnet extension introduces the concept of an optional select-only file index array in the magnet URI, so that torrent clients can automatically select specific file(s) for download after the metadata has been downloaded.

This could probably replace the `ix` parameter that we invented for this exact use case. Since this is an actual BEP, it's probably better to support this instead (though it didn't exist when we invented `ix`)

**Comment by SilentBot1** [comment]
This has been implemented as of the commit https://github.com/webtorrent/webtorrent/commit/925bb881cfe90cc055f67e747df693f32d265733.

**Comment by Daniel-Abrecht** [comment]
Wow, this was really fast. Thanks everyone.

**Comment by feross** [comment]
Released as 0.100.0.
