### ISSUE TITLE
Can you add Local peer discovery plugin?

### ISSUE THREAD

**Issue by Ornataweaver** [webtorrent/webtorrent#1404]
ZeroNet has it.
Local peer discovery plugin added to make ZeroNet work without an internet connection on the local network.
https://zeronet.io/
http://127.0.0.1:43110/Blog.ZeroNetwork.bit/
http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:126:New+version:+0.6.2

**Comment by Ornataweaver** [comment]
[local_peer_discovery.mp4.zip](https://github.com/webtorrent/webtorrent-desktop/files/1733749/local_peer_discovery.mp4.zip) of ZeroNet

**Comment by Ornataweaver** [comment]
https://github.com/webtorrent/webtorrent-desktop/issues/1328

**Comment by KayleePop** [comment]
related: https://github.com/webtorrent/webtorrent/issues/1136

**Comment by Ornataweaver** [comment]
@KayleePop tnx.
