### ISSUE TITLE
Movies stop playing on VLC at completion

### ISSUE THREAD

**Issue by fjeddy** [webtorrent/webtorrent#1408]
When watching a movie that's currently downloading using VLC, then it will stop playing / quit VLC when the download finishes, forcing you to restart.

**Comment by SilentBot1** [comment]
Hey @fjeddy,

This sounds like an issue with [WebTorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) or [WebTorrent-cli](https://github.com/webtorrent/webtorrent-cli/) and not with the WebTorrent library.

Please could you recreate this issue on the relevant issue tracker, thank you.

All the best.
