### ISSUE TITLE
Some ideas for API improvements

### ISSUE THREAD

**Issue by Daniel-Abrecht** [webtorrent/webtorrent#1412]
While I was working on my magnet-protocolhandler project, I noticed a few things that have been a bit inconvenient:

1) client.add can only be called once for a torrent

While writing a webapp where a magnet url can be entered, it's quiet tempting to just use client.add, but if the same torrent is entered again, it will fail. After I noticed this, I used client.get first, and than either waited for the torrents ready event if it was already added or use client add otherwise. But then I notices that I can miss the ready event, so I had to check if the torrent was already ready first. I ended up with the following function:
```
function addOrGetTorrent(uri,callback){
  var torrent = webtorrent.get(uri);
  if(torrent){
    if(torrent.ready){
      callback(torrent);
    }else{
      torrent.on("ready",()=>callback(torrent));
    }
  }else{
    webtorrent.add(uri,callback);
  }
}
```

Since this seams like a pretty common use case, and it's so easy to get wrong, it would be nice to have something like this as a convenience function, or alternatively a parameter for the add function so it can be used for the same torrent more than once.

2) There is no way to retrieve a single common webtorrent instance.

Currently, there is only a constructor using which any number of webtorrent instances can be created. If multiple independent libraries use webtorrent, they need to obtain a webtorrent instance, so they may all create a new one. But what would the implications of that be? The instances wouldn't share the added torrents and other things, so could that lead to a lot of resources wasted if multiple libraries add the same torrent, for example?

I think it would be nice to have a singleton function, so that all libraries can use that function to get a single shared webtorrent instance. I'm just not sure what to do about the options that can be passed to the webtorrent constructor in that case though.

Lastly, I would like to thank everyone for creating this truly awesome library.

**Comment by feross** [comment]
Thanks for the thoughtful suggestions. I'd like to consider some of these ideas when we release a promise-based API sometime in the future. I think @DiegoRBaquero had interest in working on this at open point.
