### ISSUE TITLE
ERROR: Cannot create so many PeerConnections

### ISSUE THREAD

**Issue by robertheessels** [webtorrent/webtorrent#1414]
**What version of WebTorrent?**
0.100.0

**What browser and version? (if using WebTorrent in the browser)**
Chrome latest and also Chrome Canary latest

My browser app needs to share about 100 torrents per client.

Even when I seed 'only' 12 torrents I get a constant flood of this error:
```
webtorrent.min.js:1
Uncaught DOMException:
Failed to construct 'RTCPeerConnection':
Cannot create so many PeerConnections
```

Am I allowed to seed a hundred files in the browser? Is 0.100.0 production ready?
Thanx for any help!

**Comment by DiegoRBaquero** [comment]
WebTorrent creates many simple-peers in order to send WebRTC offers to the tracker, this is about 10 per torrent. So this is a limitation of the browser (a good one). If you are seeding so many, you should try using server side seeds.
