### ISSUE TITLE
Maybe add support .mkv container?

### ISSUE THREAD

**Issue by jun-dev** [webtorrent/webtorrent#1420]
This is very dublicate issue. Maybe this rechange also front is adding this format for chrome-like browsers?

**Comment by SilentBot1** [comment]
Hey @jun-dev,

The `render-media` library is used within the browser for rendering files to the DOM, this library already has support for `.mkv`, though they must be encoded using specific audio and video codecs which the browser supports as not all are, the desired audio/video codecs can be seen here [here](https://github.com/feross/render-media/blob/80ee0103863da4eec4a7cf58c2e85c74e9b81b34/index.js#L352).

Hope this helps,
If this doesn't answer your question, feel free to re-open.
