### ISSUE TITLE
emitter.setMaxListeners() - Seed loads of torrents

### ISSUE THREAD

**Issue by hellomotow** [webtorrent/webtorrent#1423]
Hi when running the following command at boot to launch hundreds of torrents I get the following error

webtorrent download /home/vids/torrentdata/torrentfiles/*.torrent -o /home/vids/torrentdata/ --keep-seeding

(node:23279) Warning: Possible EventEmitter memory leak detected. 11 listening listeners added. Use emitter.setMaxListeners() to increase limit

What is the correct way to do this?

**What version of WebTorrent?** 1.12.3

**What operating system and Node.js version?** Ubuntu 18.04 Nodejs 6.11.4

**Comment by DiegoRBaquero** [comment]
It's fine, nothing to worry about. Just a warning that many listeners are added, but done un purpose.
