### ISSUE TITLE
How keep seeding after torrent downloaded

### ISSUE THREAD

**Issue by MaximNordWhale** [webtorrent/webtorrent#1424]
**What version of WebTorrent?**
webtorrent@0.98.21
**What operating system and Node.js version?**
Mac Os, Windows 10, Ubuntu 16
Node v8.9.4
**What browser and version? (if using WebTorrent in the browser)**
electron@1.8.6 
**What did you expect to happen?**
Situation - I can't seed files from not torrent owner, for example I run my app on 3 computers
PC 1 - owner,
PC 2 - downloader
PC 3 - downloader

I run client.seed method on PC1

I added torrent to download list on PC2 (by run client.add(torrent, {path: torrentsList[i].path}, (torrent) => {
            // ////console.log("I'm here", torrent);
            callback("addTorrentToTorrentList", {}, torrent, i)
            eventsTorrent(torrent, callback, i);
          });

I started download files - all ok, all downloaded on PC2. 

Then I run download on another computer PC3 - I got information what I downloaded from 2 seeders - from torrent owner and from PC2
But when I turn off PC1 - torrent will download from PC2 (not all but some data are downloaded)
It works if PC2 doesn't download all data.

**What actually happened?**
When PC2 downloaded all data - I can't seed from PC2 to PC3, so if pc1 will be turn off I can't download content

How I can keep seeding after all data downloaded?

**Comment by SilentBot1** [comment]
Hey @MaximNordWhale,

By default all WebTorrent clients keep seeding unless explicitly removed, so I don't understand why you are facing this issue. Without further information regarding your setup, specifically a more in depth code example, it would be hard to help you.

> When PC2 downloaded all data - I can't seed from PC2 to PC3.

In this scenario, are you closing all clients between the tests or does PC 2 stay on through PC 1 disconnecting from the swarm and PC 3 joining?

I Hope I can help you with this issue.

**Comment by DiegoRBaquero** [comment]
It should work, are you on same network (i.e. TCP or WebRTC) ?

Are the network conditions the same or there's a firewall?
