### ISSUE TITLE
Need more feature like choosing which file to downlad before download

### ISSUE THREAD

**Issue by prashantrijal96** [webtorrent/webtorrent#1426]
Hi everyone I was thinking what if we can choose which file to download before downloading all of them.

**Comment by SilentBot1** [comment]
Hey @prashantrijal96,

If you know which files from the torrent you want, this is currently achievable via setting `torrent.so` within client `infohash` event to a CSV string containing the desired files e.g. "0,2-4" which will select file 0, 2, 3 and 4, or if a magnetURI is used to add the torrent to the client, the `&so` parameter described in [BEP53](http://www.bittorrent.org/beps/bep_0053.html) is supported for selecting only specific files.

If the desired files are unknown, you could iterate through the torrent.files array in the client `metadata` event, calling`.deselect()` on all files, then `.select()` on any files which match your criteria, such as file extension, file length, ect.

Hope this helps, 
If this doesn't solve your question, feel free to re-open the issue!
