### ISSUE TITLE
Blob is too big.

### ISSUE THREAD

**Issue by SunnyQjm** [webtorrent/webtorrent#1429]
Now, I want to use webtorrent API to share a file (seed it). In the same time, use the magnetURI to download this file.  
But if this file too big. (For example in chrome, the file bigger than 800M). Use "file.getBlob()" or "file.getBlobUrl" can not create a Blob Object. The Web page will cash.

I have test that the demo web "https://instant.io/" also have this problem.

If I want to trans a Big file, How can I fix it.

**Comment by SilentBot1** [comment]
@SunnyQjm,

What browser are you using @SunnyQjm?

Browsers handle blobs differently, with some storing them solely in memory while others store the blob on disk, a good breakdown of the different limits between browsers can be seen [here](https://stackoverflow.com/a/43816041). 

> The Web page will cash.

Chrome specifically states that 
> Creating a lot of blobs, especially if they are very large blobs, can cause the renderer memory to grow too fast and result in an OOM on the renderer side. This is because the renderer temporarily stores the blob data while it waits for the browser to request it.

Using a different store would possibly help you with this issue; something like the [indexeddb-chunk-store](https://github.com/xuset/indexeddb-chunk-store).

Hope this helps.
