### ISSUE TITLE
Webtorrent does not work on Safari

### ISSUE THREAD

**Issue by tangnv** [webtorrent/webtorrent#1432]
**What version of WebTorrent?**
Latest

**What browser and version? (if using WebTorrent in the browser)**
Safari MacOS 12 beta

**What did you expect to happen?**
It should work well on Safari

**What actually happened?**
It didn't work

Hi, I tried to deploy the example, it worked well on Chrome, but it did not work on Safari.
My deploy here:
https://web-torrent-test.firebaseapp.com/

Errors log:
![image](https://user-images.githubusercontent.com/4475472/42731498-6f4cf918-8838-11e8-946d-af804ef48e3e.png)

**Comment by KayleePop** [comment]
I think this is the issue https://github.com/feross/simple-peer/issues/336
