### ISSUE TITLE
Webtorrent-seeder-problem in bash

### ISSUE THREAD

**Issue by hersche** [webtorrent/webtorrent#1433]
**What version of WebTorrent?**

0.100, as cli / in bash

**What operating system and Node.js version?**

Ubuntu 16.04 Server, Nodejs 8.11.3

**What did you expect to happen?**

Seeding files

**What actually happened?**

I can not receive data.

--------------

To explain a bit more free, i use this command:

    webtorrent --keep-seeding --no-quit -a https://tracker.thepirate.party seed /root/5chewconv.mp4 /root/small.mp4

The command gives back 2 magnet-links, but both can not be watched via instant.io nor my own implementation.

I have also installed bittorrent-tracker, which runs at https://tracker.thepirate.party/stats

It is started like this:

     bittorrent-tracker --http-hostname tracker.thepirate.party --udp-hostname tracker.thepirate.party --http --udp --ws --stats --trust-proxy

and is forwarded via nginx, cert by letsencrypt.

Not shure, what the problem is:

- should it be -a https://tracker.thepirate.party/announce ? Then, the tracker is showing it in stats, but it doesn't work and no other tracker has /announce in the magnet-link..?

- do i need to open any special ports? (already tried to allow all incoming connections via iptables)

- can nginx block the needed port 80 and 443 for webtorrent? quicktested it withouth success.

- the server is in the us, i am in eu. does that matter? i can reach the website from my webserver withouth problems.

Enough guesses, i am interessted in your answers - thanks in advance and also for this project!

**Comment by SilentBot1** [comment]
Hey @hersche,

> The command gives back 2 magnet-links, but both can not be watched via instant.io nor my own implementation.

The `WebTorrent` library in a browser (excluding Brave) can only communicate with WebRTC peers, this is likely the cause of your example not working. 

Currently `webtorrent` has two different command line implementations, `webtorrent-cli` and `webtorrent-hybrid`, which of these do you have installed as `webtorrent` in your example commands?

Which version you need installed varies on the functionality required:
`webtorrent-cli` can only talk to TCP/UDP peers + WebSeeds, it can't talk with WebRTC peers,
`webtorrent-hybrid` can talk to both WebRTC and TCP/UDP peers + WebSeeds.


> should it be -a https://tracker.thepirate.party/announce ? Then, the tracker is showing it in stats, but it doesn't work and no other tracker has /announce in the magnet-link..?

`/announce` needs to be included if you're using the bittorrent-tracker as a http tracker, which you are.
If you were using the WebSocket or UDP tracker instead, ip:port would suffice.

> do i need to open any special ports? (already tried to allow all incoming connections via iptables)

For `webtorrent` you can specify the listening TCP port by specifying `torrentPort` in client options or else a random port will be selected.
For `bittorrent-tracker` the default listening port is TCP 8000 but again can be specified.

Hope this helps, I'll wait for response regarding which implementation you're using before closing the issue as this could still be a bug depending on which you are using.

**Comment by hersche** [comment]
thanks for the hint about webtorrent-hybrid, it just works. I just should read the docs better ;)

also the explain about /announce is nice! :+1: 

i close it, since it's clearly not a bug. thanks again for your help!

**Comment by SilentBot1** [comment]
It's no problem @hersche at all.
Thank you for closing the issue :)
