### ISSUE TITLE
how to add dht into webtorrent

### ISSUE THREAD

**Issue by wildelf** [webtorrent/webtorrent#1453]
when I used webtorrent to download files with magnet that I searched from internet likes "magnet:?xt=urn:btih:JJKYYFNWS3VUILHAMURFFEZ6WFVNAAWN",it did not work.
       I find someway to deal with this issue,but i am fail.
       Begging some solution.
       thanks for any help.

**Comment by feross** [comment]
See the FAQ:

> Why does browser downloading not work? I see no peers!

> It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. WebTorrent Desktop, Vuze, webtorrent-hybrid, Playback, instant.io, or βTorrent.

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.

**Comment by wildelf** [comment]
Thanks for response.
I used webtorrent to download files in chrome,does it support dht?
I can download the files using that magnet in thunder,but it does not work in webtorrent.
Are they not a same BT protocol ?

**Comment by feross** [comment]
The browser version of WebTorrent doesn't support the DHT.

**Comment by feross** [comment]
No

**Comment by wildelf** [comment]
What a pity,but thanks a lot!
