### ISSUE TITLE
Could you make parseTorrent available?

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent#1457]
**What browser and version? (if using WebTorrent in the browser)**
0.100.0

Hi, I was wondering if the `parseTorrent` could be publicly available throught `webtorrent`
I'm looking for a way to identify if what the client are adding is a torrent or not. would be useful to have something like `.isTorrent(x)`

```js
// index.js
WebTorrent.parseTorrent = parseTorrent
```

**Comment by DiegoRBaquero** [comment]
Ummmm, but if you add an invalid torrent, you get an error, isn't that enough?

**Comment by jimmywarting** [comment]
I would prefer if it was syncron, I have a input where they can add two different things.
Could be a torrent or just regular chitchat text.

Atm i have ripped out the thing I'm most interested from that package which is
this 3 regex:

```js
if (
  /^(stream-)?torrent:/.test(str) || 
  /^[a-f0-9]{40}$/i.test(str) ||
  /^[a-z2-7]{32}$/i.test(str) {
) {
  // Do something
}
```

Which i just combined into one regex: `/(^(stream-)?torrent:|^[a-f0-9]{40}$|^[a-z2-7]{32}$)/`
It might be sufficiently

**Comment by KayleePop** [comment]
Can't you just require it separately and use browserify?

``` js
const WebTorrent = require('webtorrent')
const parseTorrent = require('parse-torrent')

const client = new WebTorrent()

function isTorrent (id) {
  try {
    parseTorrent(x)
    return true
  } catch (e) {
    return false
  }
}

if (isTorrent(x)) {
  client.add(x)
}
```

**Comment by jimmywarting** [comment]
Rather use my one regex

**Comment by DiegoRBaquero** [comment]
Are you using the hosted minified version? Trying to understand the use case

**Comment by jimmywarting** [comment]
Yes

**Comment by DiegoRBaquero** [comment]
I don't see no harm, I'll take a PR
