### ISSUE TITLE
Seed file from Google Drive to webtorrent?

### ISSUE THREAD

**Issue by wdfsinap** [webtorrent/webtorrent#1460]
is it possible to seed file from Google Drive as Drive has unlimited storage as backup and good network? how about if mount the Drive on the VPS

**Comment by DiegoRBaquero** [comment]
If the content can be hotlinked, then it can be used as a webseed :)

**Comment by fredsif** [comment]
I thought you had to create a torrent for the file to have it webseeded?
How can you do that with Google Drive?

**Comment by jimmywarting** [comment]
It would be cool if you could construct a WebSeed with custom get mechanism. 

Everything isn't as simple as a GET request with range header

Some require credentials, you might be dealing with streams coming from a sockets or other storage that don't play nice with easy hot linking. Perhaps the file isn't as well mapped as a file hierarchy maybe the file is only accessible by a hash/id identifier, you could build something that uses ftp, afp, smb protocol.

Something like this

```js
peer = new WebSeed({
  async get(pieceIndex, offset, length) {
    const chunk = await getPiece(...args)
    return chunk
  }
  destroy() {
  }
}, torrent)
```

you could then implement a WebSeed using any cloud storage API

**Comment by datnv-ibl** [comment]
Note that google drive have several limitations: request limit, download limit, quota limit and CORS

**Comment by DiegoRBaquero** [comment]
@fredsif you have to pre-create the torrent with the file. See https://hackernoon.com/how-to-create-a-swarm-cdn-for-free-with-webtorrent-bfa09d193f71

if Google Drive doesn't support CORS there's nothing we can do.
