### ISSUE TITLE
Why are peers still connected?

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent#1469]
Me and the other peer have downloaded all the pieces... Nobody is seeding but the connection is still open, why?

**Comment by DiegoRBaquero** [comment]
Normally connections are not closed in BitTorrent for the DHT to work, but in WebRTC, as there's no DHT yet, we could close the connection once both peers are at 100% downloaded.

**Comment by jimmywarting** [comment]
Closing since I got my answer.
