### ISSUE TITLE
it stays loading on instant.io, Just few torrent play properly, what could it be?  wss://tracker.fastcast.nz??

### ISSUE THREAD

**Issue by omegamerol** [webtorrent/webtorrent#1470]
it stays loading on instant.io, Just few torrent play properly, what could it be?  
¿¿wss://tracker.fastcast.nz??

**Comment by DiegoRBaquero** [comment]
It could be that the torrent you are looking for is not seeded by WebRTC peers.

**Comment by sheddup** [comment]
So why does the exact same torrent play with webtorrent-desktop but not on https://instant.io ? Isn't webtorrent-desktop the exact same code just inside of an electron app?

**Comment by DiegoRBaquero** [comment]
WebTorrent Desktop has access to both WebRTC (browser) peers and TCP/UDP peers (other BitTorrent clients). This must be it.
