### ISSUE TITLE
Some Segment fetch fail in chrome browser using webtorent.min.js

### ISSUE THREAD

**Issue by VTOSFOUNDATION** [webtorrent/webtorrent#1472]
hi 
we are using the last version of webtorent.min.js on chrome browser it fails to fetch some segments using HTTP seed server.

![image](https://user-images.githubusercontent.com/34971947/44238511-9dc7d000-a17a-11e8-9bee-bd94358070a4.png)

in mobil chrome browser work good, also in firefox work good both mobile and pc version.

if there are more peers it works well. the problem only is when there are no peers.

node version 'v9.10.1'

you can test here
https://social.vtos.io/index.php/video?_id=630

thank you, great work to all the dev of webtorrent.

**Comment by DiegoRBaquero** [comment]
Why did it fail tho? Are you sure it's not a server error?

Also, it shouldn't matter, webtorrent retries.

**Comment by VTOSFOUNDATION** [comment]
the problem is only using chrome, it gets stuck, it does not retry i have to forward the video when gets to the segment that fails., but if I open the same video using firefox it share to the chrome browser by webrtc and it completes the failed fetch.

![image](https://user-images.githubusercontent.com/34971947/44240636-c5bc3100-a184-11e8-884b-50750a6ff209.png)

the mobile version also doesn't have this problem, can you test in your chrome browser?

https://social.vtos.io/index.php/video?_id=630

**Comment by VTOSFOUNDATION** [comment]
a friend test in another network and it work good, so its a local problem, i will try to reinstall and try on different networks, thank you for your fast answer, hope we can work later with you. we are working on a live stream app using webtorrent

https://github.com/VTOSFOUNDATION/webtorrent-live-stream-on-Ethereum-blockchain.

thank you.
