### ISSUE TITLE
Route traffic thought other peers.

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent#1475]
WebTorrent is awesome since it uses WebRTC for peer-to-peer transport. It works without browser plugins, extensions, or any installations. And i believe that have been the solo purpose of building WebTorrent in the first place. But the **big** bottleneck is that there isn't enough hybrid or WebTorrent clients out there to make it somewhat useful in the browser. (not until other torrent clients start supporting WebRTC transport)

One way to solve this could be to route traffic thought other hybrid peers that are able to establish a TCP/UDP connection on behalf of WebRTC clients out there. At least until there is enough WebRTC peers in the swarm. I have seen some torrent client doing this... One example is Tribler. (they don't support WebRTC but traffic go thought other peers before it comes to you) so a middle man is download pieces for you but don't keep the content for themself.

Would this be something of interest?

**Comment by KayleePop** [comment]
This is discussed here https://github.com/webtorrent/webtorrent/issues/325

**Comment by jimmywarting** [comment]
ah, cool - closing as dupe

**Comment by jimmywarting** [comment]
Hmm, didn't quite feel like the idea i had in mind? did look more like a proxy... a think you need to install to make it to some sort of WebSeed?

**Comment by DiegoRBaquero** [comment]
You could setup a server with `webtorrent-hybrid` that is asked to add certain hashes so that they become available to WebRTC networks. But again, this is out of the scope of the library and `webtorrent-hybrid` itself.
