### ISSUE TITLE
Is there any resources that helps to contribute in Webtorrent ?

### ISSUE THREAD

**Issue by Er-rchydy** [webtorrent/webtorrent#1493]
@feross  @DiegoRBaquero 
Can you please share with us what are the best resources to develop `Webtorrent` ? 
I want to understand how it's work ( in low level not in general ), like how does the protocols used in `Webtorrent` works, video encoding ...., like if i want to contribute in `Webtorrent`  what books do i need to read .
i tried to start with how Torrent works but all i found is some books that teach how to use it not how it works so you can try modify it and play with it.
i hope you understand what i mean, thanks in advance

**Comment by KayleePop** [comment]
There's a great explanation of how bittorrent works in section two of this paper http://pages.di.unipi.it/ricci/XR-EE-LCN_2010_010.pdf

Here are the standards for implementing bittorrent clients (BEPs) http://bittorrent.org/beps/bep_0000.html

There are some code examples for webtorrent here https://webtorrent.io/intro

There are lots of example apps that use webtorrent linked on this page. https://webtorrent.io/faq You can look at the code of most of them on github
