### ISSUE TITLE
Does webtorrent support adaptive bitrate streaming?

### ISSUE THREAD

**Issue by bobpoekert** [webtorrent/webtorrent#1496]
It would be awesome if webtorrent supported DASH/HLS-style adaptive bitrate streaming where there was a 1:1 mapping between DASH/HLS-style chunks and bittorrent chunks. That way you could choose the next bitrate based both on your bandwidth and on the relative rarity of the next chunks. Is this supported?

**Comment by DiegoRBaquero** [comment]
It is not. Live streaming won't be supported by the library itself, but this could be a solution: https://github.com/webtorrent/webtorrent/issues/886.

**Comment by bobpoekert** [comment]
Adaptive bitrate streaming doesn't have anything to do with live streaming, it's what allows eg: youtube to offer video streams in multiple bitrates

**Comment by DiegoRBaquero** [comment]
You could put all the bitrates in the same torrent and have the video player choose which one to download and play. But this is out of the scope of the library.

**Comment by bobpoekert** [comment]
Does webtorrent give you a way to get a list of all the chunks in a torrent and selectively download some chunks but not others?

**Comment by DiegoRBaquero** [comment]
Yes, you can selectively download pieces :)

**Comment by DiegoRBaquero** [comment]
and/or files

**Comment by pimboli** [comment]
Hi,

interesting approach with one torrent archive which has an m3u8 file and the different chunks inside.
Did someone test it? Is the web torrent library handling itself which part is having to download first(which chunk)?
