### ISSUE TITLE
TV support

### ISSUE THREAD

**Issue by artivision** [webtorrent/webtorrent#1499]
Good day. How do i include the "webtorrent.min.js" script on my page? Can this be done on a TV web browser? Is this compatible with "popcorntime-online.tv"? Thanks.

**Comment by DiegoRBaquero** [comment]
1. Referencing in a script tag.
2. I don't think it support WebRTC, so probably not.
3. No idea, and we don't support, endorse or allow copyright infringement with WebTorrent.
