### ISSUE TITLE
Speed download is only for one torrent. Where is the total speed of all torrent ?

### ISSUE THREAD

**Issue by okleyz** [webtorrent/webtorrent#1503]
Speed download is only for one torrent. Where is the total speed of all torrent ?

**Comment by okleyz** [comment]
thanks for reply i talk about osx app not in command

**Comment by KayleePop** [comment]
Total download speed for all torrents isn't currently included in the UI of webtorrent-desktop anywhere AFAIK.

You could make a feature request for it in this repository https://github.com/webtorrent/webtorrent-desktop

**Comment by okleyz** [comment]
Thanks done :)
