### ISSUE TITLE
Seeding from the http server is not working

### ISSUE THREAD

**Issue by fran232** [webtorrent/webtorrent#1508]
WebTorrent Version: 0.102.0
node version: 8.9.4

WebTorrent is not seeding the files from the http server. I've setup a http-server for the torrent files and downloading files from that server is not working. 

On my side, the webtorrent is working well with other torrent files. This app was built with Eletron.js

This is the code for add the torrentUrl.
`
this.torrent = this.torrentClient.add(this.torrentUrl, { 
        path: this.path,
        maxWebConns: 10
      }, function(torrent, err) {
        console.log("Client is downloading:", torrent.infoHash)
        console.log(torrent)
        console.log(err)
      })
`

And then this is the torrent file infor
**

              name: aaa.exe
          filename: wow1.torrent
           comment: 
              date: 31.12.1969 07:00:00 PM (0)
        created_by: 
             files: (1)
                    1: client_wow-735_Wow-64.exe
              size: 2 7 (27567592)
          announce: http://s3-tracker.eu-west-1.amazonaws.com:6969/announce
     announce_list: 
                    - http://s3-tracker.eu-west-1.amazonaws.com:6969/announce
         info_hash: 5c33f7a3a615dd438327f6840ac8eb8c4bee8ad8
**

I'm not sure why I'm running into this problem.

**Comment by DiegoRBaquero** [comment]
I don't see the webseed address for the file. S3 tracking is just tracking, and I think it's not supported (even in nodejs env)

**Comment by fran232** [comment]
@DiegoRBaquero this is the one of the file on s3. https://s3-eu-west-1.amazonaws.com/aow-prod-launcher-media/client/wow-735/Wow.exe?torrent. After download the torrent file, I tried with bittorrent and it works. But it does not work with webtorrent & webtorrent-hybrid.
Could you please tell me what the best solution is?
