### ISSUE TITLE
MaxBlobLength is ignored

### ISSUE THREAD

**Issue by index23** [webtorrent/webtorrent#1512]
**What version of WebTorrent?**
I am using WebTorrent version 0.102.4

**What browser and version? (if using WebTorrent in the browser)**
I am using Chrome version 69.0.3497.100 (Official Build) (64-bit)

**What did you expect to happen?**
I expect to fail streaming of video.

**What actually happened?**
Video is streaming normally.

Hi, 

I stream video using `appendTo` method, and through `opts` parameter I have set `maxBlobLength` to 1:

```
file.appendTo('#player-wrapper', {
          autoplay: true,
          controls: false,
          maxBlobLength: 1
        }, (err, elem) => {
          if (err) {
            console.log('Error:', err)
          }
        }) 
```

Due to documentation,
> maxBlobLength: Files above this size will skip the "blob" strategy and fail (default: 200 * 1000 * 1000 bytes)

I have expected to fail streaming of video, video plays normally.

**Comment by feross** [comment]
This isn't necessarily a bug. The video you are trying to play may be using the `videostream` or `mediasource` strategy in which case the video is being streamed (with low memory usage) and this parameter is ignored. The `maxBlobLength` parameter is only used when the `blob` strategy is used, which is attempted after the other two. The option exists to limit the max amount of RAM that will be used to make the Blob.
