### ISSUE TITLE
Regression: File.downloaded becomes negative once the first piece is fully downloaded

### ISSUE THREAD

**Issue by corwin-of-amber** [webtorrent/webtorrent#1515]
**What version of WebTorrent?**
0.102.4

**What operating system and Node.js version?**
macOS 10.13.6
Node.js 10.0.0

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
`File.download` property should always be a nonnegative integer.

**What actually happened?**
After the first piece (`_startPiece`) of the file has finished downloaded, the file's `offset` is subtracted from the downloaded size, causing it to be a (sometimes quite large) negative.
This occurs in `file.js`, line 46 (https://github.com/webtorrent/webtorrent/blob/master/lib/file.js#L46), as of revision 6fbef8e.

I noticed the negative values after upgrading from version 0.98.24, which did not have this issue.

**Comment by corwin-of-amber** [comment]
I was able to patch the problem by replacing `- this.offset` with `- (this.offset % pieceLength)`. I am not 100% sure that this is how pieces work in a torrent so I leave it to your judgement.

**Comment by KayleePop** [comment]
Is this where it happened? https://github.com/webtorrent/webtorrent/pull/1479

**Comment by corwin-of-amber** [comment]
@KayleePop Yes, this seems so. I think the author of that push request only handled the case where there is only one large file and that this file starts at the first piece of the torrent. When there are multiple videos, for instance, and the video starts at a high-index piece (e.g. 1000), it does not make sense to initialize the size to `pieceLength - this.offset`.

**Comment by G-Ray** [comment]
I'm affected. @DiegoRBaquero what about you ?

**Comment by corwin-of-amber** [comment]
Any news about this? Seems like a pretty simple fix.
It will be so sad if WebTorrent becomes abandoned...

**Comment by DiegoRBaquero** [comment]
I'll review a PR if you a willing to take on this :)

**Comment by corwin-of-amber** [comment]
Sure, you got it.
