### ISSUE TITLE
WebTorrent are trackers needed for others to download from me ?

### ISSUE THREAD

**Issue by C0nw0nk** [webtorrent/webtorrent#1526]
I am curious with my magnet URI in order for others to download from me do I need a tracker or does webrtc solve all of that and they can download from me with the magnet uri only or the .torrent file directly.

I want to seed to others of my site without trackers etc using only the .torrent fle or magnet uri. But I don't know if it works like that so any random user around the world can download from me ?

This post indicates nobody will be downloading from me.....?
https://stackoverflow.com/questions/34082637/how-to-use-webtorrent-io
`WebTorrent doesn't support trackerless magnet URIs`

Code 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/webtorrent/0.102.4/webtorrent.min.js" type="text/javascript"></script>

<video controls="controls" controlslist="nodownload" oncontextmenu="return false;" preload="none" poster="/">
<source src="/" type="video/mp4" />
</video>

<script type="text/javascript">
var client = new WebTorrent();
var torrentId = 'magnet:?xt=urn:btih:blah-bleep-bloop'; //magnet uri only nothing else

client.add(torrentId, function (torrent) {

torrent.addWebSeed('https://www.domain.com/jpeg.jpg')

console.log('Torrent Ready')
var file = torrent.files.find(function (file) {
	return file.name.endsWith('.jpg')
})

var append_to_tag = document.getElementsByTagName('video')[0];
file.getBlobURL(function (err, url) {
if (err) throw console.log(err)
append_to_tag.poster = url
console.log('Client is downloading: ' + url)
})

})
</script>
```

**Comment by SilentBot1** [comment]
Hey @C0nw0nk,

Trackers are needed for initial peer discovery, specifically with WebTorrent in the browser, [WebSocket trackers](https://github.com/webtorrent/bittorrent-tracker) are used.

By default any torrent created by a WebTorrent client automatically has 8 trackers added, 3 being WebSocket trackers and 5 being udp, a list of these trackers can be viewed [here](https://github.com/webtorrent/create-torrent/blob/6e6fc18aac7d212a5a8d9c766b12a525618e9ceb/index.js#L16)!

Hope this helps!

**Comment by C0nw0nk** [comment]
Hello @SilentBot1 

Thank you for the information, What about DHT?

I thought it had DHT and could work/function without any trackers ? As the github homepage even says DHT support....

**Comment by SilentBot1** [comment]
@C0nw0nk,

DHT is supported, but only on platforms where possible, as a DHT node operates using UDP sockets, which aren't available for JavaScript to access in a browser, it is impossible to implement the Mainline DHT within a browser. 

Also as the Mainline DHT store peers as their listening TCP addresses (as IP:PORT encoded into a [6-byte string](https://wiki.theory.org/index.php/BitTorrentDraftDHTProtocol#Contact_Encoding)), even if browser WebTorrent clients were able to communicate with the Mainline DHT and receive the addresses, communication is impossible as like UDP sockets, TCP sockets aren't accessible to JavaScript in the browser either.

When WebTorrent is ran via NodeJS in the command line, the Mainline DHT is supported as both UDP and TCP sockets are accessible.

I hope this helps!

**Comment by SilentBot1** [comment]
@C0nw0nk,

There have been discussions about it, one of which can be seen in [this thread](https://github.com/webtorrent/webtorrent/issues/1492), but with how WebRTC connections are established and how the a DHT works, it is near, if not impossible to implement in the browser.

Sorry for the bad news, but I hope this helps none the less.

**Comment by C0nw0nk** [comment]
Be interesting to see a more universal solution to this problem.

Here is a github repo of trackers i found that i will use ontop of using the default ones.

https://github.com/ngosang/trackerslist

The more trackers we use the better right...?

**Comment by C0nw0nk** [comment]
You said `UDP sockets, which aren't available for JavaScript to access in a browser,`

So UDP trackers don't work either on websocket trackers will work ?

Because in the default tracker list there are UDP trackers strange enough.

**Comment by SilentBot1** [comment]
Hey @C0nw0nk,

I haven't tested performance differences in adding more trackers but a wide range of trackers adds more redundancy to the torrent, though you need to be sure that the trackers support WebTorrent.

The reason a range of tracker types are added is because the package that I linked, `create-torrent`, can be used in the command line to create torrents that work will all BitTorrent software, including all tracker types for the greatest level of support. 

WebTorrent uses it's own tracker protocol over WebSockets to transfer the WenRTC offer and answers, meaning that standard trackers, even if they use http or websockets, do not work. The only tracker that I know of that supports WebTorrent can be found [here](https://github.com/webtorrent/bittorrent-tracker), and all the public `bittorrent-tracker` trackers are already included by default in the list I provided earlier.

Hope this helps!

**Comment by C0nw0nk** [comment]
So why won't webtorrent add support for the other tracker types why do they have to be running a webtorrent tracker for webtorrent to talk to it... Surely to add support for what already exists in the torrent tracking world and is mostly used can't be that hard and the benefits of doing so would be huge.

**Comment by DiegoRBaquero** [comment]
The trackers need to support webtorrent because the peers are webrtc offers/answers. There's no way to proxy or use direct udp/tcp/https trackers.
