### ISSUE TITLE
Webpack + Vue issue

### ISSUE THREAD

**Issue by volokolamskspb** [webtorrent/webtorrent#1527]
What version of WebTorrent?
0.102.4
"vue": "^2.5.17"
webpack4
What did you expect to happen?
Should add video to DOM and get BlobUrl of file.
What actually happened?
Uncaught TypeError: Cannot read property reading of undefined
```
files.forEach((file)=>{
                client.add(file, this.onTorrent);
            });
torrent.files.forEach( (file) => {
                file.getBlobURL(function (err, url) {
                    if (err) throw err
                    var a = document.createElement('a')
                    a.download = file.name
                    a.href = url
                    a.textContent = 'Download ' + file.name
                    document.body.appendChild(a)
                })
            });
```

![selection_003](https://user-images.githubusercontent.com/10552101/46909787-a8b39c80-cf40-11e8-8493-05da0747356c.png)

**Comment by Miraries** [comment]
Don't know what the issue is but if you use the pre-built version it seems to work.
```
import WebTorrent from 'webtorrent/webtorrent.min'
```
