### ISSUE TITLE
Logging IP-Addresses

### ISSUE THREAD

**Issue by legallaw** [webtorrent/webtorrent#1528]
Hello,
is there a way to log the IP-Adresses and amount of data downloaded from any peer?
We found illegal copies of our customers Movies on webtorrent Sites and we need a tool to collect the IP-Addresses of the WebTorrent Sharer.

If someone can implement this feature please contact me.

Best
Frank

**Comment by SilentBot1** [comment]
Hello Frank,

It is possible to gather the ip address from the WebRTC offers sent from the websocket tracker though gathering the total amount transferred to all peers is not possible.

If you could provide more information about the website and the content stolen to the email address listed on my profile, I will be happy to try and assist you with this.

All the best, 
   Brad M.

**Comment by DiegoRBaquero** [comment]
Data downloaded, no. IPs can be retrieved from a tracker (if you run it) and the websites uses it.

Only way to get the IPs would be to join the swarm as a peer and get webrtc offers where IP is visible. Pretty much just like normal bittorrent.
