### ISSUE TITLE
Webtorrent setting a custom User-Agent in requests

### ISSUE THREAD

**Issue by C0nw0nk** [webtorrent/webtorrent#1530]
I see webtorrent sends a custom user agent in all its request to my server checking nginx logs.

`WebTorrent/0.102.4 (https://webtorrent.io)`

Isit possible to include a feature to set my own custom user agent in javascript. The benefits of that could be awesome for my server expecting a specific useragent instead in requests and also for `sha1` url's etc.

```
torrent.setUserAgent('WebTorrent/0.102.4 (https://webtorrent.io)') //can change modify and set a custom user agent for requests from webtorrent to your server
```

**Comment by SilentBot1** [comment]
Hey @C0nw0nk,
 
Currently the user agent is hard coded for all [webseeds](https://github.com/webtorrent/webtorrent/blob/master/lib/webconn.js#L117), [tracker](https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L311), and [metadata](https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L368) requests, though it would be easy to implement a changeable user agent. Would you be looking for changing all instances of the user agent including requests made to trackers or only the user agents included with WebSeed / Metadata requests?

All the best.

**Comment by C0nw0nk** [comment]
I only had interest in changing the webseed requests that my servers would
receive.

**Comment by C0nw0nk** [comment]
Ontop of what i previously wrote does webtorrent when requesting the `.torrent` file from my server can that send a custom header or modify the user-agent too ?

**Comment by jimmywarting** [comment]
Borrowing this thread a lite, But i'm wondering how you can get the user-agent of another peer...

**Comment by SilentBot1** [comment]
@C0nw0nk, the implementation I wrote which can be seen [here](https://github.com/SilentBot1/webtorrent/commit/2dd13948acd3f6da0a57025d6ee109eed83a8b3e), I'll not send a PR yet as it seems not all your requirements are there, it sets one blanket user-agent for all requests, meaning it is presented to the tracker, .torrent server (metadata server) and webseed.

If you are wanting to be able to specify all three separately, that could also be done though for your use case I would recommend using a combination of a user-agent and request origin or even a custom middleware with tokens.

Hey @jimmywarting,

The user-agent is only presented in http(s) requests to trackers, webseeds and the metadata server so currently it's not possible to get another peers user-agent, you could possibly create a [bittorrent-protocol](https://github.com/webtorrent/bittorrent-protocol) extension to exchange user-agents with remote peers if it's needed depending on what you are doing.

**Comment by jimmywarting** [comment]
Don't really need it but it would have been interesting to know and see what other torrent clients others are using.

**Comment by SilentBot1** [comment]
@jimmywarting sorry, I thought you were asking about the user-agent. 

The peerId of a peer should contain the [version and software](http://www.bittorrent.org/beps/bep_0020.html) being used in the from of a prefix, though with WebTorrent going above version `0.100.0` there is a issue with the prefix and the current version `0.102.4` shows as the prefix `-WW0002-`.

**Comment by untitledlt** [comment]
Would be great if we could add basic Auth, cookies or custom headers as many trackers requires authentication.

**Comment by SilentBot1** [comment]
Hey @untitledlt,

I agree this would be a useful feature to be able to assign individual headers for http trackers. This would require changes in at least two modules `torrent-discovery`, `bittorrent-tracker` and likely this module too, I'll have a look and start throwing something together in the next few days.

**Comment by C0nw0nk** [comment]
https://github.com/webtorrent/webtorrent/issues/1530#issuecomment-432597990 It would be better as a feature like that for custom headers to be added but then again the way @SilentBot1  has added it to the torrent options.



client = new WebTorrent([opts])


If opts is specified, then the default options (shown below) will be overridden.

{
  maxConns: Number,        // Max number of connections per torrent (default=55)
  nodeId: String|Buffer,   // DHT protocol node ID (default=randomly generated)
  peerId: String|Buffer,   // Wire protocol peer ID (default=randomly generated)
  tracker: Boolean|Object, // Enable trackers (default=true), or options object for Tracker
  dht: Boolean|Object,     // Enable DHT (default=true), or options object for DHT
  webSeeds: Boolean        // Enable BEP19 web seeds (default=true)
 userAgent: String          // Custom user agent to present on webseed, tracker and metadata requests
}

A customheader addition that allows us to specify either one or multiple custom headers to send in requests would go down so well.

**Comment by C0nw0nk** [comment]
Any update on when this will be in the mainline version for us to use :) ?

**Comment by C0nw0nk** [comment]
It also just occured to me isit possible to overwrite any request header that would be useful for authentication reasons between my HTML pages javascript and my server.

**Comment by C0nw0nk** [comment]
Interesting find here. Google Chrome does NOT respect webtorrent changing the User-Agent it will still force its own User-Agent on all requests to torrents and webseeds etc.

As for a custom header `X-Custom-Header:` I assume it would be fine and ok still.
