### ISSUE TITLE
Is it possible to createServer without waiting to finish hash checks?

### ISSUE THREAD

**Issue by untitledlt** [webtorrent/webtorrent#1533]
F.e. if 10 GB movie is already downloaded, it takes almost a minute to hash torrent and only then i can `torrent. createServer`. If it's a new torrent I can start playback in 10 seconds so it's faster to delete files and start over.
Would it be possible to start `createServer` while hashing is still in progress?

**Comment by SilentBot1** [comment]
Hey @untitledlt,

Could I ask for you to show code examples of what you are talking about?

>if 10 GB movie is already downloaded, it takes almost a minute to hash torrent and only then i can torrent. createServer

How are you adding the already downloaded torrent? Are you calling `client.seed` or `client.add`?

If you are sure you have the entire torrent downloaded, you can pass the option `skipVerify: true` in `client.add` to disable verifying downloaded chunks, note if the full file isn't downloaded and this option is set to true, the torrent will think it has all the parts and not continue the partial download.

Also seeding via `client.add` will require either another peer to already have the metadata or require the torrent to be added via its metadata (either .torrent or saved `parse-torrent` object) but will allow all verification to be skipped in conjunction with the option skipVerify. 

As this is a question I'm going to close this, but feel free to continue the discussion, I'll be happy to help.

**Comment by untitledlt** [comment]
Thanks for an answer!
I'm gonna keep all `.torrent` files in separate folder and i'll add them with `client.add` on every app restart. 
New `.torrent`s will be added the same way while application is running.

I guess I should store every torrent state to database so i would know which torrent is completed and use `skipVerify: true` for completed ones. Or is there a better way?

But still i don't understand when i should use `client.seed` and why it's better then `client.add`?

**Comment by SilentBot1** [comment]
@untitledlt I don't help with `webtorrent-desktop` too much but I believe that is similar to how they handle it. I would recommend taking a look at `webtorrent-desktop` handles things but the code is complex and not the easiest to read.

`client.seed` should be used when you want to create a torrent from complete files, this includes creating the .torrent file which needs to generate the hash of each chunk for verification. 

`client.add` should be used when you want to add an existing torrent and don't want to re-generate the metadata (though verifying the integrity of the file against the .torrent file before you start seeding is recommended but takes time).

Hope this helps.

**Comment by untitledlt** [comment]
Looks like `client.add` is all i need then.
Is it possible to trigger hash check later if i add torrent with `skipVerify: true`?

**Comment by SilentBot1** [comment]
You can't re-verify the torrent easily after passing `skipVerify` currently. Possibly a option to re-verify a torrent would be something that could be looked into in the future.
