### ISSUE TITLE
Fonts are not rendering correctly. 

### ISSUE THREAD

**Issue by ipimpat** [webtorrent/webtorrent#1535]
OS: Linux Mint 19
WebTorrent: Version 0.20.0 (0.99.3) (64-bit)

This seems to be an issue with Electron, which is already fixed.

The same problem is also visible in other Electron based applications: https://github.com/keeweb/keeweb/issues/900

This is the problem I see in WebTorren and it is seen everywhere:

![screenshot](https://i.imgur.com/DnS2jQB.png)

**Comment by feross** [comment]
Thanks for the issue report. This is fixed on `master` now and will be fixed once we release a new version.
