### ISSUE TITLE
Why webtorrent project depends on simple-peer?

### ISSUE THREAD

**Issue by Hixon10** [webtorrent/webtorrent#1537]
I <a href="https://github.com/webtorrent/webtorrent/blob/master/package.json">see</a>, that `webtorrent` depends on <a href="https://github.com/feross/simple-peer">simple-peer</a>, but I see only one using of this library:
```javascript
WebTorrent.WEBRTC_SUPPORT = Peer.WEBRTC_SUPPORT
```

Can we just inline the function?
```javascript
function getBrowserRTC () {
  if (typeof window === 'undefined') return null
  var wrtc = {
    RTCPeerConnection: window.RTCPeerConnection || window.mozRTCPeerConnection ||
      window.webkitRTCPeerConnection,
    RTCSessionDescription: window.RTCSessionDescription ||
      window.mozRTCSessionDescription || window.webkitRTCSessionDescription,
    RTCIceCandidate: window.RTCIceCandidate || window.mozRTCIceCandidate ||
      window.webkitRTCIceCandidate
  }
  if (!wrtc.RTCPeerConnection) return null
  return wrtc
}
```

After that, we can remove `simple-peer` dependency.

**Comment by DiegoRBaquero** [comment]
It's also used in `bittorrent-tracker` to generate and receive offers. It what gives use WebRTC peers.

Sure, we could inline that, but the library is still used in the dep tree and packed anyways.
