### ISSUE TITLE
few questions about webserver's index page

### ISSUE THREAD

**Issue by untitledlt** [webtorrent/webtorrent#1538]
When i start streaming server and open address in browser, i am getting index page with torrent's files list.

- How these files are ordered? Can I trust that order is gonna be the same every time?
- Is it possible to get JSON instead of HTML?

**Comment by jimmywarting** [comment]
I think the order is based in the same order the files are added to the torrent file

The order is always the same 

And it's not possible to get it as a json

**Comment by jimmywarting** [comment]
The order is not always in alphabet order doe some torrent file generator dose this when generating the torrent file.

Also depends on how it recursively it reads a folder

**Comment by untitledlt** [comment]
Thanks for an answer.
I guess json would be a great addition to this awesome lib!

**Comment by jimmywarting** [comment]
if implemented then there is two options

1) send accept header to say you want json default to html
2) add json extension to the end of the url `get('.../index.json')`

**Comment by untitledlt** [comment]
Both options are fine but i prefer separate url as it's faster to test in browser and usually less typing and easier to remember.
But it's just me :)
