### ISSUE TITLE
Uncompiled source code ?

### ISSUE THREAD

**Issue by pakipaki2000** [webtorrent/webtorrent#1544]
Hey guys,

Do you know where i can find the uncompiled source code ? I would love to take a look :)

**Comment by DiegoRBaquero** [comment]
You are in it, this repo is it! :D

**Comment by pakipaki2000** [comment]
I would like to see webtorrent.min.js in a standard version with normal variable/function names

**Comment by pakipaki2000** [comment]
I don't mind the size, can i have the version without babel compilation ? Please :)

**Comment by pakipaki2000** [comment]
thanks bro :)
