### ISSUE TITLE
restart closed server

### ISSUE THREAD

**Issue by untitledlt** [webtorrent/webtorrent#1545]
Is it possible to restart closed server?
That's what i have tried:

```
const server = torrent.createServer();
server.listen(port); // server works now

setTimeout(() => {
    server.close(); // server closes, port gets free
}, 10000);

setTimeout(() => {
    server.listen(port); // port is in use but request never finishes 
}, 20000);
```

Is it possible to restart server after it was closed or do I need to `.destroy()` and `.createServer()`?

**Comment by feross** [comment]
Fixed by https://github.com/webtorrent/webtorrent/pull/1547
