### ISSUE TITLE
Some torrents does not download

### ISSUE THREAD

**Issue by untitledlt** [webtorrent/webtorrent#1546]
**What version of WebTorrent?**
0.102.4

**What operating system and Node.js version?**
OS X Mojave, node.js: v10.13.0

**What did you expect to happen?**
Torrent download should start

**What actually happened?**
Torrent gets added but download does not start.

Some torrents do not download. They get parsed but download does not start. I know what Webtorrent requires torrents to be seeded by WebRTC compatible clients but i can download those torrent in Webtorrent Desktop app. I guess it has the same limitations but does not have this problem.

I have a listeners on `error` and `warning` events but nothing comes here.
Let me know if you need more info. 
`.torrent` file can be provided personally.

**Comment by jimmywarting** [comment]
Are you trying to download something in the browser?

**Comment by untitledlt** [comment]
it's a node.js app

**Comment by DiegoRBaquero** [comment]
Is the torrent webrtc seeded, tcp/udp seeded, or both?

**Comment by untitledlt** [comment]
How can i check that?

**Comment by untitledlt** [comment]
Torrent also does not download in instant.io. It says 0 peers. 
But it works in Webtorrent desktop app on the same machine.

**Comment by DiegoRBaquero** [comment]
Correct. And maybe there are torrents which are only seeded in one network, so trying on the other won't work.

**Comment by untitledlt** [comment]
Not that case. Webtorrent Desktop works on the same machine.

**Comment by KayleePop** [comment]
> I know what Webtorrent requires torrents to be seeded by WebRTC compatible clients but i can download those torrent in Webtorrent Desktop app. I guess it has the same limitations but does not have this problem.

Webtorrent Desktop doesn't actually have that same limitation. It acts as both a traditional bittorrent client *and* a webRTC webtorrent client. It can use webRTC and/or UDP/TCP to download torrents, so it can download a torrent seeded by a browser and it can also download a torrent seeded by something like transmission or utorrent.

webtorrent-cli only uses the webRTC protocol, while webtorrent-hybrid uses both.

The Webtorrent library (via npm) only uses the webRTC protocol in browsers, and only uses the TCP/UDP protocol in node.js. (depending on whether it's browserified or not)

**Comment by untitledlt** [comment]
Thanks for your answer. 
Is it possible to use both protocols (webRTC and tcp/udp) in node.js app?

**Comment by untitledlt** [comment]
![image](https://user-images.githubusercontent.com/7152884/48959345-4e5d2100-ef6d-11e8-9825-cbfb979a0184.png)
node.js with `webtorrent-hybrind` also standing at 0% and 0 MB/s with 6 peers.
But still, another torrent currently downloading at 20 MB/s.

What else could be wrong?

**Comment by yamashi** [comment]
We are experiencing this as well, is there anything new regarding this ?

**Comment by DiegoRBaquero** [comment]
Please don't use WebTorrent to infringe copyright.
