### ISSUE TITLE
Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary

### ISSUE THREAD

**Issue by joshuajazleung** [webtorrent/webtorrent#1550]
**What version of WebTorrent?**
v0.102.4

**What operating system and Node.js version?**
MacOS Majove, Nove v10.11.0

**What browser and version? (if using WebTorrent in the browser)**
Safari 12

**What did you expect to happen?**
I expect the web torrent client to run normally

**What actually happened?**
it doesn't run at all and displays the error message in console.

Not only on my app, https://instant.io/ has the same problem. If you open a "share link" from instant.io on a new safari tab, it doesn't run at all.

**Comment by jimmywarting** [comment]
I think this belongs more to the simple-peer repo

Basically `RTCSessionDescription` and `RTCIceCandidate` are deprecated and should just pass an object instead of a instance

**Comment by joshuajazleung** [comment]
> I think this belongs more to the simple-peer repo
> 
> Basically `RTCSessionDescription` and `RTCIceCandidate` constructor are deprecated and should just pass an object instead of a instance

But web torrent referenced the old simple-peer. The current one is v9.1.2 while webtorrent is referencing v9.0.0

**Comment by jimmywarting** [comment]
the `^` in `"^9.0.0"` means it will automatically get the latest minor patch so when u install webtorrent u will get v9.1.2

**Comment by joshuajazleung** [comment]
> the `^` in `"^9.0.0"` means it will automatically get the latest minor patch so when u install webtorrent u will get v9.1.2. it's like `9.x.x`
> 
> if it would be `~` `~9.0.0` then u get all latest bug patches `9.0.x`

So that means we have to wait for simple-peer to update?

**Comment by jimmywarting** [comment]
> So that means we have to wait for simple-peer to update?

yepp

**Comment by froduit** [comment]
still not fixed ?

**Comment by feross** [comment]
@froduit `simple-peer` has been updated and this is fixed.
