### ISSUE TITLE
Seeding all torrent files in folder

### ISSUE THREAD

**Issue by pimboli** [webtorrent/webtorrent#1551]
Hello community, I need your help.

I can seed a torrent from cmd with the following command:

webtorrent-hybrid seed 1_1542966384006.mp4.torrent  --keep-seeding

But now I want to seed all the torrents from one folder.
I would like to do something like this:

webtorrent-hybrid seed ./*.torrent --keep-seeding

which is not working. Can you please tell me the right way to seed a folder full of torrents via CMD?

Thank you in advance.

**Comment by fijiwebdesign** [comment]
I would suggest using the webseed option to seed a whole folder. 

You can add the webseed to the magnet for an individual file using: `{magnetURI}&ws=https://example.com/path/to/folder/file.mp4`

Or you can generate a magnet for the whole folder, then add the web accessible folder url as the webseed . 

An example magnet: `magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a` and with the webseed: `magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&ws=https://example.com/path/to/folder/`

**Comment by e2ckp** [comment]
I am also looking for ways to solve these problems.
How to seed a large number of MP4 files in the command line mode of the server?

I did not find an explanation for using "webseed option" in the documentation. Where should I go to find the relevant instructions?
Thank you very much for your reply.

> I would suggest using the webseed option to seed a whole folder.
> 
> You can add the webseed to the magnet for an individual file using: `{magnetURI}&ws=https://example.com/path/to/folder/file.mp4`
> 
> Or you can generate a magnet for the whole folder, then add the web accessible folder url as the webseed .
> 
> An example magnet: `magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a` and with the webseed: `magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&ws=https://example.com/path/to/folder/`
