### ISSUE TITLE
incorrect value of file progress. file progress less than 0

### ISSUE THREAD

**Issue by De-Zol** [webtorrent/webtorrent#1552]
**What version of WebTorrent?**
0.102.4

**What operating system and Node.js version?**
Window 10, Nodejs 10.11.0

After stopping and resuming torrent download progress of files is calculated incorrect.

I am stopping torrent according to documentation (https://github.com/webtorrent/webtorrent/issues/164) by deselecting whole torrent (torrent.deselect(0, torrent.pieces.length - 1, 0)) and then deselecting each file (file.deselect()). When I want to resume torrent download, I am selecting all files (file.select()). and after that i am receiving incorrect progress of files
![image](https://user-images.githubusercontent.com/45289945/48945564-792a8380-ef33-11e8-9509-55310e347e16.png)

How can I solve this problem?

note* I am using electron v3.0.6

**Comment by KayleePop** [comment]
Is this a duplicate of https://github.com/webtorrent/webtorrent/issues/1515?

**Comment by De-Zol** [comment]
> Is this a duplicate of #1515?

You are right, it`s the same problem
