### ISSUE TITLE
Customize files fragments checking, when torrent is added

### ISSUE THREAD

**Issue by BarushevEA** [webtorrent/webtorrent#1553]
Please help me solve a problem.

**What version of  WebTorrent?** - 0.102.4 
**What operating system and Node.js version?** - OS Win 10 64, Node.js - v10.11.0 

**What actually happened?**
Situation by step:

1. Add torrent "test" with many files
2. Some files are 100% downloaded, some files are still downloading
3. Stop and close the application
4. Start application
5. Add torrent "test" again
6. Before torrent is ready, webtorrent checks fragments and this process takes a lot of time

**What did you expect to happen?**
How i can stop files check, if they are 100% downloaded?

**Comment by SilentBot1** [comment]
Hi BarushevEA,

There is a option on torrents called `skipVerify` which will mark all
pieces in a torrent as downloaded. Note that depending how the torrent is
added, the metadata will still be needed before the torrent will function
normally so saving the .torrent or `parse-torrent` output and recreating
the torrent using this is ideal instead of relying on other peers for
metadata incase you're the only client.

Kind Regards
Brad

**Comment by BarushevEA** [comment]
This works for the whole torrent.
But i need to disable scanning selectively, separately for each file.

**Comment by BarushevEA** [comment]
May be need to create new options/function similar to this:
```
  _markAllVerified () {
    for (let index = 0; index < this.pieces.length; index++) {
      this._markVerified(index)
    }
      console.log(this.pieces);
  }
```

But with options for example:
```
  _markAllVerified (start, stop) {
    // validation start
    // validation stop
    for (let index = start; index < stop; index++) {
      this._markVerified(index)
    }
      console.log(this.pieces);
  }
```

**Comment by SilentBot1** [comment]
Hey BarushevEA,

As it stands, like you've said, there is currently no way to do it selectively for each file, only per torrent.

Creating a `selectiveVerify` torrent option and additional if statement inside [this](https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L503) `else` statement seems like the best way to implement something like this.

**Comment by BarushevEA** [comment]
Yes, it is very similar to what I need.

**Comment by SilentBot1** [comment]
@BarushevEA It could be implemented and I see no reason as to why it wouldn't be as it's quite useful in combination with select only.

I don't have the time at the moment to implement it properly myself, mainly writing the tests for it, but the code above should be functional.

Yourself or anybody else is more than welcome to create the PR to add this feature, sorry I'm not able to do it myself at the moment.

**Comment by BarushevEA** [comment]
I understand.
I starting this at next week.
I can implement this for my project and try to help you too.
If you do not mind.

**Comment by BarushevEA** [comment]
I guess I found a mistake.

**Function -  _verifyPieces()**
**File - torrent.js, strings 576 - 578:**

```
                        if (!this.pieces[index]) return
                        this._debug('piece verified %s', index)
                        this._markVerified(index)
```
Fix:
```
                        if (this.pieces[index]) {
                            this._debug('piece verified %s', index);
                            this._markVerified(index);
                        }
```

**and optimizing string 565:**
` parallelLimit(this.pieces.map( (_, index)=> cb => {`

Fix:
```
const clearedPieces = this.pieces.filter(piece => !!piece);
parallelLimit(clearedPieces.map( (_, index)=> cb => {
```
