### ISSUE TITLE
Is there some reason as to why loading torrent from info hash/magnet uri is slower on the web than webtorrent desktop client?

### ISSUE THREAD

**Issue by joshuajazleung** [webtorrent/webtorrent#1554]
**What version of WebTorrent?**
v0.102.4

**What operating system and Node.js version?**
MacOS, node v10

**What browser and version? (if using WebTorrent in the browser)**
Chrome 70

Some of my users mention that it takes a long time to load the torrent, some can't load at all. When I tested it, web torrent desktop client does load faster, like in 1-2 seconds, while the my website sometime takes 4-5 seconds to load. Is there some reason for that?

**Comment by jimmywarting** [comment]
Guessing webrtc's nat hole bunching takes up most of time...
It has to gather ice candidates first and not [trickle](https://webrtchacks.com/trickle-ice/)

**Comment by feross** [comment]
There are simply more peers available to the desktop app. Desktop apps can connect to WebRTC and TCP peers, while the browser can only connect to WebRTC peers.
