### ISSUE TITLE
src=(unknown) with appendTo() method on chrome

### ISSUE THREAD

**Issue by chisNaN** [webtorrent/webtorrent#1556]
**What version of WebTorrent?**

webtorrent@latest
as of today

**What operating system and Node.js version?**

macos mojave

**What browser and version? (if using WebTorrent in the browser)**

Chrome 71.0.3

**What did you expect to happen?**

my script was initially working on chrome but stopped to work recently.
It is still working on firefox (and opera)
(obviously only with mp4 files)
**What actually happened?**

`file.appendTo('body')`

will make the correct blob value of attribute src
but after several seconds of loading the src will be like this
 `src=(unknown)`

and make the video not playable
<img width="472" alt="capture d ecran 2018-12-06 a 09 54 09" src="https://user-images.githubusercontent.com/2439389/49573188-b03e6300-f93d-11e8-992c-a25b51fa97ca.png">

I tried to remove all history of chrome and executing this command:
`find ~/Library/Caches/ -type f -name "*" -delete`
to be sure i have no cache problem

but still its not working either LOCALLY or on a aws s3 bucket

**Comment by DiegoRBaquero** [comment]
This might be a regression with Chrome 71?

Video starts ? and then src will go unknown and video will stop?

**Comment by chisNaN** [comment]
Thanks for your reply.
It maybe a regression due to something changed in chrome...
Actually video never started.
The correct blob was initially written in the src value attribute but after replaced by this unknown

**Comment by chisNaN** [comment]
I confirm that i managed to try with a previous of chrome 70 and i dont have this problem...

**Comment by dannylazarow2** [comment]
https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems#remove_urlcreateobjecturl_from_mediastream

Google removed something from media stream.
Videostream package fails silently

I think this is quite a bumper. Videos on 71 does not load

**Comment by chisNaN** [comment]
@dannylazarow2 THanks for your reply. I thought about reporting a "bug" (regression) to google.
What do you guys suggest?

**Comment by DiegoRBaquero** [comment]
Sent a PR. We need @feross though.

**Comment by feross** [comment]
This works in Chrome Canary, so it's likely a regression in Chrome itself. To test it, go to https://webtorrent.io in Chrome 71 (doesn't work) and 73 (does work). The deprecation of `createObjectURL` is only for WebRTC webcam video streams, not for the MediaSource API streams. Thanks to @jhiesey for figuring this out!

**Comment by feross** [comment]
@jhiesey said that the file works fine when the audio track is removed from the file. It seems that perhaps Chrome has gotten more strict about rejecting malformed files? I found these recent issues which seem to indicate this:

- https://bugs.chromium.org/p/chromium/issues/detail?id=915228
- https://bugs.chromium.org/p/chromium/issues/detail?id=913440
- https://bugs.chromium.org/p/chromium/issues/detail?id=909559

But it's a good sign that the file works in Canary. Perhaps they reverted the change that caused this issue and this will fix itself in a future Chrome version?

**Comment by chisNaN** [comment]
Thanks for your reactivity. So the idea is maybe to wait the next version before applying any changes?

**Comment by chisNaN** [comment]
I think we can close this issue
as i confirm it work again with new current Version 72.0.3626.81
(Did not make the test on android though)
