### ISSUE TITLE
Issue with streaming on website, but works on instant.io

### ISSUE THREAD

**Issue by Kerneltroll** [webtorrent/webtorrent#1557]
Currently testing a torrent i am seeding which is of a class lecture we have recorded at college, when i upload the file to instant.io it works perfectly, downloads and streams as it go's..

However, when using the examples for html, (the sintel one) my video does not work?

If i swap out the class torrent for sintel it works, where am i going wrong? 

```
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
// Sintel, a free, Creative Commons movie
var torrentId = 'class104.torrent'

var client = new WebTorrent()

client.add(torrentId, function (torrent) {
  // Torrents can contain many files. Let's use the first.
  var file = torrent.files[0]

  // Display the file by adding it to the DOM.
  // Supports video, audio, image files, and more!
  file.appendTo('body')
})
```

**Comment by dannylazarow2** [comment]
This issue looks related to https://github.com/webtorrent/webtorrent/issues/1556
can you check in inspector does the video have source set (`src=(unknown)`)
