### ISSUE TITLE
Allow Keyboard Navigation Like All Players

### ISSUE THREAD

**Issue by infosisio** [webtorrent/webtorrent#1560]
All video players, including VLC activate backward/forward video navigation if you hit the keyboard arrows.

Webtorrent doesn't, I think it's fair to assume it should? Thanks.

**Comment by DeeGeeTill** [comment]
You can hold down ALT+LEFT or ALT+RIGHT keys to scrub backwards and forwards.

**Comment by infosisio** [comment]
@DeeGeeTill Thanks, though see YouTube, see VLC, see literally all video players. 
I am not saying the idea is to copy what the big players are doing but rather doing what is intuitive based on what the average user already knows.

**Comment by jimmywarting** [comment]
Out of the scope of webtorrent? 
Maybe belong more to webtorrent-desktop?

**Comment by DiegoRBaquero** [comment]
It is for WD
