### ISSUE TITLE
MP4 streaming is no longer working on chrome&chromium!!

### ISSUE THREAD

**Issue by Krypt0n36** [webtorrent/webtorrent#1565]
**What version of WebTorrent?**

**What operating system and Node.js version?**
Windows 10 -- Nodejs v10.15.0 -- 
**What browser and version? (if using WebTorrent in the browser)**
Chrome 71 -- Chromium 73
**What did you expect to happen?**
It used to work fine with me
**What actually happened?**
MP4 streaming is no longer working, Im using appendTo and a magnet URL, the source of the video initially set to a valid value, then it changes to (unknow).
PS: instant.io also stopped working

**Comment by DiegoRBaquero** [comment]
Same as https://github.com/webtorrent/webtorrent/issues/1556
