### ISSUE TITLE
I want to contact devs from this project

### ISSUE THREAD

**Issue by freedeck21** [webtorrent/webtorrent#1567]
I am from NIX Platform (nixplatform.io) and we have a proposal for the dev team.

Can you contact me please?

Thanks

**Comment by DiegoRBaquero** [comment]
Hello @torrmara , the team is all around the world and is made from voluntary contributors. You can contact me if you'd like to discuss the proposal: diegorbaquero@gmail.com

**Comment by frank-dspeed** [comment]
@torrmara @DiegoRBaquero Post your Proposal: Here with the Word Proposal: in the title
