### ISSUE TITLE
Streaming not working anymore

### ISSUE THREAD

**Issue by wizurijyq** [webtorrent/webtorrent#1569]
**What version of WebTorrent?**
https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js
**What operating system and Node.js version?**
browser
**What browser and version? (if using WebTorrent in the browser)**
Version 71.0.3578.98 (Official Build) (64-bit) 
Chrome mobile version
Firefox
**What did you expect to happen?**
The videos used to play as soon as the torrent starts to download.
**What actually happened?**
The torrent has to be fully downloaded to play. Even worse the big video files won't play at all.

The errors in the console are mostly 
```
webtorrent.min.js:6 Uncaught (in promise) DOMException
```

**Comment by chisNaN** [comment]
Duplicated of my post here
[1556](https://github.com/webtorrent/webtorrent/issues/1556)

**Comment by feross** [comment]
Btw, you probably want to update your webtorrent script URL to https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js instead of the one you're currently using.

See https://github.com/webtorrent/webtorrent/pull/1716/files
