### ISSUE TITLE
Problem with "Go Back" functionality

### ISSUE THREAD

**Issue by JamesKimari** [webtorrent/webtorrent#1571]
**What version of WebTorrent?**
Version 0.20.0 (0.98.21) (32-bit)

**What operating system and Node.js version?**
Windows 10 

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
I was expecting that when i press the "ESc" key while on the "Preferences Page" the application would go back to the home page. 

**What actually happened?**
The application immediately minimized itself and would not open again unless uninstalled and then installed again. Completely terminating all instances of the app in the task manager could not solve the issue. I'm not sure whether it's a unique case or a general issue on all Windows 10 platforms. This is very annoying BTW. Please fix this bug in case you find that it's evident.

**Comment by JamesKimari** [comment]
On it... Thanks.

**Comment by DiegoRBaquero** [comment]
Closed in favor of https://github.com/webtorrent/webtorrent-desktop/issues/1537
