### ISSUE TITLE
Questions about the WebTorrent protocol

### ISSUE THREAD

**Issue by jech** [webtorrent/webtorrent#1572]
1. What is the maximum SCTP chunk size? WebTorrent appears to be sending each BitTorrent message in two chunks, but I've been sending it fixed-size chunks of 4kB and it groks them.  Knowing the maximum chunk size that WebTorrent will send would be useful for sizing buffers.

2. How do I reject an offer from the tracker?  Do I just ignore unwanted offers?  Right now, I'm simply closing the WebSocket connection when I've got enough peers, is that the right thing to do?

3. If I want to generate new offers, am I allowed to send a new announce before the interval expires? It seems inefficient to generate offers before they are needed, with all the ICE traffic they cause.

**Comment by feross** [comment]
> What is the maximum SCTP chunk size? 

We don't send one specific chunk size, so I would not rely on receiving any specific size. Node.js streams by default have an internal chunk size of 16kb, I believe. But that doesn't mean that our calls to send() will necessary always be 16kb.

> How do I reject an offer from the tracker? Do I just ignore unwanted offers? Right now, I'm simply closing the WebSocket connection when I've got enough peers, is that the right thing to do?

It's fine to ignore unwanted offers. The remote peer will close it's end of the connection after a timeout.

> I'm simply closing the WebSocket connection when I've got enough peers, is that the right thing to do?

This is totally fine to do.

> If I want to generate new offers, am I allowed to send a new announce before the interval expires? It seems inefficient to generate offers before they are needed, with all the ICE traffic they cause.

You can announce before the interval expires, but it's possible that the tracker server will ignore you / ban you temporarily (it's up to the tracker) if you contact them too frequently.

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
