### ISSUE TITLE
Feature request: Custom torrent label in client

### ISSUE THREAD

**Issue by Zen-Master-SoSo** [webtorrent/webtorrent#1575]
The WebTorrent desktop client refers to each torrent by a file name. When adding torrents from BitChute, (for offline viewing later), the file is saved using a name provided by BitChute, which is just a string of random characters. Consequently, the file list in WebTorrent ends up being a stack of mystery meat.

It would be nice to be able to "rename" files in the WebTorrent client app. Even if the association between the original name and the file is kept, the user could refer to that entry in a more intuitive way on his machine.

**Comment by jimmywarting** [comment]
perhaps this belongs more to [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) repo? As this repo is the core functionality of using webtorrent in both browser, node & desktop

**Comment by DiegoRBaquero** [comment]
Correct @jimmywarting
