### ISSUE TITLE
Seeding files AND torrent 

### ISSUE THREAD

**Issue by mitra42** [webtorrent/webtorrent#1583]
I’m trying to find out how to use WebTorrent (or Bittorrent) to seed files downloaded by other means. 
The logic would be that I’ve got a subset of the  files, and a torrent file, in a directory, and I want to add them into WebTorrent or BitTorrent. 

This will be running in somewhat bandwidth constrained situations, so in this case I have to avoid downloading the rest of the files in the Torrent. 

I was assuming that I'd pass the torrent to WebTorrent along with a place to find the files references, bit looking at https://webtorrent.io/docs and the code, it seems that:

* client.add(<torrentfile>) isn’t appropriate because this starts downloading the rest of the files
* client.seed(folder) isn’t appropriate because it will recreate the torrentfile which I already have 
 
Am I missing something ?

**Comment by mitra42** [comment]
This was solved by @jhiesey when he came over.

@jhiesey  - did the changes you made make it into the default release ?

**Comment by mitra42** [comment]
@jhiesey I'm still trying to figure this out ? Our dweb-mirror is currently running off your #rescan branch and not sure if I can switch back to the main branch yet?

**Comment by jhiesey** [comment]
Sorry, I never got this upstreamed. That's entirely my fault. I'll get that fixed this weekend!

**Comment by mitra42** [comment]
Thanks ... trying to tie up some loose ends before Dweb camp, and would love to be showing webtorrent p2p between clients with the master coming from an anaemic RPI :-)

**Comment by mitra42** [comment]
Any luck ?

**Comment by jhiesey** [comment]
PR is here: https://github.com/webtorrent/webtorrent/pull/1650 I could merge it myself but I'd like someone else to take a look. I'll bug @feross

**Comment by mitra42** [comment]
Thanks

**Comment by jhiesey** [comment]
Finally released in webtorrent 0.105.0

**Comment by mitra42** [comment]
Thanks - I'll switch to that release
