### ISSUE TITLE
Cannot read property 'tracker' of null

### ISSUE THREAD

**Issue by guanzo** [webtorrent/webtorrent#1589]
I can't reproduce it locally but Sentry is reporting this error a lot. My code calls `torrent.destroy()`, which sets `this.client = null`. It seems like the `getAnnounceOpts` function is still called after the torrent is destroyed. Maybe add a guard clause: `if (this.destroyed) return`?

https://github.com/webtorrent/webtorrent/blob/1829dc225b7786cad4340d211b65012f974e4a6a/lib/torrent.js#L291

**Comment by feross** [comment]
Re-opening this issue so that someone can look into it and see if it's still an issue.

**Comment by alxhotel** [comment]
This was fixed in 0da44734ce4f20114663479801789e6ab022f069

**Comment by feross** [comment]
Thank you for fixing this, @alxhotel!
