### ISSUE TITLE
Ice connection failed react native

### ISSUE THREAD

**Issue by TriPSs** [webtorrent/webtorrent#1590]
**What version of WebTorrent?**
^0.103.0

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
`simple-peer` to connect

**What actually happened?**
`simple-peer` throwing error `Ice connection failed` 

```
simple-peer [50766ba] iceStateChange (connection: failed) (gathering: gathering)
simple-peer [50766ba] destroy (error: Ice connection failed.)
webtorrent:peer destroy 2d5744303032302d756b692b6a4c7a7671464155 (error: Ice connection failed.)
```

Does anyone now how i can tackle this issue?

**Comment by TriPSs** [comment]
This is still a issue.

**Comment by feross** [comment]
This error message just means that you could not connect to a specific peer. This is normal. It's not guaranteed that any two arbitrary peers in the network will be able to connect to each other. For example, two peers behind symmetric NATs will not be able to connect to each other.

**Comment by TriPSs** [comment]
@feross all the peers don't work while if i use webtorrent in a node instead of react native env it works as expected.

**Comment by feross** [comment]
My guess is that it's something to do with the react-native webrtc package that you're using. I think that it uses an outdated version of WebRTC. I think we can move the discussion of this to the `simple-peer` repo: https://github.com/feross/simple-peer/issues/445

In the meantime, you can just disable WebRTC peers.
