### ISSUE TITLE
Issue on Safari (MacOs), simple-peer version ?

### ISSUE THREAD

**Issue by froduit** [webtorrent/webtorrent#1594]
**What version of WebTorrent?**
Latest from CDN (https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js)
**What operating system and Node.js version?**
macOS Mojave
**What browser and version? (if using WebTorrent in the browser)**
Safari 12.0.3
**What did you expect to happen?**
I expected a video file to play flawlessly like on the other browsers.
**What actually happened?**
I often get the black player with the error : 
**Unhandled Promise Rejection: TypeError: Argument 1 ('options') to RTCPeerConnection.createOffer must be a dictionary**

I saw (#1550) that it could come from **[simple-peer](https://github.com/feross/simple-peer)**, which has been updated since then I think. But still I get the same error.
Everything works fine on Chrome & Firefox (no error at all). 
I am using webtorrent from the CND (jsdelivr.net) and I use webtorrent Desktop on Windows server 2016 to seed the files. Does it matter ?

Thank you.

**Comment by froduit** [comment]
The solution was to get the latest version of webtorrent from the **npm** folder of the CDN : 

`<script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>`

and not the one provided on webtorrent.io...

**Comment by feross** [comment]
Thanks for the issue. I just updated the docs on the site so they use the correct URL: https://github.com/webtorrent/webtorrent/pull/1682
