### ISSUE TITLE
Seed same torrent with different trackers

### ISSUE THREAD

**Issue by daeschlerdavid** [webtorrent/webtorrent#1595]
Hello,

How can I seed the same torrent with different trackers ?
I known i cloud just merge all trackers url but this is not recommanded on most trackers.

I don't see why I could not seed the same torrent multiple times, as it is just read only. 

Currently webtorrent report this error :
Cannot add duplicate torrent ${torrent.infoHash}

**Comment by feross** [comment]
WebTorrent creates one TCP server to listen for incoming connections from peers. When a peer sends a handshake, they include the torrent infohash that they're interested in sharing. If you added two torrents with the same infohash, then it would not be possible to distinguish between which of the two identical torrents they are attempting to connect to.

I recommend just adding new tracker urls to the existing torrent. Or, if you insist, you can create two WebTorrent client instances, one for each torrent. Then they'll have different listening servers and appear as two completely separate peers.
