### ISSUE TITLE
Webpack+Electron+Webtorrent doesn't work

### ISSUE THREAD

**Issue by elyulka** [webtorrent/webtorrent#1597]
**What version of WebTorrent?**
0.103.1

**What operating system and Node.js version?**
OS X 10.14, Node 10.4.1

**What browser and version? (if using WebTorrent in the browser)**
Electron 3.1.4

**What did you expect to happen?**
Torrent can be added and downloaded into folder.

**What actually happened?**
Got error 'port is undefined' because it didn't automatically set 'torrentPort' because TCPPool was undefined.
Cause of issue is that 'browser' options are being applied for 'electron-renderer' webpack target causing limited functionality.

**Comment by DiegoRBaquero** [comment]
I answered on your SO question :). You must run webtorrent in the Node.js process of your electron app for it to connect to TCP peers :)
