### ISSUE TITLE
Can i deploy this on to Amazon AWS, if yes. How?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [webtorrent/webtorrent#1603]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by jimmywarting** [comment]
if this where SO you would get so many -1 and be closed eventually for not trying

**Comment by DiegoRBaquero** [comment]
Yes. Manually installing everything on any instance: Node.js, npm, webtorrent.
