### ISSUE TITLE
announceList is not replacing default trackers

### ISSUE THREAD

**Issue by lacker** [webtorrent/webtorrent#1604]
Using:
webtorrent@0.103.0
Ubuntu 18.04.2 LTS
Node v8.10.0

When I seed a new torrent and set `announceList` to be my own set of trackers, it appears that the default set of trackers is still included. Here's the code:

```
let client = new WebTorrent();
let dir = path.resolve(__dirname, "samplesite");
client.seed(
  dir,
  {
    announceList: [["ws://localhost:4444"]]
  },
  torrent => {
    console.log("seeding torrent.");
    console.log("info hash: " + torrent.infoHash);
    console.log("magnet: " + torrent.magnetURI);

    torrent.on("wire", (wire, addr) => {
      console.log("connected to peer with address", addr);
    });
  }
);
```

The magnet URI includes tracker URLs besides just localhost, which is why I conclude it isn't properly using announceList. The docs on https://github.com/webtorrent/create-torrent state "If announceList is omitted, the following trackers will be added automatically: ..." which is why I expected it to not auto-add any trackers when announceList is provided.

**Comment by Fenny** [comment]
Same results here 
```javascript
announceList: [['ws://localhost:8000']]
```
![Image](https://i.imgur.com/EjIIZli.png)

**Comment by andymikulski** [comment]
After some digging, it looks like it's an issue around `webtorrent-hybrid`. I've found running this line of code before seeding/downloading files will remove the default trackers:

`(typeof global === 'undefined' ? window : global).WEBTORRENT_ANNOUNCE = null;`

(`global` in node environments and `window` in the browser.)

**Comment by Fenny** [comment]
Heroes don't always wear capes @andymikulski

**Comment by lacker** [comment]
This workaround works for me. I think the current behavior is still a bug that should be fixed though.

**Comment by feross** [comment]
Yeah, we should try to fix this, if possible. `webtorrent-hybrid` and the `global.WEBTORRENT_ANNOUNCE` is kind of a hack.

The whole reason I created `webtorrent-hybrid` was that installing the WebRTC in Node.js package (`wrtc`) used to cause lots of install warnings/errors for most users at one point in time. If the situation has improved since then, we can just include `wrtc` directly in the `webtorrent` package and deprecate `webtorrent-hybrid`.

**Comment by panzois2000** [comment]
I just wanted to add an info here that did not see above. To alter the trackers' urls you can go to node_modules/create-torrent/index ad chenge the announceList. That worked for me.

**Comment by SilentBot1** [comment]
To confirm, I believe this is resolved in recent versions of WebTorrent / create-torrent:

![image](https://github.com/webtorrent/webtorrent/assets/15065825/778578bf-b5a9-40d1-acbd-317f146c3fae)

This can also be achieved through the `opts.announce` argument, which is set to a 1D array of strings which represent the trackers to use, e.g.
```javascript
client.seed(..., { announce: ["ws://localhost:8000", "ws://localhost:8001"] })
```

As this appears to be resolved, I will close this issue, but if anybody can replicate this in current versions of WebTorrent, please don't hesitate to re-open this issue.
