### ISSUE TITLE
Magnet url not work on WebTorrent

### ISSUE THREAD

**Issue by GilGustavoJ** [webtorrent/webtorrent#1608]
I try to build a application for my personal use. I try to create a Web Torrent Player (in localhost) but when i pass the magnet link, not download nothing.

The magnet link works in uTorrent and Transmission (Linux)

this is my code:

var client = new WebTorrent()
var magnetUri = 'magnet:?xt=urn:btih:CC01377833C9028EDF33D3DA4E2324871B9CF7F7&dn=https://yts.am/torrent/download/CC01377833C9028EDF33D3DA4E2324871B9CF7F7&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.openbittorrent.com:80'

client.add(magnetUri, function (torrent) {
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)

  torrent.files.forEach(function (file) {
    // Display the file by appending it to the DOM. Supports video, audio, images, and
    // more. Specify a container element (CSS selector or reference to DOM node).
    file.appendTo('body')
  })
})

Sorry my English.

**Comment by alxhotel** [comment]
Please use the template provided for new issues. And check other similar issues before opening a new one. For example #1546.

If you are running your code in a browser, you need to have WebRTC peers seeding the torrent. Alternatively, you could also use webseeds.

**Comment by DiegoRBaquero** [comment]
Please don't use WebTorrent with copyrighted content.
