### ISSUE TITLE
Adding .srt subtitles in video web player

### ISSUE THREAD

**Issue by GilGustavoJ** [webtorrent/webtorrent#1614]
**What version of WebTorrent?**
v0.103.1
**What operating system and Node.js version?**
Ubuntu 18.04 / v10.15.3
**What browser and version? (if using WebTorrent in the browser)**
Firefox/Chrome (lastest)
**What did you expect to happen?**
Add subtitles .srt to video player in HTML
**What actually happened?**

I need to add subtitles .srt in the video player create with Webtorrent in the brwoser

**Comment by DiegoRBaquero** [comment]
Out of the scope of the library. You can use any video player you'd like.
