### ISSUE TITLE
Cannot Handle Invalid Windows Characters

### ISSUE THREAD

**Issue by Jaliborc** [webtorrent/webtorrent#1618]
**What version of WebTorrent?**

**What operating system and Node.js version?**
Windows 10, Node 10

**What did you expect to happen?**
When you download a torrent that contains files with names with invalid characters (colons for example, "The Banana King: Requiem - Episode 4.mp4"), either windows system invalid characters should be translated automatically like most torrent clients do, or there should be
an way in the API to assign each file a different write name individually.

**What actually happened?**
WebTorrent tries to download the file with the original name. Which fails.

**Comment by Jaliborc** [comment]
Bump

**Comment by feross** [comment]
This seems reasonable to support. Is there a list of invalid windows characters and the preferred characters to translate them into?

**Comment by Jaliborc** [comment]
I made an [npm module](https://github.com/Jaliborc/safe-filename) for our internal use that converts all the invalid characters to the most similar we could find. 

[This file](https://github.com/Jaliborc/safe-filename/blob/master/index.js) lists all the invalid characters and our suggested translations.

**Comment by ThaUnknown** [comment]
fixed in latest versions
