### ISSUE TITLE
WebTorrent using a lot of CPU/MEM

### ISSUE THREAD

**Issue by Alexdrr** [webtorrent/webtorrent#1619]
Helllo! I need help.

I installed node and webtorrent-hybrid on few servers and try seed video files.

I use bash file for start it

`webtorrent-hybrid seed -a ws://domain.com 1.mp4
webtorrent-hybrid seed -a ws://domain.com 2.mp4
....etc...
webtorrent-hybrid seed -a ws://domain.com 100.mp4
webtorrent-hybrid seed -a ws://domain.com 101.mp4
`
but have very big problem. After seeding over 100 files (one video have size 1-2GB) webtorrent use 100% CPU and use all memory (16GB) and use 30-40GB swap.

I think this is not normal. Hardware server have Xeon E3-1245 4 core 16 ram 1gbit network and with seeding 100 video webtorrents loaded on 100% cpu and memory.

I tested it on VDS with 2 core and 2-3GB ram and webtorrent seed only 15-20 torrents and server down.

For example  - Transmission torrent can work on router (like dlink or tplink) with 32mb ram and 500mhz cpu and download/seed a lot of files/movies/games/music etc (big sizes). Why webtorrent can not seed a lot of files at same time and load server on 100%???

This is a bug? or how i can use webtorrent for seeding many files and use normal hardware resources for it? Maybe webtorrent and node must be started with modules or with arguments for optimization load?

By my opinion if i want seed 500-1000 files i need server with 40 cores and 1TB ram - this is not normal! Help me pls.

P.S. what need for use webrtc library in Transmission? Maybe can compile transmission torrent with webrtc library for normal seeding?

**Comment by tomasparks** [comment]
create a torrent file and upload it to your webserver?
and why don't you webseed the contents?

**Comment by danieledwardz** [comment]
Im having this same problem, I really agrre with you. I tried host 20 videos on xserve 2009 48gb ram, 2x xeon and it crash my osx. It would be a dream webrtc work with transmission. If someone knows how to fix or any news about it please contact me daniel@edwardz.com.br, im trying solve it about 2 years.

**Comment by Alexdrr** [comment]
> Im having this same problem, I really agrre with you. I tried host 20 videos on xserve 2009 48gb ram, 2x xeon and it crash my osx. It would be a dream webrtc work with transmission. If someone knows how to fix or any news about it please contact me [daniel@edwardz.com.br](mailto:daniel@edwardz.com.br), im trying solve it about 2 years.

https://pastebin.com/F1xnYjfw

**Comment by danieledwardz** [comment]
Hey, could you please resend the link for me please?! It has expired.

**Comment by feross** [comment]
Known issue: #1026
