### ISSUE TITLE
file.getBlobURL w/o callback

### ISSUE THREAD

**Issue by tomasparks** [webtorrent/webtorrent#1625]
I have a function that calls BlobUrlFromUrl(),
in that function, I call file.getBlobURL() but, before I get a response the function has returned cause undefined errors in the string :(

` var xml = '<xml><krpano><scene id="' + pano.id + '" title="' + pano.title + '" >'
 xml = xml + '<preview url="' + BlobUrlFromUrl(files.preview, rootUrl) + '" />'
 xml = xml + '<image>'
 xml = xml + '<left url="' + BlobUrlFromUrl(files.left, rootUrl) + '"/>'
 xml = xml + '<front url="' + BlobUrlFromUrl(files.front, rootUrl) + '"/>'
 xml = xml + '<right url="' + BlobUrlFromUrl(files.right, rootUrl) + '"/>'
 xml = xml + '<back url="' + BlobUrlFromUrl(files.back, rootUrl) + '"/>'
 xml = xml + '<up url="' + BlobUrlFromUrl(files.up, rootUrl) + '"/>'
 xml = xml + '<down url="' + BlobUrlFromUrl(files.down, rootUrl) + '"/>'
 xml = xml + '</image></scene></krpano>';`

`function BlobUrlFromUrl(url,rootUrl) {
    torrent.files.forEach(function (file) {
        if ((file.path) == (rootUrl+'/'+url)) {
            file.getBlobURL(function (err, bloburl) {if (err) return log(err.message);log('file.getBlobURL() '+bloburl);success: bloburl;});
           // log('torrent.files(): '+ bloburl);
           }
        })
}`

runtime: https://tomasparks.name/krpano-and-webtorrent/index.html
source code: https://github.com/tomasparks/krpano-and-webtorrent

**Comment by tomasparks** [comment]
> also, whatsup with ;success: bloburl;?

it was a failed experiment that I didn't clean up

**Comment by tomasparks** [comment]
> also, whatsup with `;success: bloburl;`?
it was a failed experiment that I didn't clean up

**Comment by jimmywarting** [comment]
you don't have to wait for the done event to finish all files as getBlobURL can be called straight await. however the getBlobURL is async so you need to get the blob urls before creating the xml, the alternative is that you create the xml and insert the blob url afterwards

something like this (untested):
```js
file.getBlobURL(function(err, url) {
  xml.queryElement('left').setAttribute('src', url)
})
```

**Comment by tomasparks** [comment]
thanks :disappointed:
