### ISSUE TITLE
How can I get total number of downloads in a swarm. 

### ISSUE THREAD

**Issue by i-coderdev** [webtorrent/webtorrent#1627]
This is not a issues,

##
Anyone can tell me how can I get total number of downloads information from torrent infoHashes.
##

**Comment by SilentBot1** [comment]
Hi @i-coderdev 

To get this information you can use the following example code:

```javascript

torrent.discovery.tracker.on('scrape', function (data) {
  console.log('got a scrape response from tracker: ' + data.announce)
  console.log('number of seeders in the swarm: ' + data.complete)
  console.log('number of leechers in the swarm: ' + data.incomplete)
  console.log('number of total downloads of this torrent: ' + data.downloaded)
})

torrent.discovery.tracker.scrape()

```

This will invoke the scrape function within [bittorrent-tracker's](https://github.com/webtorrent/bittorrent-tracker) client and return all metadata from the tracker. Alternatively you can use [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) standalone without having the overhead of the webtorrent library.

As this is a question, I'm going to close this issue but if you need any more help with this, feel free to continue the conversation in this ticket. 

Kind regards
Brad
