### ISSUE TITLE
How to save file with node fs

### ISSUE THREAD

**Issue by MarchWorks** [webtorrent/webtorrent#1631]
**What version of WebTorrent?**
latest

How to save file with fs
```
var magnetURI = '........'
const downloadPath = app.getPath('downloads')
client.add(magnetURI, function (torrent) {
    // Got torrent metadata!
    console.log('Client is downloading:', torrent.infoHash)
    torrent.files.forEach(function (file) {
        fs.outputFile(downloadPath + file.path , file, 'utf-8') // what should I do here 
    })
}) 
```

**Comment by MarchWorks** [comment]
I found out

**Comment by Senicolonna** [comment]
Can you show me how did you do this? I can't save the files. If i put to opts the download path it downloads me only the first one file

**Comment by MarchWorks** [comment]
@Senicolonna are you sure that `{ path: 'your_pathname'}` download only the first file? Well here is what you want 
```
torrent.files.forEach(function (file) {
	  	file.getBuffer(async function (err, buffer) {
		  if (err) throw err
		  await fs.outputFile(downloadPath + (downloadPath.endsWith('/') ? '' : '/') + file.path , buffer, 'binary')
		})
	  })
```

**Comment by Senicolonna** [comment]
Yes i tried with sintel.torrent and it downloaded me only Sintel.de.srt, idk why. Now I am going to try your code, thanks bro

**Comment by Senicolonna** [comment]
> @Senicolonna are you sure that `{ path: 'your_pathname'}` download only the first file? Well here is what you want
> 
> ```
> torrent.files.forEach(function (file) {
> 	  	file.getBuffer(async function (err, buffer) {
> 		  if (err) throw err
> 		  await fs.outputFile(downloadPath + (downloadPath.endsWith('/') ? '' : '/') + file.path , buffer, 'binary')
> 		})
> 	  })
> ```

Ok now i tried but i crashes

**Comment by MarchWorks** [comment]
open a new issue
