### ISSUE TITLE
webtorrent-desktop: error while loading shared libraries: libX11-xcb.so.1

### ISSUE THREAD

**Issue by pokapow** [webtorrent/webtorrent#1632]
**What version of WebTorrent?**

The last installed just now for Ubuntu with .deb from official website

**What operating system and Node.js version?**

Ubuntu 18.04, try wirh node 7,8,9,10.

**What browser and version? (if using WebTorrent in the browser)**

Using the application

**What did you expect to happen?**

Open webtorrent-desktop for Ubuntu

**What actually happened?**

In shell, this error: 
`webtorrent-desktop: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

When I try to install the lib with `apt install libx11-xcb1`, Linux tell me it's even installed correctly.

How can I tell to webtorrent-desktop to use the correct lib ?

**Comment by pgram1** [comment]
Does `sudo apt-get install -fy libx11-xcb-dev` solve your issue?

**Comment by feross** [comment]
This issue should be fixed when we release the next version of WebTorrent Desktop. The fix (updating to Electron 6) is already on `master`. Follow this issue for updates: https://github.com/webtorrent/webtorrent-desktop/issues/1674
