### ISSUE TITLE
Webtorrent "Too many open files" Error on Ubuntu

### ISSUE THREAD

**Issue by leoherzog** [webtorrent/webtorrent#1633]
**What version of WebTorrent?**
v0.103.1

**What operating system and Node.js version?**
Up-to-Date Ubuntu 18.04, Node 10.15.3

**What did you expect to happen?**
The downloads to continue downloading

**What actually happened?**
A force quit and:
```
[warn] epoll_create: Too many open files
[err] evsignal_init: socketpair: Too many open files
```
when adding a couple of files at once.

**Comment by SilentBot1** [comment]
Hi @leoherzog 

This sounds like a duplicate issue of #1663. 

Please could you try the proposed fix in that ticket and let me know the results?

Kind regards
Brad
