### ISSUE TITLE
My Cloud Home

### ISSUE THREAD

**Issue by Jimnaebother** [webtorrent/webtorrent#1635]
Could someone develop an app similar to Webtorrent that would run on WD's My Cloud Home Storage Device.  It seems WD made a right hash it's creation however the NAS still sells and I am sure someone could make some money by developing and selling such an app. Jim

**Comment by SilentBot1** [comment]
Hi @Jimnaebother 

Just from a quick look, applications developed for the My Cloud Home are required to be in Java making it impossible to use the already created WebTorrent library application causing a large amount of complexity in developing the application.

If there is enough demand for this, I'm sure a member of the team would have a full look into the feasibility of developing this.

Kind regards
Brad
