### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by BlockLists** [webtorrent/webtorrent#1636]
Could you please tell me a way to slow down the seeding on WebTorrent because it's driving me mad and they are sucking my net and my download is worse than the seeding.
Please add something to your client to control seeding or tell me how to do it or I'll just have to use a client that has this function.
I love your client but its a little too basic.

**Comment by DiegoRBaquero** [comment]
Not possible at the moment. See https://github.com/webtorrent/webtorrent/issues/163
