### ISSUE TITLE
No WebRTC support: Specify `opts.wrtc` option in this environment

### ISSUE THREAD

**Issue by KingZee** [webtorrent/webtorrent#1639]
**What version of WebTorrent?**
0.103.1
**What operating system and Node.js version?**
Windows 7, v11.6.0

I'm having this issue again : https://github.com/feross/simple-peer/issues/110

I don't understand what I'm doing wrong. 
Here is my code for adding a torrent : 

    var TorClient = new WebTorrent({ tracker: { wrtc: false }});
    TorClient.on('error', function(err){
	    console.log('Fatal client error. Restart server.');
    });

    function addTorrent(tor,path){
	    return new Promise(function(resolve,reject){
		    try {
			    TorClient.add(tor, {path: path},function ontorrent (torrent) {
				    resolve(torrent);	//called when torrent is ready to be downloaded
			    });
		    } catch (e) {
			    reject(e);
		    }
	    });
    }

(As I pasted this snippet I just remember I added a try-catch block for this reason around a month ago, I just forgot about this problem.)

Once the torrent is added through the code above, it's downloaded for a few seconds, and then an error is thrown.
The error thrown is similar to the linked issue : 

      throw makeError('No WebRTC support: Specify `opts.wrtc` option in this environment', 'ERR_WEBRTC_SUPPORT')
      ^

    Error: No WebRTC support: Specify `opts.wrtc` option in this environment
    at makeError (...\node_modules\simple-peer\index.js:1017:13)

This is weird because I tried to go through simple-peer to disable wrtc, but it seems ironic, here's the relevant code for the error above : 

      self._wrtc = (opts.wrtc && typeof opts.wrtc === 'object')
        ? opts.wrtc
        : getBrowserRTC() //returns null if it doesn't find window

      if (!self._wrtc) {
        if (typeof window === 'undefined') {
          throw makeError('No WebRTC support: Specify `opts.wrtc` option in this environment', 'ERR_WEBRTC_SUPPORT')
        } else {
          throw makeError('No WebRTC support: Not a supported browser', 'ERR_WEBRTC_SUPPORT')
        }
      }

Setting wrtc to either a falsey value, or a truthy one, will always trigger the error. Any help on how to work around this error? Thanks.

**Comment by KingZee** [comment]
const wrtc = require('wrtc');
    var TorClient = new WebTorrent({ tracker: { wrtc: wrtc }});

Even including wrtc still triggers this error, anyone to help out please on how to fix this? Thanks.

**Comment by feross** [comment]
Are you running this code in a Node.js environment, Electron environment, or the browser? If so, which browser?

In Node.js, you shouldn't need to even set the option to `{ tracker: { wrtc: { false } }`. I'll repeat what I said in the issue you linked:

The only way the error you're getting could possibly happen (as far as I can tell), is if you're setting the `wrtc` option in `WebTorrent` like this:

```js
new WebTorrent({ tracker: { wrtc: true }})
```

Or you're setting `global.WRTC` to a truthy value, or using a shim for `RTCPeerConnection` that is confusing the `get-browser-rtc` module's detection code.

**Comment by KingZee** [comment]
The behavior of this was so inconsistent I couldn't accurately reproduce it because of the multiple packages involved (wrtc, simple-peer, and webtorrent). 

I have tried with the options you mentioned and other different workarounds, but in any case I made my own fork of simple-peer so the error is no longer thrown, so I will close this unless I can accurately reproduce it.
