### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by oijkhg** [webtorrent/webtorrent#1643]
**Feature**: Add i2p support to Webtorrent
**Why?**: Mainly for privacy and security but also to support decentralized web communications.
**How?**: BitTorrent already has wide usage of i2p thank to i2p-snarks and [XD](https://xd-torrent.github.io/).

_____________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75655242-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75655242)](https://www.bountysource.com/issues/75655242-feature-support-i2p)

**Comment by SilentBot1** [comment]
Hi @oijkhg 

I'm quite unfamiliar with I2P but I believe it's possible to add I2P support using a module like [I2P](https://www.npmjs.com/package/i2p) but this would require a rework of the many modules which make up WebTorrent.

If there is enough support for this, we can continue and look into the idea further.

Kind regards
Brad

**Comment by feross** [comment]
Duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/1606
