### ISSUE TITLE
html Video Element supports a file when directly targeting to file url in source, but doesn't suport same video if using WebTorrent

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#1644]
**What version of WebTorrent?**
latest
**What operating system and Node.js version?**
windows 10
**What browser and version? (if using WebTorrent in the browser)**
Chrome Latest, Firefox Latest
**What did you expect to happen?**
Play MP4 files
**What actually happened?**
I know similar problem this is discussed before and WebTorrent only supports MP4 files.
But I have 3 cases which was strange
1. I have a MKV file which Chrome can handle playing the file when I put the source url in the video element source, but when I use WebTorrent it doesn't play (it downloads but can not render to the video element) the video element raises the error event , strange thing is browser and video element are same, but I think its about how webtorrent serve the data to video element, maybe mkv has larger header than mp4 (which is correct) and webtorrent doesn't pass the correct header to player so the player can identifies the file.
2. I have a mkv video with ac3 audio, I have converted it to mp4 with aac audio using ffmpeg, it did not play the file again and browser can still play it if I directly put url in the video element.
Is there any bitrate limitation for audio and video?
3. There are some mkv files with mp3 audio, I converted those mkv files which usually branded as mSd (tv-series) to MP4 with same mp3 audio the file plays but without audio! I tested converting audio to aac and everything works fine.

**Comment by jimmywarting** [comment]
Don't just write latest when we ask for it. Not everyone have the lates version or know that there exist a new version out there. Also take into consideration that the issue can take months to resolve and then the "latest" will be incorrect.

**Comment by jimmywarting** [comment]
Maybe #1522 would be of any interest? 
you can stream any video format html5 video player supports without having to go thought a custom mp4 decoder

**Comment by WatchSoMuch** [comment]
Thanks jimmy, your idea is great, Actually I was expecting same behaviour from WebTorrent when I first used webtorrent.
Anyways have you tested it for streaming?
