### ISSUE TITLE
webtorrent can not download from bittorrent peer

### ISSUE THREAD

**Issue by MeowTheCat** [webtorrent/webtorrent#1647]
**  I did post the issue on webtorrent desktop but no response so far. Based on the symptom, the root cause must lie in the webtorrent library it's using.**

**What version of WebTorrent?**
Webtorrent desktop 0.20.0,  I'm building it with webtorrent 0.103.0

**What operating system and Node.js version?**
Mac Node v11.1.0

**What did you expect to happen?**
I copy the magnet link 
magnet:?xt=urn:btih:e989e1d35c0a6952e318c872cc2e84f90e77ebb2&dn=testfile.zip&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2fexplodie.org%3a6969

into webtorrent desktop.   Actually this is a file I'm seeding from a seedbox (utorrent client) 24*7.
I expect it will download the file 

**What actually happened?**
Webtorrent **could find the peer but not downloading the file**. If I use other client like qbtorrent, it is downloading the file as expected.
![WechatIMG24](https://user-images.githubusercontent.com/12821469/59900051-c5e01b00-93ab-11e9-8870-2832b59dfa7d.jpeg)

**Comment by yuqic987** [comment]
qbtorrent utorrent連不上WS協議，毒蛙安裝WS挿件可以連上，可惜無法交換數據，WS伺服器端毒蛙的連結會報錯。

Webtorrent desktop無法連接遠程UDP協議，內網的話可以連上utorrent，Webtorrent desktop之間可以相互做種，但如長時間沒有連接會話的話連接就會被拋弃，也就是說無法長時間的做種

無奈，希望作者完善下，這樣Webtorrent才能普及

**Comment by MeowTheCat** [comment]
let me translate the remarks above.
yuqic987 was saying webtorrent desktop doesn't work with UDP protocol on internet. 

Below is what I found:  Actually I found it was able to download from utorrent client while building with webtorrent 0.98.21  (however there were other issues with that version, like can't download large files > 100M ).  Can't download magnet link at all with latest version 0.103.0

**Comment by MeowTheCat** [comment]
@yuqic987  Could you elaborate 但如長時間沒有連接會話的話連接就會被拋弃 ?
意思是如果一個webtorrent 在做種，但是長時間沒有peer去下載 這個種子就失效了？

**Comment by mguomanila** [comment]
@MeowTheCat i have the same problem as yours. i set up using stand alone nodejs+webtorrent app and its downloading to up to 5% and then stays on these progress forever, im downloading a torrent file about 3Gb-6Gb size of video. I tried using the same app as microservice to be access through a port using seneca and endpoints in express, but eventually it only finds the peer but it stays on 0% progress forever, i tried to run it overnight but it stays the same, and the process was not abandoned because i set up the logging for the progress, eventually i manually stopped it. hope this issues can be solved soon.. thanks

**Comment by yuqic987** [comment]
> @yuqic987 Could you elaborate 但如長時間沒有連接會話的話連接就會被拋弃 ?
> 意思是如果一個webtorrent 在做種，但是長時間沒有peer去下載 這個種子就失效了？

是的，我遇到的情況就是這樣的，在查看WS tracker 服務端時發現長時間沒有peer連接下載時，webtorrent就不會再與 tracker通信，新的peer要下載時也就不會有任何peer連接，我想這可能是客戶端軟體做種的上傳機制問題，但是目前無法找到合適的做種軟體，並且就猶如你測試的那樣，大文件因為未知的原因無法下載

**Comment by FirstZero** [comment]
I got exactly the same issue.
Webtorrent-Desktop 0.20.0 -> cant download.
So I tried 0.19 and it magically worked again.
Similar thing is going on with webtorrent-cli

**Comment by MeowTheCat** [comment]
> I got exactly the same issue.
> Webtorrent-Desktop 0.20.0 -> cant download.
> So I tried 0.19 and it magically worked again.
> Similar thing is going on with webtorrent-cli

Can I ask what version of webtorrent library Webtorrent-Desktop 0.19 is built with?  You could be able to view it from click "about webtorrent" in the menu.
