### ISSUE TITLE
2nd html example doesn't work

### ISSUE THREAD

**Issue by PaTiToMaSteR** [webtorrent/webtorrent#1649]
Hi there guys, just starting to use and understand webtorrent. 

Sadly copy pasting the 2nd example I get an error and nothing of the 2nd html code works. Only appears a little Ui but does nothing. Following https://webtorrent.io/intro
Hence is a bit frustrating :) Additionally I cannot understand how to use the other nodejs code snippets shown at "Quick Examples". If someone can point me in the right direction will be nice, thanks.

**What version of WebTorrent?**
latest
**What operating system and Node.js version?**
Windows 10, nodejs 12.4.0
**What browser and version? (if using WebTorrent in the browser)**
Brave, latest
**What did you expect to happen?**
That the demo works...
**What actually happened?**
webtorrent.min.js:5 Uncaught Error: Error downloading torrent: XHR error
    at webtorrent.min.js:5
    at t.exports.<anonymous> (webtorrent.min.js:7)
    at t.exports.t (webtorrent.min.js:5)
    at t.exports.r.emit (webtorrent.min.js:4)
    at XMLHttpRequest.c.onerror (webtorrent.min.js:7)

**Comment by alxhotel** [comment]
Thanks for reporting @PaTiToMaSteR.

I think you are referring to this CodePen: https://codepen.io/yciabaud/pen/XdOeWM

In Chrome, it works as expected (although the line 19 of the JS file should be fix to select the mp4 file). However, as pointed out, the error appears in the Brave browser.

So it seems this is an issue with Brave browsers. In fact there is at least an issue related with this: brave/browser-laptop#12971

@feross @DiegoRBaquero any ideas?

**Comment by PaTiToMaSteR** [comment]
Thanks for the answer! Is that example, yup!

**Comment by feross** [comment]
This is indeed a bug in Brave. I opened an issue with more info here: https://github.com/brave/brave-browser/issues/5361

**Comment by feross** [comment]
I'll attempt to address this issue on the Brave side, so closing this issue here.
