### ISSUE TITLE
connection error to wss://tracker.btorrent.xyz

### ISSUE THREAD

**Issue by kamikaze1997** [webtorrent/webtorrent#1653]
Hello everyone, I am new to Webtorrent and I am facing problems, before using it I want to test it in **Instant.io** but it is not working.

I've created dorrente sentences in every way but none works, it only appears the following messages:

connection error to wss: //tracker.fastcast.nz
connection error to wss: //tracker.btorrent.xyz
connection error to wss: //tracker.fastcast.nz
connection error to wss: //tracker.btorrent.xyz
connection error to wss: //tracker.btorrent.xyz
connection error to wss: //tracker.btorrent.xyz
connection error to wss: //tracker.btorrent.xyz

Please help me, what am I doing wrong?

I'm trying to create a Torrent to test on **Instant.io** but all the torrents I create do not work.

**Comment by feross** [comment]
Those warnings are harmless because there is one other tracker server still online (https://openwebtorrent.com).

Which torrent client are you using to download the torrent? You need to use a client that supports WebRTC, like https://webtorrent.io/desktop/
