### ISSUE TITLE
get "invalid torrent indetifier" when using torrent as buffer

### ISSUE THREAD

**Issue by Naor1Levi** [webtorrent/webtorrent#1661]
webTorrent version: the new (just downloaded)

i am using webtorrent in java script (front end)
browser: chrome/firefox (both dont work)
`    client.add(torrentId, function (torrent) {
        // Torrents can contain many files. Let's use the .mp4 file
        var file = torrent.files.find(function (file) {
            if (file.name.endsWith('.mp4')){
                console.log('success finding .mp4');
                return file.name.endsWith('.mp4')
            }
        })
`
expected result: the player will appear with the video
actual results: got an error

**Comment by alxhotel** [comment]
Can you post the torrent identifier you are using?

Can you also post the details of the error thrown (such as the trace)?

By the way, based only on the code you have posted, no video is expected to appear (unless you add it to the DOM by, for example, calling `renderTo`)

**Comment by Naor1Levi** [comment]
| (anonymous) | @ | webtorrent.min.js:11
-- | -- | -- | --
  | d.run | @ | webtorrent.min.js:11
  | s | @ | webtorrent.min.js:11
  | setTimeout (async) |   |  
  | o | @ | webtorrent.min.js:11
  | c.nextTick | @ | webtorrent.min.js:11
  | S | @ | webtorrent.min.js:11
  | playTorrent | @ | script.js:50
  | xhttp.onreadystatechange | @ | script.js:29
  | XMLHttpRequest.send (async) |   |  
  | searchTorrent | @ | script.js:37
  | onclick | @ | (index):16

by the way, i am using a torrent buffer exported from search-torrent-api.
and i appended the video the the body element.

i got this error only when i am using torrent buffer, torrent files are working

**Comment by Naor1Levi** [comment]
Can someone give an example of downloadTorrent feature? That I will understand how it work

**Comment by SilentBot1** [comment]
Hi @Naor1Levi 

Without an example of the buffer returned from `search-torrent-api`'s `downloadTorrent` function, we're going to be unable to help you with this issue as I'm unfamiliar with the library.

**Note:** if you do provide a buffer, ensure it's **not** of copyrighted content.

Kind regards
Brad
