### ISSUE TITLE
Question, ports problem? 2 machines 1 website

### ISSUE THREAD

**Issue by PaTiToMaSteR** [webtorrent/webtorrent#1662]
**What version of WebTorrent?**
0.20.0

Situation: 
- Machine A: WebTorrent Desktop
- Machine B: WebTorrent Desktop
- Web, to links: 1. Magnet to Machine A video, 2. Magnet to Machine B video

Watch A (magnet link)
Watch B (magnet link)

- Copy paste of the webtorrent.io player, changing torrentId with the magnet link depending which link to press. No big deal. 
- The torrent only has my tracker, port 8000.

Result:
- Both machines cannot see the video, unless...
- I do a "trick", from Machine A I open the video so 2 peers, chrome and machine A
- We can see the video
- More info: Machine A and Machine B can see their own videos

QUESTION :)
I'm guessing is a port problem, either the tracker must be in port 80, or I need to fwd ports in my router, if so... as far I know we can't configure ports in WebTorrent Desktop. 

Thanks a lot guys! Great project.

**Comment by alxhotel** [comment]
I don't understand the scenario.

So you have two machines (A and B) seeding the same or different video?

And then you have a browser (in a third machine) that can not download the video from any of the machines (A or B)?

But if you open a browser in machine A or B which downloads the video, then it triggers the third machine to start downloading it?

**Comment by PaTiToMaSteR** [comment]
@alxhotel thanks for the answer, I solve it. I'm working on www.youmazeme.com project. Basically the content creator needs to have access through https to the .torrent file and everything else appears to work. I was just wondering what happens if the content creator is behind a CG-NAT. And I said I solve it because the content creator needs a server for the initial seeding of the content. I'm just wondering the way to use the home connection when they are behind CG-NATs or similar.

**Comment by alxhotel** [comment]
Ah good to know. For CG-NAT, I believe you can use some technique like UDP holepunching. But I think WebRTC does all the work for you (by using STUN and TURN servers), so that's why I don't understand why machine A and machine B were not able to communicate.
