### ISSUE TITLE
WebTorrent not seeding from terminal

### ISSUE THREAD

**Issue by GiuseppeEliano** [webtorrent/webtorrent#1667]
**What version of WebTorrent?**
2.0.1 (0.104.0)

**What operating system and Node.js version?**
Ubuntu 18.10 / node v8.11.4

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
Seeding a torrent file from terminal

**What actually happened?**
Currently, I'm trying seed a file from terminal, but, the .torrent file is not being seeded when requested. I'm running this command: **webtorrent seed mysound.torrent --keep-seeding --verbose**

I'm using a dedicated server with 1000mbps bandwidth, there are no firewalls or iptables rules, all ports are open on my server.

The output from the command above is something like this:

Seeding: mysound.mp3
Info hash: df6e9fcd7e4dffd6351552277228b55764e74618
Server running at: http://localhost:8000/0/df6e9fcd7e4dffd6351552277228b55764e74618/mysound.mp3
Downloading to: /var/www/prop/torrent
Speed: 0 B/s Downloaded: 4.7 MB/4.7 MB Uploaded: 0 B
Running time: 5 minutes Time remaining: N/A  Peers: 0/1
Queued peers: 0  Blocked peers: 0  Hotswaps: 0

S   Unknown                   0 B        0 B/s        0 B/s        choked

@edit: I created the .torrent file running this command: **create-torrent --urlList 'https://myserver.com/prop/torrent/mysound.mp3' mysound.mp3 > mysound.torrent**

@edit2: Running this on different server: **webtorrent download df6e9fcd7e4dffd6351552277228b55764e74618**, the output is something like this: **fetching torrent metadata from 0 peers**

I can make this work using webseed, but I want seed using my server to another files... why is this happening?

**Comment by feross** [comment]
The seed command should point to the files you want to seed, not the .torrent file.

So your command `webtorrent seed mysound.torrent --keep-seeding --verbose` is the wrong command to use. You want something like `webtorrent seed /path/to/files --keep-seeding --verbose` instead.
