### ISSUE TITLE
Is numPeers deprecated?

### ISSUE THREAD

**Issue by nimabrownlee** [webtorrent/webtorrent#1670]
**What version of WebTorrent?**
0.105.0
**What operating system and Node.js version?**
MacOS Mojave & v12.1.0
**What did you expect to happen?**
I am trying to check how many peers there is but numPeers doesnt exist.
**What actually happened?**
numPeers doesnt exist. Is the docs outdated?

**Comment by SilentBot1** [comment]
Hi @nimabrownlee 

Can you provide an example of the code you are experiencing the issue with?

I'm running the following code under Windows 10 and Node v10.16.0 using WebTorrent version 0.105.0 and `torrent.numPeers` is working as expected.

```javascript

var WebTorrent = require('webtorrent')
var Client = new WebTorrent()

var torrent = Client.add('magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F')
torrent.on('wire', (_)=>{
    console.log(`[WebTorrent-v${WebTorrent.VERSION}] [${torrent.infoHash}] Current peers: ${torrent.numPeers}`)
})

```

Kind regards
Brad
