### ISSUE TITLE
Stream video from torrent (NodeJS)

### ISSUE THREAD

**Issue by htorbov** [webtorrent/webtorrent#1673]
I apologize for creating this issue, since it's more a question than an issue.

I did:
```
mkdir webtorrent && cd webtorrent
npm install webtorrent-hybrid
touch index.js
```

index.js:
```
var WebTorrent = require('webtorrent-hybrid')

var client = new WebTorrent()
var magnetURI = '...'

client.add(magnetURI, function(torrent) {
    var server = torrent.createServer()

    server.listen(80)
})
```

But when I go to http://localhost:80, it only shows a list of the torrent's files. Can you give me an example, how can I play the .mp4 inside, using my code, when I open the browser? With progress information of download/upload, if possible? I hope when I use the NodeJS, the torrent is still downloading in the client's browser, not in my server, right?

Thanks!

**Comment by SilentBot1** [comment]
Hi @htorbov 

As mentioned in the [API documentation](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#torrentcreateserveropts), calling `torrent.createServer()` creates a HTTP server which dynamically downloads the needed torrent pieces to fulfill the HTTP request.

This means that using your example code, you are downloading the torrent's content to your [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid) client and then are serving the downloaded content from the server to the client who is making the HTTP request. The browser client **isn't** downloading the torrent directly, it's being "proxied" through the [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid) client as a webseed.

This functionality allows the initial seeding of content into the WebTorrent WebRTC swarm which is only currently being seeded on the BitTorrent TCP/UDP swarm.

[Instant.io](https://github.com/webtorrent/instant.io) is a good, existing and usable, example to demonstrate how to gather and display the torrents statistics as you're wanting to display. 

If you need any further help with this, feel free to continue the discussion in this thread and I'll happily help but as you have mentioned, this is a question and not a issue, so I'm going to close this.

Kind regards
Brad
