### ISSUE TITLE
Give DHT access to web clients

### ISSUE THREAD

**Issue by RangerMauve** [webtorrent/webtorrent#1684]
Not sure if this is the right place to post this, but I think it would be useful if hybrid clients could be used as a way to give web clients access to the DHT.

This would give us a more decentralized alternative to tracker-based peer lookup, and could enable applications that make use of the DHT.

For example, this would remove the need for a [WebRTC DHT](https://github.com/webtorrent/webtorrent/issues/288), and would enable fancy new things like [mutable torrents](https://github.com/RangerMauve/mutable-webtorrent).

This would need two pieces to work: A way to identify hybrid clients with DHT support, and an RPC API of some sort to talk to the hybrid client's DHT node.

**Comment by feross** [comment]
> to allow web clients to access the DHT through the hybrid client

WebRTC-only clients wouldn't gain anything from being able to read/write the DHT. The DHT only contains ip:port pairs for peers and a WebRTC-only client can't connect to that.

It sounds like you're describing something like https://github.com/webtorrent/ut_pex but for WebRTC connections instead of TCP/UDP ones. So, there's no DHT involved. When a WebRTC peer A connects to another WebRTC peer B to download a particular torrent, A could ask B about other WebRTC peers that it is aware of that are also interested in the same torrent. Say that peer B is connected to peer C that A is not aware of. Then B could act as the signaling server (exchanging offers/answers) between A and C so they can directly connect.

Is this along the lines of what you were envisioning?

**Comment by RangerMauve** [comment]
Yeah! The DHT to me is more of a means to exchange peer information without having one central server and utilizing peers themselves as much as possible.

However, BEP 46 is another motivating factor for having a DHT so that we could support mutable torrents on the web. I'm sure a new BEP could be drafted up to enable mutability through some sort of gossip instead of a DHT though.

**Comment by fabiosantoscode** [comment]
@RangerMauve ir you're thinking of sending a PR for https://github.com/webtorrent/webtorrent/issues/1191 @ me and tell me how I can help.

**Comment by RangerMauve** [comment]
@fabiosantoscode I don't think I'll have bandwidth for working on that any time soon. 😅 I'm too busy with Dat and WebVR stuff.

**Comment by yunfan** [comment]
> > to allow web clients to access the DHT through the hybrid client
> 
> WebRTC-only clients wouldn't gain anything from being able to read/write the DHT. The DHT only contains ip:port pairs for peers and a WebRTC-only client can't connect to that.
> 
> It sounds like you're describing something like https://github.com/webtorrent/ut_pex but for WebRTC connections instead of TCP/UDP ones. So, there's no DHT involved. When a WebRTC peer A connects to another WebRTC peer B to download a particular torrent, A could ask B about other WebRTC peers that it is aware of that are also interested in the same torrent. Say that peer B is connected to peer C that A is not aware of. Then B could act as the signaling server (exchanging offers/answers) between A and C so they can directly connect. There's an issue about this here: #1191
> 
> Is this along the lines of what you were envisioning?

but why dht must build upon the model that A should connect to C directly? can we use B as the relay peer, so that its like a udp/ip network, every  peers acts like a router ?

**Comment by RangerMauve** [comment]
Is this closed because DHT access is a `wontfix` sort of scenario? 😅

**Comment by feross** [comment]
We don't support a DHT in the web browser yet. And there's already an issue for that: #288 

Was there some other reason we need another issue for this?

**Comment by RangerMauve** [comment]
Nope, that seems reasonable, thank you.
