### ISSUE TITLE
Add examples of how to integrate with various JS video players

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1686]
This issue (https://github.com/webtorrent/webtorrent/issues/1685) mentioned a nice resource that shows how to integrate WebTorrent with various JS video libraries. 

https://qiita.com/mehdi/items/22ba55ae30bdcedd0746

Would be nice to add updated versions of these examples to the docs.

**Comment by attackpiggy** [comment]
Hey Feross, Would you want all the JS players information on the README.md file ? or was there a certain js players that would be there ?

**Comment by feross** [comment]
This information should be added to a new `docs/tutorials.md` file which we can add to the website.

**Comment by aravindmathradan** [comment]
Hey Feross, I've been trying to get WebTorrent render to video.js 7.xx player. As setting the `src` does not work in this scenario, I tried `file.renderTo()` and rendered in the `<video>` tag initialized by videojs. This resulted in a player with the native HTML5 controls along with the videojs custom controls on top of it. The video plays and is seekable. Is there some fix to this?

**Comment by rimday** [comment]
I just publish an example work with video-js 7.10.2, and webtorrent 0.112.0
[https://jsfiddle.net/quantbm/dekj6s2a/2/](url)

**Comment by rimday** [comment]
I just published an example work with video-js 7.10.2, and webtorrent 0.112.0
[example](https://jsfiddle.net/quantbm/dekj6s2a/2/)
