### ISSUE TITLE
Can webtorrent stream on iOS?

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#1688]
**What version of WebTorrent?**
the version on 2019-08-07 dont know where to find the version?!
**What operating system and Node.js version?**
iOS
**What browser and version? (if using WebTorrent in the browser)**
tested with Safari,Chrome,Firefox
**What actually happened?**
Download starts but doesn't play until its fully downloaded

It starts playing when the download completes, so I thought maybe end of file is needed for the iOS player to be able to play the file, but adding this line didn't help:
torrent.critical(torrent.pieces -16777216 / torrent.pieceLength, torrent.pieces);
This is supposed to download the last 16MB of the file, am I correct?

Or maybe there is a way to tell iOS use other player in browser?
My site visitors are starving to be able to stream on iOS, so they can do if I give an instruction

**Comment by BunnyPowah** [comment]
From what I understand, its IOS's lack of Media Source Extensions that prevents real time play on IOS.
