### ISSUE TITLE
Add browser testing for Safari

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1698]
We currently only test WebTorrent on Chrome and Firefox. Let's add Safari to the list.

**Comment by axelonet** [comment]
I just ran the HTML file from docs and added a magnet link. It started streaming the file. In safari of course. What else do I need to do to make webtorrent safari compatible,

**Comment by norzak** [comment]
Looks like removing a torrent from seeding corrupts Webtorrent on Safari.

**Comment by feross** [comment]
I added Safari to the airtap testing list a while ago. So this task is complete now.
