### ISSUE TITLE
Promote your WebTorrent-powered project/product!

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1702]
Hi all,

I frequently use the [@WebTorrentApp](https://twitter.com/webtorrentapp) Twitter account to promote cool projects that incorporate WebTorrent or related decentralized web technology (Dat, Scuttlebutt, IPFS).

I know there are lots of folks out there doing really neat things with WebTorrent and I'm happy to help promote these projects on the official Twitter account to spread the word to more folks. If you're interested in this, post a note below, in less than 280 characters to be shared on Twitter. Here's an example:

> WebTorrent is the first torrent client that works in the browser. It's written completely in JavaScript – the language of the web – and uses WebRTC for true peer-to-peer transport. No browser plugin, extension, or installation is required. https://webtorrent.io

**Comment by nirlanka** [comment]
I know there are a few file-sharing sites (that use WebTorrent) already in existence, but I anyway created my own file-sharing site at https://file-cargo.herokuapp.com 

I used Coffeescript and webpack.

It still has some bugs and missing features, and I'm working on them while learning WebTorrent.

**Comment by feross** [comment]
@nirlanka Glad to hear you love WebTorrent! Can you share the text that you'd like to be shared? I have an example of how it should look in my comment above. Must be less than 280 characters.

**Comment by fijiwebdesign** [comment]
Still in the works: 

Seedess is a P2P video streaming platform to reduce video streaming costs by up to 70% by transparently streaming video over the mature BitTorrent protocol in the browser using WebTorrent. https://seedess.com/

**Comment by playvid** [comment]
ElectronJS + WebTorrent application:

Playvid is a fast and powerfull torrent downloader:
https://github.com/playvid/playvid

It doesn't take much of your CPU/Memory and still have everything that your
browser offers.
No hidden scripts to mine cryptos.
No annoying ad's.
Just play.

Thanks to WebTorrent technology !

**Comment by sayem314** [comment]
Torrenter, a simple nodejs package to search and download torrents using CLI, these tools use some basic techniques to find the best possible torrents you are searching for and download them sanely.
https://github.com/sayem314/torrenter

![](https://github.com/sayem314/torrenter/raw/master/screenshot2.png)
![](https://github.com/sayem314/torrenter/raw/master/screenshot3.png)

**Comment by RecoX** [comment]
> 
> 
> Torrenter, a simple nodejs package to search and download torrents using CLI, these tools use some basic techniques to find the best possible torrents you are searching for and download them sanely.
> https://github.com/sayem314/torrenter
> 
> ![](https://github.com/sayem314/torrenter/raw/master/screenshot2.png)
> ![](https://github.com/sayem314/torrenter/raw/master/screenshot3.png)

Keen to integrate this in refreex

https://github.com/refreex/refreex-webtorrent-desktop

Do you have a kind of API in your code to use just the response in my code?

**Comment by sayem314** [comment]
> > Torrenter, a simple nodejs package to search and download torrents using CLI, these tools use some basic techniques to find the best possible torrents you are searching for and download them sanely.
> > https://github.com/sayem314/torrenter
> 
> Keen to integrate this in refreex
> 
> https://github.com/refreex/refreex-webtorrent-desktop
> 
> Do you have a kind of API in your code to use just the response in my code?

Torrenter exposes undocumented api, you can use it to initiate the download and return webtorrent objects on complete but this process is not automatic. Going through the code should give you an idea. If you are looking for the search api please take a look at this that torrenter uses.
https://github.com/sayem314/torrent-indexer

**Comment by XayOn** [comment]
Aksum is a decentralized book library. Using a list of webtorrent-enabled torrents, allows you to find and download specific ebooks from them. https://github.com/xayon/aksum

**Comment by mehmetcansahin** [comment]
Hello, I would like to share with you the Peersvid project, which we have developed to reduce self-host video costs and have been working on for a long time.

You can generate a key by creating a token on Peersvid and integrate this key with your javascript file into your site with a very simple code. After this point, it will be enough to define the class for the videos that will work with Peersvid technology. After this definition, your video on Peersvid will work on the p2p network. Peersvid will reduce the load on the main server and distribute the video over those watching the video. Thus, the video data transfer from the main server and your hosting costs will decrease.

We are currently in beta and are creating test groups. If you want to be one of the first members of Peersvid and contribute to the development of the project, you can create an account at https://dashboard.peersvid.com . I can help if you need technical support at this stage. Peersvid will be completely free for beta group members during the first 3 months.

**Comment by feross** [comment]
I queued up a few of these to be posted to the twitter account.

Also -- in case you haven't seen this. If you have something built with WebTorrent that you want to share with more folks, please see: https://github.com/webtorrent/webtorrent/issues/1873
