### ISSUE TITLE
Ice connection keeps switching from connected to disconnected

### ISSUE THREAD

**Issue by Tinouga** [webtorrent/webtorrent#1707]
**What version of this package are you using?**
0.107.3
**What operating system, Node.js, and npm version?**
12.8.0

Hi,
Here is my problem: right after one peer starts sharing and another starts leeching (sometimes a few Ko of data are shared and it stops right after), the state of the ice connection keeps switching from connected to disconnected.
Could anyone point me to where should I look in order to fix this problem?
(The strange thing is that everything worked fine on my website until I made a git fetch/reset to update a few files with nothing (if I'm not mistaken) related to webtorrent)

Thanks a lot for your help!

from the console:
> bittorrent-protocol [8955f413] got interested +162ms
browser.js:96 bittorrent-protocol [8955f413] unchoke +0ms
browser.js:96 bittorrent-protocol [8955f413] got request index=38 offset=0 length=2239 +91ms
browser.js:96 bittorrent-protocol [8955f413] piece index=38 offset=0 +492ms
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: disconnected) (gathering: complete) +7s
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: connected) (gathering: complete) +3s
browser.js:96 simple-peer [fff8bb0] maybeReady pc true channel true +1ms
browser.js:100 engine.io-client:socket writing ping packet - expecting pong within 5000ms +15s
browser.js:100 engine.io-client:socket flushing 1 packets in socket +0ms
browser.js:100 engine.io-client:socket socket receive: type "pong", data "undefined" +33ms
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: disconnected) (gathering: complete) +9s
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: connected) (gathering: complete) +1s
browser.js:96 simple-peer [fff8bb0] maybeReady pc true channel true +1ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +23s
browser.js:96 simple-peer [1175445] destroy (error: undefined) +3s
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [f121415] destroy (error: undefined) +1ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +2ms
browser.js:96 simple-peer [4e48551] destroy (error: undefined) +2ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [d2b3dfb] destroy (error: undefined) +1ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +0ms
browser.js:96 simple-peer [2c8dd5e] destroy (error: undefined) +0ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [2ae3ff2] destroy (error: undefined) +1ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +2ms
browser.js:96 simple-peer [04fe70d] destroy (error: undefined) +3ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [fc9a94b] destroy (error: undefined) +0ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [f75e0eb] destroy (error: undefined) +1ms
browser.js:96 bittorrent-tracker:websocket-tracker tracker timeout: destroying peer +1ms
browser.js:96 simple-peer [dae7948] destroy (error: undefined) +1ms
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: disconnected) (gathering: complete) +4s
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: connected) (gathering: complete) +2s
browser.js:96 simple-peer [fff8bb0] maybeReady pc true channel true +0ms
browser.js:100 engine.io-client:socket writing ping packet - expecting pong within 5000ms +25s
browser.js:100 engine.io-client:socket flushing 1 packets in socket +1ms
browser.js:100 engine.io-client:socket socket receive: type "pong", data "undefined" +32ms
browser.js:96 simple-peer [fff8bb0] iceStateChange (connection: disconnected) (gathering: complete) +8s
browser.js:96 simple-peer [fff8bb0] on channel close +3s
browser.js:96 simple-peer [fff8bb0] destroy (error: undefined) +0ms
browser.js:96 webtorrent:peer destroy 2d5757303030372d324e63313431643848565064 (error: undefined) +39s
browser.js:96 simple-peer [fff8bb0] destroy (error: undefined) +1ms

from chrome://webrtc-internals
>14/08/2019 à 12:50:02 | icegatheringstatechangecomplete
-- | --
14/08/2019 à 12:50:02 | iceconnectionstatechangeconnected
14/08/2019 à 12:50:02 | iceconnectionstatechange (legacy)connected
14/08/2019 à 12:50:03 | connectionstatechangeconnected
14/08/2019 à 12:50:04 | onRemoteDataChannellabel: fdcac08121283cdddf9272dd5496807cf38a9019, reliable: true
14/08/2019 à 12:50:09 | iceconnectionstatechangedisconnected
14/08/2019 à 12:50:09 | iceconnectionstatechange (legacy)
14/08/2019 à 12:50:09 | connectionstatechangedisconnected
14/08/2019 à 12:50:10 | iceconnectionstatechangeconnected
14/08/2019 à 12:50:10 | iceconnectionstatechange (legacy)connected
14/08/2019 à 12:50:10 | connectionstatechangeconnected
14/08/2019 à 12:50:18 | iceconnectionstatechangedisconnected
14/08/2019 à 12:50:18 | iceconnectionstatechange (legacy)disconnected
14/08/2019 à 12:50:18 | connectionstatechangedisconnected
14/08/2019 à 12:50:21 | iceconnectionstatechangeconnected
14/08/2019 à 12:50:21 | iceconnectionstatechange (legacy)connected
14/08/2019 à 12:50:21 | connectionstatechangeconnected
14/08/2019 à 12:50:28 | iceconnectionstatechangedisconnected
14/08/2019 à 12:50:28 | iceconnectionstatechange (legacy)disconnected
14/08/2019 à 12:50:28 | connectionstatechangedisconnected
14/08/2019 à 12:50:31 | iceconnectionstatechangeconnected
14/08/2019 à 12:50:31 | iceconnectionstatechange (legacy)connected
14/08/2019 à 12:50:31 | connectionstatechangeconnected
14/08/2019 à 12:50:38 | iceconnectionstatechangedisconnected

edit: after turning off/on my CPE (I hope it's the correct translation for "box internet") once again, everything works fine now

**Comment by feross** [comment]
Glad you got your issue resolved. Connection issues depending on network conditions are unfortunately part of life in distributed systems like WebTorrent.
