### ISSUE TITLE
hello everyone this is my first time so bare with me please

### ISSUE THREAD

**Issue by bigdog71232** [webtorrent/webtorrent#1710]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment]
Hi there! It looks like you didn't include any info in this issue. I suggest taking a look here (https://guides.github.com/activities/hello-world/) to learn a bit more about how GitHub works!
