### ISSUE TITLE
How this webtor.io is working? Its streaming non-webrtc torrent in browser ?

### ISSUE THREAD

**Issue by adamwoo2444** [webtorrent/webtorrent#1711]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by adamwoo2444** [comment]
I would like to ask how this webtor.io is working however webtorrent only support webrtc torrents in browser but this can stream non-webrtc torrents as well.
@feross @mikeal @jerodsanto @manuel @watson

**Comment by adamwoo2444** [comment]
Any lead would be highly recommended.
Thanks

**Comment by dodobyte** [comment]
I would really like to know as well.

**Comment by kaludjer** [comment]
I checked what they have under the front, and I think that they have 'service' in the middle that DL, transcode and then stream over HLS. 

They did really good job and I would like to know some details too.

**Comment by adamwoo2444** [comment]
@kaludjer  @dodobyte  you should check watchsomuch(dot)org as well.Can you tell how they are using instant.io ?

**Comment by kaludjer** [comment]
@adamwoo2444  As I saw, they hit the server that start to download the file, and start seeding over WebRTC so it's playable in browser.

**Comment by feross** [comment]
@adamwoo2444 Please do not discuss using WebTorrent for copyright infringement. No one will be able to assist you.
