### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [webtorrent/webtorrent#1715]
**What problem do you want to solve?**

Knowing an Ethereum address to send funds to for this project.

**What do you think is the correct solution to this problem??**

I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Are you willing to submit a pull request to implement this change?**

Yes, I just need to know what the Ethereum address is

**Comment by feross** [comment]
Hi there! Thanks for the issue. You can send funds to me (feross) using the Ethereum address here: https://feross.org/thanks/ I'd rather not add it to `FUNDING.yml`. Thanks.
