### ISSUE TITLE
Local network

### ISSUE THREAD

**Issue by Jedian** [webtorrent/webtorrent#1723]
Ahoy, mateys!

I am working on an educational project and I've been asked to search for ways to enhance download performance in schools. What happens is that, when a teacher, using the computer laboratory for the class, asks his students to download some educational content, i.e. a video, they all do it at the same time. The school connection is not very good and it gets overloaded.

My team and I were wondering if there is a way of a peer to peer system, with filters for educational content (that part is pretty easy with this module :smile: ). But with the additional of, in some way, detects and give preference to local network peers. This could boost download speed amazingly. So that is the question:

Is there any way of accomplishing it? Spotting and giving peers in local network priority?

(I'm sorry for my bad english. It's not my first language :x)

**Comment by subins2000** [comment]
Will increasing the piece length, say half the file size improve the performance ?
