### ISSUE TITLE
Help please, my code is not working.

### ISSUE THREAD

**Issue by huyphuctt** [webtorrent/webtorrent#1726]
Hi everyone,

I have a problem when using webtorrent.min.js

I followed the instruction at <a href="https://webtorrent.io/intro" > Get Started</a> but it does not load anything.

The code is here:  https://jsfiddle.net/x8eb4vh9/10/

But when i run the hash with <a href="https://instant.io/#209c8226b299b308beaf2b9cd3fb49212dbd13ec" >Instant.io</a>, it works like a charm.

Could anyone help me to find where I missing?

The movie is seeding via latest version of WebTorrent Desktop on Window 10 PC.

Thanks alot.

**Comment by akhld** [comment]
@feross I'm having the same issue, only that Sintel video is working so far. Try using any of these [magnet links](http://tpbc.herokuapp.com/search/mp4/), all of them has seeders and works with other torrent clients (eg: transmission). Am I missing something here?

**Comment by RecoX** [comment]
> @feross I'm having the same issue, only that Sintel video is working so far. Try using any of these [magnet links](http://tpbc.herokuapp.com/search/mp4/), all of them has seeders and works with other torrent clients (eg: transmission). Am I missing something here?

The problem you got so far is the magnet link that you use to test have not webtorrent/hybrid seeders, if the magnet link that @feross provide you works every magnet link that has at least one webtorrent/hybrid seeder should work.

You can do the test by yourself downloading webtorrent desktop, downloading that magnet link and then when you got that torrent downloaded in your computer try in your codepen. It will work.

**Comment by akhld** [comment]
I see, thanks for the clarification @RecoX
