### ISSUE TITLE
Consider deprecating `webtorrent-hyrbid` and moving `wrtc` into `webtorrent`

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1734]
`webtorrent-hybrid` and the `global.WEBTORRENT_ANNOUNCE` is kind of a hack.

The whole reason I created `webtorrent-hybrid` was that installing the WebRTC in Node.js package (`wrtc`) used to cause lots of install warnings/errors for most users at one point in time. If the situation has improved since then, we can just include `wrtc` directly in the `webtorrent` package and deprecate `webtorrent-hybrid`.

We can try including `wrtc` in one version of `webtorrent` to see how many install errors it causes and if all looks good, then we can eventually deprecate `webtorrent-hybrid`.

_Originally posted by @feross in https://github.com/webtorrent/webtorrent/issues/1604#issuecomment-528555133_

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/pull/2786
