### ISSUE TITLE
Add @KayleePop to the organization

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1735]
I'm going through closed GitHub issues and catching up on everything from the past 12 months and I noticed that @KayleePop is very knowledgeable, good at answering new user questions, and very friendly. I propose adding them to the WebTorrent organization!

@KayleePop Are you interested in this? (I would have asked you privately first, but you don't have an email or website listed on your profile)

**Comment by KayleePop** [comment]
Uh sure. :smile:

**Comment by feross** [comment]
@KayleePop Hah, sorry if this issue caught you off guard. I don't want to add you if you're uncomfortable or if you don't want to be added!

**Comment by KayleePop** [comment]
It doesn't come with any responsibility right? Just permissions to help with issue tagging and such? That sounds fine.

**Comment by feross** [comment]
Okay, I just invited you. Thanks for being awesome.
