### ISSUE TITLE
Url-encoded magnet links don't work

### ISSUE THREAD

**Issue by stopmachine** [webtorrent/webtorrent#1747]
**What version of WebTorrent?**
0.107.16

**What operating system and Node.js version?**
Ubuntu

**What browser and version? (if using WebTorrent in the browser)**
Using webtorrent-desktop, but I traced the issue to webtorrent

**What did you expect to happen?**
Adding a url-encoded magnet link will be decoded and will successfully start downloading

**What actually happened?**
Passing a url-encoded magnet link ("magnet%3A%3Fxt%3Durn%3Abtih...") fails

**Comment by feross** [comment]
I've never seen a magnet uri shared in this format.  What is the use case here?

**Comment by stopmachine** [comment]
Extracting links from a web page, where the magnet links are in the query parameters part of URLs.

For example:

## Torrent list

- Torrent 1: https://example.com/pretty-print-magnet?link=magnet%3A%3Fxt%3Durn%3Abtih...
- Torrent 2: https://example.com/pretty-print-magnet?link=magnet%3A%3Fxt%3Durn%3Abtih...

**Comment by guanzo** [comment]
Just decode the query parameter.

```
const url = new URL('https://example.com/pretty-print-magnet?link=magnet%3A%3Fxt%3Durn%3Abtih')
url.searchParams.get('link') // magnet:?xt=urn:btih
```

**Comment by stopmachine** [comment]
A non-technical user will have trouble doing that. As I mentioned the link is pasted into webtorrent-desktop, which passes it as-is to webtorrent. So the question is, should decoding be introduced in webtorrent-desktop or webtorrent. Making webtorrent-desktop's enduser do the decoding himself before pasting feels wrong.

**Comment by guanzo** [comment]
Sorry I didn't read the issue thoroughly. How does the end user receive the link? is it not possible for some code to decode before displaying to the user?

**Comment by stopmachine** [comment]
The end user copies it from the web page in his browser. There is no control over the web page's source. It is of course possible to write some kind of a tailored browser plug-in, but that would require plugins for Chrome and Firefox, and will not solve the problem for browsers without plugin support like IE.

**Comment by feross** [comment]
@stopmachine Thanks for your responses, but I'm still confused a bit.

What do the example links you posted actually link to? WebTorrent would assume this is a link to a .torrent file and attempt to download it. 

Or are you saying that the user would slice off the part after `?link=` on their own and paste that part into WebTorrent Desktop?

Also, what do other torrent clients do in this case?

- Transmission?
- uTorrent?
- qBittorrent?

**Comment by stopmachine** [comment]
> Or are you saying that the user would slice off the part after ?link= on their own and paste that part into WebTorrent Desktop?

Exactly.

I've tested Transmission, it fails too when pasting a url-encoded link (it doesn't support pasting in the main window like WebTorrent Desktop does, you have to select File -> Open URL from the menu first). But I like WebTorrent Desktop because it's better, not because it's on-par :)
