### ISSUE TITLE
end-of-stream >=1.4.2 update creates a "premature close" error on seed() when using a W3C File input

### ISSUE THREAD

**Issue by Evoks** [webtorrent/webtorrent#1757]
**What version of this package are you using?**
0.107.16

**What operating system, Node.js, and npm version?**
Mac OS 10.14.6 / Chrome 77.0.3865.90 or Safari 13 / Node 12.0.0 / npm 6.11.3

**What happened?**
On browser, when I call the `seed` method using a W3C File input, "end-of-stream" is throwing an error :
```
error Error: premature close
    at onclosenexttick (webtorrent.min.js:12485)
    at Item.run (webtorrent.min.js:3160)
    at drainQueue (webtorrent.min.js:3130)
```
It adds the torrent in the WebTorrent client but the `torrent.files === []` and `torrent.done === false`.

If I put the 1.4.1 end-of-stream package, there is no problem.

**What did you expect to happen?**
And the `torrent.files` should contain the input data and `torrent.done` should be `true`.

**Comment by alxhotel** [comment]
Yep. Thanks for notifying this @Evoks.

Looks like `end-of-stream` has added some incompatible changes in the last versions. Related [end-of-stream#11](https://github.com/mafintosh/end-of-stream/issues/11)

**Comment by umbra-scientia** [comment]
Is there any plan for this issue to be solved? Is there a known workaround to make the most minimal upload functionality work at least? All examples and documentation for uploading a file are broken out of the box using the latest release versions. Always "premature close" in the console after a short delay, for almost all file types except PNG files for some odd reason.

**Comment by lovvtide** [comment]
@umbra-scientia Webtorrent just requires ^1.1.0 so what I ended up doing was explicitly requiring end-of-stream@1.4.1 my dependencies, and that solved the problem for me. Hope it helps

**Comment by belvederef** [comment]
> @umbra-scientia Webtorrent just requires ^1.1.0 so what I ended up doing was explicitly requiring end-of-stream@1.4.1 in my dependencies, and that solved the problem for me. Hope it helps

This workaround does not work anymore. Have a look at my solution here https://github.com/webtorrent/instant.io/issues/210#issuecomment-609687048

**Comment by DeltaF1** [comment]
@alxhotel @KayleePop This issue is blocking uploads on instant.io and has crippled usability for the past several months. Is there a way that this can be assigned some sort of higher priority label?

**Comment by belvederef** [comment]
@DeltaF1 I second that. This issue is driving people away from even considering the package. I almost gave up when I saw that the npm package did not work **and** neither did the online tool/example. I spent hours trying to debug the problem and I do not believe every user is ready to do that.

**Comment by KayleePop** [comment]
instant.io is working for me right now. can you try it again?

**Comment by DeltaF1** [comment]
I just tested again on FF 75. Still getting "premature close"

**Comment by belvederef** [comment]
@KayleePop no, it is not working. If I remember correctly it will work only with a few types of file. Try with a .webm or a .pdf for example, just tried those and they do not work.

**Comment by KayleePop** [comment]
yeah, works on my laptop but not my phone for some reason.

I don't have any control over instant.io, but [here's a version on glitch.com](https://webtorrent-instant-io-1.glitch.me/) that uses these PRs (that eliminate multistream as a dependency) https://github.com/webtorrent/create-torrent/pull/115, and https://github.com/webtorrent/webtorrent/pull/1832.

Nothing else is changed from the instant.io master branch except pulling those PRs from github for `webtorrent` and `create-torrent`

**Comment by belvederef** [comment]
I confirm that the same files that caused the error on instant.io are uploading just fine in the version you posted.

**Comment by codealchemist** [comment]
I'm using `webtorrent@0.108.6` and I also experienced this issue.
Just verified that the `npm i end-of-stream@1.4.1` workaround fixes it on the browser.

Thanks for reporting it @Evoks 🙌

**Comment by feross** [comment]
It seems as if this issue has been fixed in the latest version since we pinned to end-of-stream 1.4.1. Can this be closed now?

**Comment by Arman92** [comment]
I'm still getting `Filesharing [error:"Error: premature close` on latest version of webtorent (`0.110.1`) which is using end-of-stream `1.4.1`

**Comment by Arman92** [comment]
@feross As the issue persists still, please take a look at this PR #1832 which eliminates the need for buggy dependencies!
