### ISSUE TITLE
Use larger rage request for webseed.

### ISSUE THREAD

**Issue by ivan386** [webtorrent/webtorrent#1759]
Original discussion: [Use larger chunks for torrents](https://github.com/Chocobozzz/PeerTube/issues/1865)

**What version of this package are you using?**
Don't know.
**What problem do you want to solve?**
Many small requests to one server.
![](https://user-images.githubusercontent.com/11603778/58831045-bc1f8f00-8619-11e9-89fe-da45d23ba424.png)
**What do you think is the correct solution to this problem?**
http://bittorrent.org/beps/bep_0019.html

>    HTTP/FTP are "streaming" type protocols, and do not have BitTorrent's concept of blocks. For HTTP you can use byte-ranges to resume anywhere or download specific ranges you specify, but with FTP you can only say where to start the download.

>    I wanted to have many sequential blocks ("gaps") in the data downloaded from BitTorrent peers so a HTTP/FTP connection would have big spaces to fill in. You could use the byte-ranges with HTTP to request individual blocks--but each request will show in the server's logs, and somebody is going to think it is a denial of service attack on them if their shows 100's of connections in their log from the same IP.

**Are you willing to submit a pull request to implement this change?**
No

**Comment by jimmywarting** [comment]
Remember suggesting some streaming method with the fetch api  #1497 

might be relevant

**Comment by feross** [comment]
Duplicate of https://github.com/webtorrent/webtorrent/issues/1497
