### ISSUE TITLE
--mpv error: unexpected token `('

### ISSUE THREAD

**Issue by Jaegrqualm** [webtorrent/webtorrent#1760]
**What version of WebTorrent?**
0.107.16
**What operating system and Node.js version?**
node v12.11.1, linux x64
**What browser and version? (if using WebTorrent in the browser)**
qutebrowser 1.8.1
**What did you expect to happen?**
For the stream to open in MPV.
**What actually happened?**
from the log:
mpv --really-quiet --loop=no --ontop [localhost address with  () in it]
/bin/sh: -c: line 0: syntax error near unexpected token `('

This seems to be a case of poor input sanitization, that I *think* is on the part of webtorrent.

**Comment by feross** [comment]
Thanks for opening this issue. It was fixed in https://github.com/webtorrent/webtorrent-cli/pull/138 and released :)
