### ISSUE TITLE
👀 MediaSource Stream Possible?

### ISSUE THREAD

**Issue by Fenny** [webtorrent/webtorrent#1761]
Hi all,

Chromecast removed service workers in their latest updates and we cannot use [BrowserCast](https://github.com/johanholmerin/browsercast) anymore to cast torrent media ( from the browser )

The last hope is the "Media Source Extensions" ( MSE ) but this seems complicated and I couldn't figure out how to make it work with webtorrent.

Is it possible to use webtorrent to create an MediaSource [mse-demo](https://github.com/bitmovin/mse-demo/blob/master/index.html)?

I would like to hear your thoughts, Fenny

[Reference 897](https://github.com/webtorrent/webtorrent/issues/897)

**Comment by jimmywarting** [comment]
did chromecast remove service worker?! that's a bummer!

**Comment by Fenny** [comment]
I tried to look for any changelog or more information on the service worker matter but without luck.
@johanholmerin said that a recent update broke support for service workers [browsercast issues 2](https://github.com/johanholmerin/browsercast/issues/2).

With browsercast not working, I'm trying to extend my own sender library [ChromecastJS](https://github.com/Fenny/ChromecastJS) with an extra feature to stream the video tag instead to a custom receiver using the [.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream) function and [PeerJS library](https://peerjs.com/)

So far I might found an easy fallback to cast local files / filestreams to a chromecast.
![](https://i.imgur.com/dxMypoS.png)

```javascript
  // sender
  media = torrent.files.find(function (file) {
    return file.name.endsWith('.mp4')
  })
  media.renderTo('#video', (err, elem) => {
    stream = err.captureStream(24)
    peer.call(peerreceiver, stream);
  })
```
```javascript
  // chromecast receiver
  peer.on('call', function(call) {
    call.answer();
    call.on('stream', (stream) => {
      document.getElementById('video').srcObject = stream
      document.getElementById('video').play()
    })
  });
```

However, using a direct mp4 link works fine, but using the webtorrent file stream does not transfer the audio correctly to the receiver ( messed up audio ).
I think it has to do with the [Webtorrent Videostream module](https://github.com/jhiesey/videostream)

If you got any ideas, feel free to help *.*

**Comment by Fenny** [comment]
![](https://i.imgur.com/SLtsgjB.png)

It seems that Google has removed the ServiceWorker from the navigator object.
Why would they do this?

**Comment by jimmywarting** [comment]
😞 

should file a bug report

**Comment by Fenny** [comment]
serviceWorker is still in the navigator object but your app needs to run in a "secure context" ( localhost or https )

[https://github.com/google/shaka-player/issues/2205#issuecomment-544388022](https://github.com/google/shaka-player/issues/2205#issuecomment-544388022)

The chromecast still crashes when registering a serviceworker ( even if it's empty ) while the same code works on any browser.
