### ISSUE TITLE
Serve over torrent

### ISSUE THREAD

**Issue by tejt99** [webtorrent/webtorrent#1763]
Hi, I don't actually use this as I have only started learning js this week but I like looking around GitHub.

What you've done is brilliant and I'm not even sure what I'm about to suggest is possible but, could you, in theory, put a small amount of js in your website and have the rest of this repository load over torrent?

If this is stupid just say.
Thanks.

**Comment by Fenny** [comment]
Hi @tejt99 good to hear you started learning js, welcome!

I'm not sure what you mean with 

>  repository load over torrent

But you can load the whole webtorrent library on your website with cdnjs for example
```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/webtorrent/0.107.16/webtorrent.min.js"></script>
```

Or import it like this

```javascript
function Import(url) {
    return new Promise(resolve => {
      var e = document.createElement('script');
      e.src = url;
      e.type= 'text/javascript';
      e.addEventListener('load', resolve);
      document.getElementsByTagName('head')[0].appendChild(e);
    })
  }

Import('https://cdnjs.cloudflare.com/ajax/libs/webtorrent/0.107.16/webtorrent.min.js').then(() => {
  // Webtorrent is ready!
})

```

**Comment by tejt99** [comment]
What I mean is: host webtorrent.min.js and the associated files on a torrent, and load it with a small bit of js in the website.

**Comment by tejt99** [comment]
I believe it would be possible as when using instant.io, if your torrent contains a pdf or similar, it gives a preview before you download so clearly it is being cached somewhere.
