### ISSUE TITLE
node-Tor is now open source, in clear and modular

### ISSUE THREAD

**Issue by Ayms** [webtorrent/webtorrent#1767]
FYI (https://github.com/Ayms/node-Tor) in case you want one day to integrate the Tor protocol inside webtorrent for anonymous sharing between peers

Maybe of some interest also is the way the [demo app](http://peersm.com/peersm2) for node-Tor (previously [Peersm](http://www.peersm.com) app) stores the blobs in chunks, it's in clear too but I have removed the video streaming parts (but they can be seen too in the removed dir)

**Comment by Ayms** [comment]
In fact I am not thinking to Snowflake only but implement full WebRTC so the browser can act also as the Onion router (this is already in the code but needs modifications inside browsers), so doing the Onion Proxy vai WebRTC as the client and performing the Onion Router via WebRTC as the server (ie not just relaying messages as the Snowflake WebRTC proxy is doing)

At the same time we can think of implementing WebRTC in nodejs, @feross are you aware of js implementation of WebRTC in node (ie without external binaries) and/or DTLS? I don't see anything convincing up to now

**Comment by Ayms** [comment]
The finality is duplex streams like webtorrent.pipe(node-Tor) or bitcoin.pipe(node-Tor) or <whatever protocol>.pipe(node-Tor), where the transport is TCP, WS, WebRTC

As an example, currently doing http.pipe(node-Tor) (already working but not the pipe way) and then https: http.tls.pipe(node-Tor), can't use xhr of course to pipe to the Tor protocol circuits so browserify cant' help here, neither nodejs

**Comment by Ayms** [comment]
See the more global concept here: https://github.com/Ayms/node-Tor#forking-node-tor

**Comment by Ayms** [comment]
And now the implementation and detailed docs : https://github.com/Ayms/node-Tor/tree/master/docs

So you can easily turn webtorrent or any object to a [Duplex object](https://github.com/Ayms/node-Tor/tree/master/docs#the-duplex-object-and-evented-pipes) giving to it the evented pipe properties (see the simple typical setting example) and pipe it to the Tor protocol :

``webtorrent.pipe(node_Tor)``

Inside browsers or not, using a RendezVous point or peer to peer, both via onion circuits between webtorrent peers

Once WebRTC is implemented for browsers (working right now for the desktop clients), this might be part of the next steps las well as elliptic crypto

**Comment by feross** [comment]
Thanks for this issue but since this is not a WebTorrent issue, I'm closing it,

**Comment by Ayms** [comment]
Maybe you should leave it open as an enhancement or future feature, this is of some interest I think and part of a more global project [Convergence](http://www.peersm.com/Convergence-2020.pdf), webtorrent could be plugged to node-Tor (and sustain the anonymizer browser/desktop/server nodes), see for example the discussions:

bitcoin ``https://github.com/bitcoin/bitcoin/pull/18988#issuecomment-646348599``
IPFS ``https://github.com/ipfs/ipfs/issues/439#issuecomment-593116241``
