### ISSUE TITLE
How to use the torrent file which generated by utorrent

### ISSUE THREAD

**Issue by tiger2014** [webtorrent/webtorrent#1768]
**What version of this package are you using?**

**What problem do you want to solve?**

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

**Comment by meotimdihia** [comment]
> To make BitTorrent work over WebRTC (which is the only P2P transport that works on the web) we made some protocol changes. Therefore, a browser-based WebTorrent client or "web peer" can only connect to other clients that support WebTorrent/WebRTC.
> 
> To seed files to web peers, use a client that supports WebTorrent, e.g. WebTorrent Desktop, a desktop client with a familiar UI that can connect to web peers, webtorrent-hybrid, a command line program, or Instant.io, a website. Established torrent clients like Vuze have already added WebTorrent support so they can connect to both normal and web peers. We hope other clients will follow.
> 
>
