### ISSUE TITLE
FAQ Markdown is broken

### ISSUE THREAD

**Issue by DeltaF1** [webtorrent/webtorrent#1771]
**What operating system, Node.js, and npm version?**
Firefox 70, windows 10
**What happened?**
The list of URLS in the "Who is using WebTorrent today?" is showing its markdown without parsing it after the link to GitTorrent
**Are you willing to submit a pull request to fix this bug?**
Yep! See #1772

**Comment by DeltaF1** [comment]
# Visual description
![image](https://user-images.githubusercontent.com/6278108/67747658-a1eab100-f9ff-11e9-9c09-b1a86f2cfd90.png)

**Comment by passstab** [comment]
The document is inconsistent about "–" vs "-".

**Comment by DeltaF1** [comment]
I think the short dashes are for the markdown list syntax but the long
dashes are for the actual content of the list.

**Comment by feross** [comment]
This was fixed by an unrelated PR in https://github.com/webtorrent/webtorrent/pull/1772 to move the HTML comments to the bottom of the list. For some reason, the HTML comments mid-list were confusing the markdown renderer.

I just redeployed the site.

**Comment by passstab** [comment]
Thank you, much better.
BTW The markdown list syntax is all short dashes, but the content of the list is inconsistent.
Compare "webtorrent desktop" to "instant.io"

**Comment by DeltaF1** [comment]
That's my PR as well, I just created this issue because the PR template asks for an issue that it solves

**Comment by DeltaF1** [comment]
@passstab Good catch! You should open a PR to fix that inconsistency
