### ISSUE TITLE
Web Stream Issue

### ISSUE THREAD

**Issue by NDusan88** [webtorrent/webtorrent#1778]
**What version of this package are you using?** latest

**What operating system, Node.js, and npm version?**None i code from C#  .net Core

**What happened?**

 var torrentid = "magnet:?xt=urn:btih:7BE41ED6B348A4EB3DE98DD1E130740C2065FDF4&tr=http%3a%2f%2ftrack.one%3a1234%2fannounce&tr=udp%3a%2f%2ftrack.two%3a80&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2fglotorrents.pw%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftorrent.gresille.org%3a80%2fannounce&tr=udp%3a%2f%2fp4p.arenabg.com%3a1337&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969S"

The issue is when i put magnet link nothing happens and when i use the magnet link that you provide on FAQ, it start stream the video.

Also i have tried the same magnet link above on desktop software and it working like a charm.
Can some one help me out to figure this out?
Thanks
![Capture](https://user-images.githubusercontent.com/20918713/68429695-e0762d80-01ae-11ea-9a91-c2ff2d458920.PNG)

**What did you expect to happen?**Stream Movie

**Are you willing to submit a pull request to fix this bug?**No

**Comment by KayleePop** [comment]
From the FAQ here https://webtorrent.io/faq

> ## Why does browser downloading not work? I see no peers!
> It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. WebTorrent Desktop, Vuze, webtorrent-hybrid, Playback, instant.io, or βTorrent.
> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.

The Sintel torrent has plenty of webtorrent compatible seeders and it also has an http webseed and torrent file source (`&ws=https://webtorrent.io/torrents/&xs=https://webtorrent.io/torrents/sintel.torrent`), which means it can be downloaded even without any seeders or peers to get metadata from.

Your torrent will work in the browser if you seed it from the desktop client.
