### ISSUE TITLE
a APP for Nextcloud

### ISSUE THREAD

**Issue by blackcrack** [webtorrent/webtorrent#1779]
A Application for Nextcloud or Owncloud

**What problem do you want to solve?**
Torrent downloading behind a cloud

**What do you think is the correct solution to this problem?**
there exist not a good torrent downloader for Nextcloud

this could also use to stream a Movy like in the Headpage
of webtorrent, via link moviename.wto or download name.torrent to the downloadfolder of ocdownloader what already exist and can work together with webtorrent as Cloud-app.
create a "webtorrent"-folder and push the torrentfiles in this folder where be automagically download the torrentpacks between a time "from"-"up to" and if not works moves the *torrent-file into subfolder "deactivate" or "damaged" or something.. or something..
how ever, i have give you are the idea :) could be a cool possible to have some cloudapp :) :+1: 

best regards
Blacky

**Comment by beppe9000** [comment]
> **What problem do you want to solve?**
> Torrent downloading behind a cloud

Isn't *cloud written in php? I don't think it plays well with js. Plus if the torrenting happens in the browser with WebTorrent lib then you are not torrenting behind the cloud, unless you are only torrenting with the cloud, but it's still torrenting.

**Comment by blackcrack** [comment]
> *cloud is written in php.  I don't think it plays well with js.
and ?? sorry, you have no clue..
it's maybe better to let decide the members if they want something to build or not...
and js is supported in in Webapplications ..

You don't even know what's behind this "webtorrent", so, 
let it stick... a german expression for don't speak so an junk.. 

let decide it the members of this project..
or some who want make this ..

best regards
Blacky

**Comment by beppe9000** [comment]
most reasonable way to do this:

 - convince [voltage](https://github.com/krisives/voltage) developers to make *cloud app or find someone who will do it
 - use webtorrent for the web player as I described above

**Comment by blackcrack** [comment]
1. you don't know Nextcloud or do not admin by self OwnCloud / Nextcloud ( because you should know something about an downloader )
2. (oh he have looking on the Homepage) exactly the Playing of Video and Sound is exactly this what makes specially ! Therewith it is possible to have a player directly out from a torrent way ..
and it self as a downloader in a own webdownloadfolder inside of Next/OwnCloud

so, make you're self not important and try to bring in a blabla without an clue ..

@feross , It is maybe possible to make a App for NC/OC ( maybe WebTorrentApp )
where all supports around Torrent wheres put&store the loaded files in a own folder by caching
and opening .. and so on..

**Comment by beppe9000** [comment]
This could be another example on how to get that functionality.

It looks like [swizzin](https://github.com/liaralabs/swizzin) does support nextcloud [to some extent](https://github.com/liaralabs/swizzin/blob/master/scripts/install/nextcloud.sh). Once that is done it is a matter of passing the torrent magnet link to a self-hosted mirror of http://instant.io .

So all the app needs to do is to:
 - have swizzin
 - host a static copy of player page with some js addition like preloading the server ip in the peers
 - add a play button for media files in swizzin directory that links to
      `//your.server/player.html#torrent-hash`



<hr>

> so, make you're self not important and try to bring in a blabla without an clue ..

dude you are not constructive by rejecting discussion. do that rather than talk in riddles
