### ISSUE TITLE
webtorrent does not seed

### ISSUE THREAD

**Issue by Mapteg34** [webtorrent/webtorrent#1784]
**What version of this package are you using?**
**What operating system, Node.js, and npm version?**

```
mapt@mpc webtorrent.malahov-artem.ru % npm list webtorrent
webtorrent.malahov-artem.ru@1.0.0 /var/www/webtorrent.malahov-artem.ru
├── webtorrent@0.107.16 
└─┬ webtorrent-hybrid@4.0.1
  ├── webtorrent@0.107.16  deduped
  └─┬ webtorrent-cli@3.0.5
    └── webtorrent@0.107.16  deduped
mapt@mpc webtorrent.malahov-artem.ru % node -v 
v10.1.0
mapt@mpc webtorrent.malahov-artem.ru % npm -v
5.6.0
mapt@mpc webtorrent.malahov-artem.ru % uname -a
Linux mpc 4.19.82-gentoo #1 SMP Mon Nov 11 10:04:32 +04 2019 x86_64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz GenuineIntel GNU/Linux
```

**What happened?**

```
mapt@mpc webtorrent.malahov-artem.ru % node seed.js
client.seed done { magnetURI: 'magnet:?xt=urn:btih:683999ae98d858dc4b1712457442dcdceafe76e5&dn=test.mp4&tr=http%3A%2F%2F192.168.1.44%3A8000%2Fannounce',
  ready: true,
  paused: false,
  done: true }
```

After magnet created in parallel window i use
```
mapt@mpc webtorrent.malahov-artem.ru % node download.js "magnet:?xt=urn:btih:683999ae98d858dc4b1712457442dcdceafe76e5&dn=test.mp4&tr=http%3A%2F%2F192.168.1.44%3A8000%2Fannounce"
client.seed done { magnetURI: 'magnet:?xt=urn:btih:683999ae98d858dc4b1712457442dcdceafe76e5&dn=test.mp4&tr=http%3A%2F%2F192.168.1.44%3A8000%2Fannounce',
  ready: true,
  paused: false,
  done: false }
```

And i expect a downloaded test.mp4 in ./ folder, but its not dowloaded...

**What did you expect to happen?**

Download file by webtorrent, who was seeding by webtorrent

** Files **
seed.js https://pastebin.com/uuHCQyzC
download.js https://pastebin.com/wVU444gH
I use bittorrent-tracker as a tracker
https://pastebin.com/Z6rEdRKf

**Comment by mayeaux** [comment]
Did you ever get this to work? running into the same thing

**Comment by Mapteg34** [comment]
> Did you ever get this to work? running into the same thing

No, I didn't

**Comment by mayeaux** [comment]
Here's my issue: https://github.com/webtorrent/webtorrent/issues/1812

Virtually identical.

**Comment by therealadityashankar** [comment]
could you run seed.js (by modifying the code a bit) in the browser and see if it works, this worked for me.

**Comment by therealadityashankar** [comment]
I know this is not a proper solution, but it nails down the problem to node

**Comment by therealadityashankar** [comment]
ok, so here's the issue, require("webtorrent") in node does not seed to WebRTC (which the browser uses), you've to do require("webtorrent-hybrid"), see https://github.com/webtorrent/webtorrent-hybrid ,
anyway, I didn't check with your code, but this fixed my issue,

hope this helps !

**Comment by mayeaux** [comment]
Was this actually fixed?

**Comment by therealadityashankar** [comment]
@mayeaux the code was wrong, the "webtorrent" package cannot run webrtc seeds in node you need the "webtorrent-hybrid" package to do that, these is no fix

**Comment by alxhotel** [comment]
@Mapteg34 the code you provided seems alright. I just tested this example and it works.

So closing this for now, but feel free to reopen if you have more details to debug this issue.
