### ISSUE TITLE
Seed ratio

### ISSUE THREAD

**Issue by stanislasdrg** [webtorrent/webtorrent#1785]
Hello,
I love using Webtorrent as a client, but there is a feature I miss a lot from Transmission : The seed ratio.
I would love being able to stop seeding torrents when I have shared them 2x or more.
Is this a feature that would be possible to implement in Webtorrent ?

Many thanks,

S

**Comment by alxhotel** [comment]
Thanks for the suggestion @stanislasdrg!

IMHO I don't think this should be a feature of Webtorrent.

However, the "maintain seed ratio" can be implemented as a wrapper by starting and stopping the seeding of torrents. In practice, I guess you would require a database to save your current ratio.

**Comment by stanislasdrg** [comment]
>IMHO I don't think this should be a feature of Webtorrent.
My problem is that the list of torrents grows very big over time and I have no way of knowing how much I have shared them before removing files. I also have limited space on my laptop and cannot afford to store 1Tb data locally.
I can ofc delete files, but then it is poor p2p ethos.
