### ISSUE TITLE
WebTorrent WordPress Plugin Doesn't Work

### ISSUE THREAD

**Issue by mucittin** [webtorrent/webtorrent#1789]
I am using WordPress verison 5.3 and I think that plugin needs to be updated.

![image](https://user-images.githubusercontent.com/43407836/70555217-4a576d80-1b87-11ea-9edb-e1c0ea006a68.png)

**Comment by rukenantoni** [comment]
+1

**Comment by feross** [comment]
This is a third-party plugin. I suggest contacting the plugin author: https://wordpress.org/plugins/webtorrent
