### ISSUE TITLE
Edit announce list while downloading

### ISSUE THREAD

**Issue by WheelyWonka** [webtorrent/webtorrent#1790]
Hi there, thank you for you amazing work !

I'm building a small nodejs client and i'd like to edit the announce list of a torrent while it's downloading. 

I'm guessing, for example, a simple `delete torrent.announce` or  `torrent.announce = []` inside the callback of `client.add` but i'm not sure it will be taken in count by the client. 

Any advice folks ? Thanks a lot !

**Comment by feross** [comment]
Posting for posterity's sake. Currently, editing the announce list after the torrent has been added is not a supported feature.

**Comment by WheelyWonka** [comment]
Thanks for replying, any chance to show me the way to a workaround ? Thank you !
