### ISSUE TITLE
client.seed callback not called when tab is not focused.

### ISSUE THREAD

**Issue by LucCADORET** [webtorrent/webtorrent#1796]
Hi, I am using the WebTorrent Browser version in an Angular app.

From a web-torrent.service.ts, I have a function
```
  startTorrent(callback: any) {
    this.client = new WebTorrent();
    this.client.seed(this._filesToSeed, (torrent) => {
      this._magnet = torrent.magnetURI;
      callback(torrent)
    });
  }
```

This function is called from a component, simply like that:

`this.webTorrentService.startTorrent(onTorrent)`

It turns out that my callback 'onTorrent' is never triggered when the browser tab is not in focus. It will be triggered only when the tab gets the focus again. Is it a normal behavior ?

The issue appears in both firefox and chrome.

I couldn't build a gist to reproduce the error, since there's an error with the client.seed method when you use webtorrent.min.js as-is.

**Comment by feross** [comment]
This may be because the browser is throttling timers in background tabs. I'm not sure what we can do about this.
