### ISSUE TITLE
how to catch the Uncaught Error: Invalid torrent identifier

### ISSUE THREAD

**Issue by hackedbyxx** [webtorrent/webtorrent#1809]
i've tried  
client.on('error', function (err) {
	console.error(err);
 });
torrent.on('error', function (err) {
	console.error(err);
 });
but it does not work,hou can i catch this error?thanks

**Comment by feross** [comment]
This error is a thrown exception because you're calling `torrent.add` with a known bad input. Add a try-catch around your call to `torrent.add`.
