### ISSUE TITLE
We've safely aborted connection on tracker.btorrent.xyz because it was infected with URL:blacklist

### ISSUE THREAD

**Issue by Tom12121212** [webtorrent/webtorrent#1810]
When I visit https://webtorrent.io/   I get the error message in AVG anti virus free

"We've safely aborted connection on tracker.btorrent.xyz because it was infected with URL:blacklist"

Will this same error appear if I use the code on my site? Will send my users into a panic.

Anyone out there got a work around. 

Many thanks in advance.

**Comment by jimmywarting** [comment]
if it did work before just recently then maybe i might have had some part in it... (trying to make it more secure) 
https://github.com/OpenWebTorrent/openwebtorrent-www/issues/11

**Comment by vrboy** [comment]
Thanks Jimmy for getting back to me so quickly. Today was the first day I visited your site so not sure if was good before.  

Hope this helps. I just ran another test can getting same AVG error when I visit this page as well that uses webtorrent https://fastcast.nz/videos/awakening-new-zealand-4k.html

No error on my other machine that only has windows firewall. Works a treat!!

Im interested in getting a commercial license if possible.  I have no money right now, but soon as we start making money from it I would like to pay you guys for the great work.

Good luck playing whack a mole  ;O)

**Comment by vrboy** [comment]
More intel !!
I dont get the error when I browse this version of webtorrent
https://demo.cdnbye.com/?url=https%3A%2F%2F1257070836.vod2.myqcloud.com%2F0cf6732evodtransgzp1257070836%2F81fe3a525285890782510564774%2Fv.f220.m3u8

**Comment by dheeraj-rn** [comment]
Seems like domains [tracker.btorrent.xyz](https://www.virustotal.com/gui/url/3c8f1ba37136ae1668c6ce3525930d787b41b5f18aaa4332d7446b809a946693/detection) and [btorrent.xyz](https://www.virustotal.com/gui/url/50b1305fba59ee20f7d1a60d74c50d9da8bfef87a7888dc81a82abb576c618f8/detection) are detected as malicious by few antivirus software.

**Comment by alxhotel** [comment]
> "We've safely aborted connection on tracker.btorrent.xyz because it was infected with URL:blacklist"

I think the domain `tracker.btorrent.xyz` might be blocked because some AVG user decided to block it and it might have spread to other AVG users? Don't really know where they get that "blocklist" :/

> https://demo.cdnbye.com/?url=https%3A%2F%2F1257070836.vod2.myqcloud.com%2F0cf6732evodtransgzp1257070836%2F81fe3a525285890782510564774%2Fv.f220.m3u8

This site does not seem to use the Webtorrent library. But it looks like another type of P2P technology with Webrtc, and with different trackers.

**Comment by vrboy** [comment]
Thanks for the reply.  Draeder gave me a great reply here
https://github.com/chr15m/bugout/issues/16

This was the questions I asked on that thread in response if anyone has any good ideas. 

Sorry for a newb question. Just learning P2P code

Many many thanks for finding that link for me Draeder. I'm not an advanced coder and new to P2P code.  Two quick questions please. 
1. Do you recommend using another tracker. I am not sure which one to use?
2. It seems I need to alter the index.js file from looking above. Is that a file I download edit then upload to my server and put the index.js into the route next to index.html? 

If you can suggest how to alter it would be much appreciated.

This is the part I have to edit only I presume?
  this.announce = opts.announce || ["wss://hub.bugout.link", "wss://tracker.openwebtorrent.com", "wss://tracker.btorrent.xyz"];
  this.wt = opts.wt || new WebTorrent({tracker: trackeropts});

I am trying to become a commercial customer if I can get this working.  Happy to pay for a fix if needed. 

Many many thanks in advance

**Comment by tutugreen** [comment]
just had a quick view.

CDNBye is a commercial project and seems only support m3u8/hls steam/vod.
If you use their tracker, you need to [pay by the traffic](http://docs.cdnbye.com/#/en/FAQ?id=is-it-a-must-to-pay-for-p2p-services-of-cdnbye) (when exceeding 20GB/day).

Webtorrent supports whatever format as browser support in <video> tag. You can use the built-in tracker with no fee at all, or build your own.

I think Weborrent is better for learning/start.

If you just want to pay, CDNBye provides commercial Technical Support.

If you want to start with Webtorrent, you can simply copy the code from [HTML example with status showing UI](https://webtorrent.io/intro) to an HTML file, and replace the torrentId to your own torrent.
