### ISSUE TITLE
Get started example is broken, points towards broken link

### ISSUE THREAD

**Issue by mayeaux** [webtorrent/webtorrent#1813]
https://github.com/webtorrent/webtorrent/blob/master/docs/get-started.md#creating-a-new-torrent-and-seed-it-in-the-browser

This fails because the minified JS file 404s. ( https://raw.githubusercontent.com/feross/drag-drop/master/dragdrop.min.js )

Even when I manually fix it it still errors: `Uncaught DOMException: A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs.`

**Comment by brendena** [comment]
Are you opening up the html file just in the browser or are you severing it from a nodejs server. 

When i was just opening the file, it cause permission problems.  

```c++
        // This catches permission errors with file:// in Chrome. This should never
        // throw in production code, so the user does not need to use try-catch.
        if (err) throw err
```

**Comment by alxhotel** [comment]
Hi @mayeaux,

Thanks for the feedback! I have created a PR to fix that 404 issue.

Regarding the `DOMException`, I'm not sure where the error is coming from. Can you give more details of the error stack? Also, check out this codepen  (https://codepen.io/alxhotel/pen/WVaKeo) and let me know if it works with your file.

**Comment by mayeaux** [comment]
That one seems to work for me. Maybe I'll revisit this

**Comment by alxhotel** [comment]
Closing this issue. But feel free to reopen if needed.
