### ISSUE TITLE
Adding WebSeed for Multifile torrent and SingleFile Torrent

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#1821]
**What version of this package are you using?**
0.107.13
**What operating system, Node.js, and npm version?**
Windows, Browser

**Are you willing to submit a pull request to fix this bug?**
No

Adding webseed still needs fix, when a torrent is multi-file, the webseed will only work if I give the parent path where the torrent folder exist so the webseed work, with single file torrents even those with folders, the webseed needs to be the mp4 file absolute path.
I guess we have to expect similar behavior with different torrents.
Please if you wanted to fix this, check both methods when looking for file because this may affect many sites using webtorrent

**Comment by Clodo76** [comment]
Hi, i write the same issue here: https://github.com/webtorrent/webtorrent/issues/1848

**Comment by feross** [comment]
Unfortunately, this inconsistency is part of how web seeds are specified. You can read the BEP here: https://www.bittorrent.org/beps/bep_0019.html
