### ISSUE TITLE
Add option to use only TCP, UDP or webRTC protocol

### ISSUE THREAD

**Issue by hoppingninja666** [webtorrent/webtorrent#1824]
**What version of this package are you using?**
0.107.17

**What problem do you want to solve?**
I want to have an option to choose only use TCP/UDP based communication.
**What do you think is the correct solution to this problem?**
The solution is to expose a commandline and option key value system to only use TCP/UDP for communication.
**Are you willing to submit a pull request to implement this change?**
No plan at this moment.

**Comment by ultimate-tester** [comment]
Hi there, just for clarification, is the webtorrent package not already doing that for you?

**webtorrent:** uses only TCP and UDP protocols
**webtorrent-hybrid:** uses TCP, UDP and WebRTC

**Comment by PaTiToMaSteR** [comment]
webtorrent doesn't use WebRTC?

The main page: WebTorrent is written completely in JavaScript – the language of the web – and uses WebRTC for peer-to-peer transport whenever possible

**Comment by ultimate-tester** [comment]
It's a little contradicting, yes, but the webtorrent package does not use WebRTC.
This is, of course, assuming you're running it in node and not the browser.

**Browser version:** uses WebRTC
**Node version:** uses TCP + UDP
**Hybrid version:** Combines WebRTC + TCP + UDP together, hence a hybrid

It's quite strange, but it is what it is :)

**Comment by hoppingninja666** [comment]
How do I limit the node version to use TCP only or UDP only?

**Comment by ultimate-tester** [comment]
Currently it's not possible to specify whether to use TCP or UDP only.
I was actually looking in the source to see how easy this would be to implement, but cannot even find the code where it connects over UDP. This makes me doubt how this is currently achieved. The peer soure code only contains TCP and WebRTC...

If anyone can tell me where to look for the UDP part, I will make a PR for this option.

**Comment by feross** [comment]
WebTorrent detects the capabilities of the environment it's running in and uses as many connection types as it can:

- Browser: WebRTC
- Node: uses TCP, uTP (UDP)
- Electron or `webtorrent-hybrid`: WebRTC, TCP, uTP (UDP)

We just shipped uTP support behind a flag. You can set `utp: true` or `utp: false` to control it. For WebRTC, you can use `wrtc: false` to disable WebRTC, even if the environment supports it.

**Comment by hoppingninja666** [comment]
> WebTorrent detects the capabilities of the environment it's running in and uses as many connection types as it can:
> 
>     * Browser: WebRTC
> 
>     * Node: uses TCP, uTP (UDP)
> 
>     * Electron or `webtorrent-hybrid`: WebRTC, TCP, uTP (UDP)
> 
> 
> We just shipped uTP support behind a flag. You can set `utp: true` or `utp: false` to control it. For WebRTC, you can use `wrtc: false` to disable WebRTC, even if the environment supports it.

I see the uTP support in the change logs. I thank you and the contributors. Is there a feature to use only one protocol for transmission. For example, only using uTP but no TCP?

**Comment by feross** [comment]
We don't currently have a flag to control whether `tcp` is used. Since we have flags for `utp` and `wrtc`, it seems reasonable to ask for a `tcp` flag. If you'd like to open a new issue requesting this feature, we can discuss this possibility there.
