### ISSUE TITLE
The download does not always start.

### ISSUE THREAD

**Issue by wazazuzu** [webtorrent/webtorrent#1825]
**What version of this package are you using?**
Version 0.21.0 (0.107.16) (64-bit)

**What operating system, Node.js, and npm version?**
Windows 10 x64 1909, Node.js 12.8.1, and npm 6.10.2

**What happened?**
Sometimes, when adding a torrent to the download list, the torrent is added but does not start the download. I am forced to uncheck and check the torrent checkbox several times until the download begins. The problem also occurs when resuming a partially downloaded torrent, WebTorrent will check the parts of the file already present then do nothing more instead of starting to download the missing parts of the torrent.

I often add a torrent to the download while I watch another and realize at the end of the episode, that the one that was supposed to download in the background, had not started the download and remained at 0%.
![2020-04-02_21-54-23](https://user-images.githubusercontent.com/63072933/78295814-010f9d00-752d-11ea-92e9-cde1c751dc24.gif)

**What did you expect to happen?**
Let the download start when adding the torrent without having to restart the download manually several times.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by ultimate-tester** [comment]
I think I also experienced this bug quite a few times. I use webtorrent mainly with magnet links, and I see the download getting stuck on "Initializing..." forever while I know that there's plenty of seeders on that magnet. I wonder if this is caused by the same.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
