### ISSUE TITLE
Interact with libtorrent-based clients using localhost websockets

### ISSUE THREAD

**Issue by SoniEx2** [webtorrent/webtorrent#1826]
**What version of this package are you using?**
git master

**What problem do you want to solve?**
Running webtorrent from the browser prevents it from accessing the native bittorrent network. I think this can be solved, and is easier than one might think, but a few caveats need to be kept in mind.

**What do you think is the correct solution to this problem?**
Local websockets from webtorrent to a native torrent client. The protocol would allow webtorrent to queue up a torrent, and then the native torrent client would share pieces with webtorrent, and ask for pieces it doesn't have. The torrent client would never store the pieces, as it's only acting as a proxy. Instead, it's the job of webtorrent to store the pieces, if it chooses to do so. That is, the torrent client should treat webtorrent as a storage backend. The torrent client may choose to cache pieces from webtorrent, but webtorrent shouldn't have to care about that. The protocol must not allow arbitrary connections, as that is a massive security vulnerability.

Further: There are sandboxed systems with websocket but no WebRTC (or incoming/UDP connections at all) out there, and this would benefit them, too.

**Are you willing to submit a pull request to implement this change?**
No. I don't do javascript. I'm more interested in figuring out what the protocol needs to look like so I can integrate it into a native torrent client.

**Comment by feross** [comment]
I don't think native clients will support a protocol where any web client can make them act a proxy and download arbitrary content. This isn't a design that we want to support.

**Comment by SoniEx2** [comment]
... arbitrary TORRENTS.

which websites could just... download directly if they wanted.

there isn't a security risk here. it'll just mean a standardized API for both native and web-based apps to use for communicating with torrent clients. also like ACAO etc are a thing so they could even make it so websites have to ask permission first.

**Comment by feross** [comment]
We don't want a design where a native client can be asked by a web client to download arbitrary torrents. That introduces liability for the user of the native client and I don't think it's desirable. The current design where a native client shares what it's already seeding with web clients is what we want.

**Comment by SoniEx2** [comment]
it wouldn't download them into the downloads folder, just into RAM. specifically, into the browser's/page's RAM. it'd just do the bridging across the webtorrent and bittorrent networks.
