### ISSUE TITLE
Searching for webtorrents

### ISSUE THREAD

**Issue by 34r7h** [webtorrent/webtorrent#1827]
I'm using webtorrent in the browser. I set up torrent-search-api on a cloud function which returns a list of hits from a few torrent providers to the browser, along with magnet links. However, it seems the providers are giving conventional links, not webtorrents.

How can I search for files that are available in webtorrent format?

**Comment by thanhdinh98** [comment]
Because webtorrent on browser just accept seeding from webrtc peer, you need to put the ws trackers into the magnet link. Search for some ws trackers on google and insert it to the end of the link, you will get the result. Hope this helpful

**Comment by 34r7h** [comment]
Thank you Thanh
