### ISSUE TITLE
The beauty of SodaPlayer

### ISSUE THREAD

**Issue by Kurdistann** [webtorrent/webtorrent#1831]
Hey

I have tried SodaPlayer and I think it is so nice and good. But I have read on the web that they steal files from one's computer. They haven't updated their program in a long time, nor do they respond to mail. Maybe the developer is dead or something like that. But such a program I think it deserves to be known to the world.

What I hope and please ask you to have a look at their website and try out their program and get some ideas for it. for example:

1.Integrated blazing fast SOCKS5 proxy
2.Automatically get matching subtitles in your language
3. Their design.
4. A browser extension

Website:
https://www.sodaplayer.com

Chrome extension link:
https://chrome.google.com/webstore/detail/open-with-soda-player/kmnjlbjnflmpgeebeecocdipkdfcepah

With best regards

**Comment by XayOn** [comment]
That has nothing to do with webtorrent, and looks a lot like spam
That's a conventional torrent client.

**Comment by ultimate-tester** [comment]
This ticket should be closed.

**Comment by alxhotel** [comment]
Yep, sorry @Kurdistann. This content doesn't seem to be related to Webtorrent.
