### ISSUE TITLE
Issue with re-adding previously removed torrents

### ISSUE THREAD

**Issue by parthsaxena** [webtorrent/webtorrent#1842]
**What version of this package are you using?**
`0.108.1`

**What operating system, Node.js, and npm version?**
MacOS Catalina
Node.js `v12.14.0`
npm `v6.14.4`

**What happened?**
When re-adding a torrent that was previously added then subsequently removed, I encounter an error when creating a readable stream to the file in the torrent (which is the same file that was previously being streamed):

```
TypeError: Cannot read property 'pieceLength' of null
    at new FileStream (/Users/parthsaxena/Work/Projects/Magnet/backend/node_modules/webtorrent/lib/file-stream.js:24:39)
    at File.createReadStream (/Users/parthsaxena/Work/Projects/Magnet/backend/node_modules/webtorrent/lib/file.js:90:24)
    at /Users/parthsaxena/Work/Projects/Magnet/backend/main.js:986:44
```
The error is traced back to when I attempt to create a readable stream to the file after getting the torrent from the client:
```
client.add(magnet, {path: path.join(getAppDataPath(), "streams")}, function ontorrent(torrent) {
     // ... create var selected_file to reference file that user requested
    app.get(url, function(request, response) {
        // ... get range user requested; error traces to line below 
       let stream = selected_file.createReadStream(stream_position);
       stream.pipe(response); 
    });
});
```
It's important to note that this issue only occurs when a client adds a torrent, removes a torrent, then adds it again. Note that I am using `client.remove` to remove the torrent. We also tried using the `ready` listener opposed to using `ontorrent`, but it did not solve the issue.

If I try to print out `selected_file` after re-adding the torrent, it seems that the `File` object is not being "re-created" after re-adding the torrent, but rather refers to the previously destroyed file: 
```
File {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _torrent: null,
  _destroyed: true,
  name: '...',
  path: '...',
  length: 2060345341,
  offset: 0,
  done: false,
  _startPiece: 0,
  _endPiece: 3929,
  ext: 'mp4'
}
```

**What did you expect to happen?**
I expected the client to add the torrent as usual and the readable stream to function as expected.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by parthsaxena** [comment]
Haven't heard anything from the devs... I have implemented a workaround in the meanwhile, but it would be nice to get a response regarding this issue.

**Comment by ultimate-tester** [comment]
I can see to create a PR for this, since it sounds like a valid bug.
Meanwhile, you might want to remove the evidence of downloading illegal torrents and the advertisement for the source of it..
