### ISSUE TITLE
More elaborate docs

### ISSUE THREAD

**Issue by therealadityashankar** [webtorrent/webtorrent#1846]
In the first few pages of https://webtorrent.io/ , in its get started page and other pages too, there is no mention of webtorrent-hybrid, and the fact that node's require('webtorrent') does not support WebRTC, and this must be done via require("webtorrent-hybrid"), it's there in the github page, but I kinda ignored it, and it took me about an hour to realise I need to use "webtorrent-hybrid",

anyway, an easy mention of "seeding a torrent in node will require 'webtorrent-hybrid'" to be accessible by web", should greatly help future users,

related issues:
https://github.com/webtorrent/webtorrent/issues/1784 is another user who I think had the same problem

**Comment by therealadityashankar** [comment]
another improvement would be https://github.com/webtorrent/webtorrent/issues/371 (Does webtorrent "auto-seed" torrents after add?) to the docs, could not find this specified anywhere

**Comment by ultimate-tester** [comment]
Thanks for the feedback, please provide a pull request to get where you want to go :)

**Comment by therealadityashankar** [comment]
added the pull request in https://github.com/webtorrent/webtorrent/pull/1851
