### ISSUE TITLE
Webseed - single-file vs multi-file

### ISSUE THREAD

**Issue by Clodo76** [webtorrent/webtorrent#1848]
**What version of this package are you using?**
The latest .min.js

**What problem do you want to solve?**
I made a folder

```
Test
> file1.txt
> file2.txt
```

I generate a "single.torrent" with file1.txt, and a "multi.torrent" with "Test" folder (two files).

Hosted here:
https://search-id.org/testwebseed/single.torrent
https://search-id.org/testwebseed/multi.torrent
https://search-id.org/testwebseed/test/file1.txt
https://search-id.org/testwebseed/test/file2.txt

This works (try in instant.io):
`magnet:?xt=urn:btih:2fecd2f5ee55d8f8e4220f85986fa02da2c870da&dn=file1.txt&xs=https://search-id.org/testwebseed/single.torrent&ws=https://search-id.org/testwebseed/test/file1.txt`
This works (try in instant.io):
`magnet:?xt=urn:btih:c2b12fc7fc97f9ff5a7dfb292ed0dea0dc125844&dn=test&xs=https://search-id.org/testwebseed/multi.torrent&ws=https://search-id.org/testwebseed/`

This don't work:
`magnet:?xt=urn:btih:2fecd2f5ee55d8f8e4220f85986fa02da2c870da&dn=file1.txt&xs=https://search-id.org/testwebseed/single.torrent&ws=https://search-id.org/testwebseed/test/`

So, if i understand correctly,
"xs" must be the full path of .torrent file.
In multifile torrent, "ws" is used as base path, and WebTorrent append the folder and each file request.
In singlefile torrent, "ws" must point to the full path.

I see an incongruence here, mostly because in the single-file logic, i need to know the content of a torrent to build a valid magnet with webseed.

**What do you think is the correct solution to this problem?**
Proposal:
1) Use for coherence only multifile logic ("ws" as base path).
or
2) WebTorrent use the current logic (for backward compatibility), but if 404 try the folder-logic.

Anyway, this need to work:
`magnet:?xt=urn:btih:2fecd2f5ee55d8f8e4220f85986fa02da2c870da&dn=file1.txt&xs=https://search-id.org/testwebseed/single.torrent&ws=https://search-id.org/testwebseed/test/
`

**Are you willing to submit a pull request to implement this change?**
I can try to build a pull request, if 1) or 2) can be acceptable for @feross .

**Comment by PaTiToMaSteR** [comment]
If you created the torrent with testwebseed as folder, if you inspect your torrent you probably will see that the webseed folder must be just testwebseed.

Is not like the fullpath, is the working directory when you created your torrent file.

I think you don't explain why you need to make that work, but if there is a change like that you'll break the torrents of everybody.

The solution for you is as simple as jump inside of your testwebseed and create the torrent in another way using create-torrent test as folder not testwebseed.

My 2 cents: try using create-torrent and parse-torrent and inspect the torrent you are creating.

**Comment by Clodo76** [comment]
It will not break the torrents of everybody, if implemented as fallback (solution 2).
The above two torrent are created with qBitTorrent, below the output of parse-torrent on both.
There isn't any reference to "testwebseed" folder of course.

I just try to recreate with create-torrent, except trackers added, the structure is identical.
And a magnet to it works as above.

I honestly don't understand your feedback.

```
# parse-torrent single.torrent
{
  "name": "file1.txt",
  "announce": [],
  "infoHash": "2fecd2f5ee55d8f8e4220f85986fa02da2c870da",
  "created": "2020-05-03T13:37:06.000Z",
  "createdBy": "qBittorrent v4.1.1",
  "urlList": [],
  "files": [
    {
      "path": "file1.txt",
      "name": "file1.txt",
      "length": 13,
      "offset": 0
    }
  ],
  "length": 13,
  "pieceLength": 16384,
  "lastPieceLength": 13,
  "pieces": [
    "cc39c9571fe17e95853705f497e7ac2dc7ae2b64"
  ]
}
# parse-torrent multi.torrent
{
  "name": "test",
  "announce": [],
  "infoHash": "c2b12fc7fc97f9ff5a7dfb292ed0dea0dc125844",
  "created": "2020-05-03T13:37:23.000Z",
  "createdBy": "qBittorrent v4.1.1",
  "urlList": [],
  "files": [
    {
      "path": "test/file1.txt",
      "name": "file1.txt",
      "length": 13,
      "offset": 0
    },
    {
      "path": "test/file2.txt",
      "name": "file2.txt",
      "length": 13,
      "offset": 13
    }
  ],
  "length": 26,
  "pieceLength": 16384,
  "lastPieceLength": 26,
  "pieces": [
    "540cf4828f818beca4805b83b811a2729a101c90"
  ]
}

```

**Comment by PaTiToMaSteR** [comment]
if the torrent has "path": "test/file1.txt" means your webseed folder is ws=https://search-id.org/testwebseed/ as your hd dir must be c:\blah\testwebseed\test\file1.txt and you drag ann drop the folder test, right?

what's the problem with that, maybe I don't get your point.

**Comment by feross** [comment]
Unfortunately, this inconsistency is part of how web seeds are specified. You can read the BEP here: https://www.bittorrent.org/beps/bep_0019.html
