### ISSUE TITLE
File destinations

### ISSUE THREAD

**Issue by cpwhaley** [webtorrent/webtorrent#1849]
My question is about the Brave browser implementation of WebTorrent.  I suppose that it's not a bug, but when I download a file, I watch the downloading process on my screen, but I have no idea where the files are going. After numerous DLs and numerous searches of my Mac and all attached drives, there doesn't appear to be a trace of any of them.  Shouldn't I be prompted for a destination anyway, before it starts?  Anyway, copying the magnet works fine, and then I paste it into another torrent client.  Not very efficient.  If this is not a bug, some very critical info is not provided.

**Comment by ultimate-tester** [comment]
Thanks for your message. Personally I have no experience with the Brave browser. WebTorrent itself only listens to the methods used by the implementer (e.g. where and how to download the file). Therefore, your request is better off with Brave rather than WebTorrent.
