### ISSUE TITLE
webtorrent.io/docs says torrent comment can be displayed, but it's not implemented

### ISSUE THREAD

**Issue by ok243** [webtorrent/webtorrent#1854]
Do not know if I should have added this as feature request or as a bug. I took the liberty of filing it as a bug since the docs state that torrent.comment is a feature.

https://webtorrent.io/docs
https://github.com/webtorrent/webtorrent/tree/master/lib
https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js

**What version of this package are you using?**
0.108.1
**What operating system, Node.js, and npm version?**
Win 10 Pro, v12.13.1, 6.13.2
**What happened?**
Fetched from a magnet link. Tried to console log torrent.comment after fetching on every torrent.on state. Torrent and files where successfully downloaded.
**What did you expect to happen?**
Expected to display comment on torrent.comment.

Edit:
Maybe I am wrong to assume that the comment of the torrent will be available from a magnet link since its not a part of the hash? Is there any other fields which are not part of the hash which can be fetched using a magnet link?

Edit2:
Is there any part of a torrent that can be added which are not a part of the hash, in other words mutable, and is not fetched through tracker/server?

**Comment by SilentBot1** [comment]
Hi @ok243,

I've been able to verify the issue that is occurring. When verifying the contents of `client.trrents[0].comment` on WebTorrent.io, this loads the `torrent.comment` property correctly, but when loading the same InfoHash (`08ada5a7a6183aae1e09d831df6748d566095a10`) on instant.io, the `torrent.comment` property is undefined.

The main difference between the two implementations is that instant.io is loading the metadata via `ut_metadata` whereas WebTorrent.io is loading the metadata via torrent file embedded in the `bundle.js` file.

With the torrent you're attempting this with, is this being loaded from other peers via `ut_pex` or are you supplying the `.torrent` when the `torrent.comment` property isn't loading? If it's the latter, are you able to provide a copy of this torrent (copyright permitting)?

Many thanks,
Brad Marsden

**Comment by feross** [comment]
I don't believe that `torrent.comment` will be sent with the `ut_metadata` extension since it's designed to just send the `info` portion of the `.torrent` file. Anything else outside the `info` dict can't be verified by the infohash since it's outside the `info` dict, so peers don't send it.
