### ISSUE TITLE
WebTorrent not interested in downloading files

### ISSUE THREAD

**Issue by perf2711** [webtorrent/webtorrent#1864]
**What version of this package are you using?**
`webtorrent@0.108.2`

**What operating system, Node.js, and npm version?**
Windows 10 1901 18363.836
Node.js 12.16.2
npm 6.14.4
yarn 1.21.1 (I am using yarn to install packages)

**What happened?**
I set up a minimal program to download a file from .torrent I created. The torrent has no trackers, but I plan to manually add peers using `.addPeer()`. When I add a peer, I see on the other side, that the peer has been added (I am using qBitTorrent). However, on their side, webtorrent is visible as "not interested" and "choking". I am 100% sure that the torrent file is the same. 

Sometimes, the file is downloaded (but, like 1/50 of the time).

**What did you expect to happen?**
I expect the file to download every time.

**Are you willing to submit a pull request to fix this bug?**
If I know what it is, sure.

**Example source**
```typescript
import fs from 'fs';
import WebTorrent from 'webtorrent';
import { throttle } from 'lodash';

function onDownload(torrent: WebTorrent.Torrent, bytes: number) {
    const progress = torrent.progress * 100;
    console.trace(`[${torrent.infoHash}] D ${progress}% +${bytes}B (${torrent.downloaded}B/${torrent.length}B)`);
}

function onUpload(torrent: WebTorrent.Torrent, bytes: number) {
    console.trace(`[${torrent.infoHash}] U +${bytes}B`);
}

async function main() {
    const client = new WebTorrent({
        dht: false,
        tracker: false
    });

    client.add('./sample.torrent', {
        path: './download'
    }, (torrent) => {
        torrent.on('download', throttle((bytes) => {
            onDownload(torrent, bytes);
        }, 100));

        torrent.on('upload', throttle((bytes) => {
            onUpload(torrent, bytes);
        }, 100));

        // qBitTorrent's address (this is localhost)
        torrent.addPeer('192.168.1.66:48599');
    });
}

(async () => {
    main();
})();
```

**Output (with DEBUG=*)**
```
 webtorrent [2d57573] new webtorrent (peerId 2d5757303030382d2f7534474c4172786b634875, nodeId 452b7a3e75270ac38a8a000aa9d8ed015797b55f, port 0) +0ms
  webtorrent:tcp-pool create tcp pool (port 0) +0ms
  webtorrent [2d57573] add +11ms
  webtorrent:torrent [2d57573] [unknown infohash] new torrent +0ms
  webtorrent [2d57573] listening +2ms
  webtorrent:torrent [2d57573] [fe8916f] got metadata +3ms
  webtorrent:torrent [2d57573] [fe8916f] select 0-6 (priority 0) +0ms
  webtorrent:torrent [2d57573] [fe8916f] verifying existing torrent data +1ms
  webtorrent:torrent [2d57573] [fe8916f] done verifying +2ms
  webtorrent:torrent [2d57573] [fe8916f] on store +0ms
  webtorrent:torrent [2d57573] [fe8916f] add peer 192.168.1.66:48599 +1ms
  webtorrent:peer new tcpOutgoing Peer 192.168.1.66:48599 +0ms
  webtorrent:torrent [2d57573] [fe8916f] _drain numConns 0 maxConns 55 +8ms
  webtorrent:torrent [2d57573] [fe8916f] drain (2 queued, 0/55 peers) +1ms
  webtorrent:torrent [2d57573] [fe8916f] tcp connect attempt to 192.168.1.66:48599 +0ms
56428
  webtorrent:peer Peer 192.168.1.66:48599 connected +3ms
  bittorrent-protocol [4737d5fc] new wire +0ms
  bittorrent-protocol [4737d5fc] handshake i=fe8916fcb1d4dd0a0b7af566a1c53232692513ac p=2d5757303030382d2f7534474c4172786b634875 exts={ dht: false } +8ms
  bittorrent-protocol [4737d5fc] got handshake i=fe8916fcb1d4dd0a0b7af566a1c53232692513ac p=2d7142343230302d6a756241465a49702d2e4829 exts={ dht: true, extended: true } +3ms
  webtorrent:peer Peer 192.168.1.66:48599 got handshake fe8916fcb1d4dd0a0b7af566a1c53232692513ac +28ms
  webtorrent:torrent [2d57573] [fe8916f] got wire 4737d5fc (192.168.1.66:48599) +30ms
  bittorrent-protocol [4737d5fc] setTimeout ms=30000 unref=true +8ms
  bittorrent-protocol [4737d5fc] setKeepAlive true +0ms
  bittorrent-protocol [4737d5fc] use extension.name=ut_metadata +1ms
  ut_metadata set metadata +0ms
  bittorrent-protocol [4737d5fc] use extension.name=ut_pex +18ms
  bittorrent-protocol [4737d5fc] extended ext=0 +0ms
  bittorrent-protocol [4737d5fc] got extended handshake +1ms
  bittorrent-protocol [4737d5fc] got bitfield +8ms
  bittorrent-protocol [4737d5fc] got unchoke +0ms
  bittorrent-protocol [4737d5fc] bitfield +1ms
```

![obraz](https://user-images.githubusercontent.com/9085864/82191677-24cb4e80-98f3-11ea-8243-141a9e99549d.png)

**Comment by perf2711** [comment]
I checked one more thing. WebTorrent always succeeds in downloading the torrent from another WebTorrent peer, which has already the file.

**Comment by chr15m** [comment]
Over here libtorrent developers are seeing this same issue from the other end - WebTorrent peers appear not `interested` by default.

https://github.com/arvidn/libtorrent/pull/4123#issuecomment-630809053

**Comment by paullouisageneau** [comment]
I confirm there seems to be a protocol issue with WebTorrent peers not sending an `interested` message by default. A remote peer may therefore keep a WebTorrent peer chocked, resulting in a standoff.

**Comment by alxhotel** [comment]
Agreed, this is a bug. This also happens from time to time when running the tests.

**Comment by hicom150** [comment]
Could be related to https://github.com/webtorrent/webtorrent/pull/1061 ?

> Start peers as uninterested and only move to interested if/once they have a piece that we need

**Comment by paullouisageneau** [comment]
> Could be related to #1061 ?
Yes that's probably the change introducing the bug since `_updateInterest()` seems to be called only when selections are updated. On a side note, the `_updateInterest()` method looks weird, is `interest` expected to be sent irrelevant of the presence of selections?

**Comment by alanmcgovern** [comment]
`On a side note, the _updateInterest() method looks weird, is interest expected to be sent irrelevant of the presence of selections?`
I just wanted to check this because you may pre-empted a bug!

If you send an `interested` message to another peer they will expect you to request data as soon as they unchoke you. As such, please ensure you send 'NotInterested' messages to peers if you *do not* intend to request data from them, even if they have pieces you need.

Some clients will close the connection if they send an unchoke message and the other peer does not send `request` messages. Others may mark the peer as 'do not unchoke for the next 30 minutes' or similar.
