### ISSUE TITLE
Distributed Camp 2020 – Looking for lightning talk volunteers!!

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1873]
I'll be speaking at Distributed Camp 2020. https://distributed.camp/

Two days of immersive, hands-on workshops where you get to try out some of the latest decentralized web technologies for yourself. (Last chance to register is tomorrow, Thursday May 28!)

**If you have a WebTorrent-powered project that you want to promote or share with the broader decentralized tech community, I'm looking for a few people to volunteer to give a ~5 minute lightning talk / demo of what you've built!**

Please send me an email at [my first name]@feross.org if you want to give a VIRTUAL lightning talk. It will be over video-conference app. The talk can be low-key. It should be around 5 minutes long, but you can go longer if you want. This is your chance to share anything you want -- something you built with WebTorrent, something you learned from working on or using WebTorrent, or even something else entirely.

Please lmk by Friday May 29 at the latest (earlier is better!)

**Comment by feross** [comment]
Pinging folks who might be interested: @alxhotel @Chocobozzz @Borewit @codealchemist @DiegoRBaquero @Flet @jhiesey @KayleePop @mathiasvr @rom1504

**Comment by DiegoRBaquero** [comment]
I’ll pass, too much on my mind and life atm

**Comment by feross** [comment]
@DiegoRBaquero Totally understand.

**Comment by feross** [comment]
Last chance if anyone wants to give a talk. Lmk!
