### ISSUE TITLE
Feature: refactor codebase to use Promises instead of callbacks

### ISSUE THREAD

**Issue by mihaiav** [webtorrent/webtorrent#1876]
**What version of this package are you using?**
latest
**What problem do you want to solve?**
error handling
**What do you think is the correct solution to this problem?**
Usage of  promises instead of simple callbacks . Currently it's impossible to handle errors per request. For example, consider you have multiple/parallel requests, and one `client.add` call emits an error. The error is received on `client.on('error')`. The issue is that you can't correlate the two (the error from `client.on('error')` with specific `client.add` call that generated the error). This looks like a serious issue to me.
**Are you willing to submit a pull request to implement this change?**
possibly, if PRs are reviewed and feedback is provided.

**Comment by feross** [comment]
You can use this pattern to detect issues with an added torrent:

```js
const torrent = client.add()
torrent.on('error', err => { ... })
```
