### ISSUE TITLE
Webtorrent compatible with "PeerTube" Torrent Trackers do they work ?

### ISSUE THREAD

**Issue by C0nw0nk** [webtorrent/webtorrent#1877]
So I was looking to add more Trackers to my Magnet URI's more is better right.

Here are the trackers I use right now.
```
'wss://tracker.btorrent.xyz',
'wss://tracker.openwebtorrent.com',
'wss://tracker.fastcast.nz',
'wss://tracker.sloppyta.co',
```

I found this tracker here (Added this to my tracker list to seems to work). https://github.com/ngosang/trackerslist/blob/master/trackers_all_ws.txt
```
wss://tracker.sloppyta.co:443/announce
```

Then i stumbled across [PeerTube (A github project with allot of websites)](https://github.com/Chocobozzz/PeerTube) what also seems to be using Webtorrent and then i noticed that i could use any [PeerTube](https://www.reddit.com/r/PeerTube/) websites tracker and add it to my own list of trackers in my magnet URI as seen here. 

(So i browsed google and collected a few peertube sites trackers and added them to my list)

```
wss://video.blender.org/tracker/socket
wss://peertube.live/tracker/socket
wss://open.tube/tracker/socket
```

Looking at my browser console it all seems to connect fine and i see no error logs what is a good sign but I honnestly don't know if it is working can anyone confirm that these trackers do infact work and adding them helps ?

**Comment by Chocobozzz** [comment]
PeerTube trackers are not public, and only accept they own infohashes. Using them won't work.

**Comment by C0nw0nk** [comment]
@Chocobozzz 
> 
> 
> PeerTube trackers are not public, and only accept they own infohashes. Using them won't work.

When i look at the .torrent files details from PeerTube sites none of them have the setting as "Private" ? The trackers are connecting to their websites database to check the info_hash ?

**Comment by Chocobozzz** [comment]
> The trackers are connecting to their websites database to check the info_hash

Yes they are
