### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by VamuveTV** [webtorrent/webtorrent#1885]
How to make webtorrent  work with HLS content ? I mean, i want to create a video with hls, using playlists (m3u8) to create chunks of .ts, files for different video resolutions and several audio channels and subtitles, on the same way a regular hls do.

How to make it work like this ?

Best Regards

gustavo

**What version of this package are you using?**

**What problem do you want to solve?**

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

**Comment by leoherzog** [comment]
#448

**Comment by vadootvpeer** [comment]
@VamuveTV You can look at https://github.com/vadootvpeer/p2p-cdn-sdk-javascript . This has support for both hls and dash. A web demo is available at https://api.peervadoo.com/test
