### ISSUE TITLE
mp4 files with certain audio codecs not playing

### ISSUE THREAD

**Issue by FoxD3v1lsW1ld** [webtorrent/webtorrent#1887]
**What version of this package are you using?**
webtorrent@0.108.6 / instant.io as of 2020/07/05

**What operating system, Node.js, and npm version?**
Win 10 / Node v10.15.0 / npm 6.4.1

**What happened?**
When downloading "Big Buck Bunny" via Webtorrent in the Browser, the video never plays. This can also be obseved on https://instant.io when using the magnet link for it from https://webtorrent.io/free-torrents.

1. Go to https://instant.io/
2. Paste the magnet link: `magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent`
3. Press download
4. The HTML5 video tag never loads

Tested in Chrome / Firefox. Also happens in my own implementation using the "Quick Implementation" (using a larger maxBlobLength and a callback-method for `file.appendTo`) from https://webtorrent.io/docs. I've also tried seeding a different mp4-Version of Big Buck Bunny (http://bbb3d.renderfarming.net/download.html) and that didn't work either. There are no errors visible.

On the other hand, the example "Sintel" works as expected.

**What did you expect to happen?**

The video tag should load and be able to play the video, especially since it's part of the officially listed examples.

**Observation**
The version of Big Buck Bunny which isn't working has 2 audio streams (mpga, ac-3). 
Other files i've tested (Sintel and some random mp4s i had that were between 100MB and 2 GB) have worked. These have 1 audio stream (mp4a).

I suspect that the issue arises because mpga/ac-3 are not supported audio codecs for mp4 and crash something internally. However, no error is thrown as the callback for `file.appendTo` never fires.

**Comment by sainitishkumar** [comment]
I tried to reproduce the error.
It seems that the tracker is down.
The same issue [https://github.com/webtorrent/webtorrent/issues/743](743) has the same problem.
Once the tracker is up, I think it will work properly.

**Comment by FoxD3v1lsW1ld** [comment]
Thanks! I am seeing that error too, but I believe that is a separate issue.

Fastcast isn't working, but the other trackers seem to be fine. This should cause no issues as described here: https://github.com/webtorrent/webtorrent/issues/743#issuecomment-322900830.

I also get the same error for "Sintel", but that torrent works just fine. The issue also happens when I use just my own tracker (https://github.com/webtorrent/bittorrent-tracker) and have a seeder and the client on there. It works fine for other files, but not this particular one.

**Comment by feross** [comment]
Yes, there is likely a bug in the `videostream` library that prevents this video from playing. You can file an issue here: https://github.com/jhiesey/videostream
