### ISSUE TITLE
Can't Download from Npm 

### ISSUE THREAD

**Issue by Jbone187** [webtorrent/webtorrent#1888]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**
Ubuntu 20.04 
Nodejs 12.18.2
Npm 6.14.6
**What happened?**
I am unable to download npm package

**What did you expect to happen?**
Download package
**Are you willing to submit a pull request to fix this bug?**
Not at this time

[11:46:05] jasen@BoneStone:~/ssh_copy$ sudo npm install webtorrent
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-07T18_46_14_512Z-debug.log
[11:46:14] jasen@BoneStone:~/ssh_copy$

**Comment by Jbone187** [comment]
User error sorry

**Comment by alxhotel** [comment]
Hey @Jbone187,

What was the solution (or the user error)?

(I think there might be some people with the same problem)

**Comment by Jbone187** [comment]
I think the package is tied to git some how. I had to install git and it worked. I usually install on my computer but must of forgot with this new one

**Comment by Jbone187** [comment]
ls-remote -h -t ssh://git@github.com/feross/http-node.git

**Comment by alxhotel** [comment]
Ah nice catch :+1:
