### ISSUE TITLE
Changing encryption (PE) mode

### ISSUE THREAD

**Issue by jebbgrenham** [webtorrent/webtorrent#1889]
What's the correct way to turn protocol encryption on and off? The preferences page doesn't mention it; and the documentation also doesn't mention it. Typically it can be set to required/preferred/allowed/disallowed or some subset of that.

**Comment by ivan1986** [comment]
#69

**Comment by alxhotel** [comment]
Hi @jebbgrenham, thanks for bringing this up. This features is not implemented yet.

As @ivan1986 has pointed out, please check #69. There are also some PRs related to this #1820
