### ISSUE TITLE
WebTorrent Happy Hour!! ❤️ Come chat with us!

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1892]
🌟 We're hosting a WebTorrent Happy Hour for community members to meet each other. 🌟

The format is random 1-on-1 video chats between attendees that last 2 minutes (with an "extend" button if the conversation is good).

It's happening tomorrow, July 23 @ 7 PM Pacific

👍 Join here: https://zmurl.com/webtorrent

**Comment by feross** [comment]
WebTorrent Happy Hour is HAPPENING NOW!

Join here: https://virus.cafe/r/webtorrent

**Comment by 59023g** [comment]
@feross I'll be at the next one!

**Comment by 59023g** [comment]
**sets notifications to watching**
