### ISSUE TITLE
unable to do npm install

### ISSUE THREAD

**Issue by KYGAS** [webtorrent/webtorrent#1893]
"path to module">npm install webtorrent
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2020-07-23T01_59_54_999Z-debug.log

After running

**npm install webtorrent**

I got this error

**Comment by alxhotel** [comment]
Do you have `git` installed ?

**Comment by mani9896** [comment]
Make sure you have the GIT installed on your device and accessible globally. Try to type git -v in the CMD. If it returned that the command is not recognized and GIT already installed, then you need to add it to the PATH environment variable and make sure to try the command using a new CMD session
