### ISSUE TITLE
WebTorrent Happy Hour ❤️ TODAY at 2pm PT!

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1897]
🌟 We're hosting a WebTorrent Happy Hour for community members to meet each other. 🌟

The format is random 1-on-1 video chats between attendees that last 2 minutes (with an "extend" button if the conversation is good).

It's happening TODAY @ 2pm Pacific Time

See it in your time zone: https://www.timeanddate.com/worldclock/fixedtime.html?msg=WebTorrent+Happy+Hour&iso=20200807T14&p1=224&ah=1

Join the event here: https://speakeasy.co/webtorrent

**Comment by feross** [comment]
This is starting NOW!

**Comment by 59023g** [comment]
I was there but didn't match with anyone since there were 4 participants !!!
