### ISSUE TITLE
Discord server - maintainers want staff role?

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1898]
Hey fellow maintainers,

I just created a `staff` role on our [discord server](https://discord.gg/cnXkm4Z). Right now only @alxhotel and @Borewit are active on the server, but if anyone else wants to join, lmk and I'll give you the `staff` role.

Cheers!

**Comment by DiegoRBaquero** [comment]
Changed my discord account name. Could I get staff? DiegoRBaquero#4437

**Comment by feross** [comment]
@DiegoRBaquero I can't see you in the user list for the WebTorrent Discord for some reason. Can you check that you're joined and maybe send me a DM so I can find you?

**Comment by feross** [comment]
Closing this now. If any maintainers want a staff role in the WebTorrent Discord, please send me an email or a DM on Discord.
