### ISSUE TITLE
Webtorrent doesn't open a magnet link

### ISSUE THREAD

**Issue by ashuradev** [webtorrent/webtorrent#1902]
**What version of this package are you using?**
The latest version.

**What operating system, Node.js, and npm version?**
I'm running the WebTorrent on Chrome (version 84)

**What happened?**
The WebTorrent is not playing the magnet link on this format:
```
magnet:?xt=urn:btih:<<code here>>
```

**What did you expect to happen?**
Play the magnet link.

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by alxhotel** [comment]
Hi @ashuradev,

If you are using the Webtorren library, try testing your app with known magnet links like Sintel:

```
magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent)
```

If this still doesn't work, please provide us with more information, like a code snippet.

Also note that if you are trying to play a video, check that the format is supported by the browser.

**Comment by ashuradev** [comment]
Yes, this magnet link above works, but a magnet link on this format `magnet:?xt=urn:btih:<<code here>>` doesn't works.

**Comment by alxhotel** [comment]
Do you mean with any additional parameters?

Try adding trackers to the magnet link. Otherwise, the client won't have a way to discover other peers in the browser.

**Comment by ashuradev** [comment]
Thank you :+1:
