### ISSUE TITLE
Magnet Link is not working

### ISSUE THREAD

**Issue by MittalShruti** [webtorrent/webtorrent#1915]
**What version of this package are you using?**
<script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>

**What operating system, Node.js, and npm version?**
Using it in browser, chrome

**What happened?**
The magnet link doesn't work (shows no error, no output (in console))
However, another magnet link that I got is working fine. 

**What did you expect to happen?**
The file should show in the browser

**Are you willing to submit a pull request to fix this bug?**
Don't have the solution as of yet

The following magnet link is working fine 

`var torrentId = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent'`

But the link I generated using python bencode is not working. I have a `.mp4` file in AWS s3. I created the `.torrent` using `get_object_torrent` , and generated the magnet link using `bencode`

`var torrentId = 'magnet:?xt=urn%3Abtih%3Ab%2757YEJLDLFRGRIQSPIWJAIT52IELD7PNF%27&dn=s3outputx.mp4&tr=http%3A%2F%2Fs3-tracker.us-west-2.amazonaws.com%3A6969%2Fannounce&xl=7132076'`

```
var client = new WebTorrent()

client.add(torrentId, function (torrent) {
            // Torrents can contain many files. Let's use the .mp4 file
            
            console.log('torrent', torrent)
            var file = torrent.files.find(function (file) {
              
              console.log('xxx 1', file)
              console.log('file 2', file.name.endsWith('.mp4'))
              return file.name.endsWith('.mp4')
            })

            // Display the file by adding it to the DOM.
            // Supports video, audio, image files, and more!
            torrent.files[0].appendTo('body')
          })
```

**Comment by alxhotel** [comment]
Hi @MittalShruti,

Thank you for opening an issue.

I guess that the magnet link you are trying to use is the one you posted but decoded. In other words, this one:

```
magnet:?xt=urn:btih:57YEJLDLFRGRIQSPIWJAIT52IELD7PNF&dn=s3outputx.mp4&tr=http://s3-tracker.us-west-2.amazonaws.com:6969/announce&xl=7132076
```

I have tried adding this to a Transmission client and it outputs: `Tracker gave HTTP response code 400 (Bad Requesr)`.

So based on that and the previous issue regarding Amazon S3 tracker (#979) I'm guessing that the tracker is not working properly.

**Comment by MittalShruti** [comment]
Hi @alxhotel Thanks for replying. 

Checked the above link. My s3 bucket is private. So I need to either upload the torrent file in a public s3 bucket or pass a `.torrent` file through webtorrent?

**Comment by alxhotel** [comment]
Yep, I think you need to make the file public in S3 to be able to get the torrent.
