### ISSUE TITLE
stream a torrent file stored in firebase

### ISSUE THREAD

**Issue by MittalShruti** [webtorrent/webtorrent#1916]
**What version of this package are you using?**
<script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>

**What operating system, Node.js, and npm version?**
Using it in browser, chrome

**What happened?**
I am using reactJs with flask. 

I am passing a .torrent stored in firebase to torrentId, but I am getting error
**What did you expect to happen?**
Webtorrent should have streamed the file. 

When my torrent file link in firebase is 
torrentId = `"https://firebasestorage.googleapis.com/v0/b/tryvokal.appspot.com/o/videos%2Fzs3outputx.mp4.torrent?alt=media&token=4e1971e1-08c9-4b69-ade1-eab3833b730d"`

I get `Invalid torrent identifier`

When I remove the alt and token, i.e. 
torrentId = `"https://firebasestorage.googleapis.com/v0/b/tryvokal.appspot.com/o/videos%2Fzs3outputx.mp4.torrent"`
I get the following error
```
webtorrent.min.js:1 Uncaught Error: not a number: buffer[0] = 123
    at getIntFromBuffer (webtorrent.min.js:1)
    at Function.decode.buffer (webtorrent.min.js:1)
    at Function.decode.next (webtorrent.min.js:1)
    at Object.decode (webtorrent.min.js:1)
    at decodeTorrentFile (webtorrent.min.js:6)
    at parseTorrent (webtorrent.min.js:6)
    at parseOrThrow (webtorrent.min.js:6)
    at webtorrent.min.js:6
    at webtorrent.min.js:6
    at exports.IncomingMessage.<anonymous> (webtorrent.min.js:6)
    at Object.onceWrapper (webtorrent.min.js:6)
    at emitNone (webtorrent.min.js:6)
    at exports.IncomingMessage.EventEmitter.emit (webtorrent.min.js:6)
    at endReadableNT (webtorrent.min.js:6)
    at Item.run (webtorrent.min.js:6)
    at drainQueue (webtorrent.min.js:6)
```
However, passing this `'https://webtorrent.io/torrents/sintel.torrent'` as torrentId works fine. 
Is there a way I can access and stream .torrent file in browser?

**Comment by alxhotel** [comment]
Your first link is working for me (check out https://codepen.io/alxhotel/pen/yLOeqVO).

The second link returns a JSON object, so that's why you see an error (`not a number: buffer[0] = 123`).

By the way, to catch the error you can do this `client.on('error', () => { /* handle error here */ })`.

**Comment by MittalShruti** [comment]
Thanks! This is working in html file with `<script>` tags. 

How do I get it work in `reactjs`? I added the minified file in `<script>` tags. However,
`var client = WebTorrent()` is throwing error in reactjs, that WebTorrent() is not defined. Tried `window.WebTorrent()`, but then I get Invalid torrentid error.

**Comment by MittalShruti** [comment]
Also, now both torrent and original files are public in aws, but still the video content doesn't load in the browser.

Code - [Codepen](https://codepen.io/drngke/pen/VwaxZxR)

**Comment by alxhotel** [comment]
> Also, now both torrent and original files are public in aws, but still the video content doesn't load in the browser.
> 
> Code - [Codepen](https://codepen.io/drngke/pen/abNGbEg)

Ah right. That's because AWS does not have browser peers (aka WebRTC peers) seeding the file.

**Comment by MittalShruti** [comment]
Do you have any suggestion to make it work? Or basically, I cant stream the video with webtorrent?

**Comment by alxhotel** [comment]
You can use a webseed with the public URL of the file. Or you could start your own hybrid peer in a private server.
