### ISSUE TITLE
Watching the media file in real time on mobile device using WebTorrent?

### ISSUE THREAD

**Issue by arlins** [webtorrent/webtorrent#1918]
Hello everyone, I have been looking for a solution to the problem of how to apply WebTorrent to mobile devices, but I still have no idea. My question is:

1: The user expects to watch the media files in the torrent in real time on the mobile device without waiting for the download to be completed (we assume that the download speed is fast and does not affect the viewing experience).

2: On mobile devices, the system player function is too simple, users expect to be able to use a custom player to play the media files in the torrent

I have tried the solution of "libtorrent+local HTTP server" to solve these problems, and Popcorn Time For Mobile also uses this solution. The realization principle is: create a local HTTP server for the downloading media file, through this local HTTP server, we can access the local cache of this media file. The external player can directly play the link of this local server, so that we can use the custom player to play the media files in the torrent in real time.

Libtorrent is written in C++, so this solution can be implemented for mobile devices. I want to use WebTorrent, which is more lightweight. But WebTorrent is based on JavaScript. If we implement this solution based on WebTorrent on mobile devices, users can only use our services through a browser. I have checked WebTorrent related APIs and other materials, but I have not found how to implement this solution using WebTorrent.

So I want to know: how to implement a solution similar to "libtorrent+local HTTP server" based on WebTorrent? Or does WebTorrent have any other solutions for the above problems on mobile devices?

**Comment by I-Cat** [comment]
It has to be downloaded in order of blocks, to be able to play back from an active downloading torrent.
Then call the Loop back
Cashing is needed of course. I'd say min 2gb cash would be needed Wich is most lower quality videos.

**Comment by feross** [comment]
If you have the ability to make a native app – i.e. you're not limited to running your code in the web browser – then you can just use the `torrent.createServer()` function to create a local HTTP server and then serve the content to whatever video player you want which supports HTTP streaming.
