### ISSUE TITLE
Can't remove/destroy torrents from events

### ISSUE THREAD

**Issue by JiPaix** [webtorrent/webtorrent#1924]
**What version of this package are you using?**
https://www.npmjs.com/package/websocket/v/1.0.32 

**What operating system, Node.js, and npm version?**
Debian 10 (buster)
Node v12.18.3 

**What happened?**
`client.remove()` and `torrent.destroy()` , while called in a torrent event, throw this error : 
```console
/some/path/node_modules/webtorrent/lib/torrent.js:917
this.client.emit('download', downloaded)
                  ^
TypeError: Cannot read property 'emit' of null
```
```js
client.add(torrentId, { path: downloadPath }, torrent = > {

  torrent.on('done', () => {
    get_the_file_and_send_it_through_websocket(connection)
  })

  torrent.on('download', dl => {
    if(socket.connected) {
      socket.send(torrent.progress)
    } else {
      client.remove(torrent.torrentFile)
      // torrent.destroy()
    }
  })

})
```
I also tried `torrent.removeAllListeners('download')` but it looks like a problem with `client` 

**What did you expect to happen?**
I'm sending the data from server to clients through websockets :
I'd like to remove/destroy torrents when a user leaves midway.

**Comment by alxhotel** [comment]
Thanks for reporting this, @JiPaix!

Agreed, this seems like a bug.

We are not checking if the torrent has been destroyed after the emitting the event `download`.

**Comment by JiPaix** [comment]
> Thanks for reporting this, @JiPaix!
> 
> Agreed, this seems like a bug.
> 
> We are not checking if the torrent has been destroyed after the emitting the event `download`.

Thank you for your insight, this is basically fixed by replacing those two lines : 
https://github.com/webtorrent/webtorrent/blob/7aee819796c540df0b247fec1853098f9a591d4c/lib/torrent.js#L924
https://github.com/webtorrent/webtorrent/blob/7aee819796c540df0b247fec1853098f9a591d4c/lib/torrent.js#L933

with : 
```js
if (this.client) this.client.emit('download', downloaded)
```
```js
if (this.client) this.client.emit('upload', uploaded)
```
