### ISSUE TITLE
Update ut_pex package to latest version

### ISSUE THREAD

**Issue by rogerg93** [webtorrent/webtorrent#1927]
**What version of this package are you using?**
v0.108.6

**What problem do you want to solve?**
Use the latest ut_pex version that will be released here https://github.com/webtorrent/ut_pex/issues/28

**What do you think is the correct solution to this problem?**
Update ut_pex dependency to the latest version

**Are you willing to submit a pull request to implement this change?**
Sure, as soon as ut_pex releases a new version

**Comment by feross** [comment]
Released as 0.109.0
