### ISSUE TITLE
UTP: Torrent Destroy Potential NPE

### ISSUE THREAD

**Issue by rhyswilliamsza** [webtorrent/webtorrent#1932]
**What version of this package are you using?**
0.108.6 (master head e5bea58),

**What operating system, Node.js, and npm version?**
All

**What happened?**
If torrent.destroy() is called, any dangling (specifically future reconnecting) peers throw NPEs when checking whether the client has UTP enabled.

```        
const newPeer = this._addPeer(peer.addr, this.client.utp ? 'utp' : 'tcp')
                                                ^
TypeError: Cannot read property 'utp' of null
    at Timeout._onTimeout (/root/rocket/api/node_modules/webtorrent/lib/torrent.js:1733:62)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**What did you expect to happen?**
Either all outstanding reconnections attempts should be cancelled if the client is destroyed, or a simple check should be done before executing this command.

**Are you willing to submit a pull request to fix this bug?**
Sure, if this isn't a known bug :)

**Comment by hicom150** [comment]
Thank you @rhyswilliamsza for reporting this! 👍
**uTP** support is something that has been just recently added, so a PR to fix this would be more than welcome 😉
If you find anything other problem related to **uTP** or you need any help with the PR just let me know 😊

**Comment by hicom150** [comment]
Fixed! 🎉
