### ISSUE TITLE
Magnet Link Not Working

### ISSUE THREAD

**Issue by isuckatprogram** [webtorrent/webtorrent#1934]
**What version of this package are you using?**
0.108.6
**What operating system, Node.js, and npm version?**
Linux, v12.18.3, 6.14.6
**What happened?**
When I try to add a magnet link, nothing outputs in console and nothing happens.

**What did you expect to happen?**
I expect the magnet link to work so it can download the files. 

Magnet Link: 

```
magnet:?xt=urn:btih:FABCC4BED431CE99D202F00D27891E22C76F8BAB&dn=The%20Flash%20Season%206.%20revittony&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2850%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2920%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce'
```
**Are you willing to submit a pull request to fix this bug?**

Nope, I know nothing about torrents lol.

**Comment by alxhotel** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.

Also, check [FAQs](https://webtorrent.io/faq) and previous closed issues.

**Comment by isuckatprogram** [comment]
@alxhotel can you at least tell me why it would timeout?
