### ISSUE TITLE
Error installing.

### ISSUE THREAD

**Issue by JLDENSMORE** [webtorrent/webtorrent#1936]
I keep getting this error when I try to install it.
![18CB6A85-8E89-49AC-9672-E116AE3281BC](https://user-images.githubusercontent.com/38232202/96639761-c3673b80-12e7-11eb-915d-4807fc48309f.jpeg)

**Comment by nlanson** [comment]
It says it's not able to find github.com/feross/http-node so why not try install that first. 


https://github.com/feross/http-node 


npm install http-node

**Comment by DiegoRBaquero** [comment]
Should be on https://github.com/webtorrent/webtorrent-cli

**Comment by JLDENSMORE** [comment]
> It says it's not able to find github.com/feross/http-node so why not try install that first.
> 
> https://github.com/feross/http-node
> 
> npm install http-node

I installed it globally and I’m still getting the same issue.

**Comment by nlanson** [comment]
Try install from git maybe:


https://github.com/webtorrent/webtorrent-cli

**Comment by feross** [comment]
Perhaps try cleaning your npm cache? `npm cache clean -f` then install `npm install webtorrent-cli -g` and try again.
