### ISSUE TITLE
Support 'x.pe' parameter on magnet URIs

### ISSUE THREAD

**Issue by pataquets** [webtorrent/webtorrent#1939]
**What version of this package are you using?**
All

**What problem do you want to solve?**
When opening/decoding magnet links, parsing x.pe parameter would allow faster download and bootstrapping of torrents.

**What do you think is the correct solution to this problem?**
More info: http://bittorrent.org/beps/bep_0009.html#magnet-uri-format

**Are you willing to submit a pull request to implement this change?**
Not able

**Comment by feross** [comment]
Thanks for tackling this task in #1942, @hicom150. I super appreciate it!

**Comment by feross** [comment]
Fixed in https://github.com/webtorrent/webtorrent/pull/1942

**Comment by feross** [comment]
Released as 0.110.0
