### ISSUE TITLE
No seeding in Browser

### ISSUE THREAD

**Issue by john916zhang** [webtorrent/webtorrent#1941]
**What version of this package are you using?**

The latest one, v0.109.1

**What operating system, Node.js, and npm version?**

MacOS 10.15.6, Chrome 86.0.4240.111, Safari 14.0

**What happened?**

The video shows correctly, but not seeds. Also, there are none messages on the tracker server-side (I am using https://github.com/webtorrent/bittorrent-tracker).

**What did you expect to happen?**

The browser should seed the torrent while downloading it. Also, I should see the peer information from the tracker server-side.

**Are you willing to submit a pull request to fix this bug?**

Yes, but I don't know how to fix it.

Torrent file: [https://www.gospel4china.org/videos/GFCC2020.720P.torrent](https://www.gospel4china.org/videos/GFCC2020.720P.torrent)

<img width="1342" alt="Screen Shot 2020-10-25 at 7 53 04 AM" src="https://user-images.githubusercontent.com/195719/97106308-26b1ee80-1697-11eb-9bdf-0f4b828064d3.png">

![image](https://user-images.githubusercontent.com/195719/97106327-39c4be80-1697-11eb-8a1f-c9a7cac54b3b.png)

**Comment by feross** [comment]
If you're hosting your website on `https://` (secure) then you need to ensure your websocket tracker server is also hosted on `wss://` (secure). It appears you are using `ws://` which will be blocked by the browser.

You need to put a reverse proxy like nginx in front of the tracker server to add TLS support.

**Comment by feross** [comment]
UDP trackers don't work in the browser. Only WSS.
