### ISSUE TITLE
how to get the download link of the torrent file.

### ISSUE THREAD

**Issue by paschal533** [webtorrent/webtorrent#1943]
i can't find the direct download link to the torrent file in nodejs,
how can i get the download link pls?

**Comment by feross** [comment]
Can you provide more info? I'm confused what you're asking.

**Comment by paschal533** [comment]
I wrote this code.

var WebTorrent = require('webtorrent')
var client = new WebTorrent()
var magnetURI = 'magnet: ...'

client.add(magnetURI, { path: '/path/to/folder' }, function (torrent) {
  torrent.on('download', function () {
    console.log('torrent is downloading)

})


I know it's downloading but I want to get the downloadable link and do
whatever I want with it, I don't know if there's a way to get a link
that can download the torrent from the browser and play it if I only
want to play..

**Comment by paschal533** [comment]
I am using webtorrent in an Express/node is server... So I need to send a
response to the front-end, but I can't find any useable link to send to the
front-end, here is my code.

App.get('/download', (req,res) => {
 var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var magnetURI = 'magnet: ...'

client.add(magnetURI, { path: '/path/to/folder' }, function (torrent) {
  torrent.on('done', function () {
    console.log('torrent download finished')
  })

})

I have tried console.log(torrent), but I didn't see any useful link, I
saw the name and the infohash.

It's downloading in the backend but I want it to download in the front
end when a user clicks a button.

Pls, help me out if u can.

**Comment by feross** [comment]
You will need to write some code for this.

You can get a readable stream of a specific torrent file:

```js
const stream = torrent.files[0].createReadStream()
```

Then, if you get a request for the file:

```js
app.get('/get-torrent', (req, res) => {
  const stream = torrent.files[0].createReadStream()
  stream.pipe(res)
})
```

That will stream the torrent contents to the browser when it requests `/get-torrent`. Obviously, adapt this to your application.

**Comment by paschal533** [comment]
i tried the code you sent to me but i got Error 404, not found.
if there is another way to go about doing this, pls suggest for me?

**Comment by feross** [comment]
I'm sorry but this was just an example. You'll have to figure out the details for yourself.

**Comment by feross** [comment]
You can try asking on our Discord server, link is in the main README.

**Comment by paschal533** [comment]
Ok, thanks.
