### ISSUE TITLE
NWjs/utp-native - "Error: A dynamic link library (DLL) initialization routine failed" when upgrading Webtorrent from 0.108 to 0.109

### ISSUE THREAD

**Issue by vankasteelj** [webtorrent/webtorrent#1947]
**What version of this package are you using?**
0.109.2

**What operating system, Node.js, and npm version?**
Windows 10, Node 12.13.1, npm 6.12.1

**What happened?**
Upgrading from 108.6 to 109.2 broke something. I believe this PR is to blame, because utp-native gives loads of errors: https://github.com/webtorrent/webtorrent/commit/692b3d113c0a08a17ee53bca7e16180a94b4fbfe#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R77 

This is my snippet for reproducing the issue (but it breaks everytime I use webtorrent for anything, actually): 

```js
      let magnet = '<insert a magnet link>'
      const wtorrent = new (require('webtorrent'))()
      let done

      setTimeout(() => {
        if (done) return
        wtorrent.destroy()
      }, 3500)

      wtorrent.add(magnet, (t) => {
        wtorrent.destroy()
        done = true
        console.log('magnet size is', t.length)
      })
```
Here's the line I suspect is causing this, when installing the new webtorrent with npm: 
![mintty_7XxtTJxNBJ](https://user-images.githubusercontent.com/12599850/97801448-21c3e080-1c3d-11eb-9964-ff4b4d0db414.png)

Here is the error message in console when trying to use webtorrent: 
![nw_nMDpQnW1HQ](https://user-images.githubusercontent.com/12599850/97801459-2e483900-1c3d-11eb-99f2-3016a1a2d783.png)

**What did you expect to happen?**
I'm not sure what it "should do", but not erroring, it should just "do magic" and return something to me, be it file size, informations and/or fileparts. 

**Are you willing to submit a pull request to fix this bug?**
I doubt it, I have no idea how most of webtorrent works, it just works :D

**Comment by alxhotel** [comment]
I can't reproduce the bug. The code snippet provided works for me.

Are you using the node version of Webtorrent in a browser?

If so, can you try to use the "browserified" version (`webtorrent.min.js`)?

**Comment by vankasteelj** [comment]
I forgot to say I was using nwjs 0.36.4 (but 0.49.2), it also works for me in console, but not in nwjs

**Comment by vankasteelj** [comment]
It does work with the browserified version. That's a first for me... I've never used a browserified module with nwjs

**Comment by feross** [comment]
> Note that it works for that snippet, but not for an actual download/stream of an entire video file. Even with the browserified version, it times out before connecting to anything.

That's because the browserified version doesn't connect to TCP/uTP peers. Only WebRTC ones, and there may not be any for your torrent.

> I forgot to say I was using nwjs 0.36.4 (but 0.49.2), it also works for me in console, but not in nwjs

What version of Node.js is included in the version of nwjs that you are using? It may be that it's too old/new to work with the version of `utp-native` that we're shipping.

**Comment by vankasteelj** [comment]
It's using Node v15.0.1

**Comment by vankasteelj** [comment]
This might have something to do with this, maybe : https://github.com/mafintosh/utp-native/issues/32

**Comment by vankasteelj** [comment]
I managed to get it to work, but it seems overly difficult! 

I had to: 

1. install Python 2.7 and VC++ build tools
1. `npm install -g nw-gyp node-gyp`
1. replace content of %appdata%/npm/node-gyp/src/ with the 'hacked' version for nwjs (instructions https://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/)
1. navigate to `./node_modules/webtorrent/node_modules/utp-native`
1. execute `nw-gyp rebuild --target=0.49.2 --arch=x64` to rebuild utp-native using binding.gyp with specific nwjs instructions

And it works.


----------

I do not have any idea if its an issue with utp-native or nwjs, but it does seems (to me, from my one-sided pov I mean) a hard push for people using your module, just because utp-native was added. I'd like you to consider if adding that dependency was the right move or not (not saying anything about the outcome of that consideration, you do you ofc)

**Comment by feross** [comment]
@vankasteelj Do you know when exactly the DLL initialization error occurs? Can you try, for example, adding a line like `console.log('after utp-native require)` after the `require('utp-native')` line? If it's possible for us to put a try-catch around this line, and make `utp-native` into an `optionalDependency`, then I'm happy to do that.

**Comment by vankasteelj** [comment]
Using this in lib/conn-pool.js and lib/torrent.js (similar phrasing): 

```js
console.log('before utp-native require lib/conn-pool.js')
const utp = require('utp-native') // browser exclude
console.log('after utp-native require lib/conn-pool.js')
```

I only have this log: 
![nw_c071Q9QMbY](https://user-images.githubusercontent.com/12599850/99145011-41123300-266b-11eb-827d-c81b6e20abdd.png)

The "after" is never logged, and the lib/torrent.js doesn't get triggered

**Comment by vankasteelj** [comment]
And if I try/catch it in lib/conn-pool.js, it does seem to "get over it", but then errors at lib/torrent.js, as such:
![nw_PWcYkYfaH7](https://user-images.githubusercontent.com/12599850/99145120-31dfb500-266c-11eb-9425-dac34f4b782e.png)

If I try/catch it in lib/torrent.js, webtorrent fires up without erroring, but doens't download anything. It does connect to peers though, just never starts the download. If that helps.

**Comment by feross** [comment]
Great – this is the info we needed. So `require('utp-native')` throws the error. We should:

1. Add a try catch around `require('utp-native')`

2. If the library can't be imported, we should skip all code paths that attempt to use the `utp-native` library. Essentially, we just fallback to using TCP sockets for all connections.

I believe this should fix this issue. Anyone want to take a stab at a PR?

**Comment by hicom150** [comment]
@feross  I've added #1966 as a first approach to solve the problem... any suggestion is more than welcome 😉

**Comment by vankasteelj** [comment]
@hicom150 FYI it seems to work for me, using your PR branch. It simply displays  `webtorrent.utp` as `false`, and everything seems to be working as it used to pre-0.109.x

**Comment by anesuc** [comment]
@vankasteelj  How did you manage to run the browsefied version? I am trying to get this to run on Windows and ran into the same problem as you did, but the moment I include the JS version and init webtorrent with `var client = new WebTorrent();` I get:

`Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object`

**Comment by vankasteelj** [comment]
Sorry I don't recall, it wasnt working anyways as mentionned, it just did not error. I'm currently using webtorrent 108.6 waiting for the PR to be merged and released

**Comment by anesuc** [comment]
I assume thats working properly with the latest nw.js?

**Comment by vankasteelj** [comment]
Probably, I'm using 0.49.2

**Comment by ThaUnknown** [comment]
from what I can read, this is mostly fixed, both in the upstream dependency, and inside webtorrent, I tested it a bit and forcing utp-native to fail compilation did try catch it correctly, and disabled the optional features for it inside webtorrent
