### ISSUE TITLE
Videos loading very slow inside webview

### ISSUE THREAD

**Issue by boufni95** [webtorrent/webtorrent#1949]
**What version of this package are you using?**
latest from cdn
**What operating system, Node.js, and npm version?**
It's a webview inside react native
**What happened?**
Loading stutters from http seed, The video loads the first two seconds quickly and after that it takes a lot to load the next seconds
**What did you expect to happen?**
where the http seed is the only seed available, prioritize http loading to avoid undue slowness
**Are you willing to submit a pull request to fix this bug?**
yes, I did some testing, and if I bypass the webtorrent client an grab the content url from the magnet, the video loads very quick, If there is a way to prioritize the http link it would be useful for the way we need to use it right now

**Comment by capitalistdog** [comment]
Seeing this but it's not specific to webview, even directly in a browser solely http sources load lazily.

We are using WebTorrent to provide torrent as a possible failover for files that are otherwise only served via HTTP. In testing, http is the only source.  (dedicated tracker online and ok) 

Have not yet determined if adding a classic torrent peer to the equation prevents the stutter as that's not expected to be a common scenario.

**Comment by capitalistdog** [comment]
There seems to have been other issues with webseed recently, have a hunch this is interested flapping interrupting loads...

https://github.com/webtorrent/webtorrent/pull/1823

**Comment by feross** [comment]
We also request pieces over many HTTP requests instead of one like a plain `<video>` tag would do, which could make a difference if your internet connection has high latency for each request.

**Comment by capitalistdog** [comment]
testing in "ideal" circumstances right now as far as server perf and latency to it, but if the initial pieces come back ok is it waiting to request additional pieces? thats how playback feels, like its lazily sending requests for more content rather than streaming it.

**Comment by anark1stx** [comment]
Hello, how did you make webtorrent work with react native?

**Comment by capitalistdog** [comment]
> Hello, how did you make webtorrent work with react native?

it's within a webview

**Comment by anark1stx** [comment]
> 
> 
> > Hello, how did you make webtorrent work with react native?
> 
> it's within a webview

Yeah but I get errors just from importing it
