### ISSUE TITLE
Error: Unsupported file type "": Cannot append to DOM

### ISSUE THREAD

**Issue by WaldemarKarasik** [webtorrent/webtorrent#1960]
**Latest**

**Windows 10 October 2020 Update, Node.js v14.15.0, and npm 6.14.8?**

**What happened?**
Error: Unsupported file type "": Cannot append to DOM

My code:
`createTorrent("./laxax.mp4", (err, torrent) => {
      console.log("create torrent error", err);
      fs.writeFile("./public/torrents/random.torrent", torrent, err => {
        console.log(err);
      });
    });`
I get no errors here

When the server starts, it also starts seeding all the torrents from the 'torrents' directory
`  fs.readdirSync("./public/torrents").forEach(file => {
    const torrentFile = fs.readFileSync(`./public/torrents/${file}`);
    webTorrentClient.seed(torrentFile, torrent => {
      console.log(torrent.magnetURI);
    });
  });`
I get no errors here

Client code:
` const client = new webTorrent();
    client.add(
      //magnet uri of a torrent that the server is seeding,
      (torrent) => {
        console.log(torrent.files);
        torrent.files.forEach((file) => {
          file.appendTo("body", function (err, elem) {
            console.log(err, elem);
          });
        });
      }
    );`
And here I get `Error: Unsupported file type "": Cannot append to DOM`
I can console.log for you whatever you want, just ask :kissing_heart:

**Comment by alxhotel** [comment]
It seems that you are seeding directly a ".torrent" file when doing `webTorrentClient.seed(torrentFile)`. That's why you can't append a torrent file to the DOM.

Instead you should be doing `webTorrentClient.seed("./laxax.mp4")`, since the `seed()` function already creates the torrent for you.
