### ISSUE TITLE
Remaining `bittorrent-lsd` issues

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1961]
We need to:

- [x] Pass the `lsd` option through to `torrent-discovery`, like how we do for the `tracker` and `dht` options.

- [x] Document the `lsd` option in the webtorrent docs, like how we do for the `tracker` and `dht` options.

- [x] Fix the webtorrent tests so that tests which e.g. test the DHT are not only disabling the tracker (with `tracker: false`) but also disable the lsd functionality (with `lsd: false`). Right now, peers are discovered through LSD when they shouldn't be.

- [x] [Added due to @justchen1369's comment] bittorrent-lsd currently only uses dgram, but should use chrome-dgram when running `npm build chromeapp".

**Comment by justchen1369** [comment]
Additionally: bittorrent-lsd currently only uses dgram, but should use chrome-dgram when running `npm build chromeapp".

**Comment by justchen1369** [comment]
I spent a fair amount of time figuring out why the chromeapp build didn't work :)

**Comment by feross** [comment]
@justchen1369 Good point! Yep. Added it to the list above

**Comment by justchen1369** [comment]
would adding the chromeapp field to the `package.json` work?

**Comment by feross** [comment]
> would adding the chromeapp field to the package.json work?

Yep, just merged your PR https://github.com/webtorrent/bittorrent-lsd/pull/6

**Comment by feross** [comment]
Released 0.111.0.
