### ISSUE TITLE
video appendTo callback is only called after play click or with option autoplay: true

### ISSUE THREAD

**Issue by Weedshaker** [webtorrent/webtorrent#1967]
v0.111.0 

Chrome, Ubuntu

When seeding a video, then appending it... the appendTo callback would not fire until the video gets played manually or the autoplay option is true.

appendTo callback to fire once appended to DOM

Maybe

**Comment by feross** [comment]
I agree with you. This should fire when it is appended to the DOM, since that's what the `render-media` docs say. I just fixed it in `render-media` 4.1.0 and released `webtorrent` 0.112.0.
