### ISSUE TITLE
`client.add` callback called after emittion of wire events

### ISSUE THREAD

**Issue by Banou26** [webtorrent/webtorrent#1968]
After some tests trying to understand why my wire events weren't called (when with peers on the same network), I understood that the `client.add` torrent callback is called after the fetching of metadata & wire infos resulting in almost no initial events being called when doing `torrent.on`.

One workaround i found is to simply not use the callback at all since `client.add` returns the `Torrent` instance on which you can register the events and those will be called.
e.g: 

```js
const torrent = client.add(torrentId)
torrent.on('wire', function(wire, addr) {
    console.log("WIRE event from:  " + wire.remoteAddress);
    console.log("PeerId : " + wire.peerId.toString());                        
})
```
instead of

> ```
> client.add(torrentId, function (torrent) {
> 
>  torrent.on('wire', function(wire, addr) {
>                         console.log("WIRE event from:  " + wire.remoteAddress);
>                         console.log("PeerId : " + wire.peerId.toString());                        
> }
> }
> ```
> 
> I'm using the browser version of webtorrent if that matters.
> 
> _Originally posted by @John-p0pe in https://github.com/webtorrent/webtorrent/issues/938#issuecomment-252296605_

We should probably either fix this behavior, or describe this behavior in the documentation.

**Comment by alxhotel** [comment]
I think this is the intended behaviour. The client usually gets the metadata from other peers, so some wires might have already being established before calling the callback of `client.add`.

But I agree we should emphasize this in the docs. PR is welcome :)
