### ISSUE TITLE
Consider migrating from `readable-stream` to `streamx`

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1971]
Advantages of [`streamx`](https://github.com/streamxorg/streamx) over [`readable-stream`](https://github.com/nodejs/readable-stream):

- Better performance (according to @mafintosh's testing... would be nice to see some numbers)
- Massively smaller browser bundle size (due to much simpler implementation)
  - stream: 18053 bytes (gzipped)
  - streamx: 2806 bytes (gzipped)
- Preserves 95% of the same Node.js API so most users shouldn't notice a difference
- Written by maintainers of `readable-stream` (so builds on those learnings, and possibly will become the next version of Node.js core streams)
- Opens the possibility of removing `Buffer` and using `Uint8Array` directly throughout `webtorrent`
  - This is possible because unlike `readable-stream`, `streamx` doesn't require `buffer`
  - Without `streamx`, it would be pointless to stop requiring `buffer` in `webtorrent` since `readable-stream` would just bring it into the bundle anyway

In order for the smaller browser bundle size benefits to be realized, we'd need to port the whole `webtorrent` ecosystem of packages. It looks like that's 13 packages using `readable-stream` in total.

```
webtorrent@0.111.0 /Users/feross/code/webtorrent
├─┬ bittorrent-protocol@3.2.0
│ └── readable-stream@3.6.0  deduped
├─┬ bittorrent-tracker@9.15.0
│ └─┬ simple-websocket@8.1.1
│   └── readable-stream@3.6.0  deduped
├─┬ chunk-store-stream@4.1.1
│ ├─┬ block-stream2@2.0.0
│ │ └── readable-stream@3.6.0  deduped
│ └── readable-stream@3.6.0  deduped
├─┬ create-torrent@4.4.2
│ ├─┬ filestream@5.0.0
│ │ └── readable-stream@3.6.0  deduped
│ └── readable-stream@3.6.0  deduped
├─┬ multistream@4.0.1
│ └── readable-stream@3.6.0  deduped
├── readable-stream@3.6.0 
├─┬ render-media@4.0.0
│ ├─┬ mediasource@2.4.0
│ │ └── readable-stream@3.6.0  deduped
│ └─┬ videostream@3.2.2
│   ├─┬ mp4-stream@3.1.0
│   │ └── readable-stream@3.6.0  deduped
│   └─┬ range-slice-stream@2.0.0
│     └── readable-stream@3.6.0  deduped
├─┬ simple-peer@9.9.3
│ └── readable-stream@3.6.0  deduped
└─┬ utp-native@2.2.1
  └── readable-stream@3.6.0  deduped
```

Thoughts?

**Comment by jimmywarting** [comment]
Like the idea of using plain Uint8array

how about instead of using streams use something like an async iterator/generator

- No node/browser specific stream is required.
- you can get a Readable stream with
  - nodes: `stream.Readable.from(iterator)`
  - whatwgs upcoming/suggested `ReadableStream.from(iterator)`
  - useful for both environment where service worker + native file system requires whatwg and node requires node stream to write streams
- even smaller bundle
- nodes stream are async iterable so you can already do `for await (let uint of stream) {...}`, whatwg stream specify this also but not implemented in any browser
- generating a stream of data can be as easy as `async function * { yield ... }`

**Comment by mafintosh** [comment]
streamx streams are async iterators as well. I’m actually using those a lot these days. Only word of caution is, that in a lot of cases you are gonna want to write a buffer for those as well aaaaaand boom you made your own stream impl 😆

**Comment by feross** [comment]
> how about instead of using streams use something like an async iterator/generator

Possible problems with this are – how to represent a writable stream? a transform stream? How do we handle backpressure? Also - the Node.js streams API has been present in WebTorrent since day 1 and I'd like to preserve the existing API so all user code continues to work.

**Comment by KayleePop** [comment]
[I made a little demo to help explain asyncIterators](https://flems.io/#0=N4IgtglgJlA2CmIBcBWAHAOhQFgDQgGMB7AOwGciFlDLYBDABzPihHwDMIEzkBtUEnTCIkIDAAsALmFhsaJSfAXUQAX1wChIsQCse+YgqWTqYOhBIAKAJQAdQWQCeJAgAJ2AVxeSIpV2YtXG1dge1dXAHoI10kAJzpydiJYsFcyOPghMNc6Jxd3LwIfPwAqGKIABSIAa3gwP0toAGUMoWsQ7PCk2JyAd3NJIMN012hXInZRqBbYzLB20JJw5cjo9nhJAnEY8XhXBhq6vwmdiDIp91iiVMld-Zr6pcYITuXhwdmyA-I9gF4+gbuDZbSwAAykkiYSCiB1qzwwxAizwiADcAEwRWFHEgRAAkwGgqlBdiWK1cjgg8FgUABEA+8C+pGYGD0pBsr1U2U5JGyUTSRA8sQIe3SsyE40m8RIUGuoyMAHN4LFzuwrqkAAyuAC0rgA7Gj1bzosQPNScrAKK4AEZ7BI5PJuRUkJV0STJVweMgWeW0wYJGkkIjjW5K1zEKB7XoCs3iOgovZusOxkiK7K5ZxuTzeXxLMpSmVgACSCqVMzmQQWr164i4e0scQ88ErpJWfMDPmFQUCw0oTdc4iIvVcJA8YBtypys3GJFgjnJlOpLFc1aUw-gLCX8HjS1uAvl2zpAHJznaLJwSHSRa0wAB+V7hPm3V3H63wAh0T22h0AcSULrdE50FODCmrA1q5CwuD8muQ5bF41QnlOpCzmGYqKDSpCdiGc5AV+tQ0t0GD3qs4S3GcoznNWrr+HQ55umQ2zCAkgxWjh1oeOw6yxBgrgAJoCoeNKxvG5TsZxoYeAwSbwecxF8uEECTI4ArLsxOx1KJNqoZk6Gvt0Ca7DhwGgUu9ZBgAjo2jbqakknQdhh5TmKUBzrEED7n6-SOCSZJhkyvYYLARDypYh4UlSEY0vmsojmOSqHj5ZLEXQ-R0q4h7vk8qWDAwapnAycr2hmrhOv+yRkIexHhWaACyrriBgVxeFAlh1bcjX+tcwRlPq6qJeE3IDfYRoxFKZDdKk0VFiWsRluKiZ0Gk14SvctSPEE7ommaOieoMMrqUCmwHjudw2kFQ7dFqKUDIl7yrdic2pP8bpVGtbJTcWiiKrN142CSI25RYkgnvd61bkqc4oGQ2TdL6QxMjlhzrScWKPI9zYrD2CCBcFlio6QGCCMI-WuDKBCjsYGBWkQLkYBYzqxAAEgAKjVAAyrgANT-KCAA8UAQCiAB8vMQGAPpkEKvy2CA+L4yQGBfG5ihkBgqqkJIAD6EbsB+sCSJyIARELctIwTRPwKovMRALwugq811pc6Q4VHlzCWJ8lAib8QtpBszNi-AAqSB7DJe-AUEAIyamU0fqn1iXctycjMAgRQ5jwohorqSBopHagaCAFvUAiZD6PIijKKIagALqqEAA)

**Comment by jimmywarting** [comment]
> how to represent a writable stream?

Having writable iterators isn't so common, but it's possible to pass a value in `g.next()`. to have some kind of writable interface where you can "emit" chunks and forget about them.

```js
function * generate_write_stream_to_save_to_storage () {
  let offset = 0
  while (true) {
    let uint8 = yield null
    storage.write(offset, uint8)
    offset += uint8.byteLength
  }
}

const generator = generate_write_stream_to_save_to_storage()
g.next(chunk1);
// "{ value: null, done: false }" could have returned a bucket, offset, if the write operation is open or close
g.next(chunk2);
// 2
// "{ value: null, done: false }"
```

---

It's really more simpler to think of everything as being only readable and consumable (and also transformable) instead having both read & write

for example, you can first create a <s>readable stream</s> iterator from one of the file and then you pass the readable to something that can consume it, eg a _"abstract chunk storage"_.

```js
// torrent.js
var readable = torrent.file(3).toIterator()
storage.write(readable)

// storage.js
// Instead of handing you a writeable stream Storage.js takes a readable iterator instead
class storage {
  write (readable) {
    for (let uint8 of readable) {
      // save chunk
    } 
  }
}
```

---

> a transform stream?

That's very easy
```js
// this is transform function accepts a iterator and returns a new iterator
function * multiply (iterable, x) {
  for (let chunk of iterable) {
    yield chunk * x
  }
}

function * add (iterable, x) {
  for (let chunk of iterable) {
    yield chunk + x
  }
}

var iterator = [1,2,3,4,5].values()
// cerate a new iterator by transforming it (multiply all value by 2)
iterator = multiply(iterator, 2) // yields 2,4,6,8,10 
iterator = add(iterator, 1) // yields 3,5,7,9,11 

// None of the transformation happens until you have something that consume it
// eg this log
console.log(...iterator) 
```

> How do we handle backpressure?

There is no builtin concept of backpressure with iterator/generators, but i imagine you can build a bucket using some async transformer that takes all chunks and counts how many it has while it's waiting for `g.next(chunk).then(fn)`. You can await some promise if it have more then 5 chunks in the bucket to signal a backpressure 

whatwg talked about having a [extendable queuingStrategy](https://github.com/whatwg/streams/pull/1083#discussion_r520923403)

`ReadableStream.from(asyncIterable, queuingStrategy = {})`

So some kind of possible shortcut would be to do

```js
var iterator = [1,2,3,4,5].values()
var queuingStrategy = new CountQueuingStrategy({highWaterMark: 2})
var asyncIterable = ReadableStream.from(iterator, queuingStrategy)
for await (let x of asyncIterable) {}
// dose something in parallel
```

**Comment by ThaUnknown** [comment]
@feross 
> would be nice to see some numbers

I ran a small benchmark where I downloaded and stored an >0.5GB file at ~200Mbit/s for ~25 seconds and got this:
all %'s are total CPU time
  - 48% bittorrent-protocol
    - 38% readable stream
      - 27% Buffer.from
      - 6.5% process.nextTick
    - 8% bitfield updates, announcement etc
  - 29% simple peer
    - 16% Buffer.from
    - rest is just function calls, assume WRTC?
  - 15% queue microtask
    - 8% store
    - rest kinda went poof, queue microtask itself?
  - 6% idle wire callback
  - ~4% random garbage

**Comment by ThaUnknown** [comment]
for the sake of updating this, now that render-media is dropped in v2 and webtorrent itself is pending replacing readable with streamx this tree [npm list --prod -a readable-stream] looks like this:
```
webtorrent@1.8.24
├─┬ bittorrent-protocol@3.5.5
│ └── readable-stream@3.6.0
├─┬ chunk-store-stream@4.3.0
│ ├─┬ block-stream2@2.1.0
│ │ └── readable-stream@3.6.0 deduped
│ └── readable-stream@3.6.0 deduped
├─┬ create-torrent@5.0.2
│ ├─┬ filestream@5.0.0
│ │ └── readable-stream@3.6.0 deduped
│ └── readable-stream@3.6.0 deduped
├─┬ multistream@4.1.0
│ └── readable-stream@3.6.0 deduped
├─┬ simple-peer@9.11.1
│ └── readable-stream@3.6.0 deduped
├─┬ torrent-discovery@9.4.13
│ └─┬ bittorrent-tracker@9.19.0
│   └─┬ simple-websocket@9.1.0
│     └── readable-stream@3.6.0 deduped
└─┬ utp-native@2.5.3
  └── readable-stream@3.6.0 deduped
  ```

**Comment by ThaUnknown** [comment]
TODO: bencode -> uint8

**Comment by ThaUnknown** [comment]
this is done as of 2.0.24, streamx is used where we needed pipelines and duplex streams, everywhere else I've used async iterators as they are way smaller simpler and faster, tho blocking

readable-stream isnt dropped in node for depenencies like utp-native, and potentially others, as there's no need for dropping them in node, same with buffer

gonna treat the "drop Buffer" part in this issue too, so that's still TODO, but we're only like 3-4 PR's away from dropping buffer in browser as well

**Comment by ThaUnknown** [comment]
only a few packages use Buffer:
clone - which supports fallback for when buffer doesn't exist, so it's not required
idb-chunk-store - [PR has been pending for almost a year](https://github.com/SocketDev/idb-chunk-store/pull/6), I pinged people in SocketDev but who knows when they'll merge is
thirty-two - [PR pending](https://github.com/chrisumbel/thirty-two/pull/21)
lt_donthave - it actually dropped buffer ages ago, but it doesn't have a release config [shocker] so we're using some old version

**Comment by ThaUnknown** [comment]
once lt_donthave is fixed we'll officially have dropped from 875kb bundle size down to a mere 208kb
