### ISSUE TITLE
Two controlbars under video

### ISSUE THREAD

**Issue by atomtm** [webtorrent/webtorrent#1980]
Hello everyone ! 
Can someone please help me understand why I get two controlbars under the video in this https://jsfiddle.net/bsx8dnt0/ ? I am using Firefox 83.0 64bit.
Thank you

**Comment by ThaUnknown** [comment]
this sounds like a [plyr](https://github.com/sampotts/plyr) issue not webtorrent, also doesn't happen on 1.20.110 Chromium: 88.0.4324.192

**Comment by alxhotel** [comment]
Hi @atomtm,

As @ThaUnknown mentioned, this issue seems to be related to the library you are using to create the video player. So I'm closing this.
