### ISSUE TITLE
Torrents hanging, requires a restart on webtorrent desktop

### ISSUE THREAD

**Issue by stingr4y78** [webtorrent/webtorrent#1981]
Hi, I've been using Webtorrent, which is awesome by the way, but I've hit a stumbling block I cant seem to get past.

I am trying to network with several colleagues to provide on-demand mp4 access, and I'm using Webtorrent desktop to host the torrent files. The problem is though, unless I completely restart Webtorrent, it hangs and my .html file won't launch the video. This is fixed by rebooting the webtorrent desktop client. It's every time as well, not sporadically, it'll be available to launch for approx 5 minutes after a restart then hangs again.

ANy ideas?

**Comment by Iskander0** [comment]
You are seeding files from a pc 24/7?

**Comment by R0quef0rt** [comment]
I have exactly the same issue. After seeding files from WebTorrent Desktop for anywhere from 15 minutes to 24 hours, they inevitably begin failing until I restart the client. 

I'm inclined to think this is a tracker issue. I tried loading files in several browser tabs, then closing WebTorrent Desktop. They continued to work for several hours, before starting to fail, just like WebTorrent Desktop always does.

It's almost like the peers get disconnected or blocked from the trackers. The files are undiscoverable until you re-initiate the connection by restarting the desktop client.

**Comment by R0quef0rt** [comment]
See the above PR. I found a solution to this problem, but I have not figured out how to integrate it yet. If anyone can help, it would be greatly appreciated!

For the time being, you can just run this function in the View > Developer > Show Developer process console:

`
let i = 1
function forcePeerGC() {
  let peer = new RTCPeerConnection()
  setTimeout(() => {
    peer.close()
    peer = null
  }, 10)
  console.log(i++)
  if (!(i % 20)) {
    // try to invoke GC on each 20ish iteration
    queueMicrotask(() => { 
      console.log('Collecting garbage.')
      let img = document.createElement("img")
      img.src = window.URL.createObjectURL(new Blob([new ArrayBuffer(5e+7)])) // 50Mo, more or less, as you wish to force/invoke GC cycle run
      img.onerror = function() {
        window.URL.revokeObjectURL(this.src)
        img = null
      }
    })
  }
}

setInterval(forcePeerGC, 3000)
`
It will fix the problem, and it will stay fixed until you restart WebTorrent Desktop.

**Comment by DubiousTunic** [comment]
Any idea why this might not be working for me?

**Comment by DubiousTunic** [comment]
SS

**Comment by DubiousTunic** [comment]
This error also occurs in BiglyBT's (Vuze) WebTorrent plugin:

https://ibb.co/3dtJZg3
