### ISSUE TITLE
how to disable instant.io on chrome

### ISSUE THREAD

**Issue by TomerGamerTV** [webtorrent/webtorrent#1982]
at the title says how do i disable it? or remove it

**Comment by Iskander0** [comment]
What do you mean by "remove"? It's a website...

**Comment by TomerGamerTV** [comment]
> What do you mean by "remove"? It's a website...

idk why but then I'm opening a magnet file its opens in instant.io and I don't know how to disable it

**Comment by ThaUnknown** [comment]
under settings in browser find permissions > handlers > magnet and remove instant.io

**Comment by TomerGamerTV** [comment]
> under settings in browser find permissions > handlers > magnet and remove instant.io

the website i tested it on didnt open torrent but it worked thx!

**Comment by imxieke** [comment]
# fuck the function and author
