### ISSUE TITLE
How to add torrent for download from file? Seems not working.

### ISSUE THREAD

**Issue by Oconnel80** [webtorrent/webtorrent#1985]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by Oconnel80** [comment]
Can someone give me a simple example how to add torrent from file located on user disk for download? When I use in HTML input type="file" element I can't add torrent this why. Perhaps because the filepath for security reasons in browsers are changed to "fakepath". And than I got invalid torrent identifier error on client.add function. Can someone give me simplest example in HTML how to achieve this? Or this is a bug/issue?

**Comment by Iskander0** [comment]
var WebTorrent = require("webtorrent-hybrid")
var client = new WebTorrent("tracker: wss://tracker.openwebtorrent.com")

client.seed(__dirname + "/video.mp4", function(torrent) {
        console.log(torrent.magnetURI)
})

**Comment by alxhotel** [comment]
Hi @Oconnel80,

I think the code from Instant.io can help you: https://github.com/webtorrent/instant.io/blob/master/client/index.js
