### ISSUE TITLE
The main file was downloading fine, but the .srt was waiting forever

### ISSUE THREAD

**Issue by blueskybreeze** [webtorrent/webtorrent#1986]
**What version of this package are you using?**
WebTorrent 0.24.0  (the desktop app)

**What operating system, Node.js, and npm version?**
macOS

**What happened?**
I was experimenting and the main file was downloading fine, but the .srt file (the subtitle) was at 50%, while the main file already was playing smoothly and just needing the .srt to go with it. But there seems no way to put the .srt into Maximum priority.  So now it may need the main file to be at 100% and then the subtitle at 100%, for them to be useful. Supposedly, all it takes is 3 seconds for the .srt to download, and the files can be viewed immediately, but now it will need another 45 minutes just simply because the .srt isn't there.

**What did you expect to happen?**
Let the user set the priority to maximum, or for any .srt or sutitle folder, simply download it first because they are usually quite small (can be 35kb to at most a few MB)

**Are you willing to submit a pull request to fix this bug?**
not a developer for WebTorrent the app

**Comment by ThaUnknown** [comment]
according to docs, webtorrent prioritizes streamable files first, which subtitles aren't, you could, you can manually change the priority with `file.select()` in the webtorrent process
