### ISSUE TITLE
 src=(unknown) with appendTo() method on chrome

### ISSUE THREAD

**Issue by jackhadrill** [webtorrent/webtorrent#1987]
I am experiencing the same behaviour as described in #1556 in Chromium on MacOS.

Version 89.0.4377.0 (Developer Build) (x86_64)

**Comment by jackhadrill** [comment]
My bad, Chromium doesn't support proprietary codecs. See here for more info: https://www.chromium.org/audio-video

Hopefully this will help someone else one day! :-)

**Comment by ThaUnknown** [comment]
> My bad, Chromium doesn't support proprietary codecs. See here for more info: https://www.chromium.org/audio-video
> 
> Hopefully this will help someone else one day! :-)

this data is quite a bit outdated, but oh well
