### ISSUE TITLE
FAST extensions and reqq

### ISSUE THREAD

**Issue by arvidn** [webtorrent/webtorrent#1995]
**What version of this package are you using?**

"WebTorrent 0.0.1.2" (that's the version advertised in the extended handshake).

**What problem do you want to solve?**

As a client uploading or seeding content, I would like to be able to apply back-pressure to the WebTorrent client, telling it that it has requested more outstanding pieces than I'm allowing it. I (as an uploading bittorrent client) want to cap the amount of memory I need to allocate to store the list of outstanding requests.

Right now it seems WebTorrent either has no limit, or has a very high limit (several thousands) of outstanding piece requests to a single peer.

The immediate symptom of this problem is that a seeding client is likely to just drop peer requests that exceed their limit, causing the connection to stall and eventually time out.

**What do you think is the correct solution to this problem?**

there are two prongs to solving this problem. The immediate issue can be relieved by supporting the FAST extensions of 2008. Documented [here](https://www.bittorrent.org/beps/bep_0006.html). These new messages patch up a few holes in the original protocol.

Some of those FAST messages can simply be ignored. However, the ones that need to do something are:

HAVE_ALL, HAVE_NONE and REJECT_REQUEST. The last one allows a client to actively acknowledge it received a request, and says it will not service it. The requesting client can then keep accurate records of what requests it still has outstanding. This is especially helpful around CHOKE and UNCHOKE messages. But it can also be used to issue back-pressure when an outstanding-request queue limit is exceeded.

The other, presumably much simpler, feature would be to recognize and honor the "reqq" field in the extension message. This field is in the top level extension handshake dictionary, sibling to the client name (`v`). The value of the "reqq" field is the max number of outstanding piece request messages the client accepts. i.e. any REQUEST message sent to this client, where the corresponding PIECE message hasn't been returned, counts as an outstanding request.

**Are you willing to submit a pull request to implement this change?**

No, but I'd be happy to assist in explaining any aspects of the protocol.

**Comment by rom1504** [comment]
this seems to be an important (blocker status) issue to solve for efficient communication between libtorrent and webtorrent

**Comment by arvidn** [comment]
not having a limit of the number of outstanding requests one allows to queue is a potential DoS vector. If WebTorrent doesn't have a limit, i would also recommend it adds one.

**Comment by feross** [comment]
This is something we should look at.

**Comment by ThaUnknown** [comment]
> This is something we should look at.

this is very needed for WebTorrent to be functional at scale, node doesn't really support many connections very well [https://bugs.chromium.org/p/chromium/issues/detail?id=825576], and it can't have many connections at once either, so creating any form of mass-scale hybrid server isn't possible without libraries like libtorrent

**Comment by ThaUnknown** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

yes

**Comment by paullouisageneau** [comment]
> Is this still relevant?

Yes it is. It looks like it has been delayed to Q1 2022 on the roadmap.

**Comment by paullouisageneau** [comment]
FYI, I'm planning to work on this to implement both the Fast extensions (from BEP 6) and the reqq field (from BEP 10). I should start in a few days.

**Comment by DiegoRBaquero** [comment]
@paullouisageneau awesome! Please let us know if there's anything we can help with, and feel free to work in a PR so we can all track and comment

**Comment by paullouisageneau** [comment]
I opened the PRs (https://github.com/webtorrent/webtorrent/pull/2243 and https://github.com/webtorrent/bittorrent-protocol/pull/75) to add Fast Extension. I'll also implement reqq support on another one as it is independent and simpler to implement.

**Comment by paullouisageneau** [comment]
I added reqq field support in https://github.com/webtorrent/webtorrent/pull/2246.

Reviews are welcome!

**Comment by polarathene** [comment]
From webtorrent/bittorrent-protocol#75 :

> This is the first step to fix webtorrent/webtorrent#1995.

Should this actually be closed, or wait on the related PRs that haven't yet been merged?

**Comment by DiegoRBaquero** [comment]
Correct, Github auto closed. I'll review now

**Comment by paullouisageneau** [comment]
@DiegoRBaquero Thanks, I rebased the last PR https://github.com/webtorrent/webtorrent/pull/2246.

**Comment by paullouisageneau** [comment]
@DiegoRBaquero I opened a PR with fixes to bittorrent-protocol: https://github.com/webtorrent/bittorrent-protocol/pull/79
