### ISSUE TITLE
Default electron/webtorrent setup crashes

### ISSUE THREAD

**Issue by nkavian** [webtorrent/webtorrent#2002]
**What version of this package are you using?**

webtorrent-hybrid: 4.0.3

**What operating system, Node.js, and npm version?**

mac: 10.14.6
node: 12.18.3
npm: 6.14.6
electron: 11.2.3

**What happened?**

Use the default [electron-quick-start](https://github.com/electron/electron-quick-start) and add the webtorrent [quick example](https://webtorrent.io/docs). Run `npm install`, `npm start`, wait for the console to print `torrent added`, and then close the window.

Notice the console prints an error and Mac OS displays a crash dialog.

**What did you expect to happen?**

Expected the application to shutdown gracefully and not crash.

**Are you willing to submit a pull request to fix this bug?**

Not knowledgable enough about how to debug webtorrent code, but here is a branch to easily run the above mentioned scenario

https://github.com/nkavian/electron-quick-start/tree/webtorrent-exit-crash

https://github.com/electron/electron-quick-start/compare/master...nkavian:webtorrent-exit-crash

**Comment by alxhotel** [comment]
Hi @nkavian,

Thanks for the feedback!

The only error I see is:

```
exited with signal SIGSEGV
```

Is this the same error you are describing? If so, I think this is related to WebRTC

**Comment by nkavian** [comment]
Yes, correct.

**Comment by feross** [comment]
I don't recommend using `webtorrent-hybrid`. It uses an unreliable WebRTC implementation called `wrtc`.

Since you're running Electron you have better options with `webtorrent`.

1. Use `webtorrent` from a main process (lets you connect to TCP, uTP peers)

2. Use `webtorrent` from a renderer process with `nodeIntegration` (TCP, uTP, WebRTC peers)

3. Use `webtorrent from a renderer process without `nodeIntegration` (WebRTC peers only)

**Comment by nkavian** [comment]
I'm not sure what to say. Could this bug then be reassigned to wrtc with more details and/or can you update your documentation to tell people not to use `webtorrent-hybrid`.

Options 2 and 3 aren't secure enough in my project. I'm not sure I understand option 1.

In my context, I wanted to support browser to be able to connect to the torrents in the electron app and vice versa.

I'll also just close the issue so I can stop tracking it and look for alternate solutions. Thanks.
