### ISSUE TITLE
WebTorrent is extremely slow to add a torrent from its hash

### ISSUE THREAD

**Issue by redbrain** [webtorrent/webtorrent#2009]
### Specs/version info:

I'm getting the latest version of WebTorrent from JSDelivr. At time of writing, that's v0.115.0.
I'm using Arch Linux and Chromium 88.0.4324.152, although I don't think this bug is platform-specific.
***
### Issue:
Using `client.add` with a torrent's info hash takes a *very* long time to begin torrenting.
***
### Example:
(this is testable using instant.io, btorrent.xyz, or anything else that wraps WebTorrent)

You can find a magnet link to Sintel (an open-source movie) from the WebTorrent Getting Started docs.
Entering this link in Instant or btorrent immediately begins downloading the torrent. This is expected behavior, woohoo!

Here's the info hash from that magnet: `08ada5a7a6183aae1e09d831df6748d566095a10`
Entering this hash into Instant.io, btorrent.xyz, etc, appears to never begin the download. This is not expected behavior.

I have the hash test open on Instant.io still. It got the metadata after about 10 minutes, but hangs at 0.0% progress.

No problem outside of the WebTorrent-verse: Entering the info hash into qBittorrent (libtorrent-based) works in about 2 seconds.

*EDIT 1: Sometimes it will never start, sometimes it works perfectly. Perhaps the tracker servers are behaving unreliably?*
***
### Are you willing to submit a pull request to fix this bug?
I don't have the technical knowledge required to diagnose the issue, let alone write and submit a PR.
However, it should be a priority to fix because it's a basic function of a torrent client.

**Comment by ThaUnknown** [comment]
this is an issue with the tracker or torrent you used, not webtorrent, either the tracker took ages to find peers for you or the torrent lacks WRTC compatible seeders

**Comment by redbrain** [comment]
The hash (as explained above) was WebTorrent's Sintel demo, so it definitely has WRTC seeders.
I guess the tracker wouldn't find peers if it's a hash (although it works as a magnet link), which is annoying.
I'll close the issue since it's not relevant. That being said, do you know why would this be the case, and potential solutions?

**Comment by ThaUnknown** [comment]
I've noticed this happens a lot with the Sintel demo torrent, guessing because it has some webseed and some connection limit? For testing I recommend hosting your own file via WebTorrent Desktop

**Comment by stefanodecillis** [comment]
In my case I'm using two simple clients (peer and seeder) and it takes ages to connect the first time (same machine, nodejs). I find it strange that when I restart the seeder, it goes immediately. I don't know if there are some timeout on the seeder but I will try to investigate more on this (hoping it's not my bad)
