### ISSUE TITLE
[feat req] Download only specific files from a torrent

### ISSUE THREAD

**Issue by redbrain** [webtorrent/webtorrent#2011]
### What version of this package are you using?
Latest from JSDelivr (0.115.1)

### What problem do you want to solve?
I'd like to be able to only choose one file to download from a torrent.
For example, with the example "Sintel" torrent, perhaps I want to download only "Sintel.mp4" and not any other files in the torrent.
Some torrent clients (such as qbittorrent) have this functionality already. I couldn't find a way to do this from the doc pages.

### What do you think is the correct solution to this problem?
Adding a function to Torrent class that limits it to ignore specific file(s), or ignore all files but some specific files.

### Are you willing to submit a pull request to implement this change?
I'm currently unfamiliar with the library's code, but I could write something functional for a PR if no one else contributes.

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#filedeselect
https://github.com/webtorrent/webtorrent/issues/164#issuecomment-248395202

**Comment by redbrain** [comment]
Thank you! I somehow missed that in the doc pages, probably because I thought it would be a Torrent option and not a File option.
Closing.
