### ISSUE TITLE
Sending the Bat-Signal for Feross!

### ISSUE THREAD

**Issue by markmdscott** [webtorrent/webtorrent#2012]
@feross we in libtorrent land request your assistance!

So WebTorrent was designed from the ground up with good streaming media support in mind. Arvid and I are trying to improve libtorrent's support for smooth streaming of media playback. Specifically we're working on the piece picking algorithm, which right now is more suitable for the default rarest-first. We're adding the ability to sequentially stream a range from a torrent (similar to WebTorrent's file.createReadStream({start,end}) API call) but the basic piece picking could also be improved as well. Towards this end we had some questions of you, like how you built WebTorrent's streaming/sequential piece picking algorithm. Like for every piece in the range does it make a "global" decision (among all connected peers) or a local one (eg. which blocks from peer A should I pick given A's available pieces?). Now obviously a global decision is more expensive, and libtorrent's existing streaming picker does that, along with employing deadlines etc., though it is not scalable and there are issues with it. Therefore the normal (rarest-first) picker has a sequential download mode to try to be good enough, but it makes a local decision, per peer. And I'm wondering, based on your experience with WebTorrent, how to maybe improve things here. So how did you make sequential/streaming piece picking work in WebTorrent, and how does it interact with the rarest-first picker?

(To quote Arvid on how piece picking works in libtorrent:

"The streaming picker asks a different question than the normal one. The normal piece picker asks:
Peer A just completed a block, which is the next block I should request from peer A?
Whereas the streaming picker needs to ask:
A block was just completed, which is the next block I should pick and from which peer?")

https://github.com/arvidn/libtorrent/pull/5996#issuecomment-784749886

(I sent you a couple of emails over the course of more than a week in addition to initially @mentioning you in the PR comment, to no avail.)

**Comment by markmdscott** [comment]
@feross are you there perchance?

**Comment by markmdscott** [comment]
@feross are you there at all?

**Comment by feross** [comment]
Hey, I'm behind on GitHub notifications (as always). I'll do my best to get to this as soon as I can. Haven't received any emails from you, btw.

**Comment by markmdscott** [comment]
Thanks for the acknowledgement Feross! I appreciate it!

Re: Emails, check your spam folder? My first email was Feb 24, then Mar 4, then Mar 10, and finally Mar 18.

I've looked at the torrent.js file, which I think contains the piece picking code. It appears that for either sequential or rarest-first strategies you pick pieces from a peer at a time and submit them to request them from the peer. Like you don't choose among all existing connected peers (wires) which to best request a given piece from. You don't do this sort of "global" optimization.

Though it appears you do kind of try to replace pieces requested of a peer to a different peer. What exactly does the `_hotswap()` method do?

From the two line comment I wasn't sure of its role. Let me know if this is correct:

In either rarest-first or sequential mode, a peer who is being requested a piece from may be swapped out for another peer to request the piece from based on superior bandwidth of the replacement peer?

If this is correct, under what conditions does this swap happen?

And what was the motivation for this logic?

Btw what does the `_reservations` member represent?
