### ISSUE TITLE
Unable to add torrent from store

### ISSUE THREAD

**Issue by arnWolff** [webtorrent/webtorrent#2014]
While re-adding torrent from store, the `_verifyPieces` method failed with `piece invalid` error.

For example, this would failed, even if stored datas are valid:

`client.add(parsedTorrent, {store: idb})`

This line is the problem: 
[torrent.js#L589](https://github.com/webtorrent/webtorrent/blob/a860773ec4d379cb10922b60de3489559c6913cd/lib/torrent.js#L589)

`const length = index === this.pieces.length - 1 ? this.lastPieceLength : undefined`

Should be i guess:

`const length = index === this.pieces.length - 1 ? this.lastPieceLength : this.pieceLength`

Not sure the reason `length` is set to `undefined`?!

**Comment by ThaUnknown** [comment]
what lib did you use for the custom IDB store?

**Comment by arnWolff** [comment]
I tried  `https://github.com/xuset/indexeddb-chunk-store` and `https://github.com/substack/idb-chunk-store`.
Both failed but work on older webtorrent versions.

Thank you.

**Comment by ThaUnknown** [comment]
> I tried [indexeďdb-chunk-store](https://github.com/xuset/indexeddb-chunk-store) and [idb-chunk-store](https://github.com/substack/idb-chunk-store).
> Both failed but work on older webtorrent versions.
> 
> Thank you.

this isnt a webtorrent issue, this is an issue with the libraries you used, https://github.com/xuset/indexeddb-chunk-store/pull/20
that change isn't out of spec, however it could be improved, I recommend u make a PR for it

**Comment by jhiesey** [comment]
OK I have a fix in webtorrent in #2015.

@arnWolff the problem with always passing `this.pieceLength` like you suggested is that it causes the data to be copied an extra time in most chunk store implementations.

My solution here is to not pass `length` at all, but arguably `indexeddb-chunk-store` shouldn't be using `'length' in opts` to check if it's defined.

**Comment by feross** [comment]
Thanks for the fix, @jhiesey! We should ideally fix this in https://github.com/xuset/indexeddb-chunk-store too, since it shouldn't be using `in` to check for the existence of `length`, but rather if it's `!= null` (which checks for `null` and `undefined`)

**Comment by ThaUnknown** [comment]
> Thanks for the fix, @jhiesey! We should ideally fix this in https://github.com/xuset/indexeddb-chunk-store too, since it shouldn't be using `in` to check for the existence of `length`, but rather if it's `!= null` (which checks for `null` and `undefined`)

again, this was already addressed in https://github.com/xuset/indexeddb-chunk-store/pull/20
