### ISSUE TITLE
Webtorrent does not start download or report any errors on WebKit browsers (including Safari)

### ISSUE THREAD

**Issue by anesuc** [webtorrent/webtorrent#2020]
**What version of this package are you using?**
Using include latest from CDN. I'm not sure how to check the exact version.

**What operating system, Node.js, and npm version?**
Ubuntu 18.04 (and MacOS, iOS)

**What happened?**
Does not start downloading the torrent. I am seeding from both a web browser and Node. Downloads in Chrome and Firefox.

**What did you expect to happen?**
Download the torrent.

**Are you willing to submit a pull request to fix this bug?**
Yes if I find out what the issue is and how to fix it.

**Comment by ramonmedeiros** [comment]
Same issue here

**Comment by ramonmedeiros** [comment]
One thing that helped me was to change the trackers in the magnet link

**Comment by anesuc** [comment]
> One thing that helped me was to change the trackers in the magnet link

To which ones may I ask?

**Comment by ramonmedeiros** [comment]
I first got the trackers from the example in the quick start https://webtorrent.io/intro

Now I'm looking for a better solution to only select the more fast to me. If you have some suggestion, please let me know

**Comment by anesuc** [comment]
I looked there and it's just the magnet link and no specific trackers. Are you just testing that specific magnet link or have you used your own magnet link? If so can you just list them here so that I can test them?

**Comment by ramonmedeiros** [comment]
Right now I'm using this trackers in my app:

https://github.com/ramonmedeiros/juan_carlos_web/blob/main/src/Watch.js#L33

**Comment by SilentBot1** [comment]
Hi @anesuc,

Are you able to re-run your tests with the following variable set in your browser while performing your tests and post the results? `localStorage.debug = '*'`

As noted by @ramonmedeiros, it's possible that the default WebTorrent trackers were currently unavailable while performing the tests, so hosting and adding your own to the magnet links would help, though this may not be necessary based on the results above.

Please understand that **there must be no reference to any copywritten work** in any of the examples provided, as we don't support or aid with piracy.

If there's any issues with this, just let me know.

Many thanks,
Brad
