### ISSUE TITLE
npm install latest webtorrent failed

### ISSUE THREAD

**Issue by CoelisMyName** [webtorrent/webtorrent#2027]
What version of this package are you using?**

Win10, Node.js 15.14.0, and npm 7.5.2

npm return this message

npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/feross/http-node.git
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

and install failed

**Comment by alxhotel** [comment]
Maybe these SO answers helps you: https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository

**Comment by CoelisMyName** [comment]
> Maybe these SO answers helps you: https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository

thank u. and i met another issue. i delete all the cache manually. and everything fine.
