### ISSUE TITLE
IMPOSSIBLE TO REMOVE. EVERY MAGNETIC LINK WILL OPEN IN THIS ONLY.

### ISSUE THREAD

**Issue by DhananjayBhosale** [webtorrent/webtorrent#2038]
The solution which works-
Chrome doesn't really have any handler settings directly so visit **_### chrome://settings/handlers_** & from here you can disable or change your handler.

**Comment by alxhotel** [comment]
Hi @DhananjayBhosale,

Please don't use all caps in the title and add more info in your description box.

If you are using Chrome, under settings find permissions > handlers > magnet and remove the program
