### ISSUE TITLE
Add support WebTRANSPORT.

### ISSUE THREAD

**Issue by korenevskiy** [webtorrent/webtorrent#2047]
Welcome new technology in JS this WebTRANSPORT with UDP.
Add support WebTransport.

**Comment by DiegoRBaquero** [comment]
For reference: https://w3c.github.io/webtransport/

Still not a stable API.

But this is for client-server communication, how would this help WebTorrent?

**Comment by korenevskiy** [comment]
> For reference: https://w3c.github.io/webtransport/
> 
> Still not a stable API.
> 
> But this is for client-server communication, how would this help WebTorrent?

there are many modes. The browser will be a server or a client to choose from. What is the point of creating a technology in JS that is similar to the existing ones? Because this technology should solve the problems of connections between browsers. The technology just wasn't tested on a large scale. In the Google lab, she went to the synthetic tests successfully. Stable status is a matter of time. Do you think this technology does not bring anything new? passed synthetic tests. Stable status is a matter of time. Do you think this technology is something new? Was it just made up?

**Comment by ThaUnknown** [comment]
from what I understand webtorrent wants to be at least a bit backwards compatible, so I doubt something that new would be used?

**Comment by korenevskiy** [comment]
@DiegoRBaquero 
I think you're right.
It's a pity that the browser-browser can not be linked.
But please explain, according to the specified link it is written clearly. That Webtransporter is intended to replace WebSockets. Please read this immediately in the introduction to the W3C.

@ThaUnknown 
Adding a new one does not mean abandoning backward compatibility.
But if the new one gives a performance boost, then why not support 2 technologies at once?

**Comment by DiegoRBaquero** [comment]
WebTransport could help the tracker connection to save memory as websocket consume much more resources, but it's not helpful in the p2p part of WebTorrent, sadly :(

**Comment by korenevskiy** [comment]
1. How much will WebTransport help with the tracker? will it help to increase the speed of peer search peers ( by 2 times)?

> WebTransport could help the tracker connection to save memory as websocket consume much more resources, but it's not helpful in the p2p part of WebTorrent, sadly :(


 2. Does WebTransport perform worse when loading, or does it not matter?

**Comment by DiegoRBaquero** [comment]
1. Speed, I don't think it reaches 50% increase, websockets are fast. But would help the tracker owner save costs/scale more.
2. Don't think it matters

**Comment by DiegoRBaquero** [comment]
Moved to https://github.com/webtorrent/bittorrent-tracker/issues/360
