### ISSUE TITLE
ES8 Target

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2055]
- [ ] addr-to-ip-port
- [ ] bep53-range
- [ ] bittorrent-dht
- [ ] bittorrent-peerid
- [ ] bittorrent-protocol
- [ ] bittorrent-tracker
- [ ] bittorrent-lsd
- [ ] create-torrent
- [ ] fs-chunk-store
- [ ] instant.io
- [ ] ip-set
- [ ] load-ip-set
- [ ] lt_donthave
- [ ] magnet-uri
- [ ] node-bencode
- [ ] parse-torrent
- [ ] render-media
- [ ] string2compact
- [ ] torrent-discovery
- [ ] torrent-piece
- [ ] ut_metadata
- [ ] ut_pex
- [ ] webtorrent
- [ ] webtorrent-cli
- [ ] webtorrent-desktop
- [ ] webtorrent-fixtures
- [ ] webtorrent-hybrid
- [ ] webtorrent.io

Things we can use:

- `const / let`
- `async / await`
- classes
- block-scoped variables
- arrow functions
- `Array.includes`
- template literals
- de-structuring
- ESM

**Comment by DiegoRBaquero** [comment]
For the first two, they are supported in ES9 (2018), which we don't plan to support YET, because it drops Firefox 78 support. Less use of Buffer is def on the way :)

**Comment by DiegoRBaquero** [comment]
Example https://github.com/webtorrent/bittorrent-tracker/commit/e5994d2ebdec10fe2165e31f5b498382eeeaaf5f

**Comment by DiegoRBaquero** [comment]
Example https://github.com/webtorrent/bittorrent-protocol/commit/3d3e244319036583230d64824ce1388287233e02

**Comment by king-11** [comment]
Hey @DiegoRBaquero I would like to work on it do you have any suggestions on which section I can work on refactoring. Thanks!
