### ISSUE TITLE
Publish new Wormhole chunk stores

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#2057]

**Comment by feross** [comment]
We just published the File System Access API chunk store: https://github.com/SocketDev/fs-access-chunk-store

It's used in production on Wormhole and it performs nearly as fast as `memory-chunk-store` while using a lot less RAM, obviously.

The [File System Access API](https://web.dev/file-system-access/) is currently only supported in Chromium browsers, so this chunk store needs to be used with an IndexedDB or memory fallback.

**Comment by feross** [comment]
We decided against releasing our Cache API chunk store since it doesn't seem possible to reliably delete chunks from storage using this browser API.

Our Storage Foundation API chunk store is still pretty rough and experimental so we're holding off on publishing it since we're not currently using it in production on Wormhole. @ftreesmilo has published an experimental chunk store using this API here: https://github.com/ftreesmilo/storage-foundation-chunk-store

We do have a modified `idb-chunk-store` with many fixes that we want to release or publish as a fork. Leaving this issue open until we've done that.

TODO: Publish the Wormhole `idb-chunk-store`

**Comment by jimmywarting** [comment]
Fyi, i created a [adapter/polyfill for native file system](https://github.com/jimmywarting/native-file-system-adapter)

You are able to choose from different underlying sources such as the sandboxed api, indexeddb, memory, and even the cache api: here is test & performances: https://jimmywarting.github.io/native-file-system-adapter/example/test.html

**Comment by feross** [comment]
Very useful – thanks for sharing.

**Comment by feross** [comment]
New `idb-chunk-store` implementation published: https://github.com/SocketDev/idb-chunk-store

Removed extra copies, removed bugs where it stored the full `ArrayBuffer` instead of just the specific `Uint8Array` view. Removed extra nextTicks. Handled forgotten error cases. And more. It's published under the same `idb-chunk-store` name as version 1.0.0.
