### ISSUE TITLE
Large Video very slow to start

### ISSUE THREAD

**Issue by CoelisMyName** [webtorrent/webtorrent#2076]
**What version of this package are you using?**
0.118.0

**What operating system, Node.js, and npm version?**
Windows10 20H2 Node.js v15.14.0 npm 7.7.6

**What happened?**
i followed the demo and made a server. server create torrent file contain video url and my tracker url. the browser load torrent file and use renderTo API. however, the browser makes hundreds of request to pull video. almost downloaded all the video (3.02GB). i am pretty sure the video file is MP4 based (H264 AAC). before download complete, the video cannot play. therefore cannot seek.

**What did you expect to happen?**
i expect to start playing video as soon as press play button and able to seek

**Are you willing to submit a pull request to fix this bug?**

**Comment by SilentBot1** [comment]
Hi @CoelisMyName,

Are you able to provide the results of running `ffprobe` on the file that you're attempting to playback? For MP4's, it's recommended that the `moov` atom is moved to the start of the file to allow quicker loading and streaming of the content, without having to request the end of the file first. In ffmpeg, this is done with the flag `-movflags +faststart`.

If there's any issues with providing this, please let me know.

Many thanks,
Brad Marsden

**Comment by CoelisMyName** [comment]
`PS D:\test> ffprobe.exe -hide_banner  .\video.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : video
    encoder         : Lavf58.45.100
  Duration: 02:29:44.26, start: 0.000000, bitrate: 2893 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x872 [SAR 1:1 DAR 240:109], 2758 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler`
i try -movflags +faststart, and it solve slow start problem. but seeking still need to wait download all the chunck (between zero and seeking location i guess). is there any way webtorrent just pull the chunk really needs first.
![QQ截图20210523104020](https://user-images.githubusercontent.com/63242816/119246407-f2ae9580-bbb3-11eb-8fd4-5f402b2a43ec.png)
