### ISSUE TITLE
Wormhole Sponsor Image barely visible on GitHub Dark

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2079]
<img width="541" alt="Screen Shot 2021-05-21 at 10 57 17 AM" src="https://user-images.githubusercontent.com/2006839/119165634-52296b80-ba23-11eb-9548-cbb187f4d165.png">

**Comment by ThaUnknown** [comment]
![logo](https://user-images.githubusercontent.com/6506529/119168045-cafae880-ba60-11eb-890b-e98b3d405657.png)
bit big, but same filesize :P
