### ISSUE TITLE
WebTorrent Video URL Path Quetion

### ISSUE THREAD

**Issue by jeonmogeon** [webtorrent/webtorrent#2085]
I cant understand why video's url is host's url.

I thought that it has to be ip address of each peers but it was the domain of host server. 
![image](https://user-images.githubusercontent.com/53516171/119442578-149a4a80-bd63-11eb-9760-fce1a61676ab.png)

so is it just a proxy address to peer..?

can anybody explain about it please...

**Comment by jhiesey** [comment]
It's a [web seed](https://www.bittorrent.org/beps/bep_0019.html); a non-WebRTC peer.

It keeps the torrent available even if all other peers are offline.
