### ISSUE TITLE
WebTorrent Desktop doesn't seed to browser without restart

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent#2087]
**What version of this package are you using?**
latest version of webtorrent desktop with instant.io and my own WebTorrent site

**What operating system, Node.js, and npm version?**
ubuntu 16.04 

**What happened?**
(pdf) files typically don't seed from WebTorrent Desktop to instant.io or my own site. (the instant.io link from WebTorrent desktop just hangs up at "adding"). but if webtorrent desktop is restarted they seed for a moment. 

**What did you expect to happen?**
i expect the web links to be constantly accessible when WebTorrent Desktop is seeding. these torrents are added with a .torrent file but i believe the issue also happens when they are added with a magnet link

**Are you willing to submit a pull request to fix this bug?**

**Comment by alxhotel** [comment]
Hi @DubiousTunic,

I have tried to reproduce your bug and I don't seem to experience it.

This might be a problem with the tracker.

Can you look at the websocket connections in the `Network` tab to check if the tracker is sending an answer?

**Comment by DubiousTunic** [comment]
101 tracker.xyz
101 tracker.openwebtorrent

i looked at the network tab on the clientside (in the browser) -- is that what you meant?

thanks for paying attention to this as i want to launch an alpha of my site soon

**Comment by DubiousTunic** [comment]
Hi, this is still relevant to me. I have most of my life invested in getting a project going, and it relies on one of you fine citizens fixing this code. @feross are you able to help me by any chance? i linked a reproduction of the issue

**Comment by DubiousTunic** [comment]
Yes still relevant. I don't mean to annoy anyone! The hotfix I linked to doesn't work for me for whatever reason.

**Comment by DubiousTunic** [comment]
Bump

**Comment by Shpingalet007** [comment]
Hey folks, I see this too. My case is a little different. I'm just starting working with webtorrent and trying to test it locally. Start seed from one script and try to download it from another.

**Comment by DubiousTunic** [comment]
> Hey folks, I see this too. My case is a little different. I'm just starting working with webtorrent and trying to test it locally. Start seed from one script and try to download it from another. After restart, torrent is seeded fine while not finished. After that is dying again.
> 
> Checked on node 14 and 17 between 2 node processes.
> 
> Update: Looks like using **ReadableStream** instead of **string path** to the seeding file solved my situation. Curious why...

Are you saying that if I seed the file in the browser as a ReadableStream the WebTorrent Desktop will recognize it?

**Comment by DominikNovosel** [comment]
Hi, I also noticed WebTorrent Desktop would stop seeding after a while (because no peers are requesting the files?), and it appears to resume after being restarted or pausing and unpausing all transfers.

**Comment by grind2** [comment]
> Hi, I also noticed WebTorrent Desktop would stop seeding after a while (because no peers are requesting the files?), and it appears to resume after being restarted or pausing and unpausing all transfers.

I have the same issue on Ubuntu 22.04 LTS.
