### ISSUE TITLE
WebTorrent release notes for 1.0

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#2093]
What should we include in the release notes?

**Comment by DiegoRBaquero** [comment]
- Top errors fixed
- Improved performance
- Reduced dependencies
- Will be actively maintained
- Increase verification and automation

**Comment by feross** [comment]
New chunk stores available:

https://github.com/SocketDev/fs-access-chunk-store
https://github.com/SocketDev/idb-chunk-store

**Comment by ThaUnknown** [comment]
we're on v2 now... xD
