### ISSUE TITLE
Proper Torrent pause support

### ISSUE THREAD

**Issue by Crauzer** [webtorrent/webtorrent#2101]
**What version of this package are you using?**
1.0

**What problem do you want to solve?**
Proper support for pausing of torrents

**What do you think is the correct solution to this problem?**
Either implementing download/upload throttling for individual torrents or by removing existing wires/peers from a given torrent

**Are you willing to submit a pull request to implement this change?**
Yes I would be willing to work on this feature

Currently the only way to actually properly "pause" a torrent is by removing it from the client and then re-adding it again which causes some unexpected bugs such as metadata loading being slow or not being able to connect to more than 1-2 peers for a long period of time.

The Torrent pause method should properly pause the download or upload of given torrent not just stop new peer connections from being made.

**Comment by alxhotel** [comment]
Hi @Crauzer,

Thank you for the feedback!

It seems that what you want is already in progress. Check out #2062. This PR will allow to throttle the speed and control the pausing/resuming of the torrent (in a following PR).

I'm closing this issue. But feel free to open it if you need it.
