### ISSUE TITLE
webtorrent npm installation is not working!!!....

### ISSUE THREAD

**Issue by Nymka-9229** [webtorrent/webtorrent#2105]
hello!.. i am trying to start with webtorrent and i tried to install webtorrent npm in my nodeJS project with command line script(npm install webtorrent) but it doesn't work, in every trying to install npm command line says "this is related to npm not being able to find a file".. Please someone guide me or just send the npm zip file to my email address: nymjargal9229@gmail.com.. please

My webtorrent version:      v1.0.0
My device:                          windows

i just need the npm file as zip format so that i can include that in my nodeJS project

**Comment by alxhotel** [comment]
Hi @Nymka-9229,

What version of NodeJS and NPM are you using?

**Comment by Nymka-9229** [comment]
At first, npm installation is not working but after i understood that it's
because i dont have ssh key for github authentication. So i created ssh key
and it worked perfectly..👌👌

anyway, thanks for reply...
