### ISSUE TITLE
typeError: data.hasOwnProperty is not a function...

### ISSUE THREAD

**Issue by Nymka-9229** [webtorrent/webtorrent#2109]
i am trying to run webtorrent on my nodeJS server and when i run my server that error(typeError: data.hasOwnProperty is not a function...) appears on console. What should i do?... Please reply me!!

**Comment by alxhotel** [comment]
Hi @Nymka-9229,

Thanks for the feedback!

Please provide us with more info, like: a code snippet to reproduce the bug and the stack trace of the exception.
