### ISSUE TITLE
Error: invalid argument when connecting to uTP peers via IPv6

### ISSUE THREAD

**Issue by ThaUnknown** [webtorrent/webtorrent#2114]
**What version of this package are you using?**
v1.0.2
**What operating system, Node.js, and npm version?**
Windows 10 LTSC 1809, electron 13.1.2, node 14.16.0
**What happened?**
Adding/connecting to a peer which uses IPv6 string throws an error:
```
path\node_modules\utp-native\lib\connection.js:197
  binding.utp_napi_connect(this._utp._handle, this._handle, port, ip)
          ^

Error: invalid argument
    at Connection._connect (path\node_modules\utp-native\lib\connection.js:197:11)
    at path\node_modules\utp-native\lib\connection.js:189:10
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EINVAL'
  ```
code used:
```js
      const peers = [{ type: 'utpOutgoing', addr: '[2001:5b0:4ec0:c848:4985:2d28:bde4:40e2]:39214' }]
      for (const peer of peers) {
        if (peer.type === 'webSeed') {
          this.torrent.addWebSeed(peer.addr)
        } else if (peer.type !== 'webrtc') {
          this.torrent.addPeer(peer.addr)
        }
      }
```
this also occurs when naturally connecting to uTP peers via trackers
this doesnt occur for webSeeds/tcp peers

**Comment by jczasgit** [comment]
Having the same issue midway download. Works fine on my windows 10 local machine, but in ubuntu 18.04 throws the error.

```
Error: invalid argument 
    at Connection._connect (/mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:197:11)
    at /mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:189:10 at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    at runNextTicks (node:internal/process/task_queues:63:3) 
    at listOnTimeout (node:internal/timers:526:9) at processTimers (node:internal/timers:500:7) { code: 'EINVAL' }
```

code:
```typescript
this.client.add(this._torrentSource, (_torrent) => {
        // deselect all unnessesary files.
        _torrent.files.forEach((file) => {
          file.deselect();
        });
        _torrent.deselect(0, _torrent.pieces.length - 1, 0);

        // get only mp4 file
        let file = _torrent.files.find((file) => file.name.endsWith(".mp4"));
        file.select();
        self._getTorrentFileStats(file, _torrent);

        self._downloadStats.total = file.length;

        _torrent.on("done", () => {
          self._setState(DOWNLOAD_STATES.FINISHED);
          file = null;
          resolve({
            folder: self._fileStats.folder,
            filename: self._fileStats.filename,
            tmpFilename: self._fileStats.tmpFilename,
            tmpFilepath: self._fileStats.tmpFilepath,
            ext: self._fileStats.extension,
            noExt: self._fileStats.noExtFile,
          });
        });

        _torrent.on("download", (bytes) => {
          self._updateProgress(
            bytes,
            _torrent.downloadSpeed,
            _torrent.uploadSpeed,
            _torrent.progress
          );
        });
        _torrent.on("error", (err) => {
          self._setState(DOWNLOAD_STATES.ERROR);
          if (typeof err === "string") {
            err = new WebtorrentDownloadError(
              self._fileStats.tmpFilepath,
              "Torrent Download Error.",
              self.id,
              new Error(err)
            );
          }
          file = null;
          reject(
            new WebtorrentDownloadError(
              self._fileStats.tmpFilepath,
              "Torrent Download Error.",
              self.id,
              err
            )
          );
        });

        file.createReadStream().pipe(this._fileStats.filestream);
      });
```

**Comment by ThaUnknown** [comment]
> Having the same issue midway download. Works fine on my windows 10 local machine, but in ubuntu 18.04 throws the error.
> 
> ```
> Error: invalid argument 
>     at Connection._connect (/mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:197:11)
>     at /mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:189:10 at processTicksAndRejections (node:internal/process/task_queues:82:21) 
>     at runNextTicks (node:internal/process/task_queues:63:3) 
>     at listOnTimeout (node:internal/timers:526:9) at processTimers (node:internal/timers:500:7) { code: 'EINVAL' }
> ```
> 
> code:
> 
> ```ts
> this.client.add(this._torrentSource, (_torrent) => {
>         // deselect all unnessesary files.
>         _torrent.files.forEach((file) => {
>           file.deselect();
>         });
>         _torrent.deselect(0, _torrent.pieces.length - 1, 0);
> 
>         // get only mp4 file
>         let file = _torrent.files.find((file) => file.name.endsWith(".mp4"));
>         file.select();
>         self._getTorrentFileStats(file, _torrent);
> 
>         self._downloadStats.total = file.length;
> 
>         _torrent.on("done", () => {
>           self._setState(DOWNLOAD_STATES.FINISHED);
>           file = null;
>           resolve({
>             folder: self._fileStats.folder,
>             filename: self._fileStats.filename,
>             tmpFilename: self._fileStats.tmpFilename,
>             tmpFilepath: self._fileStats.tmpFilepath,
>             ext: self._fileStats.extension,
>             noExt: self._fileStats.noExtFile,
>           });
>         });
> 
>         _torrent.on("download", (bytes) => {
>           self._updateProgress(
>             bytes,
>             _torrent.downloadSpeed,
>             _torrent.uploadSpeed,
>             _torrent.progress
>           );
>         });
>         _torrent.on("error", (err) => {
>           self._setState(DOWNLOAD_STATES.ERROR);
>           if (typeof err === "string") {
>             err = new WebtorrentDownloadError(
>               self._fileStats.tmpFilepath,
>               "Torrent Download Error.",
>               self.id,
>               new Error(err)
>             );
>           }
>           file = null;
>           reject(
>             new WebtorrentDownloadError(
>               self._fileStats.tmpFilepath,
>               "Torrent Download Error.",
>               self.id,
>               err
>             )
>           );
>         });
> 
>         file.createReadStream().pipe(this._fileStats.filestream);
>       });
> ```

what env/node version are you using?

**Comment by H0301ein** [comment]
![2021-06-29-00:16:44](https://user-images.githubusercontent.com/85063227/123695290-9f44fc80-d86f-11eb-8f03-e4ece5f5ee93.png)

**Comment by nuzzesick** [comment]
Same problem here! Please help!

**Comment by H0301ein** [comment]
https://github.com/webtorrent/webtorrent/commit/0df9eb60171ff18cec052e8f31a515b341bdd03a that's the problem

**Comment by jczasgit** [comment]
> > Having the same issue midway download. Works fine on my windows 10 local machine, but in ubuntu 18.04 throws the error.
> 
> what env/node version are you using for both machines?

I am using node version 15.14.0 for both machines. I opened an issue in the upt-native repo, https://github.com/mafintosh/utp-native/issues/44. It seems that WebTorrent is passing an invalid ip address.

**Comment by jczasgit** [comment]
> [0df9eb6](https://github.com/webtorrent/webtorrent/commit/0df9eb60171ff18cec052e8f31a515b341bdd03a) that's the problem

With that change, the code logic should still work the same way isn't it? By default the option for utp is false, and therefore the utp won't be enabled.
```javascript
```

**Comment by jczasgit** [comment]
As for now, a workaround for me is to explicitly set utp to false when creating a new client.
```javascript
let client = new WebTorrent({ utp: false }); // this solves my problem with Ubuntu server
```

**Comment by DiegoRBaquero** [comment]
Need some extra details, can you guys please enable debug logs: `DEBUG=webtorrent:*`?

I tried to reproduce in my M1 mac using x86 emulation, seems to work fine with utp peers. Latest webtorrent version that is.

**Comment by ThaUnknown** [comment]
> Need some extra details, can you guys please enable debug logs: `DEBUG=webtorrent:*`?
> 
> I tried to reproduce in my M1 mac using x86 emulation, seems to work fine with utp peers. Latest webtorrent version that is.

issue is, for me this is a bitch to reproduce, it happens very rarely only had it happen 3 times on a single torrent a d it hasn't happened since, I'm gonna assume there's some torrent client out there in the wild that causes this, but good luck finding which

**Comment by mafintosh** [comment]
FYI, it's because a bad IP is passed to utp (it throws an assertion error). I've made utp emit it instead in 2.5.2, but you should prob check your that there isn't a bug in your IP parser somewhere :) (there is also a small change it's something else obvs)

**Comment by H0301ein** [comment]
> > [0df9eb6](https://github.com/webtorrent/webtorrent/commit/0df9eb60171ff18cec052e8f31a515b341bdd03a) that's the problem
> 
> With that change, the code logic should still work the same way isn't it? By default the option for utp is false, and therefore the utp won't be enabled.
> 
> ```js
> false === true // false
> false !== false // false
> true === true // true
> true !== false // true
> // the same result
> ```

make sense 
but i change it to true and it's work fine 
im not sure why

**Comment by ThaUnknown** [comment]
> FYI, it's because a bad IP is passed to utp (it throws an assertion error). I've made utp emit it instead in 2.5.2, but you should prob check your that there isn't a bug in your IP parser somewhere :) (there is also a small change it's something else obvs)

![image](https://user-images.githubusercontent.com/6506529/123932641-eaefc700-d991-11eb-9a7b-85784dae1f80.png)
seems like you are completely right, it tries to connect to an ipv6 peer and has a stroke
@DiegoRBaquero this is the issue seems like

**Comment by jczasgit** [comment]
Add ip validation before creating an outgoint peer?
https://github.com/webtorrent/webtorrent/blob/421d6c90edb197be2f8c948eb1b15d8adb8f7dae/lib/peer.js#L89

**Comment by ThaUnknown** [comment]
> Add ip validation before creating an outgoint peer?
> https://github.com/webtorrent/webtorrent/blob/421d6c90edb197be2f8c948eb1b15d8adb8f7dae/lib/peer.js#L89

those are valid IP's, they are just parsed incorrectly?

**Comment by mafintosh** [comment]
Yea utp only has ipv4 atm

**Comment by jczasgit** [comment]
> > Add ip validation before creating an outgoint peer?
> > https://github.com/webtorrent/webtorrent/blob/421d6c90edb197be2f8c948eb1b15d8adb8f7dae/lib/peer.js#L89
> 
> those are valid IP's, they are just parsed incorrectly?

Yes you are correct. What I meant is to verify for ipv4 addresses
