### ISSUE TITLE
128KB piece length breaks client

### ISSUE THREAD

**Issue by tom-adsfund** [webtorrent/webtorrent#2120]
I increased the pieceLength for when I seed to attempt to reduce server requests for web seeds, but when I set it to 128KB, the client stopped functioning (failing to create the new torrent).

**Comment by DiegoRBaquero** [comment]
Can you please provide more info? Maybe some error logs?

**Comment by tom-adsfund** [comment]
Previously working code just stops working completely with multiple errors.

I think someone would have to devise a working case if they wanted to work on the problem. I've just set the size back to the default, but it could be good to be able to change this and is clearly a bug.
