### ISSUE TITLE
Web browser seeding lifetime?

### ISSUE THREAD

**Issue by coryl** [webtorrent/webtorrent#2122]
I'm trying to let a user seed/download videos through a web interface with webtorrent. So far, so good: the file is able to transfer from seeder to leecher.

However, after about ~10 minutes, the seeder is no longer accessible. Trying to load the same file's magnetURI doesn't return anything. I have to reload the page and seed the file again to make it available.

Is there a way to persist my browser based seeding?

**Comment by DiegoRBaquero** [comment]
What's your setup? seeding from browser to browser? webrtc?

Anything on the logs? Do tracker websockets look alive?

**Comment by coryl** [comment]
Everything browser based, I assume its webrtc? Just using client.seed() and client.add().

Is there a way to easily output logs? How do I check websocket status?

**Comment by coryl** [comment]
> What's your setup? seeding from browser to browser? webrtc?
> 
> Anything on the logs? Do tracker websockets look alive?

Everything browser based, I assume its webrtc? Just using client.seed() and client.add().

Is there a way to easily output logs? How do I check websocket status?

**Comment by coryl** [comment]
After a bit more testing, I'm able to better identify the problem. It does not appear to be seeding that is the issue, I can leave a tab open for hours and it will still be seeded.

The problem seems to be long living `client` objects (or networking apparatus) in a browser tab. So if I leave my tab open for a while, and then call `client.add()` on it, it sometimes has have difficulty finding the torrent file. Either:

1) The file will eventually be found, after 30s to several minutes pass.
2) An error will occur, triggering event listener `torrent.on('warning')` with `Error: Connection error: Ice connection failed.`
`WebRTC: ICE failed, add a TURN server and see about:webrtc for more details`

In the event of #2, usually closing the tab and reinitializing the website solves this.

**Comment by coryl** [comment]
I've identified the reason for failure: the tracker server closes the websocket connection periodically.

**Comment by guanzo** [comment]
> the tracker server closes the websocket connection periodically

@coryl Do you know where this happens in the code? I tried looking for it but couldn't find any disconnection logic.

**Comment by coryl** [comment]
> > the tracker server closes the websocket connection periodically
> 
> @coryl Do you know where this happens in the code? I tried looking for it but couldn't find any disconnection logic.

It’s not in the library code, it’s the remote server most likely closing the connection
