### ISSUE TITLE
Newly bumped utp-native dependency is throwing an error and stalling torrent downloads

### ISSUE THREAD

**Issue by YOUPERT-INC** [webtorrent/webtorrent#2128]
**What version of this package are you using?**
1.0.0   Edit: its 1.1.4 specifically (package-lock.json)

**What operating system, Node.js, and npm version?**
Windows 10 64 bit. Node 14.17.1  npm 6.14.13

**What happened?**
Torrent downloading stalls. Upon closer inspection, the issue turned out to be stemming from a recent change (4 days ago) to a dependency `utp-native`. it was bumped form `2.5.0` to `2.5.3` and it is logging an error on console when running under electron `13.1.4`. The specific error message is attached.

```
<user>\torrent-player\node_modules\utp-native\lib\connection.js:197
  binding.utp_napi_connect(this._utp._handle, this._handle, port, ip)
          ^

Error: invalid argument
    at Connection._connect (C:\Users\felix\Documents\Sayam\api-player\node_modules\utp-native\lib\connection.js:197:11)
    at C:\Users\felix\Documents\Sayam\api-player\node_modules\utp-native\lib\connection.js:189:10
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EINVAL'
}
```

**What did you expect to happen?**
As this error also results in download getting stalled,the error should not occur. 

**Are you willing to submit a pull request to fix this bug?**
As much as I wish I could, this is beyond my ability as it involves native modules.

**Comment by IRGC** [comment]
I also had this error and reported in discord chat. I disabled it by utp: false in webtorrent constructor

**Comment by DiegoRBaquero** [comment]
Should be fixed in latest version
