### ISSUE TITLE
Video never streams in browser

### ISSUE THREAD

**Issue by jczasgit** [webtorrent/webtorrent#2131]
**What version of this package are you using?**
I am using the latest version cdn is providing, https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js
**What operating system, Node.js, and npm version?**
Windows 10
**What happened?**
After file.appendTo(root), the video element is appended but never starts streaming or downloading. The "download" event is never triggered.
**What did you expect to happen?**
I expect the video to start streaming or at least downloading somewhere in my machine so that it can play.
**Are you willing to submit a pull request to fix this bug?**
Not sure if I am capable of fixing this. Very new to bittorrent protocol and mediasource.

```javascript
        this._client.add(file, (torrent => {
            torrent.files.forEach(file => file.deselect());
            torrent.deselect(0, torrent.files.length - 1, 0);

            let mp4 = torrent.files.find(file => file.name.endsWith('.mp4'));
            mp4.select();

            torrent.on("download", console.log)
            mp4.appendTo(this._container, (err, elem) => {
                if (err) console.error(err)
                console.log(elem);
            });
```

**Comment by DiegoRBaquero** [comment]
Are you seeding the video yourself? If not, probably it doesn't have any WebRTC peers.

**Comment by jczasgit** [comment]
> Are you seeding the video yourself? If not, probably it doesn't have any WebRTC peers.

When I use uTorrent to download the files, it works.
![image](https://user-images.githubusercontent.com/46619361/124979676-59233200-e001-11eb-959f-8f3e42f240d8.png)
If I use WebTorrent on nodejs it also works, but it just doesn't on the browser. It is really weird.

**Comment by DiegoRBaquero** [comment]
1. Don't use WebTorrent for copyright infringement
2. https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#why-does-browser-downloading-not-work-i-see-no-peers
