### ISSUE TITLE
CacheStore closed

### ISSUE THREAD

**Issue by alxhotel** [webtorrent/webtorrent#2141]
**What version of this package are you using?**
1.2.4

**What operating system, Node.js, and npm version?**
Node 16.4.1
NPM 7.18.1

**What happened?**
The tests are a bit flaky. When running the current Github action tests multiple times sometime I get this error:

```
# torrent.createServer: programmatic http server
ok 742 got "torrent" event
ok 743 server is listening on 37665
ok 744 got http response for /
ok 745 should be truthy
ok 746 got http response for /0
ok 747 should be deeply equivalent
ok 748 server closed
ok 749 client destroyed
not ok 750 loaded seed content into torrent
  ---
    operator: error
    at: <anonymous> (/home/runner/work/***/***/test/node/server.js:25:11)
    stack: |-
      Error: CacheStore closed
          at /home/runner/work/***/***/node_modules/cache-chunk-store/index.js:20:38
          at internal/process/task_queues.js:141:7
          at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
          at AsyncResource.runMicrotask (internal/process/task_queues.js:138:8)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
  ...
```

An example of this error can be found (for example) in a PR which only adds some documentation:

https://github.com/webtorrent/webtorrent/pull/2140/checks?check_run_id=3104279546#step:7:818

**What did you expect to happen?**
The tests to pass consistently

**Are you willing to submit a pull request to fix this bug?**
I'll let this issue open if someone wants to tackle it. If after sometime it doesn't get solved, I can try it.

**Comment by DiegoRBaquero** [comment]
yeah, I've seen this happen multiple times, I will investigate too

**Comment by DiegoRBaquero** [comment]
Seemed related to disk access speed. Fixed in https://github.com/webtorrent/webtorrent/commit/b1f720f4372679e3d30f62b537c6c5921c67aed5
