### ISSUE TITLE
WebTorrent no Error but no video showing

### ISSUE THREAD

**Issue by Gomez0015** [webtorrent/webtorrent#2146]
I am using the latest version and when I try to use this magnet link:
magnet:?xt=urn:btih:9b19a5f055ea162b1b837ffc7ac900c82f59d10e&dn=Space.Jam.a.New.Legacy.2021.1080p.WEBRip.x265-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2790&tr=udp%3A%2F%2F9.rarbg.to%3A2760&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14740&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15770

It just stays blank forever and has no error in the console please help!

**Comment by DiegoRBaquero** [comment]
Please don't use WebTorrent for copyright infringement
