### ISSUE TITLE
100% browser CPU on rarest strategy

### ISSUE THREAD

**Issue by tom-adsfund** [webtorrent/webtorrent#2150]
This is in the browser, version 1.2.5.

When I use 'rarest' strategy, browser goes to 100% CPU. Using Chromium's profiler, I see it's from trySelectWire, with 35% coming from getRarestPiece.

This makes the interface almost unresponsive.

**Comment by alxhotel** [comment]
Hi @tom-adsfund,

Thanks for the feedback!

This seems something we should look into.

**Comment by jimmywarting** [comment]
dupl: #1558

**Comment by alxhotel** [comment]
Thanks @jimmywarting

**Comment by tom-adsfund** [comment]
I can't see how this issue has anything to do with #1558.

Would you be able to explain?
