### ISSUE TITLE
speed-limiter error: 'this._events.emit is not a function'

### ISSUE THREAD

**Issue by OsmanAltun** [webtorrent/webtorrent#2152]
**What version of this package are you using?**
1.3.0

**What operating system, Node.js, and npm version?**
win32 x64, node v14.17.3, npm 7.20.0

**What happened?**
```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.5.3, webtorrent 1.3.0, node v14.17.3, win32 x64, exit 1
D:\Workspace\Code\webtorrent-cli\node_modules\speed-limiter\lib\throttle.js:134
    this._events.emit('destroyed')
                 ^

TypeError: this._events.emit is not a function
    at Throttle.destroy (D:\Workspace\Code\webtorrent-cli\node_modules\speed-limiter\lib\throttle.js:134:18)
    at ThrottleGroup.destroy (D:\Workspace\Code\webtorrent-cli\node_modules\speed-limiter\lib\throttle-group.js:73:16)
    at WebTorrent._destroy (D:\Workspace\Code\webtorrent-cli\node_modules\webtorrent\index.js:427:30)
    at WebTorrent.destroy (D:\Workspace\Code\webtorrent-cli\node_modules\webtorrent\index.js:396:10)
    at process.gracefulExit (D:\Workspace\Code\webtorrent-cli\bin\cmd.js:789:10)
    at process.emit (events.js:375:28)
```
Happens when exiting webtorrent-cli. Limiting bandwidth does work though.

**What did you expect to happen?**
No error.

**Are you willing to submit a pull request to fix this bug?**
No.

Quick patch would be to check if emit function exists (@alxhotel inside speed-limiter library).
```js
if (typeof this._events.emit === "function") { 
    this._events.emit('destroyed') 
}
```

**Comment by alxhotel** [comment]
Hi @OsmanAltun,

Thanks for opening this issue!

I have released a new version of `speed-limiter` (1.0.1) which solves this bug: https://github.com/alxhotel/speed-limiter/commit/f54bfa6ac0d857c6f454b4d5fa3e51c38ca1e51c

**Comment by OsmanAltun** [comment]
I stumbled on another issue. Setting the limit to 0 is supposed to block data from being uploaded or downloaded, but it doesn't work. The client acts as though there is no limit (-1). Should I open a new issue for this @alxhotel ?

**Comment by alxhotel** [comment]
Yes, please @OsmanAltun!

Make sure to add the steps to reproduce the bug.

Thanks :)
