### ISSUE TITLE
Setting speed limit to 0 does not block data upload/download

### ISSUE THREAD

**Issue by OsmanAltun** [webtorrent/webtorrent#2156]
**What version of this package are you using?**
1.3.0

**What operating system, Node.js, and npm version?**
win32 x64, node v14.17.3, npm 7.20.0

**What happened?**
I ran something like this:
```bash
node bin/cmd.js "magnet_here"  --download-limit 500 --upload-limit 0
```
The downloadLimit is set to 500 kb/s (which works)
The uploadLimit is set to 0 to block uploading (fails to work)
Use case with 0 speed always fails (regardless of upload or download), it acts as though there is no limit set. Probably an if/else logic issue here ?

U can try my webtorrent-cli fork using the `feat/limit-bandwidth` branch to reproduce. 

**What did you expect to happen?**
download speed set to 500 kb/s
upload speed set to 0 kb/s (BLOCK)

**Comment by OsmanAltun** [comment]
Now it gets stuck on fetching metadata with the use case above @alxhotel.

**Comment by alxhotel** [comment]
> Now it gets stuck on fetching metadata with the use case above @alxhotel.

I think that's the correct behaviour, @OsmanAltun 

Because by setting the `upload-limit` to `0` all the requests you do to peers will be block. Therefore, you will not be able to request any metadata. (the same goes if you set the `download-limit` to `0`)

**Comment by OsmanAltun** [comment]
So... if I were to use a `.torrent` file which holds metadata it still wouldn't work, because all peers are blocked (If I were to specify only `--upload-limit 0`, both upload and download would be 0 B/s). Is that really desirable @alxhotel ? 

Anyway, good to know it is intended, I will be putting up my PR.

**Comment by alxhotel** [comment]
Thanks @OsmanAltun. Yes, I think that it is the desirable functionality.

In the case of the torrent file, the metadata is already in the torrent file so there is no need in downloading it.
