### ISSUE TITLE
Enable webtorrent to be built on IPv6-only machines

### ISSUE THREAD

**Issue by oxzi** [webtorrent/webtorrent#2157]
**What version of this package are you using?**
1.0.2 as a dependency, but does not matter.

**What problem do you want to solve?**
The used `http-node` version is a fork from @feross, namely:
https://github.com/webtorrent/webtorrent/blob/f13ef12bf05c98416d5fa74c8fbeaad11076e83c/package.json#L52

As it seems, there are only two small changes. Those are the dependencies to `chrome-net`:
https://github.com/jscissr/http-node/compare/master...feross:webtorrent

However, by enforcing a dependency to GitHub, one cannot build the software on an IPv6-only machine as GitHub does not support the current version of the Internet Protocol.

**What do you think is the correct solution to this problem?**
I know that this is not the perfect place for this issue, but `feross/http-node` has no issue tracker and he seems to be a big maintainer here as well.

My suggestion would be to push this to npm to be available via IPv6.

**Are you willing to submit a pull request to implement this change?**
No code needs to be changed.

**Comment by DiegoRBaquero** [comment]
We could fork and publish under @webtorrent org, still interested?

**Comment by oxzi** [comment]
@DiegoRBaquero: Thanks a lot for coming back to this issue. I would be very happy seeing it published there.

**Comment by feross** [comment]
FYI – transferred the repo from @feross to @webtorrent org. We can publish it to npm for now, until we find a way to remove the need for it.
