### ISSUE TITLE
How to detect if a magnet hash is not valid?

### ISSUE THREAD

**Issue by abbestrov** [webtorrent/webtorrent#2160]
I'm creating a test app where the user sends the magnet hash in the request.
is there any way to detect if the hash that the user sends is valid?

**Comment by DiegoRBaquero** [comment]
Just parsing it should be enough

Diego

**Comment by DiegoRBaquero** [comment]
Using https://github.com/webtorrent/magnet-uri/

**Comment by abbestrov** [comment]
I've tried magnet-uri package. it will parse it even if the hash is not correct.
for example: 
this is the magnet uri to download ubuntu: `magnet:?xt=urn:btih:JOSPX5ZDDI5GMDUGRETQPUS4CNKTHILK` if I change just the last char it will parse it too.
and that's why when the server receives an invalid hash it just hangs there with no response.
I think because I have a bad client response from:
`client.add(magnetURI, {ops}, (torrent) => {})`
and that's why I think no event gets triggered.

any suggestions?

**Comment by DiegoRBaquero** [comment]
Any hash is correct as long as format matches.

You are looking if a certain hash has content/peers

You can listen for the metadata event, and the noPeers event, that would give you an answer 

Diego
