### ISSUE TITLE
Adding Multiple WebSeeds to a torrent to increase speed

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#2166]
I have some questions and thoughts of adding multiple webseeds

1. Is it a good idea at all?
2. Has it been thought and tested in this code?
3. How is it handled? will it be prioritized by webseed speed?
4. Is there any possibility that a piece is downloaded from multiple servers and waste bandwidth?
5. If Webseed A is 1 Mb/s and Webseed B is 2Mb/s will the torrent be downloaded at 3Mb/s ?

I did a test on 2 webseeds and couldn't detect any bandwidth increase, but torrent was downloading pieces randomly from both servers.
Also I checked if one webseed goes down, torrent still sends requests to that webseed and will never give up trying, is it normal?

**Comment by DiegoRBaquero** [comment]
1. yes
2. yes
3. they act as equals
4. no, reservations per piece are made
5. should be
