### ISSUE TITLE
In browser, if no trackers specified, use wss://tracker.webtorrent.io

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#218]
People think code like this should work:

``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <script src="http://cdn.rawgit.com/feross/webtorrent/master/webtorrent.min.js"></script>
        <script src="http://wzrd.in/standalone/concat-stream@1.4.7"></script>
    </head>
    <body>
        <script>

    var url = 'magnet:?xt=urn:btih:b781cc28e64373378bff35f6a4a66d62cd5c6661';
    var client = new WebTorrent();

    client.add(url, function (torrent) {
      // Got torrent metadata!
      console.log('Torrent info hash:', torrent.infoHash);
    });
        </script>
    </body>
</html>
```

Currently, you need to do:

``` js
client.add(url + '&tr=wss://tracker.webtorrent.io', function () {})
```

To tell the client to use the webtorrent tracker.

**Comment by jessetane** [comment]
Just tried webtorrent for the first time - basically copied the example (which uses `torrent.infoHash`), and got this error. It's not obvious from the message exactly _how_ to add the tracker though - perhaps the example could use `magnetURI`, or if `client.add`'s `opts` somehow accepts this, document it?

**Comment by FrancoAguilera** [comment]
Hi guys, I'm kind of new in all this js world, so my question is that I had use the example above. here is my code (it was writen in an empty html file)
```js
<script src="js/webtorrent.min.js"></script>
<script src="http://wzrd.in/standalone/concat-stream@1.4.7"></script>
<script>
	var client = new WebTorrent()
	var magnetUri = 'magnet:?xt=urn:btih:b781cc28e64373378bff35f6a4a66d62cd5c6661'

        client.add(magnetUri + '&tr=wss://tracker.webtorrent.io', function (torrent) {

		// Got torrent metadata!
		console.log('Torrent info hash:', torrent.infoHash)

		// Let's say the first file is a webm (vp8) or mp4 (h264) video...
		var file = torrent.files[0]

		// Create a video element
		var video = document.createElement('video')

		video.controls = true
		document.body.appendChild(video)

		// Stream the video into the video tag
		file.createReadStream().pipe(video)

	});
</script>
```
tested on chrome, and the browser doesn't trow any error , but despite that... nothing seems to happen, I'm I missing something out ?

**Comment by feross** [comment]
@FrancoAguilera It's likely that you're trying to download a torrent with no seeders. See: https://github.com/feross/webtorrent/wiki/FAQ#why-does-browser-downloading-not-work

**Comment by prashant-andani** [comment]
<script src="js/webtorrent.min.js"></script>
<script src="http://wzrd.in/standalone/concat-stream@1.4.7"></script>
<script>
    var client = new WebTorrent()
    var magnetUri = 'magnet:?xt=urn:btih:d20d2186e129712666ba4c5b40e78877b814418f'

        client.add(magnetUri + '&tr=wss://tracker.webtorrent.io', function (torrent) {

        // Got torrent metadata!
        console.log('Torrent info hash:', torrent.infoHash)

        // Let's say the first file is a webm (vp8) or mp4 (h264) video...
        var file = torrent.files[0]

        // Create a video element
        var video = document.createElement('video')

        video.controls = true
        document.body.appendChild(video)

        // Stream the video into the video tag
        file.createReadStream().pipe(video)

    });
</script>
This doesnt seem to be working. The same .torrent file for the given magnet file i could play it using npm through vlc player.
Im i missing out anything....

**Comment by feross** [comment]
@prashant-andani Yes, you probably are. Read this: https://github.com/feross/webtorrent/wiki/FAQ#why-does-browser-downloading-not-work

**Comment by prashant-andani** [comment]
@feross  can we have list of few explicitly seeded torrent files. It would be of great help.

**Comment by feross** [comment]
Just seed your own file at https://instant.io and test against that. :)

**Comment by sqren** [comment]
I was struggling with the tracker part for a couple of hours. No obvious errors as far as I could tell. In the end it worked by explicitly adding a tracker:

```
client.add({
    infoHash: infoHash,
    announce: 'wss://tracker.webtorrent.io'
}, function (torrent) {...});
```

Instead of just
```
client.add(infoHash, function (torrent) {...});
```

An explicit error would definitely be helpful.

**Comment by feross** [comment]
That's weird. Are you running the latest version of webtorrent? There's code to automatically add some [reasonable defaults](https://github.com/feross/create-torrent/blob/master/index.js#L5-L11) if you don't specify any trackers.

https://github.com/feross/webtorrent/blob/e8783fec76bb965605875101399096d4ee2aa57d/lib/torrent.js#L124-L127

**Comment by sqren** [comment]
Thanks for quick reply!

I'm on 0.42 and seeing the problem. I've created a jsbin (with 0.41) to reproduce it:
http://jsbin.com/rivudu/4/edit?html,console

**Comment by feross** [comment]
Try 0.43, which fixes the issue. Not sure why that's not on the CDN yet, but you can use https://rawgit.com/feross/webtorrent/master/webtorrent.min.js to get the latest script from the github repo.

**Comment by sqren** [comment]
0.43 did the trick. Awesome!

**Comment by feross** [comment]
Awesome, glad it works for you now :)

**Comment by Enelar** [comment]
@feross i think this should be implemented, as far as user always able to disable it.
like `client.disableDefaultTracker()`
