### ISSUE TITLE
torrent.on('swarm') doesn't work with client.seed

### ISSUE THREAD

**Issue by DubiousTunic** [webtorrent/webtorrent#2189]
**What version of this package are you using?**
Latest version 
**What operating system, Node.js, and npm version?**
Browser :Firefox, Chrome
**What happened?**
client.seed(file, function(torrent){
   torrent.on("wire"... 
}) 

doesn't work but client.add ... torrent.on("wire"...) works
**What did you expect to happen?**
I expected to be able to check for peer connections after i seed a file but i can only check for peer connections after i add a file
**Are you willing to submit a pull request to fix this bug?**
too noobie

**Comment by DiegoRBaquero** [comment]
When seeding, are you testing connecting from another tab/CLI process?

is this the same torrent?

**Comment by DubiousTunic** [comment]
Oh okay I think I was being foolish. I'm a little special. I thought that if I seeded "the same" empty file in two different tabs, they would necessarily have the same infoHash. I'm just gonna assume it wasn't the same torrent because although empty files have the same content they don't have the same "signature" or something.
