### ISSUE TITLE
host webtorrent.min.js on a cdn

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#219]

**Comment by jimaek** [comment]
I wanted to let you know that the new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/

**Comment by DiegoRBaquero** [comment]
@jimaek Great news! That's a great improvement.

Is there a blog post about the new features? Any deprecations?

Thank you for letting us know!

**Comment by jimaek** [comment]
I am working on it. The only deprecation is the old style of adding files using pull requests. You cant do that anymore, but of course all old files are still accessible. Nothing will break for anyone.
