### ISSUE TITLE
Graceful exit

### ISSUE THREAD

**Issue by kaiser101** [webtorrent/webtorrent#2193]
client.destroy does not gracefully exit the node process. I have to shut it down manually by hitting CTRL + C

**Comment by DiegoRBaquero** [comment]
Is this for webtorrent cli? Or a custom app using webtorrent? Please provide more context

**Comment by kaiser101** [comment]
It is using a simple js app using the Webtorrent api.

I am listening to the torrent on done event

torrent.on("done", () => {
    client.destroy((err) => {})
})

It never exits gracefully, even after almost couple of minutes.
