### ISSUE TITLE
Webtorrent is blocked in some browsers

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#2195]
Hello

I noticed webtorrent is not working in some browsers like puffin and LG webos chrome browser.
Any file named webtorrent.min.js is blocked in puffin, renaming will work, but lg webos is blocked it in another way and renaming doesn't work.
anybody knows why?

**Comment by WatchSoMuch** [comment]
I also found that webtorrent.min.js (latest version 2021/09/28 on cdn) doesn't work on tizen samsung browser 3 and playstation safari 12, the "new WebTorrent()" breaks and I had to put it in try ... cache.

**Comment by DiegoRBaquero** [comment]
We can't do anything if vendors block certain urls. Best would be to download the minified and rename, host it yourself

**Comment by WatchSoMuch** [comment]
> We can't do anything if vendors block certain urls. Best would be to download the minified and rename, host it yourself

Yes of course I did that as I mentioned in my first comment, its fixed in some browsers but didn't work in LG webos Chrome browser and Tizen's samsung browser 3, and for sure I can make it work finally.

But wait...
Really? I see you are the second main contributor and was that all your answer? I did not write a single code in this project but I care more than you, I think webtorrent is one of the best projects and could be the future of streaming.
or maybe you didn't get the point! webtorrent is known as harmful to many browsers and nobody is curious about it? I'm not a githubber and not familiar with the rules but my concern is if somebody has added a dangerous code to webtorrent that caused this.

**Comment by jimmywarting** [comment]
WebTorrent is not harmful or dangerous. There isn't any embedded code that steals or gathering analytics about you. And it don't mind bitcoins either. WebTorrent runs in the most secure container ever, the browser. So it don't have any access to your filesystem. 

But torrent is so much associated with pirating so no wonder they choose to block it... Also it can use the clients network and consume a lot of bandwidth without the user knowing about it. 
Torrent in itself is not harmful. In fact it can be quite useful but not everyone see it like that
Apple is so strict that it doesn't allow any torrent client to be hosted on apple store. Many vendors and public WiFi  don't want you to use up all there bandwidth
And they don't specifically block only WebTorrent. Some have a filter and block any url that has the word torrent in the url

So yeah, there isn't much we can do about it other then say: host it yourself

**Comment by WatchSoMuch** [comment]
I have hosted it and renamed the file, solved 50% of browsers, I guess other browsers detect the script by something else.
First o thought renaming WebTorrent in the minified file, but then I see in my html page, there is lots of webtorrent keywords and is not blocked, there must be something else.
As I understand webtorrent is not using regular torrent functionality and is based of webrtc that is used for chats, can browsers disallow webrtc to prevent it? I don't think so.
But I remembered there were some features added to webtorrent that uses regular torrent protocols like udp, maybe thats where it started getting blocked?
And since these protocols like udp is not working on browsers, isn't it good idea to separate webtorrent for browser and nodejs? 
I can use older versions, but maybe there are some bugs fixed on newer version that I will lose them?

**Comment by DiegoRBaquero** [comment]
UDP and TCP parts are not bundled into the browser's version. There must be some other kind of detection, maybe class name.

**Comment by ThaUnknown** [comment]
class names are mangled in the minified version of wt, so that's not it either, it must be the filename itself

**Comment by WatchSoMuch** [comment]
> UDP and TCP parts are not bundled into the browser's version. There must be some other kind of detection, maybe class name.

Are you sure? Maybe I have picked the wrong version?
Is this the browser version?
<script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>

**Comment by WatchSoMuch** [comment]
> class names are mangled in the minified version of wt, so that's not it either, it must be the filename itself
> 
> edit: also, I think original issue is that the browsers don't support webtorrent, for example samsung browser doesn't even have many array functions, and string operations like stardswith endswith includes, slice, array from, date.now, performance.now, and console

There is not only one problem, the rename and hosting it fixed 50 percent of my visitors problem, but there is something wrong in new version, I had an older version (site 877,995 bytes), used it and it fixed the others' problem.
Because I renamed it I don't know the version.
