### ISSUE TITLE
Unable to install - npm not being able to find a file.

### ISSUE THREAD

**Issue by MillaSense** [webtorrent/webtorrent#2201]
154 error code ENOENT
155 error syscall spawn git
156 error path git
157 error errno -4058
158 error enoent Error while executing:
158 error enoent undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
158 error enoent
158 error enoent
158 error enoent spawn git ENOENT
159 error enoent This is related to npm not being able to find a file.

"yarn" works! ..but maybe you want to fix this. have a good one!

**Comment by alxhotel** [comment]
Hi @MillaSense, I think you need to install git
