### ISSUE TITLE
Incremental Update to ESM

### ISSUE THREAD

**Issue by king-11** [webtorrent/webtorrent#2202]
**What problem do you want to solve?**
Converting codebase to typescript to better support readability and use.

**What do you think is the correct solution to this problem?**
- [ ]  Switching from browserify to native ESM Modules.
- [ ] Adding a `jsconfig.json`

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by jimmywarting** [comment]
I have worked with typescript and esm togheter and it is a nightmare.
typescript have had a long time to adabt to new ESM but the process have been nothing but slow.

I love typing but i really hate the syntax. what can i say... i like buildless tool chains
So I do actually provide typing support without typescript syntax by supplying jsdoc that works as equally good. Then I have checkjs turned on globally in vscode.

**Comment by jimmywarting** [comment]
Even doe i don't use typescript syntax, i do have a tsconfig.json with this code (in other projects of my own): 

```js
{
  "include": ["*.js"],
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["ES2020"],
    "module": "es2022",
    "moduleResolution": "es2022",
    "allowJs": true,
    "checkJs": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "allowSyntheticDefaultImports": true
  }
}
```
This tsconfig is setup for vanilla js
this will , 
- allowjs - to write with vanilla js
- checkjs - to inspect and validate jsdoc's
- emitDeclarationOnly- only generate `d.ts` files based on jsdoc.
