### ISSUE TITLE
Workflow support for Node 16

### ISSUE THREAD

**Issue by king-11** [webtorrent/webtorrent#2203]
**What problem do you want to solve?**
NodeJS 16 will be getting LTS status in [26/10/2021 ](https://nodejs.org/en/about/releases/) running workflow test on Node 16 can be a good addition

**What do you think is the correct solution to this problem?**
Adding Node 16 into version matrix for workflow

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by DiegoRBaquero** [comment]
Agreed, happy to review PR :)
