### ISSUE TITLE
Webpack 5 compatibility for drowser

### ISSUE THREAD

**Issue by Corentin-pro** [webtorrent/webtorrent#2206]
Using latest version : `1.5.6` on Arch Linux with webpack `5.58.0` (everything else also up-to-date) the building process seems to target node as it get the error : `Buffer is not defined` then `process is not defined` if using polyfill for the Buffer error.

As Webpack 5 changes the `target` behavior the README can be misleading for the newer version of webpack (5+).

The recommended configuration only works for Webpack 4:
```
{
  target: 'web',
  node: {
    fs: 'empty'
  }
}
```
I tried different configurations following [official migration documentation](https://webpack.js.org/migrate/5/) without succeding.

The only solution I found is `require('webtorrent/webtorrent.min.js')` or `import WebTorrent from 'webtorrent/webtorrent.min'` in my case.

I think the README should address the issue for Webpack 5, maybe the target detection could be updated too, I might take a look at the code to fix this and do a PR but I cannot guaranty that with my actual schedule.

**Comment by ThaUnknown** [comment]
configuring the bundler should be up to the user. webtorrent recommends browserify, not webpack, you aren't even polyfilling node globals, I assume you missed the massive "wp5 doesn't polyfill node by default anymore"

here's my config that works:
```js
const path = require('path')
const webpack = require('webpack')
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
module.exports = {
  entry: './index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
    library: 'WebTorrent',
    sourceMapFilename: 'bundle.js.map'
  },
  mode: 'production',
  devtool: 'source-map',
  plugins: [
    new webpack.ProvidePlugin({
      process: 'process-fast'
    }),
    new NodePolyfillPlugin()
  ]
}```
you can additionally polyfill a faster version of zlib, but I didn't bother

**Comment by Corentin-pro** [comment]
> I assume you missed the massive "wp5 doesn't polyfill node by default anymore"

I don't understand your tone nor what you are referencing here nor how is this helping. Yes I realised quickly when upgrading about that issue but no solution is included in the code nor workaround in the README.

Adding that `node-polyfill-webpack-plugin` is a fix for webpack 5 is indeed a solution so the following:

```
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
module.exports = {
    [...]
    plugins: [
        new NodePolyfillPlugin(),
    ],
    [...]
};
```

is enough to to make webtorrent works in browser using webpack.


> webtorrent recommends browserify, not webpack

This is not stated and even if it would be an hard sell while webpack is way more popular and webtorrent can work fine with it.

I will make a PR for the README for the `node-polyfill-webpack-plugin`, usually I try to keep dependencies as minimal, I checked a little bit it seems that webpack 4 depends on `node-libs-browser` wich seems to do quiet the same anyway.

**Comment by Clay-Ferguson** [comment]
@Corentin-pro 's answer definitely is what's required to get the latest webpack working. This info really badly needs to be added to the **"Getting Started"** page because everyone using webpack (latest version) will have this same issue, guaranteed.
