### ISSUE TITLE
Return Torrent when client.seed finds a duplicate

### ISSUE THREAD

**Issue by Clay-Ferguson** [webtorrent/webtorrent#2215]
When calling `client.seed` we correctly throw an error if the torrent would be a duplicate, but it should somehow pass back (via. return or callback) the actual Torrent instance, because there's no clean way to know WHICH torrent is the duplicate without searching by filename+length which is ugly and also not guaranteed to find the correct one.

**Comment by Bruce-Hopkins** [comment]
Can I be assigned the fix??

**Comment by DiegoRBaquero** [comment]
Feel free to create a PR :)

Diego

**Comment by Bruce-Hopkins** [comment]
Great! I'll get started on the PR.

**Comment by Bruce-Hopkins** [comment]
I refactored to pass the duplicate torrent in the callback, but I didn't add any way to know if you are handling a new torrent or a duplicate. I'm thinking about passing a boolean to represent if the torrent is original or a duplicate, but I'm not sure if it's necessary.
