### ISSUE TITLE
sha1 wrapper (Node 14, WebCrypto)

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2217]

**Comment by ThaUnknown** [comment]
https://github.com/jimmywarting/wt-common
?

**Comment by ThaUnknown** [comment]
yes

**Comment by DiegoRBaquero** [comment]
To be honest, I don't remember. I think we can close this

**Comment by ThaUnknown** [comment]
> To be honest, I don't remember. I think we can close this

I'd happily drop rusha, it's a lot less bundle size

**Comment by ThaUnknown** [comment]
yeah, re-opening this for https://github.com/orgs/webtorrent/projects/1#card-60702974 and 4.8% bundle size reduction

**Comment by ThaUnknown** [comment]
cool, web crypto is AT BEST 900% slower than `node:crypto` and only 25% faster than `rusha` this is really bad....

**Comment by ThaUnknown** [comment]
related PR's:
https://github.com/webtorrent/bittorrent-protocol/pull/98
https://github.com/webtorrent/create-torrent/pull/184
https://github.com/webtorrent/parse-torrent/pull/117
https://github.com/webtorrent/ut_metadata/pull/79
https://github.com/webtorrent/bittorrent-dht/pull/257
https://github.com/webtorrent/webtorrent/pull/2390
but this is pretty much umergable util ESM/Promises, but it's there
