### ISSUE TITLE
WebTorrent no Error but no video showing

### ISSUE THREAD

**Issue by mrsmook** [webtorrent/webtorrent#2220]
Hello i'm using the latest version when using the torrent url provided all works just fine but when using others magnet URI i have no error and the video is not showing. ( link below free to use no copyright problem )

URI : magnet:?xt=urn:btih:BEC53CF70ACFC15DCDBDBA17F952148910A3BE8F&dn=Rigmar+Mix+Carnberries+%26amp%3B+Crazy+Frog+Video&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce

Thank you in advance.

**Comment by ThaUnknown** [comment]
browser? node? app? version? reproduce?
the video codec is h264/MPEG which browsers don't support

**Comment by mrsmook** [comment]
My bad bad link that do not support WebRTC
