### ISSUE TITLE
bittorrent-tracker too slow under high load

### ISSUE THREAD

**Issue by skdrek** [webtorrent/webtorrent#2225]
Hi, I have a problem that the bittorrent-tracker is very slow under such a load.
torrents | 1426
-- | --
activeTorrents | 520
peersAll | 26709
peersSeederOnly | 26602
peersLeecherOnly | 107
peersSeederAndLeecher | 0
peersIPv4 | 26709
peersIPv6 | 0

Receiving information takes from 30 to 50 seconds. The server does not slow down, there are enough resources 
https://i.imgur.com/p53LExw.png

bittorrent-tracker -v
9.18.3

CentOS 8.4

node -v
v12.22.7

npm -v
6.14.15

**Comment by DiegoRBaquero** [comment]
Probably not related to the tracker itself. Are you measuring time to generate the SDP offers/answers? Checking the traffic from both peers and server. Also I'd recommend upgrading Node and npm
