### ISSUE TITLE
date.now based speedometer

### ISSUE THREAD

**Issue by ThaUnknown** [webtorrent/webtorrent#2226]
**What version of this package are you using?**
\-
**What problem do you want to solve?**
Speedometer reporting inaccurately high speeds after opening a window in a previously "hidden" state. I assume this happens because it uses set timeouts which are throttled when the window is in a hidden state. This leads to unrealistically high speeds being reported which makes the downloadSpeed/uploadSpeed very unreliable to use in code elsewhere.
**What do you think is the correct solution to this problem?**
Use Date.now and calculate speeds based on that.
**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by Bruce-Hopkins** [comment]
Can I work on this?

**Comment by ThaUnknown** [comment]
go for it

**Comment by DiegoRBaquero** [comment]
Related: https://github.com/mafintosh/speedometer/issues/9

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/pull/2314
