### ISSUE TITLE
flags for flatpaks

### ISSUE THREAD

**Issue by chaibronz** [webtorrent/webtorrent#2240]
**What version of this package are you using?**
4.0.2 (1.5.8)

**What problem do you want to solve?**
stream webtorrents with flatpak versions of supported media apps (ie. mpv and vlc)

**What do you think is the correct solution to this problem?**
enable flags for flatpak apps such as vlc and mpv
ie. webtorrent magnet_uri --org.videolan.VLC

**Are you willing to submit a pull request to implement this change?**
if i can figure out how to code it, sure, but wouldn't count on that. 

If anyone is willing to tackle this, below are the commands for running vlc and mpv via flatpak:

flatpak run io.mpv.Mpv
flatpak run org.videolan.VLC

**Comment by chaibronz** [comment]
Closing this issue as I just noticed the vlc-command already accounts for the vlc flatpak.

**Comment by hello-smile6** [comment]
> Closing this issue as I just noticed the vlc-command already accounts for the vlc flatpak.

Okay!!!
