### ISSUE TITLE
node applications can't load torrents from nyaa.si

### ISSUE THREAD

**Issue by rodrigogsilva** [webtorrent/webtorrent#2241]
**What version of this package are you using?**
1.5.8

**What operating system, Node.js, and npm version?**
Linux, node v16.13.1,  npm 8.3.0

**What happened?**
Any torrent from the website nyaa.si won't load in the node versions of webtorrent but if I use the wenbtorrent executable (.deb) it runs fine.
I also tried use the instant.io to check if I was doing something wrong but it also is not able to run the video.

**What did you expect to happen?**
run the video from the torrent

**Are you willing to submit a pull request to fix this bug?**
I'm not sure how the lib works but if the problem is found, I can try

**Comment by DiegoRBaquero** [comment]
Probably the torrents in the website you mention don’t have webrtc seeders, so it won’t load.

Diego

**Comment by rodrigogsilva** [comment]
> Probably the torrents in the website you mention don’t have webrtc seeders, so it won’t load. Diego
> […](#)
> On 11/01/2022, at 10:13 AM, Rodrigo Gonçalves ***@***.***> wrote: ﻿ What version of this package are you using? 1.5.8 What operating system, Node.js, and npm version? Linux, node v16.13.1, npm 8.3.0 What happened? Any torrent from the website nyaa.si won't load in the node versions of webtorrent but if I use the wenbtorrent executable (.deb) it runs fine. I also tried use the instant.io to check if I was doing something wrong but it also is not able to run the video. What did you expect to happen? run the video from the torrent Are you willing to submit a pull request to fix this bug? I'm not sure how the lib works but if the problem is found, I can try — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Indeed that is the problem. My bad.
