### ISSUE TITLE
Memory usage goes up downloading a torrent but never goes down again after it finishes

### ISSUE THREAD

**Issue by Noxde** [webtorrent/webtorrent#2245]
**What version of this package are you using?**
1.5.7

**What operating system, Node.js, and npm version?**
linux x64, 16.13.2, 8.1.2 (heroku)
windows11 x64, 16.13.2, 8.1.2 (my pc)

**What happened?**
im using webtorrent to make a bot to download torrents and its hosted on heroku, having the free plan i have available 512Mb of memory, i can see that when it finished downloading a small torrent it might reach around 100Mb of memory having started at around 60Mb of memory usage when idle(i checked this using process.memoryUsage().rss) and it won't go down so when i start downlodaing another torrent it starts at 100Mb of memory usage eventually crashing.
another issue i had is memory usage while downloading it goes up pretty fast in bigger torrents with more seeders but i'd like to first fix the former issue

this is the code im using.
```js
const WebTorrent = require("webtorrent");
const client = new WebTorrent();

client.add(args[1], { path: "./temp/" }, (torrent) => {
  let update = setInterval(() => {
    console.table(
      client.torrents.map((t) => ({
        torrent: t.name,
        progress: `${(t.progress * 100).toFixed(2)}%`,
        speed: `${(t.downloadSpeed / 1000000).toFixed(2)}Mb/s`, 
      }))
    );
  }, 2000)

  torrent.on('done', () => {
    t.destroy({ destroyStore: true });
  }
});
```

**What did you expect to happen?**
i expected the memory usage to go down the same amount it went up or approximately

**Are you willing to submit a pull request to fix this bug?**
i don't know how this could be fixed as the only experience i have is making some discord bots but i would like to help to fix this if i knew how to.

this is the first issue i ever made, im not sure if this is a webtorrent issue but i tried downloading a few different torrents on my pc using this and hosting it on heroku and i got the same results, i tried using a readStream and writeStream instead of this approach but the issue was still there sorry if there is anything wrong with this post

**Comment by Banou26** [comment]
I also get increased memory usage after adding a torrent / destroying it.
