### ISSUE TITLE
file.streamTo not working (gives me a 404 url)

### ISSUE THREAD

**Issue by canoziia** [webtorrent/webtorrent#2256]
**What version of this package are you using?**

1.7.2

**What operating system, Node.js, and npm version?**

Chrome 97.0.4692.99 （64 bit）

**What happened?**

file.streamTo gives a url that is 404 NOT FOUND. Could you give me an example of this function? I'm not sure if it's a bug or my mistake.

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by ThaUnknown** [comment]
> [Requires client.loadWorker to be ran beforehand.](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#filestreamtoelem-function-callback-err-elem--browser-only)

**Comment by canoziia** [comment]
> > [Requires client.loadWorker to be ran beforehand.](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#filestreamtoelem-function-callback-err-elem--browser-only)

These are my codes.

js in index.html: 
``` js
if ("serviceWorker" in navigator) {
        window.addEventListener("load", function () {
            navigator.serviceWorker
                .register("/serviceWorker.js", { scope: "/" })
                .then(function (registration) {
                    console.log("ServiceWorker registration successful with scope: ", registration.scope);
                    client.loadWorker(navigator.serviceWorker.controller); // client.loadWorker
                })
                .catch(function (err) {
                    console.log("ServiceWorker registration failed: ", err);
                });
        });
    }
```

serviceWorker.js:
``` js
this.addEventListener("install", (event) => {
    console.log("installing");
    event.waitUntil(console.log("installed successed!!"));
});

```

**Comment by ThaUnknown** [comment]
oh. hm.

I'll clear it up in the docs

use either: https://github.com/webtorrent/webtorrent/blob/master/sw.min.js

or implement https://github.com/webtorrent/webtorrent/blob/master/lib/worker.js in your own custom worker

**Comment by canoziia** [comment]
> oh. hm.
> 
> I'll clear it up in the docs
> 
> use either: https://github.com/webtorrent/webtorrent/blob/master/sw.min.js
> 
> or implement https://github.com/webtorrent/webtorrent/blob/master/lib/worker.js in your own custom worker

thanks, it works well.
