### ISSUE TITLE
git bot closing unfixed issues?

### ISSUE THREAD

**Issue by mitra42** [webtorrent/webtorrent#2284]
It looks like git-bot is closing issues that are unfixed, and they do not appear to be re-openable by mere mortals, but considered by it "Stale" this makes me concerned that there may be many more problems that are still extant, but not showing up because the team working on this seems to be small, and the lack of documentation in the code makes it hard for causual bug finders to dip in and fix one problem without causing others ? 

(The specific issue is #2222 , and I'm not suggesting its a high priority issue, but I bet it bites someone else trying to build something that uses webtorrent, also of relevance is #2279 by @Bruce-Hopkins about the lack of commenting).

**Comment by DiegoRBaquero** [comment]
#2222 is not an actual bug imho, if you are using an external id, as soon as infohash is obtained, that should be used to get it. Feature request to get it on par is something I'm open to reviewing if anyone is willing to work on it.

Bugs/security issues should never be stale and closed, we have certain rules to prevent that.

Happy to hear your thoughts

**Comment by mitra42** [comment]
That's the point - you can't get the infohash from the id without doing an "add", which is a: expensive and unnecessary if its previously been added, and b: I believe will fail if its previously been added.  The only workaround I could find was to keep a separate structure in the caller that maps external id to infohash. 

The usecase that failed was going to a second webpage that had the same video on it. 

I'd have worked on it, but the code is pretty obscure without the comments (as discussed by Bruce in #2279) so its really hard to figure out how to fix something like this - that requires extra data structure in the library - without breaking something else that is making different assumptions.

**Comment by DiegoRBaquero** [comment]
One could re-implement the full parsing (remote or not) as the add to the get. If someone is willing to PR, I'll review it. But I don't think maintainers will.

**Comment by mitra42** [comment]
Yes - probably, except with poorly documented code its easier to build a workaround than to fix the bug :-( which is what I did a long time ago.

**Comment by Saghen** [comment]
A simple rule that might alleviate the issue is only marking stale and closing issues that have a maintainer's comment as the most recent. Here's another example of an issue that never got a resolution https://github.com/webtorrent/webtorrent/issues/2245

**Comment by DiegoRBaquero** [comment]
It is actively mantained, but the few of us can’t be in top of everything. I’m sorry we’ve missed a few issues.

Feel free to bump bugs as much as needed and tag me personally.

**Comment by DiegoRBaquero** [comment]
Gonna close this and try my best to have eyes on everything :)
