### ISSUE TITLE
Allow setting withCredentials option for web seeds that cross domains [patch included]

### ISSUE THREAD

**Issue by zedshaw** [webtorrent/webtorrent#2289]
I have a patch that implements this for review (see below). If this isn't the best solution then the requirement is:

1. I set an option to either WebTorrent or Torrent.
2. WebTorrent then passes the correct fetch({credentials}) to get web seeds across different sites.
3. This should allow cookies set with a .subdomain.com style Domain to then pass to distributed hosts, allowing for authenticated torrents that can be hosted on multiple servers.

This patch does that, and seems to work.  It's used like this:

```javascript
  client.add(media.torrent_file, {private: webtorrent.private, withCredentials: true}, (torrent) => {
    // handle your torrent here
  });
```

**What version of this package are you using?**

Latest version from git, 1.8.12

**What problem do you want to solve?**

There's no way to pass credentials:"include" (xhr.withCredentials) to WebTorrent so that it can access webseeds using authentication cookies cross site.

**What do you think is the correct solution to this problem?**

Not sure if this is the best way, but it seems that adding an option to Torrent allows you to alter the web requests as needed.

**Are you willing to submit a pull request to implement this change?**

Yes, as long as the project is willing to accept the work.  If not then no more work on my side too.

```diff
From c21bbab063884db012b38f8e39c88e025adb6963 Mon Sep 17 00:00:00 2001
From: "Zed A. Shaw"
Date: Mon, 28 Mar 2022 00:49:53 -0400
Subject: [PATCH] Enable users to set a withCredentials option on Torrent
 objects so that webseeds will send credentials:'include' on cross domain
 requests.

---
 lib/torrent.js | 1 +
 lib/webconn.js | 3 +++
 2 files changed, 4 insertions(+)

diff --git a/lib/torrent.js b/lib/torrent.js
index 7c49e6e..ec31dda 100644
--- a/lib/torrent.js
+++ b/lib/torrent.js
@@ -70,6 +70,7 @@ class Torrent extends EventEmitter {
 
     this._debugId = 'unknown infohash'
     this.client = client
+    this.withCredentials = opts.withCredentials
 
     this.announce = opts.announce
     this.urlList = opts.urlList
diff --git a/lib/webconn.js b/lib/webconn.js
index b1170a6..f27a778 100644
--- a/lib/webconn.js
+++ b/lib/webconn.js
@@ -24,6 +24,7 @@ class WebConn extends Wire {
     this.connId = url // Unique id to deduplicate web seeds
     this.webPeerId = sha1.sync(url) // Used as the peerId for this fake remote peer
     this._torrent = torrent
+    this.withCredentials = torrent.withCredentials;
 
     this._init()
   }
@@ -88,6 +89,7 @@ class WebConn extends Wire {
     let requests
     if (files.length <= 1) {
       requests = [{
+        withCredentials: this.withCredentials,
         url: this.url,
         start: rangeStart,
         end: rangeEnd
@@ -133,6 +135,7 @@ class WebConn extends Wire {
       )
       const opts = {
         url,
+        withCredentials: this.withCredentials,
         method: 'GET',
         headers: {
           'user-agent': `WebTorrent/${VERSION} (https://webtorrent.io)`,
-- 
5.17.2 (Apple Git-113)

```

**Comment by DiegoRBaquero** [comment]
I don't see why not, feel free to PR. I'm not 100% sure about naming, but I like the feature
