### ISSUE TITLE
client.seed option to specify port

### ISSUE THREAD

**Issue by Speculor** [webtorrent/webtorrent#2293]
**What version of this package are you using?**
"webtorrent": "^1.8.13"
**What problem do you want to solve?**
We run a webtorrent NodeJS service within the context of kubernetes. In order for the kubernetes ingress (Nginx-ingress attached to an AWS NLB) to be able to seed files, we need a way to bind a specific containerPort to the client.seed service.
**What do you think is the correct solution to this problem?**
Add an option for client.seed for host:port ie "0.0.0.0:8080"
**Are you willing to submit a pull request to implement this change?**
Possibly, if there are no existing workarounds

**Comment by asdfisdffdg** [comment]
Yes need option for port!!!

**Comment by asdfisdffdg** [comment]
it appears it already exists: client.torrentPort, but it is missing from documentation!

**Comment by ThaUnknown** [comment]
> it appears it already exists: client.torrentPort, but it is missing from documentation!

make a PR to add it to docs
