### ISSUE TITLE
Support webtorrent in PWA's

### ISSUE THREAD

**Issue by unicomp21** [webtorrent/webtorrent#2306]
https://github.com/mdn/content/issues/15242#event-6485374059

**Comment by ThaUnknown** [comment]
this is helpful how?
why PWA's only? its not exclusive to PWA's?

**Comment by unicomp21** [comment]
Think Occulus based webgl applications which need to download large amounts of meshes etc.  No, it does not need to be specific to PWA's I suppose.  But, it would be nice if there was an api consumable from the app side, which automatically takes care of all the ServiceWorker concerns (ie the datachannel is running in the serviceworker)

**Comment by ThaUnknown** [comment]
i still dont understand what 3d rendering and VR has to do with webtorrent

it can't be ran in a worker anyways, you still need to manage all the connections and webrtc on the main thread, and push the streams to the workers.

not only would this become incompatible with node, you'd need to re-write webtorrent from scratch just to implement this, and you wouldn't even be saving any resources, just introducing more compatibility issues and overhead

webrtc isnt what takes up the most CPU time in webtorrent right now, but the node readable-stream polyfill

**Comment by unicomp21** [comment]
Are we saying the new "transferable" rtcdatachannel cannot be transferred to a serviceworker?  Did you look at the link above?

**Comment by ThaUnknown** [comment]
> Are we saying the new "transferable" rtcdatachannel cannot be transferred to a serviceworker? Did you look at the link above?

what???
this reply feels like you took the entire message I wrote above, pushed it to the side, and came up with your own response and put it there instead of my message.
neither the word "service worker" or "transferable" showed up in my reply, I don't understand where you're coming from

**Comment by ThaUnknown** [comment]
as WebTorrent is "supported in PWA's" as is visible by [this list](https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#who-is-using-webtorrent-today), and the issue fails to describe if it's meant to be an enhancement, feature request or bug report, instead points to a pending implementation, I'm gonna treat this as "low effort trolling" and close it
