### ISSUE TITLE
Uploaded / Downloaded using all wire sent/received data, not just pieces

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2319]
@alxhotel it's because of https://github.com/webtorrent/webtorrent/pull/2062/files#diff-e5eeda71546bb4a993c32e575d0c54c2ef19adffc968e3f63cf20e623bcedb52R205-R214

is using the whole conn, previously the event was only when a piece was sent/received

**Comment by ThaUnknown** [comment]
this is intended https://github.com/webtorrent/webtorrent/issues/722
