### ISSUE TITLE
Segmentation fault (core dumped) on Alpine

### ISSUE THREAD

**Issue by Stefanuk12** [webtorrent/webtorrent#2327]
**OS**
Linux Alpine
**Package Version**
1.3.22

**Reason**
This **only** occurs on Linux Alpine because one of your dependencies (that have pre-compiled binaries) are not compatible with the musl alpine libc.

I am not sure which one this is.

Similar issue can be seen on stackoverflow [here](https://stackoverflow.com/questions/45019750/docker-node-alpine-8-segmentation-fault-core-dumped)

**Comment by DiegoRBaquero** [comment]
Does the answer found in the link shared work for you?

Out of our hands, if it is bcrypt causing this.

**Comment by Stefanuk12** [comment]
> Does the answer found in the link shared work for you?

Unfortunately not. None of the dependencies use bcrypt anyway - as far as I can see.

**Comment by DiegoRBaquero** [comment]
can you share full stack trace?

**Comment by Stefanuk12** [comment]
> can you share full stack trace?

I used the following script to test
```js
const WebTorrent = require("webtorrent")
const client = new WebTorrent()

const torrentId = 'https://webtorrent.io/torrents/wired-cd.torrent'

client.add(torrentId, {
    path: "./"
},function (torrent) {
  torrent.on('done', function(){
    console.log('torrent finished downloading')
  })

  torrent.on('download', function (bytes) {
    console.log('total downloaded: ' + torrent.downloaded)
    console.log('progress: ' + torrent.progress)
  })

  console.log('Torrent name:', torrent.name)
  console.log('Files:')
  torrent.files.forEach(file => {
    console.log('- ' + file.name)
  })
  
  // Deselect all files on initial download
  torrent.files.forEach(file => file.deselect());
  torrent.deselect(0, torrent.pieces.length - 1, false);

  // Torrents can contain many files. Let's use the .mp4 file
  const file = torrent.files.find(function (file) {
    console.log(`We will only download and play ${file.name}`)
    file.select()
    return file.name.endsWith('.mp3')
  })
})
```

There is no stacktrace, it just logs `Segmentation fault (core dumped)` and exits the process. With that torrent, it does it at the end of downloading but with longer torrents, it may do it sooner.

```
total downloaded: 1949696
progress: 0.03477209402199473
total downloaded: 1949696
progress: 0.03477209402199473
torrent finished downloading
Segmentation fault (core dumped)
```

**Comment by DiegoRBaquero** [comment]
there's no log files in cwd? I can't help with just this info

**Comment by Stefanuk12** [comment]
Here's a list of packages that may use binaries. (I searched for .c)
```
utp-native
libutp
napi-macros
bufferutil
utf-8-validate
```

**Comment by DiegoRBaquero** [comment]
if you rebuild them all, does it work?

**Comment by Stefanuk12** [comment]
> if you rebuild them all, does it work?

Just tried that, nope.
