### ISSUE TITLE
webtorrent not working in the browser

### ISSUE THREAD

**Issue by maxakash** [webtorrent/webtorrent#2331]
I am using the below code to run webtorrent in the browser
```
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>

<script>
  var client = new WebTorrent()

  const torrentId = 'magnet:?xt=urn:btih:8148C169C4B84048FCF8D44AAF275F82BC33829E&dn=Spider-Man%3A+No+Way+Home+%282021%29+%5B1080p%5D+%5Byts.torrentbay.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=http%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce'
  console.log("running");

  const torrent = client.add(torrentId)

  torrent.on('ready', () => {
    console.log('Torrent name:', torrent.name)
    console.log(`Files:`)
    torrent.files.forEach(file => {
      console.log('- ' + file.name)
    })

    // Torrents can contain many files. Let's use the .mp4 file
    const file = torrent.files.find(file => file.name.endsWith('.mp4'))

    // Display the file by adding it to the DOM
    file.appendTo('body', { muted: true, autoplay: true })
  })
</script>
```

It only works when I use the magnet link for sintel.mp4. For all other magnet links it doesn't work. I have even tried adding different trackers.

**Comment by meotimdihia** [comment]
Trackers had to support the webtorrent protocol first.

**Comment by maxakash** [comment]
> meotimdihia

Can you please give me a list of trackers supported by webtorrent protocol ?
Thanks

**Comment by meotimdihia** [comment]
I just re-visited to check if it matures enough for everyone to use. (I may be wrong something, you should verify it)
And it is explained in the Readme.md.
1. We need everyone to use a torrent client that supports Webtorrent first. ( Hard part)
2. Torrent files have to add trackers support Webtorrent. ex: https://instant.io/ (I think you have to find the list)

![msedge_2022-06-20_22-00-02](https://user-images.githubusercontent.com/300961/174630439-6f1e6f5a-f1c9-4d77-865c-90cea79ec80d.png)
