### ISSUE TITLE
Option for default number of offers per announce

### ISSUE THREAD

**Issue by tom-adsfund** [webtorrent/webtorrent#2333]
I think it's at 50, but my application would benefit from a lower number.

**Comment by DiegoRBaquero** [comment]
It's 5 by default: https://github.com/webtorrent/bittorrent-tracker/blob/a048097ab41231f15b835c44bc7ed24008afb9ec/lib/client/websocket-tracker.js#L61

**Comment by tom-adsfund** [comment]
Thanks for correcting me!

So I guess that means I can just pass in a getAnnounceOpts function and set numwant, and then I'll get that option I'm looking for?

**Comment by tom-adsfund** [comment]
Awesome! I'm guessing that the torrent-level opts overwrite the client-level opts?

**Comment by DiegoRBaquero** [comment]
Correct

Diego

**Comment by tom-adsfund** [comment]
OK, thanks so much for your help!
