### ISSUE TITLE
Webtorrent.add() is not working even after 5 minutes, seeded torrent is not downloading

### ISSUE THREAD

**Issue by resession** [webtorrent/webtorrent#2340]
**What version of this package are you using?**
1.8.24

**What operating system, Node.js, and npm version?**
ubuntu, node v16.15.1, npm v8.11.0

**What happened?**
i am using webtorrent on a ubuntu vps. the following code will not resolve to a torrent even after 5 minutes, it is a legal torrent that i created for myself(which has no copyrighted content) and i have multiple computers seeding this torrent.
```
new Promise((resolve, reject) => {
client.add('3a3cdaed103c555f8067a7e77e118f21a2d65c70', {path: 'somePathHere'}, (torrent) => {
resolve(torrent) // does not work
// torrent.on('done', resolve) will not work either
})
})
```
i used deluge and qbittorrent on my ubuntu vps and the infoHash/torrent downloaded as expected, so this issue is with webtorrent only.

**What did you expect to happen?**
the torrent should download as expected

**Are you willing to submit a pull request to fix this bug?**
i am but i wouldn't know where to start and i don't know if this is even a bug. needs to be researched more.

**Comment by Ryan6578** [comment]
Does the user you're running the app with have r/w permissions for the path? Are you sure the torrent is good? Have you tried it with other public torrents to make sure it's not just yours?

**Comment by resession** [comment]
fixed by using `tracker : {wrtc}` option and using webtorrent-hybrid
