### ISSUE TITLE
Malware detected Avira/Windows Defender:  Misleading:Win32/Lodi

### ISSUE THREAD

**Issue by wellington1993** [webtorrent/webtorrent#2341]
![image](https://user-images.githubusercontent.com/6920053/176083766-7bb5feab-107f-484b-9816-c25080ca596c.png)

Detectado: Misleading: Win32/Lodi
Data: 28/06/2022 00:03
Detalhes: Este programa exibe mensagens de produtos enganosos.
file: C:\Users\chris\Downloads\WebTorrentSetup-v0.24.0(1).exe
file: C:\Users\chris\Downloads\WebTorrentSetup-v0.lqibg8hg.24.0(1).exe.part

From VirusTotal:
https://www.virustotal.com/gui/file/08b97a6a4b5999bd0f0c2f0eb368eb938a16c373999b672db24ea89664d35714

![image](https://user-images.githubusercontent.com/6920053/176084464-7cb4534c-3853-4d63-85a7-f4a3daaa0e8f.png)

**Comment by DiegoRBaquero** [comment]
It’s a torrent app. Fuck the virus scanning apps marking it unsafe and fuck windows tbh. If you are downloading from website or GitHub, it’s safe.

**Comment by ThaUnknown** [comment]
this is depressing, considering all my webtorrent based apps don't get flagged, so they actually went out of their way to do this, instead of writing some detection for webtorrent. lol.

**Comment by abdulhannanali** [comment]
I also got this notification from Virus Scanner in Windows. An old installer that I used was marked as unsafe. Thankfully, good to know it's just false positive.
