### ISSUE TITLE
Seeding is working correctly???

### ISSUE THREAD

**Issue by Apple1204** [webtorrent/webtorrent#2343]
I am testing in two pcs.
in one pc, I run `webtorrent.seed()` and in another pc, I run `webtorrent.add(<info hash>)`...

but I can't download file with this `webtorrent.add(<info hash>)`..

when I run these code in one pc, It is working but when I try with two pcs, It is not working...

What is the reason?

**Comment by resession** [comment]
i am having the same issue. for some reason, this does not work for me most of the times. few times it works, but most times it does not. and when it does work, it takes over 2 or 3 minutes.

are you computers in the same household/network or is one of your computer a remote vps or something?

**Comment by Apple1204** [comment]
1. One is household pc and another one is VPS...(not working)
2. VPS and VPS (not working)

**Comment by resession** [comment]
yes, same thing. i tried my computer and a remote vps. then i tested it with my computer and another person's computer in another state and country. so both personal computer/vps and personal computer/another person's computer did not work. i hope this gets looked at. webtorrent will be really important for what i am working on.

**Comment by Apple1204** [comment]
Can anyone help me with this problem?

**Comment by Apple1204** [comment]
Hi,  @resession. Did try like that?
run `client.seed()` in you pc and then, in instant.io download with info hash.
Is It working?

**Comment by resession** [comment]
> Hi, @resession. Did try like that? run `client.seed()` in you pc and then, in instant.io download with info hash. Is It working?

instant.io does not seem to work. but one interesting thing is other bittorrent clients work. qbittorrent and deluge works as it should. so only webtorrent is having issues downloading my torrent.

**Comment by Apple1204** [comment]
instant.io is working with my code but It is not working with webtorrent desktop...
I am not sure for this... 
It is working sometimes in qbittorrent

**Comment by resession** [comment]
@Apple1204 i switched to webtorrent-hybrid. Its faster and works on my vps. But i tested with another person and it timed out for them. So works better but doesn't fix it.

**Comment by Apple1204** [comment]
I am using webtorrent-hybrid at the frist time... but It is same for me...
