### ISSUE TITLE
Move SHA1 hashing to another process/worker

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#235]
Creating SHA1 hashes for large multi-gigabyte files can take up **a lot** of CPU time.
- [ ] In the browser, we should investigate moving this work to a web worker with [transferrable objects](http://updates.html5rocks.com/2011/12/Transferable-Objects-Lightning-Fast).
- [ ] In node, we should investigate spawning worker processes to do hashing.

**Comment by astro** [comment]
Transferrable objects worked well for Bitford:
* https://github.com/astro/bitford/blob/master/src/store.js#L616
* https://github.com/astro/bitford/blob/master/src/sha1-worker.js#L18

**Comment by astro** [comment]
It is not clear to me how to integrate this into the browserify process. Maybe with [workerify](https://github.com/shama/workerify)?

**Comment by feross** [comment]
Managed to make `client.seed` much faster by skipping the piece verification in `storage.js`. It's unnecessary since we're the first seeder of a new file.

Before: 
```
createTorrent.parseInput: 0.598ms
index.js:206 createTorrent: 6654.848ms
index.js:211 add: 186.781ms
index.js:220 tasks (storage.load): 6906.296ms
index.js:224 seed: 13752.465ms
```

After:

```
createTorrent.parseInput: 0.626ms
index.js:209 createTorrent: 6656.904ms
index.js:214 add: 419.079ms
index.js:223 tasks (storage.load): 256.499ms
index.js:227 seed: 7337.118ms
```

Total time for 250MB file almost cut in half. 13s to 7s.

**Comment by feross** [comment]
With this PR (https://github.com/michaelrhodes/simple-sha1/pull/1) to `simple-sha`, the time to prepare a 250MB file is only 2 seconds.

**Comment by feross** [comment]
Aaaand, using the web crypto API gets us down to <1 second to seed a 250MB file!

PR out: https://github.com/michaelrhodes/simple-sha1/pull/3

We're now officially in the territory of C speeds. We probably can punt on web workers for a while. This is so much faster than it was before (13.7 seconds).

**Comment by feross** [comment]
Released 0.22.0 using `simple-sha1` for *MUCH* faster perf in the browser.

**Comment by Svenskunganka** [comment]
@ferros This is amazing! Really needed! We should try to push the larger BitTorrent client developers to implement WebRTC as WebTorrent is revolutionary to BitTorrent!

**Comment by feross** [comment]
@Svenskunganka Yep, we need to apply pressure and/or send them pull requests that add WebRTC support. Do you know any client developers?

**Comment by Svenskunganka** [comment]
@ferros Unfortunately not. As for µTorrent, it seems the only thing we can do there is to make a feature request on their forums...

**Comment by servermeta** [comment]
we could also try the other way around: create a desktop and mobile app with node.js/Meteor.

Being desktop based, I could create a bridge between the standard torrent protocol and webtorrent, using Unix Pipes on linux.

**Comment by Svenskunganka** [comment]
@servermeta that won't cut it in the long run as people are still going to use µTorrent, Transmission, Vuze and all the other large BitTorrent clients. The only way to get to the large audience is if those clients adds support for WebRTC. I imagine only seedbox users would be interested in using a bridge.

**Comment by servermeta** [comment]
the idea is to substitute them. We could have the momentum, as webtorrent is firewall proof.

**Comment by MzHub** [comment]
> As for µTorrent, it seems the only thing we can do there is to make a feature request on their forums...

They seem to be quite active with the responses though, so I believe they are reading the requests. A while ago I was already writing a request there, but then I hesitated, since I don't know if that is on the agenda at this point. I thought it might be better to wait for the BEP and other such things that are still pending. What do you think?

**Comment by Svenskunganka** [comment]
@MzHub maybe we can open their eyes with Feross awesome presentation from JSConf Asia? https://www.youtube.com/watch?v=kxHRATfvnlw

It's very educational and really brings forth the weight and importance of WebRTC support!

**Comment by cmawhorter** [comment]
just passing through but npm webworker-threads might be of interest

**Comment by arestov** [comment]
did you see?
https://github.com/pgriess/node-webworker

**Comment by josephfrazier** [comment]
It looks like [threads.js](https://github.com/andywer/threads.js/tree/80da63400f283d9abeaa0c77c3107a091c7bcffb) (`npm install threads`) has most of what is needed here:

* ["Use different APIs (web worker, node child_process) transparently"](https://github.com/andywer/threads.js/tree/80da63400f283d9abeaa0c77c3107a091c7bcffb#threadsjs)
* [Transferable Objects](https://github.com/andywer/threads.js/tree/80da63400f283d9abeaa0c77c3107a091c7bcffb#transferable-objects)

However, it [doesn't](https://github.com/andywer/threads.js/tree/80da63400f283d9abeaa0c77c3107a091c7bcffb#thread-code-in-separate-files) provide the ability to use `require` in the browser, but that [appears](https://github.com/andywer/threads.js/tree/80da63400f283d9abeaa0c77c3107a091c7bcffb#use-external-dependencies) to be an upcoming feature. I wonder if [webworkify](https://github.com/substack/webworkify) could help out with that.

**Comment by feross** [comment]
Closing this. See: https://github.com/webtorrent/webtorrent/issues/1233#issuecomment-386474882 for reasoning.
