### ISSUE TITLE
Please add a limit on internet usage.

### ISSUE THREAD

**Issue by IAMSTANDARD** [webtorrent/webtorrent#2352]
**What version of this package are you using?**
0.24.0

**What problem do you want to solve?**
It uses all the internet available and whenever I run it, I can't do anything else.

**What do you think is the correct solution to this problem?**
I think I should be allowed to choose how much data I want web torrent to use at maximum. 

**Are you willing to submit a pull request to implement this change?**
I don't think I'm capable of doing that.

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#client--new-webtorrentopts

uploadLimit and downloadLimit exist

**Comment by IAMSTANDARD** [comment]
This is in bytes, it is not useful. The limit needs to be set in
percentage. Because the internet speed is not a consistent number. It
changes regularly.

**Comment by IAMSTANDARD** [comment]
from checking internet speed. and then only using 50% or 25% of that
generally.

**Comment by IAMSTANDARD** [comment]
Um, I wish I could, sorry, I was just having problems doing my work
while using web torrent in the background.

**Comment by fijiwebdesign** [comment]
@IAMSTANDARD You can throttle down/upload with 

```ts
webtorrent.throttleDownload (rate: Bytes)
webtorrent.throttleUpload (rate: Bytes)
```

 ```js

// get upload and download speed from somewhere
const downloadSpeed = getInternetDownloadSpeed()
const uploadSpeed = getInterentUploadSpeed()

const percent = 80; 
const ratio = percent/100; 

webtorrent.throttleDownload(downloadSpeed * ratio)
webtorrent.throttleUpload(uploadSpeed * ratio)


```
