### ISSUE TITLE
NodeJS seed doesn't work

### ISSUE THREAD

**Issue by andyoknen** [webtorrent/webtorrent#2354]
Hi! I have a few questions about seeding

I'm looking at your Webtorrent Desktop implementation and I don't fully understand your way - 
You are using a "webtorrent" library (not a "hybrid") in the electron window - as far as I understand, this is equivalent to running code in the browser. Am I right?
And it works great - even with my own tracker

Now I run a script in nodejs that just wants client.seed(filePath) and it doesn't work.
In my case (nodejs) I see requests to the tracker, but it looks like my peer and seed can't connect to each other - this is my headache at the moment.

I don't want to use hybrid (WebRTC) since this is very expensive in terms of resources for my project.
I will be glad of any help and am ready to provide code and logs, although the code does not differ much from the code in the documentation.

**Comment by andyoknen** [comment]
https://github.com/webtorrent/webtorrent/discussions/2353

**Comment by andyoknen** [comment]
I think I'm starting to understand - there is a project https://github.com/webtorrent/webtorrent-cli
And it looks like it needs to be used if I want to use the web torrent client in native nodejs
I will try and supplement this comment after the tests

**Comment by andyoknen** [comment]
It doesn't seem to work properly either - I know that TCP/UDP communications may not always work, but how do you implement this in WebTorrent Desktop and why doesn't it work anywhere else?

**Comment by zenxds** [comment]
may be you need to run your code on a server that the public network can access

**Comment by andyoknen** [comment]
> maybe you need to run your code on a server that the public network can access

But what's the point of this in home use?

**Comment by tolui** [comment]
> maybe you need to run your code on a server that the public network can access

but why on server? Webtorrent supposed to work on client side(local machines)?
