### ISSUE TITLE
Plase support Metalink.

### ISSUE THREAD

**Issue by ytrezq** [webtorrent/webtorrent#2364]
Metalink simplify things in the way a single file can be used for all peer to peer system and thus allow to better share bandwidth with the options supportted by ones but not the others. Here’s an example file :

    <?xml version="1.0" encoding="UTF-8"?>
    <metalink version="3.0"
      xmlns="http://www.metalinker.org/"
      generator="http://metalinks.sourceforge.net/"
      >
    <files>
	    <file name="openethereum/xdai/db/3c648cbdc4c9333d/archive/db/MANIFEST-5000106">
    		<size>3225514</size>
		<verification>
			<hash type="md4">824a1df9bd9ea6300a53bc2459abdfa6</hash>
			<hash type="md5">5c195056e38b0c94aa48c134ee43f0ae</hash>
			<hash type="sha1">3cfe548c8a8908293d44bbe75d9b8a20231d2c6a</hash>
			<hash type="sha256">0958ec814021221216d01e7c9e9c0820e75bf0781cf8705989a190a163705ad8</hash>
			<hash type="sha384">cc1d817a477c41900763c96d5c0b2e0212074a4475ff2b2f2cbf79879f167b2cb56b0d4025d25be75d0b7aa8b9c7ebb9</hash>
			<hash type="sha512">64ba0d7d1d49588d1493c93174102859dc6615fad6b9a9c6259778dd98b5d4a70e4cad176a5be1d611d390bd8abb596bd6ffd13c1bbb7096c091e2fdc84d0356</hash>
			<hash type="ripemd160">cee32a4a1d5000b815c4a223c5449d257724fc2c</hash>
			<hash type="tiger192">e4cb6e4e9f72c36a7dbf61af90da2f7561cbf01f5f9470f9</hash>
			<hash type="crc32">9735c97c</hash>
			<hash type="ed2k">824a1df9bd9ea6300a53bc2459abdfa6</hash>
			<pieces length="4194304" type="sha1">
				<hash piece="0">3cfe548c8a8908293d44bbe75d9b8a20231d2c6a</hash>
			</pieces>
		</verification>
		<resources>
			<url type="magnet" preference="90">xt=urn:sha1:3cfe548c8a8908293d44bbe75d9b8a20231d2c6a&amp;dn=MANIFEST-5000106&amp;xl=3225514</url>
			<url type="ed2k" preference="95">ed2k://|file|MANIFEST-5000106|3225514|824a1df9bd9ea6300a53bc2459abdfa6|/</url>
			<url type="gnunet" preference="100">gnunet://ecrs/chk/8RDBH01K6HGUFVB3QNR6ODM0H5PI5TC76SDUG4AO5UHM7R94OKSNDOR5OIPLGIGSL1MNV6BMF0MSK8KEK2THC1OJIH6GV3RRJ361D38.TE9U8B9CB6IAD8AJ7O4OJ9TL46EEHVSKRCOUQ5CSPM48D76ULD1O9FNP3R9K80NV9Q562RED9S532V412NOMJJBSR3L05TG2QJ6HQKO.3225514</url>
			<url type="torrent" preference="80">ftp://getblockchain.download/openethereum/xdai/db/3c648cbdc4c9333d/archive/db/MANIFEST-5000106.torrent</url>
	    	</resources>
	</file>

**Are you willing to submit a pull request to implement this change?**
no

**Comment by DiegoRBaquero** [comment]
Hello ytrezq, thank you for the suggestion.

However, it doesn't make sense. You can just use the magnet/torrent off the metalink. Because webtorrent does not support the other resources or the verifications.

Also, if you are not willing to submit a PR? Who is going to do it?

**Comment by ytrezq** [comment]
Please repoen !

@DiegoRBaquero : this isn’t for verification but also for dht. In addition to that there’s accessing bittorrent files as you can see. A downloader may support e2Donkey2000 and Gnutella and an other one might not support Gnutella but Bittorent and e2donkey2000.

Thus allowing webtorrent to support Metalink partially would help to have better bandwidth for downloads.

**Comment by DiegoRBaquero** [comment]
If anyone wants to add support for it, they can open a PR. I don't want open issues that probably nobody will work on.

**Comment by ytrezq** [comment]
@DiegoRBaquero : Issue guidelines seems to told it’s Ok to have open Feature request.

Basic support is just the matter of parsing the xml for downloading the torrent files.

**Comment by DiegoRBaquero** [comment]
It is ok, and this issue will be kept forever in the history of the repo if anyone wants to see if it's been suggested and wants to work on it.

Anyone is free to work on Metalink integration and open a PR.

I'm just saving time as it'll go stale in 2 weeks and closed in a month anyways.
