### ISSUE TITLE
torrent.remove() error in remove peers

### ISSUE THREAD

**Issue by wentony30** [webtorrent/webtorrent#2373]
![image](https://user-images.githubusercontent.com/62290720/190013209-49433504-b9ac-495b-9998-91ff939e4274.png)

When removing the torrent it gives an error when removing the peers.
Validate when getting the peer id, I think that would solve it.

**Comment by Jassi10000** [comment]
Also please check if  ( this._peers  ) is getting some value

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/issues/2299
