### ISSUE TITLE
[REACT] Error streamTo, cannot make it work in any way

### ISSUE THREAD

**Issue by drakonkat** [webtorrent/webtorrent#2374]
**What version of this package are you using?**
1.8.30 | 1.8.29 | 1.8.26 | 1.8.14 | 1.7.4

**What operating system, Node.js, and npm version?**
Node v16.17.0 | NPM 8.15.0

**What happened?**
I followed the documentation but never worked
Followed example:
[https://github.com/webtorrent/webtorrent/blob/master/docs/tutorials.md#service-worker-renderer](https://github.com/webtorrent/webtorrent/blob/master/docs/tutorials.md#service-worker-renderer)
The main error is "stream[Symbol.asyncIterator] is not a function
    at ServiceWorkerContainer.<anonymous>"

**What did you expect to happen?**
That it works better than "renderTo" method

**Are you willing to submit a pull request to fix this bug?**
If i can understand the problem maybe i can help

I'm creating a repository with the error that i encountered, i will post in the comment ASAP

**Comment by Baldarello** [comment]
Here you can find our testing project, we tried it on Firefox, Edge, Chrome.

To start it:
1) clone
2) npm i
3) npm run start

webtorrent v 1.8.30
service worker (sw.min.js) got from the node_modules so i guess is the correct one to run with the webtorrent@1.8.30

https://github.com/Baldarello/webtorrent-streamto-error

**Comment by ThaUnknown** [comment]
I can't seem to start the dev server to debug this
```js
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
D:\Webdevelopment\webtorrent-streamto-error\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\Webdevelopment\webtorrent-streamto-error\node_modules\loader-runner\lib\LoaderRunner.js:111:13)     
    at D:\Webdevelopment\webtorrent-streamto-error\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.8.0
```

**Comment by Baldarello** [comment]
Pushed a v0.1.2 with a new script to start the project with node18 (they changed something and react made boom)
"start-node18": "react-scripts --openssl-legacy-provider start"

also added another button to test the renderTo function, that doesn't work too with the "Can only pipe to one destination" error.

If you can pull the update and try to start again ♥

**Comment by ThaUnknown** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/6506529/190417734-4c17e603-9ad2-4384-acca-03fe966642d1.png)

**Comment by ThaUnknown** [comment]
re: renderTo: https://github.com/webtorrent/webtorrent/issues/2369

**Comment by Baldarello** [comment]
![image](https://user-images.githubusercontent.com/13116656/190424570-f35e0f30-cdbe-4b9e-a773-439be6215807.png)

that's what we get, did you try to refresh the page and click the button? because we get it working like 1 time out of 15 tries

**Comment by ThaUnknown** [comment]
browser? version?

**Comment by Baldarello** [comment]
![image](https://user-images.githubusercontent.com/13116656/190425234-b6d4640e-3393-4aa6-abc7-9143a0a3cc3f.png)

already read the #2369 but the "solution" is to use streamTo if I'm not mistaken

**Comment by Baldarello** [comment]
> are you sure you dont have any other service workers registered for the scope? ![image](https://user-images.githubusercontent.com/6506529/190425645-29a190de-20f5-44ff-9215-8adae8d26ffe.png)

yes, only got sw.min.js

![image](https://user-images.githubusercontent.com/13116656/190425894-efc741f9-30d6-45e8-9b1a-b51d10bf7768.png)


browser from the screnshots is Edge v105.0.1343.33, but got the same problems with Chrome v105.0.5195.125 and Firefox v104.0.2

**Comment by ThaUnknown** [comment]
could i see the network tab too?

**Comment by Baldarello** [comment]
![image](https://user-images.githubusercontent.com/13116656/190429768-6e69bf74-fa82-4b70-a88f-87c15365ebb9.png)
I saw the same fetch spam also when it works

**Comment by ThaUnknown** [comment]
ah I see the issue, you're using a library which patches the `fetch` on the window [`globalThis.fetch`] functionality, which breaks it, I recommend you track that down and get rid of it
