### ISSUE TITLE
Client doesn't seed unless restart on nodejs

### ISSUE THREAD

**Issue by injaan** [webtorrent/webtorrent#2375]
**What version of this package are you using?**
1.8.30

**What operating system, Node.js, and npm version?**
Windows 10, nodejs: v16.13.1, npm: 8.1.2

**What happened?**
I run most minimal code for seed one video file. following is my code
```
const WebTorrent = require('webtorrent');
const client = new WebTorrent();

client.seed('./uploads/video.mp4', (torrent)=>{
    console.log(torrent.magnetURI)
});
```
it gives me magnet link
![image](https://user-images.githubusercontent.com/10773668/190580777-4bf7f0cd-336f-4cc0-a4a9-55dd69a18daf.png)

if I add magnet link on other torrent client for download it will stuck at retrieving metadata state and keeps forever. If I restart script metadata will retrieved successfully. And torrent file stuck at "stalled" status forever, no download started unless restart script once.

you can see this problem from following screencast

https://user-images.githubusercontent.com/10773668/190583126-b38cbe21-e800-4098-9b72-da2a7613266f.mp4

**Comment by alEXE-tech** [comment]
What do you get when you just console.log(torrent)?

Maybe there's something in that output that can help us here.

**Comment by tolui** [comment]
> What do you get when you just console.log(torrent)?
> 
> Maybe there's something in that output that can help us here.

`<ref *1> Torrent {
  _events: [Object: null prototype] {
    close: [Function: bound onceWrapper] { listener: [Function: onClose] },
    wire: [Function (anonymous)]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  _debugId: 'faa184c',
  client: <ref *2> WebTorrent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    peerId: '2d5757303130382d64504f79714a694358387877',
    peerIdBuffer: <Buffer 2d 57 57 30 31 30 38 2d 64 50 4f 79 71 4a 69 43 58 38 78 77>,
    nodeId: 'ec47c4d9ca5a5fbe2d78a36d1d77c6447cbbb016',
    nodeIdBuffer: <Buffer ec 47 c4 d9 ca 5a 5f be 2d 78 a3 6d 1d 77 c6 44 7c bb b0 16>,
    _debugId: '2d57573',
    destroyed: false,
    listening: true,
    torrentPort: 51174,
    dhtPort: 63979,
    tracker: {},
    lsd: true,
    torrents: [ [Circular *1] ],
    maxConns: 55,
    utp: true,
    _downloadLimit: -1,
    _uploadLimit: -1,
    serviceWorker: null,
    workerKeepAliveInterval: null,
    workerPortCount: 0,
    throttleGroups: { down: [ThrottleGroup], up: [ThrottleGroup] },
    _connPool: ConnPool {
      _client: [Circular *2],
      _pendingConns: Set(0) {},
      _onTCPConnectionBound: [Function (anonymous)],
      _onUTPConnectionBound: [Function (anonymous)],
      _onListening: [Function (anonymous)],
      _onTCPError: [Function (anonymous)],
      _onUTPError: [Function (anonymous)],
      tcpServer: [Server],
      utpServer: [UTP]
    },
    _downloadSpeed: [Function (anonymous)],
    _uploadSpeed: [Function (anonymous)],
    dht: DHT {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: 0,
      _tables: [LRU],
      _values: [LRU],
      _peers: [RecordCache],
      _secrets: [Array],
      _hash: [Function: sha1],
      _hashLength: 20,
      _rpc: [RPC],
      _verify: null,
      _host: null,
      _interval: Timeout {
        _idleTimeout: 300000,
        _idlePrev: [Timeout],
        _idleNext: [TimersList],
        _idleStart: 634,
        _onTimeout: [Function: rotateSecrets],
        _timerArgs: undefined,
        _repeat: 300000,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 15,
        [Symbol(triggerId)]: 1
      },
      _runningBucketCheck: true,
      _bucketCheckTimeout: Timeout {
        _idleTimeout: 47663,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 641,
        _onTimeout: [Function: checkBucket],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 24,
        [Symbol(triggerId)]: 17
      },
      _bucketOutdatedTimeSpan: 900000,
      listening: true,
      destroyed: false,
      nodeId: <Buffer ec 47 c4 d9 ca 5a 5f be 2d 78 a3 6d 1d 77 c6 44 7c bb b0 16>,
      nodes: [KBucket],
      [Symbol(kCapture)]: false
    },
    enableWebSeeds: true,
    ready: true,
    [Symbol(kCapture)]: false
  },
  announce: [
    'udp://tracker.leechers-paradise.org:6969',
    'udp://tracker.coppersurfer.tk:6969',
    'udp://tracker.opentrackr.org:1337',
    'udp://explodie.org:6969',
    'udp://tracker.empire-js.us:1337',
    'wss://tracker.btorrent.xyz',
    'wss://tracker.openwebtorrent.com'
  ],
  urlList: [],
  path: './uploads',
  addUID: false,
  skipVerify: true,
  _store: [Function: Storage],
  _preloadedStore: null,
  _storeCacheSlots: 20,
  _destroyStoreOnDestroy: false,
  _getAnnounceOpts: undefined,
  strategy: 'sequential',
  maxWebConns: 4,
  _rechokeNumSlots: 10,
  _rechokeOptimisticWire: null,
  _rechokeOptimisticTime: 0,
  _rechokeIntervalId: Timeout {
    _idleTimeout: 10000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 672,
    _onTimeout: [Function (anonymous)],
    _timerArgs: undefined,
    _repeat: 10000,
    _destroyed: false,
    [Symbol(refed)]: false,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 433,
    [Symbol(triggerId)]: 432
  },
  ready: true,
  destroyed: false,
  paused: false,
  done: true,
  metadata: <Buffer 64 38 3a 61 6e 6e 6f 75 6e 63 65 34 30 3a 75 64 70 3a 2f 2f 74 72 61 63 6b 65 72 2e 6c 65 65 63 68 65 72 73 2d 70 61 72 61 64 69 73 65 2e 6f 72 67 3a ... 3825 more bytes>,
  store: ImmediateStore {
    store: CacheStore {
      store: [Storage],
      chunkLength: 16384,
      inProgressGets: Map(0) {},
      cache: [LRU]
    },
    chunkLength: 16384,
    mem: []
  },
  storeOpts: undefined,
  files: [
    File {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _torrent: [Circular *1],
      _destroyed: false,
      _fileStreams: Set(0) {},
      name: 'video.mp4',
      path: 'C:\\Users\\User\\Documents\\webtorrent_test\\uploads\\video.mp4',
      length: 2770390,
      offset: 0,
      done: true,
      _startPiece: 0,
      _endPiece: 169,
      _serviceWorker: null,
      open: [Function: thunk],
      [Symbol(kCapture)]: false
    }
  ],
  pieces: [
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    ... 70 more items
  ],
  _amInterested: false,
  _selections: [],
  _critical: [],
  wires: [],
  _queue: [],
  _peers: {},
  _peersLength: 0,
  received: 0,
  uploaded: 0,
  _downloadSpeed: [Function (anonymous)],
  _uploadSpeed: [Function (anonymous)],
  _servers: [],
  _xsRequests: [],
  _fileModtimes: undefined,
  infoHash: 'faa184cb76162d4025c0c80753a6b3333c8dc8df',
  info: {
    length: 2770390,
    name: <Buffer 76 69 64 65 6f 2e 6d 70 34>,
    'piece length': 16384,
    pieces: <Buffer 79 98 08 ca 46 95 da b2 f4 b6 de b6 54 02 ab 48 4e 4e 73 67 72 41 94 24 ae 78 cb e8 4f b5 21 4a 62 49 ac 07 4b 1c 3f a4 cc 85 2e 09 97 5a 31 db 74 89 ... 3350 more bytes>
  },
  infoBuffer: <Buffer 64 36 3a 6c 65 6e 67 74 68 69 32 37 37 30 33 39 30 65 34 3a 6e 61 6d 65 39 3a 76 69 64 65 6f 2e 6d 70 34 31 32 3a 70 69 65 63 65 20 6c 65 6e 67 74 68 ... 3421 more bytes>,
  name: 'video.mp4',
  infoHashBuffer: <Buffer fa a1 84 cb 76 16 2d 40 25 c0 c8 07 53 a6 b3 33 3c 8d c8 df>,
  created: 2022-09-18T03:37:29.000Z,
  createdBy: 'WebTorrent/0108',
  length: 2770390,
  pieceLength: 16384,
  lastPieceLength: 1494,
  magnetURI: 'magnet:?xt=urn:btih:faa184cb76162d4025c0c80753a6b3333c8dc8df&dn=video.mp4&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com',
  torrentFile: <Buffer 64 38 3a 61 6e 6e 6f 75 6e 63 65 34 30 3a 75 64 70 3a 2f 2f 74 72 61 63 6b 65 72 2e 6c 65 65 63 68 65 72 73 2d 70 61 72 61 64 69 73 65 2e 6f 72 67 3a ... 3825 more bytes>,
  _rarityMap: RarityMap {
    _torrent: [Circular *1],
    _numPieces: 170,
    _pieces: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0,
      ... 70 more items
    ],
    _onWire: [Function (anonymous)],
    _onWireHave: [Function (anonymous)],
    _onWireBitfield: [Function (anonymous)]
  },
  _hashes: [
    '799808ca4695dab2f4b6deb65402ab484e4e7367',
    '72419424ae78cbe84fb5214a6249ac074b1c3fa4',
    'cc852e09975a31db74899d96da45c93e4c4a67f9',
    '01c4120bb414db6cc7980111e59c833418fd82c8',
    '6c0bdd4d528239c779719abaecf4a92e2fe77a77',
    '5867794c208a0aa0bffd5d25d40b5a08dd483263',
    'bd25e95e330a5e237fefe0b6099f9a64bc9247bb',
    'ff3d38de3d5601e4a8107aaa52d5be5e64eecca4',
    '8c907c8a65fcb35d1632e3359d79f19b4c62d3e5',
    'ea4cc4ebff13c8020a7f3df217ac9967fa922411',
    'b1b9acb3428f2c21137ee69ba995887b3f1a3a47',
    '8a63c05aaeb45564535b69a2852d866bad47e9a6',
    '76140d8705312932ce61bbec0886759f269d18ea',
    'ee9b0a935980abbb3b9e8239bf84613fefaf7918',
    'f34df17dd70fbb2c0ca17e94fdf930fb79f6cc40',
    'a5573666f2fb2a970690851903afe5c31c9fd683',
    '37af2df28972de69c0daffb68e67995fcf5ee49d',
    '342367e227b5b867b0c0cfdeafb1bac861d54799',
    '8e230e64f420e2812dab01b46389235f3791d796',
    '6806b509f6ec2621df5f0eb66eb0c4c01beee335',
    '4ba51b79663481618848581f3b33af10c8aef1fa',
    '436e36eda5f6ec3f5fdf4cb07324ae277deda488',
    '989c1543727f1afad0039b66afdcdb9231a4cd0e',
    '0676b67245c7c3882dd9eda7e5daa832bb257c50',
    'ec6f5488caeb9e6908f0cdb47e971f2dc3ed30fd',
    'c2dcf9d1458771af18bcee1a72b8085fbe9e57d5',
    'b5a26e32373f23c8f9c0080a0e2374f7f86b72b2',
    '4f8c18a0e7c7fc298179bb9a2d3facf6d7a6c481',
    '46213a38a6194deeff317d4c3478d5a8f368d383',
    '7e4a5df6e4da3453d2659fd172271b9f8b3b9f2f',
    '7ba862d1640221fb1a4f0d78a30728dd4b7294a3',
    '9247aff9b8d4e884ad07e69db8a0af5bbcfacf89',
    'c1d09038b2b6e426cdd3ff76e94d6f674ef10542',
    '9326085b7a80847163d15da3493ee2274620a4ec',
    '1db5dd4317b08c7c20a64cd1abe5010aced465b4',
    '5e442f4f2c51eba22e4e7105cf8d0d2fa420d15a',
    '67c8f80c1ad19f8f61a6c07d5a23ee250f646344',
    '5c193c2d30196179bb652d6e340d4c298271f4ab',
    '49ae076d8a99c4148b998784299cad6b61a7cbb0',
    'dbd79261888752962021c1a2bbef53af0bc16d17',
    'f3c08caf7ec6d4be23f53613121b5497c2913bc4',
    'cdf2125e06bf11d8678ab56cc798ae77a82861a3',
    'b26ef6fb641d22a04d6299b9fe7f94c80a03d5e2',
    '5a3cee317e2220d6d4e5376d80ef4e053ae38825',
    '25bb8da76feeaefa0532fee67652e35ce5dbd003',
    'a7b76d9d25d6ca3aa4194ce20131750bd9eae1e8',
    'af9ebfa33e188f22e8558f3f03be8acc4cc36d56',
    'b83a4d5e94c195402f1aa5ad234f5b1a5e11f9c4',
    'fea20e778083b66f770f54719857c95ea7c2f9f2',
    'a4a49002e74967399182ee0f5a3ecb9db6c98d21',
    'cc27301571e1e855eeb66099195faa0514ae30df',
    '0f8ca5993d767d31010cbf141726f04d255581bf',
    'ac11d17ae57912f990ed7a7746f30326311184a8',
    '0fd6c819fd2bd81f34b891de0f6679e7a9cf855a',
    '46fd6479cec78d553b3994f0a7cad12e8866bc14',
    '0eb03436c7ae095074e9f9e7a5f7e29160089e98',
    '209765b32b07bae716104f308aa024aadbef3193',
    'd3d0770efae5110e1d23b72c628335bf38e7e70f',
    '9e42691978e4f77c3a55816bdc240ae92e095f20',
    '3a4aa0f0141b1db2434e6761642a4ff23af448bc',
    'cf6d2383d04a51319e173333407090e1ba6121b0',
    'e671835ed402a318e7551568a0601c3f235ace9b',
    'a17a6354ef86e1a0e2aa85de51af833b90ef996d',
    '68528a888114395816088b351c68ea535fac0270',
    '7881e8a3a947f1149afecfdf5f3d161848ea9a89',
    'cf9347c077cd5dc7e48142c86dc7dc0137efac32',
    'ff24e0e6963cc4430f2d5e220e431d7171cddc64',
    'f06559e68ec3035e13533cf9ff41f0b1368065fd',
    'f75e944e265f92a4074292e030b3e1a62cc1579e',
    'e0ccfc9d0367875120f1fe16b8e43b27866adb76',
    'be3432108c47a4b937401c546751e908122a6a86',
    '33dfa620c77b96687ecd3e7410e8efc715bd5a8c',
    '29d037e8eb857f264204a4cd5b308f5a0ac9fe6c',
    '1453b69f3017e69b93d7d93170d7a955e49ebe0f',
    '0e9f75db44b8079cc12ba6ab36e31c7e5571228f',
    '487a2cfb87af56c06ccffe214f7cd1adcfe42ae0',
    '6898347dad26ef18568d6bcf8b451d376213b042',
    '682d057b33d249875b3b7673dba490b13cf868d7',
    'fe1ae7a8c318dadf082a0cd272d7b4563e19a149',
    '3e74f53996bcb808edbe0f21c6c80fb0d041adce',
    '7b6f21294f384e156d5d0239275f655a67903e7f',
    '4f1186ee84c0526fe8c1c0d3fc694b2c2c4319ea',
    '892fb845e4f3722334ad8d56b646be62ddce39dc',
    '400c46d4aaab7eab898db19eea79c3fe7d5b18b2',
    'b2ecee057a88979ba9a13aa420380e37351d8914',
    '66bd6049de6167ea482e925f11e676b233c91477',
    '2c606b311df42cc06ba429a9cd7795b643817c2a',
    '688742a5d626059bc170bcf04a9d33f6b5787064',
    'dcf960121f98d5ee20c45fb623af1c5476e1159f',
    '10f05ad89e1e460ca2bf813d6ab09a00830ef3a3',
    '400a75956bd51a7af81ae46baf0425103397e947',
    'd9ae89d34995932428c823b66477e8dfca5bd21f',
    '1ac26876d17cccd5b5329442512e68d3ca4d5529',
    '9054d6df2f5616a83ae9be3e6c7fafee3c51fa45',
    '25a4cc1c713ff0627d1d591fd7c7cc84ccafa2b2',
    'b5a1cccae412def303f373cab07f1609cb092a18',
    'fed2b2a433c697575ec891726b9f9f509ee31b68',
    '9726aece8290ad19d90cc04083e877efed5fea2d',
    'd87c3c2afc3ec4cddfb282c73af952bb20a38a07',
    '73b7e7fc0f749e791da41cd63b461ac9e7c315d7',
    ... 70 more items
  ],
  _reservations: [
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    null, null, null, null, null, null, null, null, null, null,
    ... 70 more items
  ],
  bitfield: BitField {
    grow: 0,
    buffer: Uint8Array(22) [
      255, 255, 255, 255, 255,
      255, 255, 255, 255, 255,
      255, 255, 255, 255, 255,
      255, 255, 255, 255, 255,
      255, 192
    ]
  },
  discovery: Discovery {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      peer: [Function (anonymous)],
      trackerAnnounce: [Function (anonymous)],
      dhtAnnounce: [Function (anonymous)],
      warning: [Function (anonymous)]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    peerId: '2d5757303130382d64504f79714a694358387877',
    infoHash: 'faa184cb76162d4025c0c80753a6b3333c8dc8df',
    _port: 51174,
    _userAgent: 'WebTorrent/1.8.30 (https://webtorrent.io)',
    destroyed: false,
    _announce: [
      'udp://tracker.leechers-paradise.org:6969',
      'udp://tracker.coppersurfer.tk:6969',
      'udp://tracker.opentrackr.org:1337',
      'udp://explodie.org:6969',
      'udp://tracker.empire-js.us:1337',
      'wss://tracker.btorrent.xyz',
      'wss://tracker.openwebtorrent.com'
    ],
    _intervalMs: 900000,
    _trackerOpts: { getAnnounceOpts: [Function: getAnnounceOpts] },
    _dhtAnnouncing: false,
    _dhtTimeout: false,
    _internalDHT: false,
    _onWarning: [Function (anonymous)],
    _onError: [Function (anonymous)],
    _onDHTPeer: [Function (anonymous)],
    _onTrackerPeer: [Function (anonymous)],
    _onTrackerAnnounce: [Function (anonymous)],
    _onLSDPeer: [Function (anonymous)],
    tracker: Client {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      peerId: '2d5757303130382d64504f79714a694358387877',
      _peerIdBuffer: <Buffer 2d 57 57 30 31 30 38 2d 64 50 4f 79 71 4a 69 43 58 38 78 77>,
      _peerIdBinary: '-WW0108-dPOyqJiCX8xw',
      infoHash: 'faa184cb76162d4025c0c80753a6b3333c8dc8df',
      _infoHashBuffer: <Buffer fa a1 84 cb 76 16 2d 40 25 c0 c8 07 53 a6 b3 33 3c 8d c8 df>,
      _infoHashBinary: 'ú¡\x84Ëv\x16-@%ÀÈ\x07S¦³3<\x8DÈß',
      destroyed: false,
      _port: 51174,
      _getAnnounceOpts: [Function: getAnnounceOpts],
      _rtcConfig: undefined,
      _userAgent: 'WebTorrent/1.8.30 (https://webtorrent.io)',
      _proxyOpts: undefined,
      _wrtc: undefined,
      _trackers: [Array],
      [Symbol(kCapture)]: false
    },
    dht: DHT {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: 0,
      _tables: [LRU],
      _values: [LRU],
      _peers: [RecordCache],
      _secrets: [Array],
      _hash: [Function: sha1],
      _hashLength: 20,
      _rpc: [RPC],
      _verify: null,
      _host: null,
      _interval: Timeout {
        _idleTimeout: 300000,
        _idlePrev: [Timeout],
        _idleNext: [TimersList],
        _idleStart: 634,
        _onTimeout: [Function: rotateSecrets],
        _timerArgs: undefined,
        _repeat: 300000,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 15,
        [Symbol(triggerId)]: 1
      },
      _runningBucketCheck: true,
      _bucketCheckTimeout: Timeout {
        _idleTimeout: 47663,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 641,
        _onTimeout: [Function: checkBucket],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 24,
        [Symbol(triggerId)]: 17
      },
      _bucketOutdatedTimeSpan: 900000,
      listening: true,
      destroyed: false,
      nodeId: <Buffer ec 47 c4 d9 ca 5a 5f be 2d 78 a3 6d 1d 77 c6 44 7c bb b0 16>,
      nodes: [KBucket],
      [Symbol(kCapture)]: false
    },
    lsd: LSD {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      peerId: '2d5757303130382d64504f79714a694358387877',
      infoHash: 'faa184cb76162d4025c0c80753a6b3333c8dc8df',
      port: '51174',
      cookie: 'bittorrent-lsd-2d5757303130382d64504f79714a694358387877',
      destroyed: false,
      annouceIntervalId: Timeout {
        _idleTimeout: 300000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 679,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: 300000,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 472,
        [Symbol(triggerId)]: 432
      },
      server: [Socket],
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false
  },
  [Symbol(kCapture)]: false
}`

**Comment by zackees** [comment]
See webseed. It works much better. Webtorrent seeding using nodejs is kinda known to be broken and just stop.

**Comment by ThaUnknown** [comment]
Fairly sure this is a tracker issue as I can't reproduce it with a local tracker

**Comment by midzer** [comment]
What tracker software did you use locally (with v2), @ThaUnknown?
