### ISSUE TITLE
Tracker object doesn't work on client opts

### ISSUE THREAD

**Issue by injaan** [webtorrent/webtorrent#2376]
**What version of this package are you using?**
1.8.30

**What operating system, Node.js, and npm version?**
Windows 10, nodejs: v16.13.1, npm: 8.1.2

**What happened?**
Tried to initiate new client with custom opts and provided tracker object like following code

```js
const WebTorrent = require('webtorrent');
const trackerObject = {
    announce: [
        'udp://localhost:8000'
    ]
}
const client = new WebTorrent({
    tracker: trackerObject
});

client.seed('./uploads/video.mp4', (torrent)=>{
    console.log(torrent.announce)
});
```

and console logged torrent files announce addresses it gives me default addresses instead my provided custom one

![image](https://user-images.githubusercontent.com/10773668/190893102-4ee26e39-36c5-491b-89ff-ff1ba10964fe.png)

**Comment by gauravsaini** [comment]
`const WebTorrent = require('webtorrent');
const trackerObject = {
    announce: 'udp://localhost:8000'
};
const client = new WebTorrent({
    tracker: trackerObject
});

client.seed('./uploads/video.mp4', (torrent) => {
    console.log(torrent.announce);
});
`
Try this instead

**Comment by injaan** [comment]
@gauravsaini same result

**Comment by gauravsaini** [comment]
@injaan 
`const announceUrls = [
    'udp://localhost:8000',
    // ...additional announce URLs here
];

const client = new Client({
    // other options here...
    announce: announceUrls
});`

**Comment by qjinle** [comment]
I had the same problem

**Comment by LisAlexander1** [comment]
now it works like this
```js
client.seed('./seed-me.txt', { announce: ['ws://[::1]:5000'] }, (torrent) => {})
```

**Comment by LostBeard** [comment]
When looking through the source code last, I noticed the tracker property of opts was never used.

**Comment by SilentBot1** [comment]
I can confirm this is the case. Currently, `client.tracker.announce` (set via `opts.tracker.announce` on client creation) will always be ignored and `torrent.announce` (set via `opts.announce` on torrent creation) will always be used.


```javascript
torrent.seed(..., {announce: ['tracker1', 'tracker2']})
torrent.add(..., {announce: ['tracker1', 'tracker2']})
```
This is the only way trackers are passed through to the `torrent-discovery` instance created in the current versions of WebTorrent.

I will look at getting a fix implemented for this in the next couple of days.
