### ISSUE TITLE
High disk occupation for magnetic re downloading

### ISSUE THREAD

**Issue by WZY1999428** [webtorrent/webtorrent#2400]
Store the magnetic download in nedb and restart the nodejs service. Download a file with half the data size of 10G to add and reuse the client Add adds 100% disk usage
![image](https://user-images.githubusercontent.com/48763949/202204882-82bda72e-c8bb-4628-b228-404eec913d02.png)
![image](https://user-images.githubusercontent.com/48763949/202205021-fad5115d-5e85-4f17-a7d5-84e59e9178ac.png)

**Comment by ThaUnknown** [comment]
when restarting a torrent it's rescanned, meaning all data is re-verified and re-hashed, you can skip this using [skipVerify](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-) which assumes all pieces are already downloaded [even ones that are not so be careful using it!]
