### ISSUE TITLE
Horrific uncaught error code all over this package

### ISSUE THREAD

**Issue by risharde** [webtorrent/webtorrent#2401]
Hi! I totally understand that this module is open source and theoretically free but it's been so horrific to work with that I decided I'd try to make the developers aware of the many issues taking place with it (NodeJS context).

Firstly, I do not understand the unique complexities of a torrent in what it takes to code one to download torrent files but I am getting the impression that whomever wrote this package did not cater for errors - many assumptions were done leading to uncaught errors in mant different areas - and I'm referring to FATAL errors which kills the entire nodejs application even though there is a callback for errors when downloading torrents - somehow it still breaks!

A review of this module is in order. I've been patching this code but only to try to avoid uncaught errors and I don't think it would be useful as a PR but if you think it would be, I can probably try to provide it. Basically I've had to try and catch things because I don't have the time to understand what's really going on due to my limited time.

**Comment by ThaUnknown** [comment]
complaints are cool and all, but you provided no:
- error traces
- version information
- code examples
- actual issues

**Comment by risharde** [comment]
You caught me on the first 3 but really 4? I explained the uncaught errors. The worst thing is to make errors be fatal enough that even try catch within the main program using the package fails. Of course just my opinion but I hardly come across nodejs packages that do that, this one stands out greatly.

It's not that I didn't want to be helpful, I have just been working with a close due date that I cannot provide all the details unfortunately.

Hopefully I can give you more details on specific issues but again the point is that lots of issues in the queue would likely be avoided if the errors are treated differently. An error in a torrent download should hardly ever be critical enough to kill the entire app even with try clauses in the main app.
