### ISSUE TITLE
When cancelling a torrent, the following error appears (does not get caught in the on.error clause either)

### ISSUE THREAD

**Issue by risharde** [webtorrent/webtorrent#2405]
**What version of this package are you using?**
1.9.3

**What operating system, Node.js, and npm version?**
Ubuntu 20.x
Node v16.16.0
Npm v8.11.0

**What happened?**
Cancelling a torrent outputs this error, not exactly sure how to fix this one since I feel like a try catch wouldn't be best here?

TypeError: Cannot read properties of null (reading 'dht')
    at Peer.handshake (/client_nodejs/node_modules/webtorrent/lib/peer.js:330:61)
    at Peer.onConnect (/client_nodejs/node_modules/webtorrent/lib/peer.js:217:44)
    at Socket.<anonymous> (/client_nodejs/node_modules/webtorrent/lib/torrent.js:1860:39)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1173:10)

**What did you expect to happen?**
If the value is null, it should be caught and whatever the problem is should be properly resolved

**Are you willing to submit a pull request to fix this bug?**
No since I don't understand what exactly would need fixing - I don't understand the repercussions of try catching this and now allowing the rest of code to properly execute.

**Comment by ThaUnknown** [comment]
seems like peers are still being spawned after destroy, a longer stack trace could be useful, does this happen on 1.9.2?

**Comment by risharde** [comment]
Sorry for the short stack trace, that's all node gave me during the app termination. I don't exactly know how to get a longer stack trace unfortunately but I'll do some research.

As for the 1.9.2 version, I can't say for sure but I vaguely recall this was an issue with older versions since I only now updated to 1.9.3 (since I have been using a very patched hacky version as I tried to get around these types of uncaught errors).

If I can provide any more details I'll try my best to do so!

**Comment by risharde** [comment]
I don't know if this is helpful, but I tried to destroy the torrent while it was being download - would this error make sense in this case? Or is it that the destroy method isn't doing something properly? Sorry I have limited knowledge here and my environment makes it difficult to debug since I don't run torrents on the dev environment.

**Comment by risharde** [comment]
Alternatively, I tried destroying the entire client after noticing a severe memory leak and that gave me the following error. So there's another place outside of this library that throws an error which kills the app. I'm not sure if the webtorrent module is able to handle these errors to avoid total crashes but I don't think I'm able to do that without manually fixing whatever is causing it and the stack traces seem really short as mentioned above.

Error: UTP_ECONNRESET
    at createUTPError (/client_nodejs/node_modules/utp-native/lib/connection.js:238:15)
    at Connection._onerror (/client_nodejs/node_modules/utp-native/lib/connection.js:175:16) {
  code: 'UTP_ECONNRESET',
  errno: 1
}
