### ISSUE TITLE
Using webtorrent in electron as hybrid client

### ISSUE THREAD

**Issue by Muller555541** [webtorrent/webtorrent#2436]
I built an electron app that plays torrents using webtorrent (kinda like webtorrent-desktop) yet I am not able to connect with instant.io.
Do I have an announce problem? do I have to include webseed announce url to my client?

**Comment by SilentBot1** [comment]
Hey @Muller555541,

I would recommend checking out [webtorrent-desktop](https://webtorrent.io/desktop/) for a reference implementation how to do this. To connect to peers on instant.io, you must have a websocket tracker added to the torrent (must be wss://, not just ws://), as peers using instant.io is unable to speak directly to TCP/UDP clients or trackers.

**Note:** the Ice servers used on instant.io are currently not online at the moment, so this may also harm peer discovery too.

If you run into any errors, please feel provide further information on the issue you are experiencing and I can try to give you a hand.

Many thanks,
Brad Marsden

**Comment by Muller555541** [comment]
dear Brad Marsden
Thank you for the feedback.
 I tried the solution you suggested and it did work !
Thanks again
