### ISSUE TITLE
Update Documentation for CDN Script Tag Usage

### ISSUE THREAD

**Issue by leoherzog** [webtorrent/webtorrent#2449]
In [README.md](), the following is mentioned:

> ##### Script tag
> 
> WebTorrent is also available as a standalone script
> ([`webtorrent.min.js`](webtorrent.min.js)) which exposes `WebTorrent` on the `window`
> object, so it can be used with just a script tag:
> 
> ```html
> <script type='module'>
>   import WebTorrent from 'webtorrent.min.js'
> </script>
> ```
> 
> The WebTorrent script is also hosted on fast, reliable CDN infrastructure (Cloudflare and
> MaxCDN) for easy inclusion on your site:
> 
> ```html
> <script type='module'>
>   import WebTorrent from 'https://esm.sh/webtorrent'
> </script>
> ```

It seems that as of version 2.0, this is no longer true.

https://github.com/webtorrent/webtorrent/blob/v1.9.7/webtorrent.min.js  
vs  
https://github.com/webtorrent/webtorrent/blob/v2.0.0/webtorrent.min.js

This also breaks CDN compatibility, such as [`cdnjs`](https://cdnjs.com/libraries/webtorrent) and [`jsdelivr`](https://www.jsdelivr.com/package/npm/webtorrent).

**Comment by ThaUnknown** [comment]
yes, because this is now in /dist/ so the path is /dist/webtorrent.min.js, when I re-wrote the documentation I interpreted it as if a user manually copied the dist, not the path relative to the repository as that doesn't make sense

**Comment by ThaUnknown** [comment]
anyways I don't see this as a bug, jsdelivr doesn't bundle esm correctly anyways and i've never heard of cdnjs, esm.sh does the job fantastically

**Comment by leoherzog** [comment]
Got it! Thanks!

`https://cdn.jsdelivr.net/npm/webtorrent@2.0.0/dist/webtorrent.min.js`

P.S. `cdnjs` is Cloudflare's, and is one of the three backends that powers `jsdelivr`, depending on user location!

https://jsdelivr.com/statistics

**Comment by leoherzog** [comment]
The following works:

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/webtorrent@1/webtorrent.min.js"></script>
</head>
<body>
  <script>
  document.addEventListener('DOMContentLoaded', function (e) {
    let client = new WebTorrent();
  });
  </script>
</body>
</html>
```

but this does not:

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/webtorrent@2/dist/webtorrent.min.js"></script>
</head>
<body>
  <script>
  document.addEventListener('DOMContentLoaded', function (e) {
    let client = new WebTorrent();
  });
  </script>
</body>
</html>
```

Console:
```js
Uncaught SyntaxError: Unexpected token 'export' (at webtorrent.min.js:1:325217)
test.html:9 Uncaught ReferenceError: WebTorrent is not defined
    at HTMLDocument.<anonymous> (test.html:9:18)
```

Thoughts, @ThaUnknown?

**Comment by ThaUnknown** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <script type='module'>
    import WebTorrent from 'https://cdn.jsdelivr.net/npm/webtorrent@2/dist/webtorrent.min.js'
    let client = new WebTorrent();
  </script>
</head>
<body>
</body>
</html>
```
I also recommend you read up on what defer, async and type does to a script tag, how it affects evaluation and loading orders
