### ISSUE TITLE
upload/download events fire for tracker traffic

### ISSUE THREAD

**Issue by ftreesmilo** [webtorrent/webtorrent#2486]
Can you enable a way to distinguish between other protocol traffic vs torrent chunk data transfer?

**Comment by ThaUnknown** [comment]
without recalculating the data transfered, afaik no, I've known about this for ages now and decided to intentionally keep it this way because it then becomes harder for webtorrent to become leechware, as setting upload to 0 will also stop all download as you cant query trackers

**Comment by ftreesmilo** [comment]
I'm not asking to turn off upload, i just want to segregate the traffic metrics

**Comment by ftreesmilo** [comment]
For speed limit, I don't care.

**Comment by ftreesmilo** [comment]
like.. even a boolean on an upload/download even to tell me if the xfer was chunk data or metadata would really help me out

**Comment by ThaUnknown** [comment]
yes but decoupling the 2 means speed limit would no longer throttle tracker traffic

**Comment by ftreesmilo** [comment]
Does an upload event ever fire for both tracker traffic AND chunk data at once?
Again, I don't care if you keep speed limit the way it is, I just want the data identified in the metrics.

**Comment by ThaUnknown** [comment]
for the 3rd time, yes!
