### ISSUE TITLE
Avoid importing json

### ISSUE THREAD

**Issue by nikolay-borzov** [webtorrent/webtorrent#2490]
**What version of this package are you using?**
`2.0.13`

**What operating system, Node.js, and npm version?**
- OS: Windows
- Node.js: `18.14.1`
- NPM: `9.3.1`

**What happened?**
In a CLI Node.js application (type: "module") importing `webtorrent` outputs:
```
(node:22736) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
```

**What did you expect to happen?**
No warning output.

**Are you willing to submit a pull request to fix this bug?**
Not sure

For Node.js
```javascript
import info from './package.json' assert { type: 'json' }
```
can be replaced with:
```javascript
 import { readFileSync } from 'node:fs'

 const info = JSON.parse(readFileSync(new URL('./package.json', import.meta.url)))
```
But I don't know how to handle reading a JSON file on browser

**Comment by ThaUnknown** [comment]
exactly, there's no other way to read JSON data on browser thats standardized, so this is staying

**Comment by v0l** [comment]
Import assertion is still a proposal feature and is causing problems for me when using this lib in `create-react-app`

**Comment by ThaUnknown** [comment]
then you can downgrade to 1.9.6
