### ISSUE TITLE
Link to Torrent file client.add broken

### ISSUE THREAD

**Issue by PBnFlash** [webtorrent/webtorrent#2494]
I recently updated from a very old version of webtorrent.min.js and none of my videos would load. 

Checking the console:

`Uncaught (in promise) TypeError: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.
    at p (browser.js:6:45)
    at index.js:180:90
    at Array.map (<anonymous>)
    at index.js:180:81
    at Array.map (<anonymous>)
    at index.js:179:24
    at async P (index.js:35:5)
    at async s (index.js:103:7)
p @ browser.js:6
(anonymous) @ index.js:180
(anonymous) @ index.js:180
(anonymous) @ index.js:179
await in (anonymous) (async)
I @ index.js:85
await in I (async)
I @ index.js:55
_onTorrentId @ torrent.js:222
await in _onTorrentId (async)
lt @ torrent.js:142
add @ index.js:266
(anonymous) @ (index):120
`

I am passing client.add a link to a torrent file 

`client.add("{{ .Site.BaseURL }}t/video.mp4.torrent", function (torrent) {`

and it seems(?) to be trying to decode it as something else.

I rebuilt the torrent files with current create-torrent still no luck, works fine in an older version of webtorrent.

**Comment by ThaUnknown** [comment]
fixed in v2.0.18
