### ISSUE TITLE
Invalid torrent identifier 

### ISSUE THREAD

**Issue by midzer** [webtorrent/webtorrent#2495]
Hi,

after upgrading my app to latest v2, seeding files is broken and I get `Invalid torrent identifier` in the console.

Relevant code:
```
const fileInput = document.getElementById('upload');
fileInput.addEventListener("change", () => {
        const files = fileInput.files;
        if (files.length) {
	        const client = new WebTorrent();
	        client.seed(files, { announce }, addTorrent);
	    }
});
```
I've read the breaking changes. What am I missing?

Have a nice weekend
midzer

**Comment by drakonkat** [comment]
I debugged it a little bit and fixed it changing the announce parameter. In the old version you can pass an announce array like this:
`["wss://sometracker.net"]`

In the actual v2 it goes on error with "Invalid torrent identifier", to fix it simple pass it as an array of array of string as in the documentation say and everythings get back to work. Example:
`[["wss://sometracker.net","wss://sometracker.net"]]`

I hope it will help someone

**Comment by midzer** [comment]
Hi @drakonkat and thanks for your comment.

I changed to 
```
const announce = [["wss://tracker.openwebtorrent.com"]];
```
and problem still persists for my app.

**Comment by midzer** [comment]
I solved this by passing an `announceList` (not `announce`) to:

```
client.seed(files, { announceList }, addTorrent);
```
