### ISSUE TITLE
Is WebTorrent Desktop Ever gonna get updated or is it Dead ?

### ISSUE THREAD

**Issue by Kristijan1001** [webtorrent/webtorrent#2498]
This has been updated constantly, but the Webtorrent Desktop App is still like 3 years old.

**Comment by DubiousTunic** [comment]
Yes and I would add that torrents don't seed to browser after running for ~3 minutes making it essentially defunct!!

**Comment by vankasteelj** [comment]
Webtorrent moving to ESM (from CJS) and Webtorrent-desktop being built on Electron, itself being not compatible with ESM (as far as I know, at least), I'm afraid there's an incompatibility issue here: the app could be updated, but not with the latest webtorrent patches and fixes.

**Comment by ThaUnknown** [comment]
duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/2272
