### ISSUE TITLE
Webtorrent rejecting piece requests from another webtorrent instance

### ISSUE THREAD

**Issue by 90felipe09** [webtorrent/webtorrent#2500]
**What version of this package are you using?**

```
"webtorrent": "^2.0.11",
"webtorrent-hybrid": "^5.0.2"
```

**What operating system, Node.js, and npm version?**

```
OS: Windows 11 and Ubuntu 22

npm: 6.14.13

node: v14.17.0
```

**What happened?**

- Two instances of webtorrent are running in the same network in different devices;
- One created a torrent and is seeding it;
- The other one added it and is trying to download the content;
- Both instances recognizes one another as peers;
- Infohash is calculated;
- Seeder receives successives piece requests, but always responds with a reject request payload;
- Due this, download doesn't progress, being always in 0%
- Attached image only illustrates the problem with piece request and reject request as captured from wireshark

![image](https://user-images.githubusercontent.com/6313981/225424275-e16c45b8-fc1c-46c7-8a6a-c0bd60ea004c.png)

**What did you expect to happen?**

I expected that the seeder would accept piece requests and would respond appropriately requests.

**Are you willing to submit a pull request to fix this bug?**

yes, if i discover what may be the issue.

**Extra information**

- Reproduced the experiment in different machines and different network topologies and the problem persists. (Same network peers and Peers in different networks, same network peers but in another network);
- Code used to seed:

```
const torrentOptions: CreateTorrentOptions = {
            name: name,
            createdBy: identity,
            comment: comment,
            info: metadata,
            pieceLength: 16 * 1024
        }
client.seed(filepath, torrentOptions, onSeedStarted);
```
- Code used to download:

```
client.add(
            magneticLink,
            {
                skipVerify: false
            },
            onTorrentAdded)
```

**Comment by ThaUnknown** [comment]
I'm think this is caused by providing custom piece lengths or custom names, which changes the torrent's metadata? I'm not 100% sure on this tho

**Comment by SilentBot1** [comment]
Hey @90felipe09,

Are you able to attempt this again on the newest version of WebTorrent?

I've attempted to replicate the issue with using the same settings as provided (ignoring the `options.info`), and this has worked successfully for me cross-machine between two WebTorrent clients.

If you run into any issues, please let me know with some further replication steps, and I can continue looking into this.
