### ISSUE TITLE
Seed from Download Location

### ISSUE THREAD

**Issue by DubiousTunic** [webtorrent/webtorrent#2503]
Is there a way we can add seeding from a Download location, so that if the files are already on my computer webtorrent will seed them without having to redownload from the tracker?

I am trying to make a bittorrent client in the browser and i want to add torrents and seed from a user-selected folder location

thanks

**Comment by ThaUnknown** [comment]
see [rootdir in storeOpts in client.add](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-), you can specify a path or a FileSystemDirectoryHandle object to use a specific path for seeding that specific torrent, tho it's structure needs to be the same as the created torrent's, if you want to change that you can pass in a custom store with your own file path handling logic
