### ISSUE TITLE
Incorrect File.type delivered

### ISSUE THREAD

**Issue by midzer** [webtorrent/webtorrent#2507]
Howdie,

Using latest version in v2, it sometimes happens that a `File` returns an incorrect `type`.

After investigating source code in https://github.com/webtorrent/webtorrent/blob/dfa56fd08f88db248570e9a152606199135942ce/lib/file.js#L20

I found out that `mime.getType` function needs a File's extension rather that the whole file name, ref https://github.com/broofa/mime#quick-start

A solution would be to extract File extension from `this.name` before passing to `mime.getType`, like so:

```
function getFileExtension(filename) {
  return filename.slice((filename.lastIndexOf(".") - 1 >>> 0) + 2);
}
```
^via StackOverflow

I can open a PR if you like.

Have a nice day
midzer

**Comment by ThaUnknown** [comment]
as per https://github.com/broofa/mime#mimegettypepathorextension

> mime.getType(pathOrExtension)

you issue likely stems from the fact that you're using some little known file type [which you didn't provide in the issue template so we can't reproduce this], as as webtorrent uses mime/lite and not the full blown mime db, which saves ~16kb on bundle sizes

**Comment by midzer** [comment]
Yeah, that was probably the issue. Thanks @ThaUnknown. Gonna close this one for good.
