### ISSUE TITLE
Could this replace Email? (Now you interested) 😂

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [webtorrent/webtorrent#2519]
https://github.com/subins2000/p2pt/issues/55https://github.com/subins2000/p2pt/issues/55

Hello everyone, I'm wondering if WebTorrent, the above way, has the potential to replace email as we know it, and possibly even every other communication, discovery and onboarding channel. I would appreciate your thoughts on this. While it may seem simple at the end, I have spent weeks and many all-nighters considering this possibility.

**Comment by SilentBot1** [comment]
Hi @worldpeaceenginelabs 

As this is more of a question, and not an issue related to WebTorrent, I'm going to close this down.

What you're describing sounds like a perfect use case for using [BEP 46](https://www.bittorrent.org/beps/bep_0046.html), which would allow any device with your private key to update contents of the public key over time, and allow for the peers to pull the latest version of content from the DHT as this updates.

If you have any further questions, feel free to ask them in the comments without re-opening the issue.

**Comment by worldpeaceenginelabs** [comment]
Hi @SilentBot1 

Thanks for hinting me on the BEPs. 

My concept is basicly this:
![image](https://github.com/webtorrent/webtorrent/assets/67427045/7777fd8e-1cca-489f-a7a0-a9e624a12704)
![image](https://github.com/webtorrent/webtorrent/assets/67427045/03c8840c-81b6-4e70-ba25-b8a69644a096)

Should i make this a recommandation for a new BEP maybe?
