### ISSUE TITLE
Add torrent encryption as default download method to avoid `dmca_p2p` report

### ISSUE THREAD

**Issue by yingshaoxo** [webtorrent/webtorrent#2527]
I recently downloaded an animation called `Rick and Morty`, by doing so, the server provider send me a `dmca_p2p` report, and say they'll shutdown my server if I did that.

```
Violation Type: dmca_p2p
Reported By: Vobile Compliance

Our automated detection system has identified activity on your account that appears to violate Vultr's Acceptable Use Policy.
```

The magnet link is: 

___

As far as I know, the transmission has an option to force using encryption method to download files.

If you guys could create this feature, that would be good, otherwise, I'll drop webtorrent for my server safety.

https://en.wikipedia.org/wiki/BitTorrent_protocol_encryption

**Comment by ThaUnknown** [comment]
MSE is already added and enabled by default, I recommend you use a private tracker instead

MSE only really provides protection agains MITM spying, what your issue is that you're seeding to public trackers which is why you got dmca'd

**Comment by yingshaoxo** [comment]
> 

Please don't think me as a professional content sharer, I'm just a normal torrent user who wants to do some contribution by seeding the file.

If I use privite traker, others won't be able to download my file.

**Comment by DiegoRBaquero** [comment]
Please don’t use WebTorrent for copyright infringement DiegoOn 1/05/2023, at 7:53 PM, yingshaoxo ***@***.***> wrote:﻿


Please don't think me as a professional content sharer, I'm just a normal torrent user who wants to do some contribution by seeding the file.
If I use privite traker, others won't be able to download my file.
