### ISSUE TITLE
Failed download on larger files.

### ISSUE THREAD

**Issue by JonathanDotCel** [webtorrent/webtorrent#2534]
Note: please disregard and close the issue if the intergrated Brave browser version is too far forked or divergent from the main release. I have little experience with either.

**What version of this package are you using?**
The version Brave browser uses internally.

**What operating system, Node.js, and npm version?**
Windows 10 (latest), N/A for node and npm

**What happened?**
Clicked a 4gb magnet link.
It contained 3x <100byte files + 1x 4gb file
Let it download to completion.

**What did you expect to happen?**
When I hit "save file", each file would immediately be saved (having been cached).
Instead the smaller files immediately saved to disk while the large file sat on "downloading, 2 hours"

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by ThaUnknown** [comment]
brave is ~80 versions behind so this likely isn't valid, their saving methods are also bad as they use zips loaded into memory directly
