### ISSUE TITLE
Speed limiter (downloadLimit) not working @1.9.7

### ISSUE THREAD

**Issue by vankasteelj** [webtorrent/webtorrent#2582]
**What version of this package are you using?**
1.9.7

**What operating system, Node.js, and npm version?**
Windows 11 x64, Node 20.1.0 (via NW.js) and npm 9.5.1

**What happened?**
Using opts.downloadLimit with a bytes/sec value does not throttle the download speeds. I've tried 3500000 (3,5Mb), 1000000 (1Mb), 10000 (10kb) or 1000 (1kb) doesnt do anything, it still downloads the torrent at somewhat maximum speeds (6 - 10 - 30mb/s depending on the available seeds)

**What did you expect to happen?**
For the download speeds to not go too high

**Are you willing to submit a pull request to fix this bug?**
No, I don't understand how ThrottleGroup works, but this patch on 0.108.x works flawlessly, I've taken it from here (an old never merged PR), maybe there's something there? (link: https://github.com/webtorrent/webtorrent/compare/master...vankasteelj:webtorrent:master)

**Comment by ThaUnknown** [comment]
can't reproduce on [2.1.3](https://github.com/webtorrent/webtorrent/commit/3f160eb96daedf22ce3737e882e16a78d5841d6a)
