### ISSUE TITLE
createServer() method doesn't work in NodeJS

### ISSUE THREAD

**Issue by keerthivasansa** [webtorrent/webtorrent#2613]
**What version of this package are you using?**
2.1.12

**What operating system, Node.js, and npm version?**
Windows 11 
Node 16.18.0
NPM 8.9.2

**What happened?**
After using client.add() to add magnetURI, using the callback `torrent` to create a server with `torrent.createServer()` but it throws an error: `torrent.createServer is not a function`

**What did you expect to happen?**
Create a server for serving the contents of the torrent.

**Are you willing to submit a pull request to fix this bug?**
Yes.

**Comment by ThaUnknown** [comment]
that's a v1 API, you're using webtorrent V2, use client.createServer

**Comment by keerthivasansa** [comment]
Where is the documentation for that? Even the types included in the package seem to be in sync with the old way
