### ISSUE TITLE
uncaught type error: file appendTo is not a function.

### ISSUE THREAD

**Issue by davymaish** [webtorrent/webtorrent#2648]
**What version of this package are you using?**
2.0.37
**What operating system, Node.js, and npm version?**
Linux
**What happened?**
I followed exactly in the docs how to stream a video to a video player and I got the error above. The application assets are compiled by Laravel vite. 
**What did you expect to happen?**
The video to stream like sintel
**Are you willing to submit a pull request to fix this bug?**
Don't have a solution.

**Comment by ThaUnknown** [comment]
the website is outdated and we don't have permissions to update it, see https://github.com/webtorrent/webtorrent/tree/master/docs for up to date documentation

**Comment by lallenfrancisl** [comment]
This issue should be pinned. Wasted a full day because of this
