### ISSUE TITLE
Want to ADD CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by taqui-786** [webtorrent/webtorrent#2673]
I want to add a CODE_OF_CONDUCT.md file . A code of conduct sets the tone for our project community, emphasizing that it is open and welcoming to everyone, regardless of their background, identity, or experience level. This inclusivity can attract a more diverse and talented group of contributors.

Please assign me .

**Comment by Anamika1-cpu** [comment]
Assign me this issue

**Comment by ThaUnknown** [comment]
just make a PR for i
