### ISSUE TITLE
no reasonable clean way to get a timeout on add

### ISSUE THREAD

**Issue by uriva** [webtorrent/webtorrent#2686]
a common use case is that someone is calling `add` on a torrent with not many seeders.

then the callback might never be returned.

the usual approach which is wrapping it in a promise, and using `Promise.race` with a timeout can work, but then the torrent will get added and start downloading eventually, and there would be no easy way to know this happened or clean it up.

**Comment by ThaUnknown** [comment]
you can utilise:
https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#torrentonnopeers-function-announcetype-
