### ISSUE TITLE
Webtorrent does'nt work for torrents other than the example one.

### ISSUE THREAD

**Issue by Zephyriyn** [webtorrent/webtorrent#2706]
version: latest

windows 11

const element = provider.video; // `HTMLVideoElement`
                const client = new WebTorrent()

                const torrentId = '9c464e65465e52864d80d518929f188637bb3083'
                
                client.add(torrentId, function (torrent) {
                    // Torrents can contain many files. Let's use the .mp4 file
                    const file = torrent.files.find(function (file) {

                        return file.name.endsWith('.mp4')
                    })
                    file.appendTo('body')

this doesnt work for any torrent id except the default one. but when i paste the torrent id in the desktop app it works.

**Comment by willmartian** [comment]
Same here.

**Comment by SilentBot1** [comment]
WebTorrent in the browser can only speak to WebRTC peers, not standard TCP or UTP peers.
