### ISSUE TITLE
The Docs Need to be UPDATE.

### ISSUE THREAD

**Issue by JohnGuan** [webtorrent/webtorrent#2737]
**What version of this package are you using?**
1.9.7 and 2.1.33

**What operating system, Node.js, and npm version?**
macOS, LTS(18+)

**What happened?**
After my careful reading of the documentation, code, and testing.
It tortured me for a week. This discrepancy was confirmed by going through the code and history commits after I read the docs thoroughly.
The core problem is. The docs state that downloading a file requires a getBlobURL, and at least 2.1.32. file API has changed drastically.
If following the current docs doesn't work at all for 2.0+ code.

**What did you expect to happen?**
It seems like we should update the docs.

**Are you willing to submit a pull request to fix this bug?**
I'd love to! I can try my best. But it would be better if the API author had some basic instructions or a draft.

**Comment by ThaUnknown** [comment]
[docs on github](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md) are up to date
the webtorrent.io website is outdated, but we don't have access to it, as the person that owns it is MIA and isn't updating it

**Comment by willmartian** [comment]
Hi @ThaUnknown, do you know how long has the site owner been MIA? Is it to the point where references to the webtorrent.io site should be removed from the repo to avoid confusion? Maybe we should make a new docs site on GitHub pages? :eyes: 

**Related:** it looks like the TypeScript types were recently updated to match out-of-date docs on webtorrent.io: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70992

**Comment by ThaUnknown** [comment]
years. co-maintainers deemed that malicious so it was voted against. those types updated outdated types, thats for wt 0.1, we're on like 2.5
