### ISSUE TITLE
Extend to allow standard websockets

### ISSUE THREAD

**Issue by manicphase** [webtorrent/webtorrent#2760]
**What version of this package are you using?**
2.1.37

**What problem do you want to solve?**
Make it easier to push files to a headless server from the browser. 
Simultaneously send files to workers (ie, peertube-runners) before upload is finished. 
Resumable uploads.

**What do you think is the correct solution to this problem?**
Webrtc still seems too flaky to be relied upon in webtorrent-hybrid. Extend Webtorrent to have `WebsocketServer` and `WebsocketClient ` as new peer types. This way the server is guaranteed to be able to download from at least one peer in the swarm.

**Are you willing to submit a pull request to implement this change?**
Yes, but I'd need advice on where to make changes. (Should it be `webtorrent/lib` or `bittorrent-protocol` or somewhere else?)

**Comment by ThaUnknown** [comment]
while this is unironically a good suggestion, it's gonna be difficult to implement a new peer type, which would still be undocumented, same as the current webrtc peer for webtorrent, which after all these years isn't documented lol, but +1
