### ISSUE TITLE
Hi, I have built a collaborative video editor with webtorrent support

### ISSUE THREAD

**Issue by danilaplee** [webtorrent/webtorrent#2775]
Can you add my app to the list of apps using webtorrent?
https://www.starpy.me/

**Comment by SilentBot1** [comment]
Hey @danilaplee

Please submit a PR to add yourself to the [FAQ](https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#who-is-using-webtorrent-today) and I'll be happy to approve this, though as this isn't an issue, I'm going to close this.

Feel free to ask any questions related to this in the closed issue.
