### ISSUE TITLE
Do not use the old `import ... assert` syntax.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [webtorrent/webtorrent#2777]
This package is using the legacy "import assertions" proposal, to import a JSON file in https://github.com/webtorrent/webtorrent/blob/c8ffdda0d0a03571bab2644cb5e0033d47486294/index.js#L20.

That proposal now uses a different syntax: `import info from './package.json' with { type: 'json' }`. The old syntax is only supported in Node.js and Chrome, and they are both planning to remove support for it (Node.js 22 next week, and Chrome 126 in June), so it will make this package not work anymore.

For more info, see https://github.com/tc39/proposal-import-attributes/issues/135.

**Comment by ThaUnknown** [comment]
it was used because it was compatible with webpack, while `with` wasnt, feel free to PR a fix
