### ISSUE TITLE
autoStart option for client.add

### ISSUE THREAD

**Issue by ilyachase** [webtorrent/webtorrent#2780]
Found from one of the old issues, but faced it myself and would be nice to have it: https://github.com/webtorrent/webtorrent/pull/1285

> autoStart option for client.add, when set to false prevents from selecting full torrent from downloading.

**What version of this package are you using?**: latest

**What problem do you want to solve?**: better download control when adding new torrents

**What do you think is the correct solution to this problem?**: add a new option

**Are you willing to submit a pull request to implement this change?**: can try

**Comment by SilentBot1** [comment]
Hi @ilyachase,

This has been implemented recently in #2757 as the [option](https://github.com/webtorrent/webtorrent/blob/41cb62b3b7095742f553de169bf1ce8e319ea6cb/docs/api.md?plain=1#L129) `deselect` when performing `client.add`.

**Comment by ilyachase** [comment]
@SilentBot1 cool! Although I don't think the [docs ](https://webtorrent.io/docs)have been updated?

**Comment by SilentBot1** [comment]
> Although I don't think the [docs ](https://webtorrent.io/docs)have been updated?

[webtorrent.io](https://webtorrent.io) can't be updated by the remaining active maintainers, so it's best to just refer to the documentation in GitHub instead.

**Comment by ilyachase** [comment]
I didn't know, thanks
