### ISSUE TITLE
wrong Return Value type of client.get() in @types/webtorrent packages

### ISSUE THREAD

**Issue by TechQuery** [webtorrent/webtorrent#2782]
## What version of this package are you using?

`@types/webtorrent@0.109.8`

## What operating system, Node.js, and npm version?

- OS: Windows 10 Pro 22H2
- Node.js: 18.x
- PNPM: 9.x

## What happened?

Latest WebTorrent has an async `client.get()` method:

https://github.com/webtorrent/webtorrent/blob/41cb62b3b7095742f553de169bf1ce8e319ea6cb/docs/api.md?plain=1#L231-L233

but its Type Defination package has no `Promise` type on the return value of `client.get()`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0474990ae3c1b3745cc7bd6dd83f69c2f574f4de/types/webtorrent/index.d.ts#L136

## What did you expect to happen?

The Type Defination package has the same type of the Implement package.

## Are you willing to submit a pull request to fix this bug?

I may submit a PR after this bug being confirmed by @webtorrent team.

**Comment by ThaUnknown** [comment]
yes, this is a bug in the `@types/webtorrent` package, which isn't maintained by webtorrent, we have no control over it
