### ISSUE TITLE
Version 2.2.1 requires webrtc-polyfill due to loose dependency on torrent-discovery

### ISSUE THREAD

**Issue by proton-ab** [webtorrent/webtorrent#2796]
**What version of this package are you using?**

2.2.1

**What operating system, Node.js, and npm version?**

`node:18-alpine` @ https://hub.docker.com/_/node/tags

**What happened?**

```
18-alpine: Pulling from library/node
Digest: sha256:5069da655539e2e986ce3fd1757f24a41b846958566c89ff4a48874434d73749
Status: Image is up to date for node:18-alpine
+ yarn --frozen-lockfile --non-interactive
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /drone/src/node_modules/node-datachannel: Command failed.
Exit code: 2
Command: prebuild-install -r napi || (npm install --ignore-scripts --production=false && npm run _prebuild)
Arguments: 
Directory: /drone/src/node_modules/node-datachannel
Output:
prebuild-install warn install No prebuilt binaries found (target=8 runtime=napi arch=x64 libc=musl platform=linux)
npm warn config production Use `--omit=dev` instead.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated are-we-there-yet@1.0.6: This package is no longer supported.
npm warn deprecated gauge@1.2.7: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@1.2.1: This package is no longer supported.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported.
npm warn deprecated npmlog@7.0.1: This package is no longer supported.
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated gauge@5.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm warn deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

added 694 packages, and audited 696 packages in 1m

74 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (5 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> node-datachannel@0.9.1 _prebuild
> prebuild -r napi --backend cmake-js

prebuild info begin Prebuild version 12.1.0
prebuild info build Preparing to prebuild node-datachannel@0.9.1 for napi 8 on linux-x64 using cmake-jsusing libc musl
[
  '/usr/local/bin/node',
  '/drone/src/node_modules/node-datachannel/node_modules/.bin/cmake-js',
  'rebuild',
  '--arch=x64',
  '--CDnapi_build_version=8'
]
ERR! OMG C++ Compiler toolset is not available. Install proper compiler toolset with your package manager, eg. 'sudo apt-get install g++'.
ERR! OMG C++ Compiler toolset is not available. Install proper compiler toolset with your package manager, eg. 'sudo apt-get install g++'.
prebuild ERR! build Error: Failed to build cmake with exit code 1
prebuild ERR! build     at ChildProcess.<anonymous> (/drone/src/node_modules/node-datachannel/node_modules/prebuild/cmakebuild.js:32:19)
prebuild ERR! build     at ChildProcess.emit (node:events:517:28)
prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What did you expect to happen?**

I expect versions below 2.3.0 to not require `webrtc-polyfill` and `node-datachannel`, as that feature is only introduced in 2.3.0. However, version 2.2.2 already bumps `torrent-discovery` requirement to `^11.0.4` which depends on `webrtc-polyfill`. Additionally, all versions below 2.2.2 that loosely depend on `torrent-discovery` in version >= 11.0 will automatically resolve to 11.0.4 which requires `webrtc-polyfill`. This should've been seen as breaking change in `torrent-discovery` and its version bumped to 11.

This should be considered a breaking issue - new native module is now required on versions which do not use its functionality due to lack of strict dependency control on `webtorrent` part. Anyone who is not using proper lockfiles or who wishes to refresh their lockfile will pull in `node-datachannel` via `webrtc-polyfill`. All current consumers of this package that are using Alpine are affected across all webtorrent versions down to [v2.1.28](https://github.com/webtorrent/webtorrent/releases/tag/v2.1.28)

**Are you willing to submit a pull request to fix this bug?**

Not at the moment, there is no clear path to solve this self-incurred dependency hell short of releasing version 2.2.3 which would strictly depend on `torrent-discovery == 11.0.2`, however that would still pull `webrtc-polyfill` dependency via `bittorrent-tracker` which is loose dependency of `torrent-discovery`. A proper new release of either of these packages can not be done without breaking existing `webtorrent` 2.3 packages which makes it a rather ugly situation.

**Comment by ThaUnknown** [comment]
yeah, there's pretty much nothing that can be done about this, you can lock the version of torrent discovery manually if you wish to, this is an unfortunate consequence of automating dependency updates, and there's actually nothing that can be done about it, it can't be removed from npm or undone

I don't consider this breaking, as there's no platform that libdatachannel doesn't support, including shitshows like nodejs: android x86 and arm

seems like your issue can be solved by as you said, using a proper lockfile, locking versions, or adding g++

**Comment by proton-ab** [comment]
> this is an unfortunate consequence of automating dependency updates

In future you could consider making such changes in major releases of `torrent-discovery` or `bittorrent-tracker` (so that `^` is not satisfied by new version), or use pinned versions instead of loose dependency for them so that future changes to these packages do not propagate to older `webtorrent` releases unintentionally. Personally, I'd recommend going forward with version pinning, as you already are using Renovate to update loose dependency (ie. `^11.0.4` update in 2.2.2 is effectively no-op because `^11.0.2` already satisfies it and will automatically pull newest version across `11.*.*`).

> using a proper lockfile

Using lockfile is only ever a temporary solution, they need to be refreshed periodically to update transitive dependencies. Thankfully for me, Yarn allows me to override resolutions of specific packages globally, which means I can pin both `torrent-discovery` and `bittorrent-tracker` to `11.0.2`, however other users might not be so lucky.

> I don't consider this breaking [...] seems like your issue can be solved by [...] adding g++

I would like to reiterate that I should not be forced to do anything if I did not update `webtorrent` dependency. Breaking existing setups for users who did not update your dependency is ill manners and one of pitfalls of Node ecosystem that maintainers should be very careful about. I discovered this in my CI pipeline when Renovate tried to do it's weekly lockfile refresh, so it had minimal impact (aside from time wasted to debug issue), but that will not be true for every consumer of your library. Please be mindful of your users. Thankfully this particular issue's impact is limited only to `musl` distros thanks to `node-datachannel` providing wide range of prebuilt binaries.

**Comment by proton-ab** [comment]
Feel free to close this issue in favor of https://github.com/webtorrent/webtorrent/discussions/2795 if you do not plan to address `webrtc-polyfill` dependency in `2.2.x` releases.

**Comment by ThaUnknown** [comment]
> In future you could consider making such changes in major of torrent-discovery

again, that was automated, it happened in around a second, there was nothing I could have done to stop it

> I would like to reiterate that I should not be forced to do anything

yup it's an unfortunate situation, not much I can do about it as even tho I'm the last dev on this package, I actually have 0 admin permissions on both github and npm, so I can't fix any of this even if I wanted.

Fortunately the impact of this is minimal, you just got unlucky
