### ISSUE TITLE
Syntax error on webtorrent-min.js  for multiple version

### ISSUE THREAD

**Issue by rezos2** [webtorrent/webtorrent#2811]
![Screenshot 2024-06-15 220859](https://github.com/webtorrent/webtorrent/assets/143471984/2a5ac621-4569-4842-9953-26ce9c4c02b6)

I've also tried using 1.9.7 and also hosting webtorrent.min.js  locally with same errors.

**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by SilentBot1** [comment]
Hi @rezos2,

Can you provide the actual error you're seeing? 

This looks like a linting warning, not an actual issue that needs to be reported/fixed, as the library loads without problems in the browser.

**Comment by rezos2** [comment]
invalid asm.js invalid token, the photo is where that invalid token points to on line 16

`<style>
  body { background:black; color:white;}
</style>
<script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>
<script>
//const WebTorrent = require('webtorrent')

const client = new WebTorrent()

// Sintel, a free, Creative Commons movie
var torrentId = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent';

torrentId = 'magnet:?xt=urn:btih:A779FA758F2229586EEBC2E5960EB32FE5659596&amp;dn=Sintel%20(2010)&amp;tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&amp;tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&amp;tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&amp;tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337';

client.add(torrentId, function (torrent) {
  // Torrents can contain many files. Let's use the .mp4 file
  const file = torrent.files.find(function (file) {
    return file.name.endsWith('.mp4')
  })

  // Display the file by adding it to the DOM.
  // Supports video, audio, image files, and more!
  file.appendTo('body')
})

</script>`


this one also fails. Can you provide a working torrent file to test? the sintel torrent tracker is apparently obsolete, i tried one from yify and same asm.js error on line 16

**Comment by SilentBot1** [comment]
Please note that jsdelivr hasn't updated WebTorrent since 1.9.7, and we're currently on 2.4.2.

This example will work, though the video will not play due to a bug with `file.appendTo` in version 1.9.7:
```html
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js"></script>
        <script>

        const client = new WebTorrent()

        // Sintel, a free, Creative Commons movie
        const torrentId = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent';

        client.add(torrentId, function (torrent) {
            // Torrents can contain many files. Let's use the .mp4 file
            const file = torrent.files.find(function (file) {
                return file.name.endsWith('.mp4')
            })

            // Display the file by adding it to the DOM.
            // Supports video, audio, image files, and more!
            file.appendTo('body')
        })

        </script>
    </head>
    <body>
    </body>
</html>
```

Please refer to and use the more up-to-date example here: https://github.com/webtorrent/webtorrent/blob/master/docs/get-started.md

**Comment by LostBeard** [comment]
[Free torrents:](https://github.com/webtorrent/webtorrent/blob/master/docs/free-torrents.md)

Those torrents are working.

[Blazor WASM WebTorrent Client](https://lostbeard.github.io/SpawnDev.BlazorJS.WebTorrents/) that currently uses version 2.3.5. [Blazor WASM WebTorrent Client repo](https://github.com/LostBeard/SpawnDev.BlazorJS.WebTorrents)

**Comment by SilentBot1** [comment]
Hi @rezos2,

As this doesn't appear to be an issue with the library, I'm going to close this issue down, but if you still need further help with this, please feel free to continue discussing it here, or join the Discord [here](https://discord.gg/4PM8JTe8Yy), where I can provide more real-time help.
