### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isIP')

### ISSUE THREAD

**Issue by Pronicio** [webtorrent/webtorrent#2814]
**🔑 Datas :**
• Node version : 20.9.0
• NPM version : 10.2.2
• webtorrent version : [v2.4.1](https://github.com/webtorrent/webtorrent/releases/tag/v2.4.1)

**🛑 What happened?**
I'm using **nuxt** v3.12.2, and I get this error when I import the module.
 ![Texte alternatif](https://i.imgur.com/anwPObr.png)

My application is blank and contains only app.vue with : 
```vue
<template>
  <main>
    <h1>Hello Webtorrent !</h1>
  </main>
</template>

<script setup>
import WebTorrent from 'webtorrent'

onMounted(() => {
  const client = new WebTorrent()
  console.log(client)
})
</script>
```

Here is my nuxt config file:

```ts
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineNuxtConfig({
  devtools: { enabled: true },
  vite: {
    plugins: [nodePolyfills({ protocolImports: true })],
    define: {
      global: {},
    }
  }
})
```

**📍 What did you expect to happen?**
Just make sure the module loads properly, and log the client to verify.

**Comment by SilentBot1** [comment]
Hi Pronicio,

WebTorrent can't be server side rendered and also can't be bundled with
vite.

You should change the import to `webtorrent/dist/webtorrent.min.js` and use
the pre-bundled version to prevent bundling.

To disable ssr, you can set the option to false on your route settings.
Consult the nuxt3 docs here:
https://nuxt.com/docs/guide/concepts/rendering#route-rules

**Comment by Pronicio** [comment]
**Thank you, the tip you gave me works very well.** However, after putting the `sw.min.js` file in the public folder and registering the service worker, the download function is executed but the client doesn't add the torrent. 

```js
  function download() {
    console.log(true) // WORK WELL
    client.add("magnet:...", torrent => {
      console.log(torrent) // DOES NOT WORK
    })
  }

  navigator.serviceWorker.register('./sw.min.js', { scope: './' }).then(reg => {
    const worker = reg.active || reg.waiting || reg.installing
    function checkState (worker) {
      return worker.state === 'activated' && client.createServer({ controller: reg }) && download()
    }

    if (!checkState(worker)) {
      worker.addEventListener('statechange', ({ target }) => checkState(target))
    }
  })
```

I also noticed a cancel request, I don't know if this is normal.
![image](https://github.com/webtorrent/webtorrent/assets/52421988/67ffb807-faff-454e-89d4-e9caca52e531)

Here is the full code : https://sourceb.in/poke0zB6uV  
And the config file : https://sourceb.in/x6kCDlYERE

**Comment by SilentBot1** [comment]
Hi @Pronicio,

Is the magnetURI you're using seeded on the WebRTC swarm?

The callback of `client.add` not being called indicates that metadata is not resolving, meaning there are likely no WebRTC peers.

If you add, the following magnetURI `magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.dev&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent` 

Does this add to the client and call the callback?

**Comment by Pronicio** [comment]
Yours seems to work indeed, I was using this one which is the same video but it seems to be "blocked"...

`magnet:?xt=urn:btih:A779FA758F2229586EEBC2E5960EB32FE5659596&tr=udp%3A%2F%2Ftracker.breizh.pm%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fwww.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fbubu.mapfactor.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&dn=%5BBitsearch.to%5D+Sintel+(2010)+%5B720p%5D+%5BBluRay%5D+%5BYTS.MX%5D`

**Comment by SilentBot1** [comment]
The one you shared likely has peers on the WebRTC swarm (has no websocket trackers). 

WebTorrent in the browser can **not** download from regular TCP/uTP peers, and can only download from WebRTC peers or WebSeeds.

WebTorrent (>=2.3.0) running in NodeJS **can** speak to both regular TCP/uTP peers, and WebRTC peers and effectively relay between the two swarms.

**Comment by Pronicio** [comment]
Okay, I now understand better, that's a pity, thank you very much for your help.
