### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by sojusnik** [webtorrent/webtorrent#2825]
Would be great if this version could be published on Flathub, since the other [WebTorrent](https://flathub.org/apps/io.webtorrent.WebTorrent) version is outdated.

**Comment by SilentBot1** [comment]
Hi @sojusnik,

As noted 2 weeks ago when you raised issue #2792 

> Hi @sojusnik,
> 
> This issue appears to relate to the [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) application/repo and is a duplicate of the issue https://github.com/webtorrent/webtorrent-desktop/issues/2272.
> 
> Due to this, I'm going to close this issue and ask for any further discussion/questions to take place in the issue linked above.

This repo is the underlying library which powers WebTorrent desktop, the versions aren't linked with WebTorrent desktop, and the latest version of WebTorrent desktop is the one released on Flathub. 

Please follow the existing issue here: https://github.com/webtorrent/webtorrent-desktop/issues/2272.
