### ISSUE TITLE
Metadata is forgotten on page reload

### ISSUE THREAD

**Issue by danielblnc** [webtorrent/webtorrent#2829]
Torrent metadata is forgotten by the browser after a page reload, even though the downloaded files are still there. If we are the only seed, this results in a dead torrent until a new peer with metadata appears in the swarm and our browser connects to it.

**What version of this package are you using?**
2.3.2

**What operating system, Node.js, and npm version?**
Chrome, Edge, Brave

**Comment by ThaUnknown** [comment]
yes, webtorrent only stores torrent file data, metadata isn't stored, you need to implement that functionality yourself

**Comment by danielblnc** [comment]
Is there a specific reason for this? It feels like keeping the metadata would be desirable.

**Comment by ThaUnknown** [comment]
it's a library, not a torrent client, for a torrent client it makes sense, for a library not so much

**Comment by danielblnc** [comment]
Related to this, what would be the proper way to delete storage from a torrent for which we don't have metadata? 

```
client.add(infohash)
client.remove(infohash, { destroyStore: true })
```
This doesn't seem to work because torrent.store is not initialized until `_onMetadata()`

**Comment by SilentBot1** [comment]
I believe this does what you're wanting:
```javascript
client.add(infohash, {destroyStoreOnDestroy: true})
```
