### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by theoparis** [webtorrent/webtorrent#2837]
**What problem do you want to solve?**

I would like to see [Deno](https://deno.land) support for the webtorrent package and/or webtorrent CLI.
See #2616, not sure why it is locked and closed.

**What do you think is the correct solution to this problem?**

See https://github.com/denoland/deno/issues/16490#issuecomment-1298376219

**Are you willing to submit a pull request to implement this change?**

Probably not...

Edit: Depends on https://github.com/denoland/deno/issues/16164
```
error: Uncaught (in promise) Error: Cannot find module '../build/Release/node_datachannel.node'
Require stack:
- /home/theo/.cache/deno/npm/registry.npmjs.org/node-datachannel/0.10.1/lib/index.js
```

**Comment by ThaUnknown** [comment]
deno simply doesn't support many things which webtorrent uses, like postinstall scripts, import assertions and a bunch more
