### ISSUE TITLE
File transfer through WebTorrent works on local network, but not on the internet.

### ISSUE THREAD

**Issue by Swanand01** [webtorrent/webtorrent#2842]
**What version of this package are you using?**
2.4.11

**What operating system, Node.js, and npm version?**
Development OS: MacOS
Deployed on: Linux 
Node.js version: 20.10.0
npm version: 10.5.0

**What happened?**
When the client and receiver are on different networks, WebTorrent fails to download from the magnet URL.
I have built a simple P2P file-sharing application using socket io and WebTorrent. 
Socket IO is used to create rooms and establish a connection between the client and receiver.
The sender can seed a file and the receiver can download it. 
This works perfectly fine on a local network, but fails when transferring files over the internet.
No errors or warnings are shown.

Here's the relevant code in my repo:

Send a File:
https://github.com/Swanand01/Pulse/blob/e7c33c9d588a2cdf422e8ee8ea6cf2c9dbb5d218/client/src/hooks/useFileSharing.ts#L48-L71

Download a File:
https://github.com/Swanand01/Pulse/blob/e7c33c9d588a2cdf422e8ee8ea6cf2c9dbb5d218/client/src/hooks/useFileSharing.ts#L120-L157

**What did you expect to happen?**
The file should be downloaded.

**Are you willing to submit a pull request to fix this bug?**
Probably.

**Comment by SilentBot1** [comment]
Hi @Swanand01 

Can you please provide more information on how you tested this, devices, browsers, WebTorrent versions, and if the devices you tested with are behind NAT/CGNAT?

Depending on the internet connection of both peers, you may not solely be able to rely on STUN to allow peers to connect, as there are certain NAT types where peers will still not be able to connect directly to each other:

![image](https://github.com/user-attachments/assets/95f01438-41fa-4885-9843-5ada3bfa63d8)
(source: [liveswitch.io](https://www.liveswitch.io/blog/webrtc-nat-traversal-methods-a-case-for-embedded-turn))

**Comment by Swanand01** [comment]
Hi @SilentBot1, thanks for the quick response!

Here's the web app that I was talking about: [Link](https://pulse-zmn77.ondigitalocean.app/)

I opened the app on two devices, one connected to the WiFi and the other connected to mobile internet. 

I am not sure if these devices are behind a NAT. 

Browsers used on both devices are Chrome.

**Comment by SilentBot1** [comment]
Hi @Swanand01,

After running a quick check with two devices on different internet connections (one in the UK, one in Germany), I've been able to connect both peers and send a file:

![image](https://github.com/user-attachments/assets/f42d70ea-ffb0-4194-8d5b-c0e3f198931f)

From what you've said, and what I can see from testing the site, both of your devices are likely behind CGNAT, preventing the peers from connecting. Unfortunately, the only workaround is to implement a TURN server.

If you would like to test a connection outside of your network, feel free to join this room and verify that you can connect to the machines I tested with above: https://pulse-zmn77.ondigitalocean.app/4b400d76-8b16-49f2-8fb2-57a1e1bcbb2f

**Comment by Swanand01** [comment]
Thanks for your help @SilentBot1!
I'll now look into how to implement a TURN server.
