### ISSUE TITLE
I am trying to implementing webtorrent to my react native project.

### ISSUE THREAD

**Issue by havoc10H** [webtorrent/webtorrent#2845]
I am trying to make simple torrent downloader using webtorrent and react native.
My testing torrent url is https://webtorrent.io/torrents/sintel.torrent.
This torrent has one video file, one image file and other files.
I can download to my mobile phone most contents from torrent but not video file.
I am trying to webtorrent in webview and also webtorrent module of react native.
Please help me make simple torrent video downloader using react native.
Thank you, 
Best.

**Comment by SilentBot1** [comment]
Hi @elite10feenix,

Can you provide more information about what errors you are facing, what you have tried and what your code currently looks like?

It's challenging to help with issues like this without the above information.

**Comment by havoc10H** [comment]
Thank you for care.
I already solved myself.

**Comment by leonlee0116** [comment]
> I am trying to make simple torrent downloader using webtorrent and react native. My testing torrent url is https://webtorrent.io/torrents/sintel.torrent. This torrent has one video file, one image file and other files. I can download to my mobile phone most contents from torrent but not video file. I am trying to webtorrent in webview and also webtorrent module of react native. Please help me make simple torrent video downloader using react native. Thank you, Best.

hi may I ask how did you managed to integrate into React Native project? I was keep getting error when run the app. Please drop me an email whenever you are free thanks leonlee0116jl@gmail.com
