### ISSUE TITLE
When used in dedicated worker, webtorrent can not connect to tracker

### ISSUE THREAD

**Issue by bigradish** [webtorrent/webtorrent#2853]
**What version of this package are you using?**
2.4.12

**What operating system, Node.js, and npm version?**
Windows 11; Node 20.11.1; npm 10.2.4

**What happened?**
When webtorrent is used in a dedicated worker of the Edge browser, and a private tracker is used, after seeding a file, the tracker can not receive the "announce" message from the webtorrent client. When webtorrent is used in the main thread, this issue does not exist.

**What did you expect to happen?**
The tracker can receive messages from a webtorrent client in a dedicated worker of the browser.

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by SilentBot1** [comment]
Hi @bigradish,

Can you please provide steps to replicate this?

Is the private tracker you're attempting to connect to a WebTorrent tracker, or a standard HTTP/UDP tracker?

**Comment by ThaUnknown** [comment]
web workers do not support webrtc, webrtc exists only on the main thread
