### ISSUE TITLE
Add new WebTorrent app: P2PFileShare

### ISSUE THREAD

**Issue by ya1Ry** [webtorrent/webtorrent#2872]
Hey!
I created a new app that allows users to easily share files, would love to get it featured on the FAQ page.
Added WebTorrent credit on FAQ, About and Terms pages :)

<img width="761" alt="Screenshot 2024-10-14 at 12 38 53" src="https://github.com/user-attachments/assets/1b81dbf3-995f-4c71-827f-2753b757cc11">

https://p2pfileshare.com/

Thank u!

**Comment by ahmadnadeem6236** [comment]
Please assign this to me!

**Comment by ya1Ry** [comment]
is it still possible to feature webtorrent apps on webtorrent site?

**Comment by SilentBot1** [comment]
Hey @ya1Ry,

Feel free to create a PR and I can approve and merge this.

As a note, webtorrent.io is in a different repo [here](https://github.com/webtorrent/webtorrent.io), and none of the active maintainers have permission to update this site, so this change would only be to the GitHub page [here](https://github.com/webtorrent/webtorrent/blob/master/docs/faq.md#who-is-using-webtorrent-today).

**Comment by ya1Ry** [comment]
Hey @SilentBot1, thank for the reply and sending the correct repo.

I created a PR - https://github.com/webtorrent/webtorrent/pull/2879
