### ISSUE TITLE
Real Debrid usage?

### ISSUE THREAD

**Issue by rzfzr** [webtorrent/webtorrent#2882]
Anyone knows what it would take to implement RD functionality? The web ui for streaming is very clunky.

**Comment by ThaUnknown** [comment]
RD usage has very little to do with torrenting, you're not running an RD client, and RD providers run their own clients, RD is really just a web seed/url

if you wish to add RD as a webseed in webtorrent, webtorrent already supports webseeds, you can create your own webseed by following [the reference implementation](https://github.com/webtorrent/webtorrent/blob/master/lib/webconn.js)
