### ISSUE TITLE
Getting seeders/leechers from webtorrent?

### ISSUE THREAD

**Issue by akhilcacharya** [webtorrent/webtorrent#298]
How would one get the number of seeders and leechers form a particular torrent?

**Comment by feross** [comment]
There's no easy way to do this right now. PR welcome!

There are two possible ways to interpret this feature request:

- How many peers *that our client is connected to* are seeders vs. leechers?
- How many complete vs. incomplete peers are *reported by each tracker that we are connected to*?

**Comment by vankasteelj** [comment]
I'm interrested in this feature too, to know if and how many of the peers I'm connected to at some point are 'peers I can download from', if the speed is at 0 (are we all trying to get a file that nobody seeds? or is the connexion only taking some time? this kind of info is useful)

**Comment by ThaUnknown** [comment]
```js
// https://stackoverflow.com/a/47225591/14188773
function partition(array, isValid) {
  return array.reduce(([pass, fail], elem) => {
    return isValid(elem) ? [[...pass, elem], fail] : [pass, [...fail, elem]]
  }, [[], []])
}

const [seeders, leechers] = partition(client.torrents[0].wires, ({ isSeeder })=> isSeeder)
```
