### ISSUE TITLE
Handle large files better in the browser

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#319]
**_Moving this issue from https://github.com/feross/instant.io/issues/3 to here, for better visibility.**_

After lots of work on fixing memory leaks, I was able to seed a 1GB video from Firefox and stream it to Chrome! But there are still issues: 
- [ ] Can't seed files larger than 500MB in Chrome due to a [chromium bug](https://code.google.com/p/chromium/issues/detail?id=375297).
- [x] Can't seed or download files larger than 1GB because of a [buffer limitation](https://github.com/nodejs/io.js/issues/1719). This limitation comes from V8 and we could probably lift [this limit](https://github.com/feross/buffer/blob/0b25bfb16c0b4dfb0656fe1d2daa09a3c15c6dcd/index.js#L17) in `feross/buffer` and improve the situation in Firefox.

Besides fixing the above issues, future work should include using browser storage (#86) to get this data out of memory.

---

Update (5/26/2015):
- Chrome supports seeding and video streaming (i.e. downloading) files up to 1GB now, due to [this PR](https://github.com/DamonOehlman/filestream/pull/17) that implements streaming blob reading in the `filestream` package! Downloading via the download blob link is still limited to 500MB until the [chromium bug](https://code.google.com/p/chromium/issues/detail?id=375297) is fixed.

**Comment by kawa-** [comment]
I wondered how mega.nz dealing with the problem and found http://stackoverflow.com/questions/15994554/download-files-like-mega-co-nz . Looks like they are doing every ways hierarchically. How about mega.nz's solution?

**Comment by kawa-** [comment]
But actually, I tried to upload 183.1MB file to mega.nz by Mac OSX Chrome (42.0.2311.135 (64-bit)), it crashed :(

**Comment by kawa-** [comment]
[update] MEGA does not solve it with plugin-free. I tried downloading over 1GB file from MEGA by Firefox, MEGA required addon. Looks like there's so far no compatible way to manage large data within a browser.

**Comment by jakefb** [comment]
Have you seen this https://github.com/eligrey/FileSaver.js/? I'm interested in downloading a blob without displaying a link on the page.

**Comment by kawa-** [comment]
@jakefb I've not tried FileSaver.js, but they say they have a size limitation. Firefox 800MiB, Chrome 500MiB from README.md.

**Comment by feross** [comment]
Chrome supports seeding and video streaming (i.e. downloading) files up to 1GB now, due to [this PR](https://github.com/DamonOehlman/filestream/pull/17) that implements streaming blob reading in the `filestream` package! Downloading via the download blob link is still limited to 500MB until the [chromium bug](https://code.google.com/p/chromium/issues/detail?id=375297) is fixed.

**Comment by aniquetahir** [comment]
@kawa- I can download a 1.8GB file from mega just fine using my Firefox(dev)
https://mega.co.nz/#F!81skTRYK!Ybk7gc4oQfbOM_5P3POzcw

**Comment by kawa-** [comment]
@aniquetahir Great, I've successfully downloaded the file of deepin_2014.3_amd64.iso (1.9GB) from your link in my Firefox ESR (31.7.0, yes it's old) without any addons.
MEGA using blob. I wonder if MEGA manages them.

**Comment by feross** [comment]
WebTorrent should be able to handle downloading a 1.8GB file just fine in Firefox once we lift the 1GB limitation in [buffer](https://github.com/feross/buffer). I'll look at doing that now.

**Comment by feross** [comment]
I just released a new version of the browserify buffer that has an increased max size limit of 2GB, instead of 1GB.

I just tested https://instant.io with a 1.5 GB file. Firefox (nightly) can seed and download it with no problems!

Chrome still can't seed files larger than 500GB because of the [blob bug](https://code.google.com/p/chromium/issues/detail?id=375297), but it can *stream* the 1.5 GB video/audio file without problems now! The download link doesn't work because of the same [blob bug](https://code.google.com/p/chromium/issues/detail?id=375297).

The Chrome team is actively working on that bug, so it's just a matter of time. :+1:

**Comment by alexeisavca** [comment]
HTML5 filesystem API?

**Comment by feross** [comment]
@alexeisavca The filesystem API is Chrome only, and it's non-standard and deprecated (and might be removed from Chrome eventually). I'd rather just wait for chrome to fix the blob bug. I've seen lots of commit activity on it recently – it'll be fixed soon.

**Comment by ericwooley** [comment]
@alexeisavca I actually attempted a workaround using the filesystem api for a chrome extension, and ran into more problems. The 500mb cap applies to all your blobs, so you can make a buffer splice it into blobs, and write it, but once you have created 500mb of them, you run into the same issue. So what you need to do is release the memory from blobs which are already written, but you can't.

We sort of hacked it using https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL, (even though we didn't create an object url out of the blob) and it worked about half the time. The half the time it didn't work, it crashed the browser.

I saw someone claimed some kind of workaround writing from indexdb, but I chose to stop trying to implement half baked solutions and wait for the bug to be fixed.

**Comment by qgustavor** [comment]
Does anyone tried using Streams API for downloading files on Chrome? It allows download huge files but seems an active service worker is required. A test where a 1 GB random file is generated and download: [rawgit link](https://cdn.rawgit.com/qgustavor/4a7222eb1867fe4c6751813176656630/raw/ba8c67685cef16c2a5d1c2bf58c617cdca7de206/).

**Comment by feross** [comment]
The Streams API won't help us with generating a Blob to use with a download link, since Blobs still can't be more than 500MB in Chrome. But it's a good thought.

**Comment by ovidiualx** [comment]
Have you guys looked into what those guys did handling big files? reep.io is their web page and they have the code open source in github. Maybe this can help bypassing the google chrome issues.

**Comment by qgustavor** [comment]
@feross Just don't use blobs: stream the download directly to the disk or temporally store chunks in IndexedDB then download creating in a Service Worker a stream using those stored chunks as source.
@ovidiualx [It uses](https://github.com/KodeKraftwerk/reepio/blob/fe9d0874242764f7120ef0da7f075b7e8744ae3a/src/js/download/storageService.js#L30) the deprecated FileSystem API, which [@feross don't want to use](https://github.com/feross/webtorrent/issues/319#issuecomment-117793051).

**Comment by ericwooley** [comment]
@qgustavor How do you steam directly to disk? 

And can you explain your indexdDB solution more in depth?

**Comment by qgustavor** [comment]
@ericwooley I wrote directme.ga when Streams API was implemented just on Canary, so maybe the spec changed and it's now broken. I will say how it works (or worked), so the only difference will be instead of using [mega](https://github.com/tonistiigi/mega) as a source just use WebTorrent as a source (both libraries uses Node streams).

Let's download some file, let's say [Big Buck Bunny](https://directme.ga/?!MAsFwa4b!d8o1uz6SffMAATSQmERLIYITkyc-eTbKQ6xqI3IQSms). Instead of downloading chunks (via HTTP or WebRTC) and storing it in a big blog it's used to feed a [ReadableSteam](https://streams.spec.whatwg.org/#rs-constructor), which is downloaded using Service Workers and finally being [handled as a normal HTTP download](https://camo.githubusercontent.com/99b81aff225524cb01a7180414ca2f28d6a59e27/68747470733a2f2f692e696d6775722e636f6d2f3735304f7572462e706e67), thus stored in the disk, reducing memory usage and using the disk as the storage.

As ServiceWorkers still [can't connect to WebRTC peers](https://github.com/slightlyoff/ServiceWorker/issues/670) IndexedDB is used as a intermediate storage between the download page and the service worker which will create the download stream. It can be also used to allow the WebTorrent download start before the HTTP download.

**Comment by jimmywarting** [comment]
Whooot! @qgustavor I thought i was the only one that had that idea with service worker + fetch
cheers 🍺 

I knew this was going to be possible long before cuz i could do it in the main thread with response + stream from an existing api that returned a stream but wasn't able to save it until it was possible to construct it in a service worker

**Comment by qgustavor** [comment]
@jimmywarting I never trought I was the only only which got this idea, but maybe one of the first which implemented it, as I don't found nothing about it when I created that website, just the spec. I think those who idealized and wrote Streams API got that idea first.
For the second part, sorry, I could not understand your English.

**Comment by jimmywarting** [comment]
Sorry för my bad English. Yea, they probably thought they needed a way to save large data. But they didn't implement a way create a write stream to the filesystem

**Comment by jimmywarting** [comment]
Did put up an simple example of how to do it in the [readme](https://github.com/jimmywarting/StreamSaver.js#get-a-node-stream-from-webtorrent)

```javascript
const client = new WebTorrent()
const torrentId = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4'
// Sintel, a free, Creative Commons movie

client.add(torrentId, torrent => {
    // Download the first file

    const file = torrent.files[0]
    const writeStream = streamSaver.createWriteStream(file.name)

    // Unfortunately we have two different stream protocol so we can't pipe.
    file.createReadStream()
        .on('data', data => writeStream.write(data))
        .on('end', () => writeStream.close())
})
```

**Comment by feross** [comment]
@jimmywarting Cool module, and including the example is very helpful 👍

**Comment by jimmywarting** [comment]
Thanks

**Comment by feross** [comment]
FYI Chrome finally fixed the 500MB blob size limitation! https://bugs.chromium.org/p/chromium/issues/detail?id=375297#c107

This is shipping in tomorrow's Chrome Canary. We can test it out there and see if things work better now!

**Comment by guest271314** [comment]
@feross  @jimmywarting  Can `webtorrent` or `StreamSaver.js` handle downloading 1GB+ files [Download large data stream (> 1Gb) using javascript](http://stackoverflow.com/questions/42614880/download-large-data-stream-1gb-using-javascript) ?

**Comment by kocoten1992** [comment]
Firefox 50 able to seed to 4GB (maybe more)
Chrome ~1GB, crash on 1.2GB

**Comment by jimmywarting** [comment]
@guest271314 StreamSaver is able to save any size. But it has one limitation in that the service worker dies/restart after 10m. https://github.com/jimmywarting/StreamSaver.js/issues/39

So you need to be quick

**Comment by andreapaiola** [comment]
What is the actual upper limit?

**Comment by feross** [comment]
Chrome supports super large files now (>2GB). I'm closing this issue.
