### ISSUE TITLE
Connect timeout improvements

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#337]
WebRTC connections take longer than TCP connections, especially on networks with high latency since there's a lot of roundtrips involved (I experienced this firsthand while traveling in Berlin last week).

As a hack, I made the connect timeout 25s for all connections: https://github.com/feross/bittorrent-swarm/commit/e4f67a137c7fd96b4f16aa23bec23352ea5f076e
Ideally, we treat each type of peer differently. 5s for TCP connections. 25s for WebRTC connections.

**Comment by ThaUnknown** [comment]
https://github.com/webtorrent/webtorrent/blob/master/lib/peer.js#L9

this was already fixed
