### ISSUE TITLE
Consider applying for Google Summer of Code

### ISSUE THREAD

**Issue by hackerkid** [webtorrent/webtorrent#584]
WebTorrent has a very active community. The applications of GSOC2016 for organizations is not yet started. The reach and audience a GSOC acceptance can bring to a project is exponential. 
If the there are moderators who can spare some time mentoring students, do consider applying for GSOC. I am not sure about the legal terms but this is what I got from the GSOC [website](http://www.google-melange.com/gsoc/document/show/gsoc_program/google/gsoc2015/help_page#1._How_does_a_mentoring_organization) on the eligibility of participating organizations. 

> Mentor organizations must be organizations or individuals running an active and viable open source or free software project whose proposals are approved by Google's Open Source Programs Office. Organizations based in Crimea, Iran, Syria, Cuba, Sudan, and North Korea, with whom we are prohibited by U.S. law from engaging in commerce, are ineligible to participate.

WebTorrent is a really cool mad science project. University students like me would have great fun working on it. 

/cc @feross

**Comment by feross** [comment]
This would have been a great idea, but sadly, we missed the deadline. Next year!

**Comment by hackerkid** [comment]
@feross The program is open now :)

https://summerofcode.withgoogle.com/
