### ISSUE TITLE
Uncaught exceptions in browsers without webrtc support

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#614]
There's an "Error: No WebRTC support: Not a supported browser" exception in Safari.

Visible on https://webtorrent.io. We can handle this more gracefully, which has the excellent side benefit of making torrent with web seeds (http fallback) continue to work just fine.

This would make WebTorrent more viable for use cases like relieving the server load for sites like https://glittering.blue/

**Comment by gverni** [comment]
Hi @feross,  

I started working on this bug, but I found out that as of version 11 Safari is supporting WebRTC. I don't get anymore the "No WebRTC" support, but i'm getting some different exceptions now: 

[Error] Unhandled Promise Rejection: [object DOMError]
	(anonymous function)
	rejectPromise
	n (webtorrent.min.js:1:116340)
	r (webtorrent.min.js:1:189815)
	l (webtorrent.min.js:1:190266)
[Error] Unhandled Promise Rejection: NotSupportedError (DOM Exception 9): The operation is not supported.
	(anonymous function)
	rejectPromise
	play
	s (webtorrent.min.js:1:189293)
[Error] Unhandled Promise Rejection: [object DOMError]
	(anonymous function)
	rejectPromise

The video gets loaded, but it gets played only at the end of the download. 

If you want I can work on those other exceptions instead. I haven't found them in any other bugs, so i'm not sure if someone is already working on them. 

Giuseppe

**Comment by feross** [comment]
@gverni Thanks for looking into this. Sorry for the delay in getting back to you about it.

Safari 11 on macOS does indeed support WebRTC, so this error should not be encountered by most users anymore.

Also, the promise rejection and the delayed video playback are also fixed now, thanks to work by @jhiesey on `videostream`.

I'm going to close this issue now :)
