### ISSUE TITLE
Corrupted mp4 files

### ISSUE THREAD

**Issue by luisnomad** [webtorrent/webtorrent#624]
I use webtorrent to download mp4 video files, and it happens very often that, at the end of the file (98% playback), the video stops and can't continue. Happens on all players, but, it does not happen if I download the same file using bittorrent, or if I stream the video file with webtorrent.

I can provide error details because there are no errors whatsoever.

One thing that might be a hint: I download the file directly to a network drive, not locally (using Mac OS).

**Comment by DiegoRBaquero** [comment]
Do you get a checksum mismatch with the downloaded mp4?

Can you provide more details about your setup? Node version, WebTorrent version, OS, etc.

**Comment by luisnomad** [comment]
Hi, yes, the checksum doesn't match, I have just checked.

Node version: 4.0
Webtorrent: 0.72.2
Mac Os X 10.9.5

Today it has happened again with another file, just 2 minutes near the end, the video playback stopped. Streaming it was okay, but the downloaded file is not.

**Comment by feross** [comment]
@luisnomad Thanks for reporting this. This will be hard to fix without a way to consistently reproduce the issue. Will keep my eye out for this, but any other info you can provide would help a lot!

**Comment by luisnomad** [comment]
If it helps, it only happens when I run webtorrent --download in a network drive (/Volumes/MultimediaDrive/SomeFolder/)

Another thing I have noticed is that webtorrent takes a very long time to exit after finishing the download. Sometimes it takes minutes. I don't know if that has anything to do, but since I see no errors, that's all so far.

Thanks!

**Comment by rom1504** [comment]
I think an example of (non-copyrighted) torrent that reproduce this would be useful.
