### ISSUE TITLE
With a large number of torrents (> 500) WebTorrent blocks, making the entire machine unresponsive

### ISSUE THREAD

**Issue by niieani** [webtorrent/webtorrent#625]
Upon re-adding 500 torrents to WebTorrent (on node, under Linux) the machine basically dies by becoming unresponsive and a hard reboot is required to continue operation.
This is the last output to the console I managed to capture:

<img width="775" alt="screen shot 2016-02-18 at 12 23 27" src="https://cloud.githubusercontent.com/assets/563469/13145878/5d3a5368-d653-11e5-9650-2d85ff1b4bb7.png">

From what I've read online the problem seems to be with I/O going synchronous when overloaded.
I think the solution might be to set a static, configurable limit on all the I/O done by WebTorrent instances.
Equally, IP connections should have a static, global limit, as in default Ubuntu configuration (without changes to `sysctl`) I'm experiencing global connections (unrelated to WebTorrent) being dropped very soon (even with only 100 torrents in the instance).

I realize running 500, or even 100 torrents at the same time is not something most people want to do, but there should be some basic safeguards from the app crashing the system.

**Comment by rom1504** [comment]
related https://github.com/feross/webtorrent/issues/587 https://github.com/feross/webtorrent/issues/599

**Comment by feross** [comment]
WebTorrent needs resource management - this is a known issue.
