### ISSUE TITLE
Proper support for "ws=", "as=" and "xs=" magnet link parameters

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#714]
Full spec here: https://wiki.theory.org/BitTorrent_Magnet-URI_Webseeding
- [X] Retrieving payload data - "ws=", "as=" parameter
- [x] Retrieving metadata - "xs=" parameter

**Comment by DiegoRBaquero** [comment]
This is what I shared you? I'll grab this issue and work on it!

**Comment by feross** [comment]
@DiegoRBaquero Ah, yes. I forgot who originally sent it to me :)

**Comment by feross** [comment]
'xs=' is implemented now, will be released after https://github.com/feross/webtorrent/pull/809 is merged

**Comment by RationalCoding** [comment]
How can the `ws` parameter retreive metadata? I thought it was reserved for ordinary HTTP servers that don't "know" about the torrent protocol at all?

**Comment by DiegoRBaquero** [comment]
@RationalCoding ws doesn't retrieve metadata. It just serves the files of the torrent.

**Comment by RationalCoding** [comment]
I know it doesn't currently, but there's an item on the list "Retrieving metadata - "ws=" parameter". I was wondering how that could be implemented.

**Comment by DiegoRBaquero** [comment]
Ahhhh, I see your point now. It shouldn't. `ws` and `as` are for direct files

**Comment by feross** [comment]
This issue is done. We support all forms of "ws=", "as=" and "xs="
