### ISSUE TITLE
Data usage

### ISSUE THREAD

**Issue by ParkerQ** [webtorrent/webtorrent#738]
- WebTorrent version: curent
- Node.js version:?
- Browser name/version (if using WebTorrent in the browser)
  This may be a silly question but my monthly data usage caps out at 300GB per month, so streaming and download size is important. When I add a magnet link and download to watch on webtorrent, am I only using the amount data of the file size or am I using the amount of file size plus the time used to stream the movie?
  I hope that question makes sense, I wasn't sure how to phrase it.

Thanks,
P

**Comment by alxhotel** [comment]
Hi @ParkerQ,

When you are downloading a file with webtorrent, you are downloading and uploading at the same time.

So, the total amount of data used is usually higher than just the size of the file downloaded.

I hope this answers your question
