### ISSUE TITLE
Error: Offset is out of bounds (like #773)

### ISSUE THREAD

**Issue by aksenofo** [webtorrent/webtorrent#850]
- WebTorrent version:???
- Node.js version: v4.4.5
- Browser name/version (if using WebTorrent in the browser): console

the case #773 still exist

After I **aborted** downloading and **restart** my demo application I have got an error:
 Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at onread (/home/aksenofo/node_modules/webtorrent/node_modules/fs-chunk-store/node_modules/random-access-file/index.js:84:8)
    at FSReqWrap.wrapper [as oncomplete](fs.js:576:17)

I attached tar file with my code and partly downloaded files. I believe, the error for sure linked with  files.
[Error_Offset_is_out_of_bounds.tar.gz](https://github.com/feross/webtorrent/files/344592/Error_Offset_is_out_of_bounds.tar.gz)

**Comment by aksenofo** [comment]
in the line index.js:84:
fs.write(self.fd, buf, _buf._length - offset__, length, offset, onwrite)
where **_buf.length - offset_** is a **_huge negative value_**

**Comment by aksenofo** [comment]
Here is the current tmp folder( the bug 100% reproduced with it )

http://wikisend.com/download/552204/xaa
http://wikisend.com/download/579098/xab

**Comment by feross** [comment]
@aksenofo Your download links expired before I had the chance to download them. Can you re-upload so that I can attempt to reproduce this bug?
