### ISSUE TITLE
Feature Request: control select/deselect default on new torrents

### ISSUE THREAD

**Issue by retrohacker** [webtorrent/webtorrent#873]
I've seen this raised several times (i.e. #758), and I would find it useful for PeerWeb.

When a new torrent is added to a client, it has the files in the torrent set to selected by default. It would be nice to be able to change this so you could fetch the metadata and then control which files you want to download at what priority from there.

This would clean up the logic when you need a single file from a massive torrent (>1k files).

I would like to propose adding a setting to the opts of `client.add` that would allow you to control whether the files in a torrent are selected or deselected by default:
### `client.add(torrentId, [opts], [function ontorrent (torrent) {}])`

Start downloading a new torrent.

`torrentId` can be one of:
- magnet uri (string)
- torrent file (buffer)
- info hash (hex string or buffer)
- parsed torrent (from [parse-torrent](https://github.com/feross/parse-torrent))
- http/https url to a torrent file (string)
- filesystem path to a torrent file (string) _(Node.js only)_

If `opts` is specified, then the default options (shown below) will be overridden.

``` js
{
  announce: [],              // Torrent trackers to use (added to list in .torrent or magnet uri)
  getAnnounceOpts: Function, // Custom callback to allow sending extra parameters to the tracker
  maxWebConns: Number,       // Max number of simultaneous connections per web seed [default=4]
  path: String,              // Folder to download files to (default=`/tmp/webtorrent/`)
  store: Function,           // Custom chunk store (must follow [abstract-chunk-store](https://www.npmjs.com/package/abstract-chunk-store) API)
  startDownload: Boolean     // Automatically start downloading the files once metadata is available
}
```

If `ontorrent` is specified, then it will be called when **this** torrent is ready to be
used (i.e. metadata is available). Note: this is distinct from the 'torrent' event which
will fire for **all** torrents.

If you want access to the torrent object immediately in order to listen to events as the
metadata is fetched from the network, then use the return value of `client.add`. If you
just want the file data, then use `ontorrent` or the 'torrent' event.

If you provide `opts.store`, it will be called as
`opts.store(chunkLength, storeOpts)` with:
- `storeOpts.length` - size of all the files in the torrent
- `storeOpts.files` - an array of torrent file objects
- `storeOpts.torrent` - the torrent instance being stored

**Comment by retrohacker** [comment]
Again, happy to do the legwork on implementing this if it seems like a sane thing to do.

**Comment by vankasteelj** [comment]
I would actually like if we could set all files deselected by default. The .select() or .deselect() file api calls seem pretty heavy on a slow CPU like an Atom Z3735, and as I only play 1 video file at a time, I usually have to deselect all files, then reselect the one I wanna play, which, in case of a 8 to 20 files torrent can take between 5 and 30 sec (on an atom again, on an i5 it goes nearly instant).

**Comment by maxogden** [comment]
@retrohacker did you ever find a workaround for this?

**Comment by SilentBot1** [comment]
This feature has been implemented and is available as the `{deselect: true}` argument within `client.add` as of #2757, from here, once the `metadata` event is fired, you can iterate and filter `torrent.files` and call `file.select()` on files you wish to download.

This can also be achieved by setting the `so` property on `torrent` before the metadata is received or additionally by appending `&so` to the magnet in line with https://www.bittorrent.org/beps/bep_0053.html if the file indexes are known beforehand.

Due to this being implemented, I'm going to close the issue, but please feel free to re-open this if you disagree.
