### ISSUE TITLE
100% CPU use for 20+ seconds on startup

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent#903]
- WebTorrent version: 0.96.4
- Node / browser version: Electron 1.3.3
### Steps to reproduce
- Use WebTorrent Desktop to create a few torrents from large folders with ~100MB each of test data. Remove all trackers except the webtorrent (`wss://`) trackers
- Restart the app

The app becomes unresponsive for ~20+ seconds on startup, while most of the torrent progress bars are stuck at 0%. The whole OS becomes slow to respond. Opening Dev Tools takes ~5+ seconds.

Dev Tools shows that all the resource use is all in the webtorrent process (ie, not in the window or main processes).
### Here's the Timeline view:

<img width="802" alt="screen shot 2016-09-05 at 5 34 02 pm" src="https://cloud.githubusercontent.com/assets/169280/18258682/6165bc00-738f-11e6-9149-00c3553a9232.png">

<img width="798" alt="screen shot 2016-09-05 at 5 34 24 pm" src="https://cloud.githubusercontent.com/assets/169280/18258684/66ca83e2-738f-11e6-967b-19119a6fbaa1.png">
### Potential problems
- Tons of time spent in `close()`
- The top of the flame graph is always 'Timer fired'. Something inside `webtorrent.js` is probably creating zillions of setIntervals or setTimeouts
- Two solid seconds spent in a single (?) call to RTCPeerConnection (probably the constructor?)

**Comment by mmckegg** [comment]
Yep, this is exactly what I'm seeing. 

@feross I recorded the seed-start progress using devtools and attached the dump here for inspection:

[CPU-20161009T155508.cpuprofile.zip](https://github.com/feross/webtorrent/files/518071/CPU-20161009T155508.cpuprofile.zip)

That was seeding 18 torrents all at once. Each file ranges from 5 - 100 MB.

By the way, when `torrentClient.tracker.wrtc = false` there is barely even a noticeable blip of cpu.

**Comment by mmckegg** [comment]
More info:

I'm noticing that even after the initial crazy cpu spike, it stays idling near 40%. When I record timeline/profile, it doesn't actually show anything unusual (very little is happening, virtually idle). But the cpu is still being used by something in that process. Must be another bug in wrtc I suspect 😢

**Comment by feross** [comment]
I think the WebRTC crypto required to set up an RTCPeerConnection object is pretty heavy weight. Will think on ways to improve this.

**Comment by gpetrov** [comment]
@feross  Any news on this? We tracked it down to https://github.com/feross/simple-peer/blob/master/index.js#L263 causing high cpu and taking 2-3secs to close the connections... per peer

**Comment by gpetrov** [comment]
Just to clarify this issue happens if you have more than 10 torrents running with WebTorrent and connecting to multiple peers with webRTC. CPu usage is high initially when adding the torrents and also on every 10 minites refresh from the trackers. So everything locks up every minutes - very annouying.

We had to switch off wrts just like @mmckegg to have our app running. Without WebRTC everything is a breeze... So not sure if this is a bug in the Chrome code or in Webtorrent as it happens to us at RTCPeerConnection.close

@feross could you please investigate as this renders the "web" part of the webtorrent project completely unusable ... have you ran test cases with more than 10 torrent files?

**Comment by feross** [comment]
@gpetrov Thanks for the sleuthing. I think we need to vastly lower the number of webrtc connections we attempt. We should also file a bug with the various browser vendors. Which browser did you experience the 2-3 second close times in?

**Comment by gpetrov** [comment]
@feross we were using the latest chrome from the nwjs project (version 18.6 that is Chrome 54) but due to the high CPU and instability we had to throw away the whole webRTC and are now doing torrents in the isolated node context only. That is running really fine.

**Comment by feross** [comment]
Yeah, this is such a bummer. I wish that webrtc connections weren't so heavyweight in the current webrtc implementations. I'll raise this issue with the chrome team.

**Comment by Marak** [comment]
@feross 

Has there been any activity on this? Any word from the Chrome team, or perhaps local optimizations here in `webtorrent` project?

We are planning to roll out an application using `webtorrent` with many users and are concerned about performance. 

Appreciate any help you can provide in this matter, thank you. 😃

**Comment by MeowTheCat** [comment]
> torrentClient.tracker.wrtc = false
@mmckegg Could you share where you set this? I couldn't find this in webtorrent-desktop. Thank you!
