### ISSUE TITLE
Feature Request: Bind to interface or Stop all traffic option (VPN/proxy drop protection)

### ISSUE THREAD

**Issue by FatalRev** [webtorrent/webtorrent#941]
Currently, WebTorrent immediately continues to torrent after an interface change, resulting in a user being exposed quicker than they can shut down the application.

A preferable solution would be adding the ability to bind to a particular interface and block all other connections à la Vuze.
A quick temporary solution could be a "Stop/Block all traffic" option that can be set to activate whenever a connection drop or change of interface occurs, allowing the user to resume once they've figured out what happened.

**Comment by TylerSharpe11** [comment]
I recently started working on a way to let the user easily set the number of connections they want webtorrent to allow. There are calculators that run a speed test on your connection and tell you the optimal amount of upload and download connections for your connection so I was thinking of maybe having an optimize button that can do that. The default number of connections is 55 and I think that might be too much especially if a user wants to open another torrent in a another tab.

**Comment by feross** [comment]
@FatalRev Are you just asking for an option to specify the `host` in node.js's `server.listen(post, host)`? That's not too hard to support.

But if you're asking for something more elaborate, I think the right place to handle this is at the VPN level. Most VPN software supports such an option.
