### ISSUE TITLE
Webtorrent doesn't call callback of add when files are too big

### ISSUE THREAD

**Issue by antoniomuso** [webtorrent/webtorrent#944]
Hi , I have a problem when file is too big.
When i run program in my computer desktop(Windows 10) it works well, but if i run program in RaspBerry PI (Debian "Raspian") it doesn't work if I add big files. it isn't a memory issues.
- Code: https://github.com/antoniomuso/WebTorrentRep/blob/master/routes/torrent.js
- WebTorrent version:
- Node.js version: 6.7.0
- Browser name/version (if using WebTorrent in the browser):

**Comment by feross** [comment]
- How much memory does your Raspberry Pi have?
- What version of Raspian are you running?
- Is Raspian 32 or 64-bit?
- How large is the torrent that is failing?
- Can you figure out the size at which WebTorrent starts to fail? For example, does it work for 3GB torrents, but fail for 4GB ones?
- Can you run your program with the following environment variable `DEBUG=*,-bittorrent-dht` and post the logs of when it fails?
