### ISSUE TITLE
Multiple files doesn't work in Brave

### ISSUE THREAD

**Issue by mikeal** [webtorrent/webtorrent#965]
If you take multiple files and drag/drop them into the browser and send the list of files from `drag-drop` to `webtorrent.seed` you get this error:

```
Uncaught TypeError: item.path.shift is not a function
```

Digging into it a bit it looks like Brave has a property on each File object that Chrome doesn't, the `.path` property. The property also appears to be immutable, I've tried working around the issue by deleting it or setting it to null but nothing happens, it doesn't throw either though.

Webtorrent does a bunch of mutation of the file object properties which all may not work in Brave right now. May want to migrate that code to use local variables instead of mutating the file object.

* WebTorrent version: 0.97.2
* Node.js version: 6
* Browser name/version (if using WebTorrent in the browser): Brave

**Comment by josephfrazier** [comment]
(this can be reproduced using Brave against a local instance of https://github.com/feross/instant.io)

**Comment by mikeal** [comment]
Single files are also messed up in Brave because of the same or similar code. The filename and path encoded into the torrent are just the last character in the string :(

**Comment by feross** [comment]
I think this was fixed a while ago, but since Brave will not be using Electron going forward, I think that they'll get the same `File` implementation as Chrome now so this should definitely work in Brave beta now. LMK if this is not the case.
