### ISSUE TITLE
Does not work with Amazon s3 tracker

### ISSUE THREAD

**Issue by layn35** [webtorrent/webtorrent#979]
* WebTorrent version: 0.97.2
* Node.js version: 6.4.0

I try to use webtorrent to download files from an AWS S3 bucket like described on documentation : http://docs.aws.amazon.com/AmazonS3/latest/dev/S3Torrent.html
It work fine on clients like deluge or µTorrent.

With webtorrent lib or webtorrent cli, dowload and parsing torrent file is successfull, some peers are connected, but download does not start.

Here an example image file : https://s3-eu-west-1.amazonaws.com/iam-a-test-bucket/test?torrent

**Comment by feross** [comment]
It's not clear to me upon a quick examination why this would be happening.

**Comment by ducdigital** [comment]
@fquillien It seem like s3 does not provide webrtc seeding so unless you downloaded the file on some hybrid node. The file won't be available on the network of webtorrent.

**Comment by feross** [comment]
@ducdigital But he said that he tried with the webtorrent CLI, which can connect to normal torrent peers, not just webrtc peers.

**Comment by cphoover** [comment]
To me this would be a game changer if s3 provided webtorrent seeding.

**Comment by DiegoRBaquero** [comment]
You can use S3 for webseeding: https://hackernoon.com/how-to-create-a-swarm-cdn-for-free-with-webtorrent-bfa09d193f71
