### ISSUE TITLE
The download stops, client still is connected to peers

### ISSUE THREAD

**Issue by vankasteelj** [webtorrent/webtorrent#994]
I encounter an issue, on nodejs (https://github.com/butterproject/butter-desktop/issues/525)

Might be a bug, I don't know : I've set maxconns to 55, as recommended, and sometimes the torrent just stops downloading, speed gets to 0, peer list continues to changes so I think it's still doing things under the hood, but it doesn't want to download anything. There are no errors thrown. This seem to happen when the app is running in the background.

Hence my questions: 
- Why would the download stop? Might it be related to the app being not focused (which would be very strange, and impractical with VLC and/or slow torrents)

**Comment by feross** [comment]
Not sure what could cause this. I'll leave this issue open for a while in case you or others have more info.
